/**
 * Furniture & Fixtures, Home & Kitchen, Clothing & Textiles,
 * Beauty & Personal Care.
 *
 * Sixteen shelves, three products each.
 *
 * The consumer departments are where a generated catalogue usually gives
 * itself away, because consumer copy is where marketing language lives. So the
 * rule is the same one the rest of the registry is written under and it simply
 * bites harder here: every sentence describes something that could be checked
 * by holding the product. A chair has a gas lift with a stated travel; it is
 * not "the ultimate in comfort". A serum has a volume, a texture and a pump;
 * it does not "transform your skin in seven days".
 *
 * Nothing in the personal care shelves claims a clinical or dermatological
 * result, and nothing anywhere claims a certification - organic, cruelty free,
 * dermatologically tested - because those are audits somebody paid for and not
 * adjectives this catalogue is entitled to use.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const CONSUMER_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // FURNITURE & FIXTURES
  // =======================================================================
  shelf('office-furniture', [
    {
      key: 'furn-off-desk',
      type: 'Office desk',
      title: 'Straight Office Desk with Cable Port and Modesty Panel',
      brand: BRANDS.furniture,
      short:
        'Straight office desk with a 25 mm top, a grommeted cable port and a steel modesty panel.',
      long: 'A straight office desk with a twenty-five millimetre melamine top on a steel frame, a grommeted cable port at each rear corner and a steel modesty panel. The feet adjust for an uneven floor and the frame is bolted rather than welded, so it goes through a doorway flat.',
      img: 'office desk workspace furniture wood',
      specs: {
        Top: '25 mm melamine faced board',
        Frame: 'Bolted steel with adjustable feet',
        'Cable management': 'Grommeted port at each rear corner',
        Panel: 'Steel modesty panel',
      },
      facets: ['Top', 'Frame'],
      axes: [
        ['dimensions', ['1,200 x 800 mm', '1,400 x 800 mm', '1,600 x 800 mm']],
        ['finish', ['Oak', 'White', 'Walnut']],
      ],
      price: [8_400_00, 24_000_00],
      stock: [3, 48],
      moq: 1,
      grams: 34_000,
      leadDays: 5,
      featured: true,
    },
    {
      key: 'furn-off-pedestal',
      type: 'Desk pedestal',
      title: 'Three-Drawer Mobile Desk Pedestal with Anti-Tilt',
      brand: BRANDS.furniture,
      short:
        'Three-drawer mobile pedestal with a central lock, an anti-tilt interlock and a filing drawer.',
      long: 'A three-drawer mobile pedestal with two shallow drawers and a filing drawer, a central lock and an anti-tilt interlock so only one drawer opens at a time. It rolls on five castors and tucks under a standard desk.',
      img: 'office pedestal drawers furniture storage',
      specs: {
        Drawers: 'Two shallow and one filing',
        Lock: 'Central locking',
        Safety: 'Anti-tilt interlock',
        Castors: 'Five',
      },
      facets: ['Lock', 'Safety'],
      axes: [
        ['finish', ['Oak', 'White', 'Walnut']],
        ['configuration', ['Three drawer', 'Two drawer']],
      ],
      price: [4_800_00, 12_800_00],
      stock: [4, 60],
      moq: 1,
      grams: 22_000,
    },
    {
      key: 'furn-off-meetingtable',
      type: 'Meeting table',
      title: 'Boardroom Meeting Table with Recessed Power Module',
      brand: BRANDS.furniture,
      short:
        'Boardroom meeting table with a recessed power and data module and a post leg base.',
      long: 'A boardroom table with a recessed module in the top carrying power and data outlets behind a flush lid, on post legs with a levelling foot each. The top is a twenty-five millimetre board with an ABS edge on all four sides.',
      img: 'boardroom meeting table office furniture',
      specs: {
        Top: '25 mm board with ABS edge all round',
        Module: 'Recessed power and data behind a flush lid',
        Base: 'Post legs with levelling feet',
      },
      facets: ['Top', 'Module'],
      axes: [
        ['dimensions', ['1,800 x 900 mm', '2,400 x 1,200 mm']],
        ['finish', ['Oak', 'Walnut']],
      ],
      price: [18_500_00, 52_000_00],
      stock: [1, 20],
      moq: 1,
      grams: 68_000,
      leadDays: 14,
      mrp: 0.1,
    },
  ]),

  shelf('seating', [
    {
      key: 'furn-seat-ergonomic',
      type: 'Ergonomic office chair',
      title: 'Adjustable Ergonomic Office Chair with Mesh Back',
      brand: BRANDS.furniture,
      short:
        'Ergonomic office chair with a mesh back, adjustable lumbar support, seat depth and arm height.',
      long: 'An ergonomic office chair with a mesh back over a flexible frame, an adjustable lumbar pad on a vertical track, a seat that slides for depth and arms that adjust for height and width. The tilt locks in four positions and the tension matches the sitter.',
      img: 'ergonomic office chair mesh furniture',
      specs: {
        Back: 'Mesh over flexible frame',
        Lumbar: 'Adjustable pad on a vertical track',
        Seat: 'Sliding for depth',
        Tilt: 'Four-position lock with tension adjustment',
        Base: 'Five-star nylon with castors',
      },
      facets: ['Back', 'Lumbar'],
      axes: [
        ['colour', ['Black', 'Grey', 'Navy']],
        ['armrest', ['Fixed arms', 'Height adjustable arms', '3D adjustable arms']],
        ['headrest', ['Without headrest', 'With headrest']],
      ],
      price: [6_800_00, 28_000_00],
      stock: [3, 50],
      moq: 1,
      grams: 16_000,
      featured: true,
    },
    {
      key: 'furn-seat-visitor',
      type: 'Visitor chair',
      title: 'Cantilever Visitor Chair with Stackable Frame',
      brand: BRANDS.furniture,
      short:
        'Cantilever visitor chair on a chrome frame, stackable four high with linking brackets.',
      long: 'A cantilever visitor chair on a chrome frame that stacks four high, with linking brackets available so a row stays a row. The seat and back are upholstered over a moulded shell and the floor glides are replaceable.',
      img: 'visitor chair office seating stackable',
      specs: {
        Frame: 'Chrome cantilever, stacks four high',
        Linking: 'Brackets available',
        Upholstery: 'Over a moulded shell',
        Glides: 'Replaceable',
      },
      facets: ['Frame', 'Linking'],
      axes: [
        ['colour', ['Black', 'Charcoal', 'Blue']],
        ['material', ['Fabric', 'Faux leather']],
      ],
      price: [2_800_00, 9_800_00],
      stock: [6, 90],
      moq: 2,
      step: 2,
      grams: 8_400,
    },
    {
      key: 'furn-seat-stool',
      type: 'Draughtsman stool',
      title: 'Draughtsman Stool with Footring and Gas Lift',
      brand: BRANDS.furniture,
      short:
        'Draughtsman stool with an adjustable footring, a gas lift and a five-star base.',
      long: 'A draughtsman stool for a high bench, with a footring that adjusts independently of the seat so it can be set for the sitter rather than the chair. Gas lift, five-star base, and castors that can be swapped for glides.',
      img: 'draughtsman stool high chair office',
      specs: {
        Footring: 'Independently adjustable',
        Lift: 'Gas lift',
        Base: 'Five star',
        Feet: 'Castors, glides available',
      },
      facets: ['Footring', 'Lift'],
      axes: [
        ['colour', ['Black', 'Grey']],
        ['material', ['Fabric', 'Polyurethane']],
      ],
      price: [4_200_00, 14_800_00],
      stock: [4, 60],
      moq: 1,
      grams: 11_000,
      mrp: 0.12,
    },
  ]),

  shelf('storage-shelving', [
    {
      key: 'furn-stor-boltless',
      type: 'Boltless shelving bay',
      title: 'Boltless Shelving Bay with Adjustable Levels',
      brand: BRANDS.furniture,
      short:
        'Boltless steel shelving bay that assembles with a rubber mallet, with levels adjustable every 25 mm.',
      long: 'A boltless steel shelving bay that goes together with a rubber mallet and nothing else, with beams that reposition every twenty-five millimetres. Each level takes a chipboard or a steel deck and the uprights are pre-punched for a run of bays.',
      img: 'boltless shelving racking warehouse storage',
      specs: {
        Assembly: 'Boltless, mallet only',
        Adjustment: 'Beam levels every 25 mm',
        Decking: 'Chipboard or steel',
        Uprights: 'Pre-punched for extension bays',
      },
      facets: ['Assembly', 'Decking'],
      axes: [
        ['dimensions', ['900 x 400 mm', '1,200 x 450 mm', '1,200 x 600 mm']],
        ['shelf_count', ['4 shelves', '5 shelves', '6 shelves']],
      ],
      price: [3_400_00, 14_800_00],
      stock: [4, 70],
      moq: 1,
      grams: 28_000,
      featured: true,
    },
    {
      key: 'furn-stor-cupboard',
      type: 'Steel storage cupboard',
      title: 'Steel Storage Cupboard with Adjustable Shelves',
      brand: BRANDS.furniture,
      short:
        'Powder-coated steel storage cupboard with a three-point lock and adjustable shelves.',
      long: 'A powder-coated steel storage cupboard with a three-point locking bar, doors on concealed hinges and shelves adjustable on a punched upright. The base has levelling feet under the corners.',
      img: 'steel storage cupboard office furniture',
      specs: {
        Lock: 'Three-point locking bar',
        Hinges: 'Concealed',
        Shelves: 'Adjustable on punched uprights',
        Feet: 'Levelling',
      },
      facets: ['Lock', 'Shelves'],
      axes: [
        ['dimensions', ['1,000 mm high', '1,800 mm high']],
        ['colour', ['Grey', 'Black', 'White']],
      ],
      price: [9_800_00, 24_000_00],
      stock: [2, 34],
      moq: 1,
      grams: 42_000,
      leadDays: 7,
    },
    {
      key: 'furn-stor-lockers',
      type: 'Personnel locker',
      title: 'Personnel Locker Nest with Ventilated Doors',
      brand: BRANDS.furniture,
      short:
        'Steel personnel locker nest with ventilated doors, a card holder and a cam lock.',
      long: 'A steel personnel locker nest with louvred ventilation in each door, a card holder for a name and a cam lock keyed to differ. Each compartment has a hat shelf and a coat hook.',
      img: 'personnel lockers steel storage workplace',
      specs: {
        Ventilation: 'Louvred doors',
        Lock: 'Cam lock keyed to differ',
        Fittings: 'Hat shelf and coat hook per compartment',
        Identification: 'Card holder on each door',
      },
      facets: ['Ventilation', 'Lock'],
      axes: [
        ['shelf_count', ['2 door', '3 door', '4 door', '6 door']],
        ['colour', ['Grey', 'Blue']],
      ],
      price: [11_400_00, 32_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 48_000,
      leadDays: 10,
      mrp: 0.11,
    },
  ]),

  shelf('retail-display', [
    {
      key: 'furn-ret-gondola',
      type: 'Gondola display unit',
      title: 'Double-Sided Gondola Display Unit with Adjustable Shelves',
      brand: BRANDS.furniture,
      short:
        'Double-sided gondola display unit with shelves adjustable on a slotted upright.',
      long: 'A double-sided gondola display unit on a base frame, with shelves that hook into slotted uprights and cant forward two positions. It bolts to the next bay in a run and takes a header board.',
      img: 'retail gondola shelving display shop',
      specs: {
        Sides: 'Double sided',
        Shelves: 'Hook into slotted uprights, two cant positions',
        Extension: 'Bolts to the next bay',
        Header: 'Takes a header board',
      },
      facets: ['Sides', 'Shelves'],
      axes: [
        ['dimensions', ['1,000 mm wide', '1,250 mm wide']],
        ['shelf_count', ['6 shelves', '8 shelves']],
      ],
      price: [12_800_00, 34_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 54_000,
      leadDays: 10,
      featured: true,
    },
    {
      key: 'furn-ret-slatwall',
      type: 'Slatwall panel',
      title: 'Slatwall Panel with Aluminium Inserts',
      brand: BRANDS.furniture,
      short:
        'Slatwall panel with aluminium inserts in the grooves, for heavier hanging loads.',
      long: 'A slatwall panel with aluminium inserts pressed into the grooves, which is what lets a hook carry a real load without the board crushing. Supplied ready-grooved on a standard pitch with a laminated face.',
      img: 'slatwall retail display panel shop fitting',
      specs: {
        Inserts: 'Aluminium in every groove',
        Pitch: 'Standard groove pitch',
        Face: 'Laminated',
      },
      facets: ['Inserts', 'Face'],
      axes: [
        ['dimensions', ['1,200 x 1,200 mm', '2,400 x 1,200 mm']],
        ['finish', ['White', 'Black', 'Oak']],
      ],
      price: [4_800_00, 16_800_00],
      stock: [3, 48],
      moq: 1,
      grams: 26_000,
    },
    {
      key: 'furn-ret-mannequin',
      type: 'Display mannequin',
      title: 'Display Mannequin with Removable Limbs and Glass Base',
      brand: BRANDS.furniture,
      short:
        'Display mannequin with removable limbs and a glass base with a chrome stem.',
      long: 'A display mannequin whose arms and lower legs come off at concealed joints, so garments go on without stretching. It stands on a glass base with a chrome stem, and the calf socket takes the stem rod.',
      img: 'retail mannequin display shop window',
      specs: {
        Joints: 'Concealed, removable arms and lower legs',
        Base: 'Glass with chrome stem',
        Fitting: 'Calf socket for the stem rod',
      },
      facets: ['Joints', 'Base'],
      axes: [
        ['fixture_type', ['Female form', 'Male form']],
        ['finish', ['Matt white', 'Matt black', 'Skin tone']],
      ],
      price: [6_800_00, 18_500_00],
      stock: [2, 34],
      moq: 1,
      grams: 12_000,
      mrp: 0.13,
    },
  ]),

  // =======================================================================
  // HOME & KITCHEN
  // =======================================================================
  shelf('kitchenware', [
    {
      key: 'home-kit-cookset',
      type: 'Cookware set',
      title: 'Triple-Ply Stainless Steel Cookware Set',
      brand: BRANDS.home,
      short:
        'Triple-ply stainless steel cookware set with an aluminium core through the base and the walls.',
      long: 'A triple-ply cookware set with an aluminium core running through the walls as well as the base, so the heat reaches up the sides instead of stopping at the join. The handles are riveted and stay cooler than the pan; the lids are tempered glass with a vent.',
      img: 'stainless steel cookware set pots pans',
      specs: {
        Construction: 'Triple ply, core through base and walls',
        Handles: 'Riveted stainless',
        Lids: 'Tempered glass with vent',
        Induction: 'Induction compatible',
        'Dishwasher safe': 'Yes',
      },
      facets: ['Construction', 'Induction', 'Dishwasher safe'],
      axes: [
        ['piece_count', ['3 piece', '5 piece', '7 piece']],
        ['lid_included', ['With lids', 'Without lids']],
      ],
      price: [4_800_00, 22_000_00],
      stock: [4, 70],
      moq: 1,
      grams: 6_400,
      featured: true,
    },
    {
      key: 'home-kit-knifeblock',
      type: 'Kitchen knife set',
      title: 'Forged Kitchen Knife Set in a Magnetic Block',
      brand: BRANDS.home,
      short:
        'Forged stainless knife set with full tangs, in a magnetic block rather than a slotted one.',
      long: 'A forged stainless knife set with full tangs and triple-riveted handles, supplied in a magnetic block rather than a slotted one - a slot cannot be cleaned and a magnet can. The bolster is forged rather than welded on.',
      img: 'kitchen knife set block cooking',
      specs: {
        Construction: 'Forged, full tang, triple riveted',
        Bolster: 'Forged',
        Block: 'Magnetic, wipeable',
        Steel: 'Stainless',
      },
      facets: ['Construction', 'Block'],
      axes: [
        ['piece_count', ['4 piece', '6 piece', '8 piece']],
        ['handle_material', ['Pakkawood', 'Composite']],
      ],
      price: [3_400_00, 16_800_00],
      stock: [4, 60],
      moq: 1,
      grams: 3_200,
    },
    {
      key: 'home-kit-storagejars',
      type: 'Storage jar set',
      title: 'Airtight Glass Storage Jar Set with Bamboo Lids',
      brand: BRANDS.home,
      short:
        'Airtight borosilicate glass storage jar set with bamboo lids and replaceable silicone seals.',
      long: 'A set of borosilicate glass storage jars with bamboo lids and silicone seals that can be taken out and replaced - which is the part that perishes and the reason most airtight jars stop being airtight. The jars stack and the lids are interchangeable across the set.',
      img: 'glass storage jars kitchen airtight',
      specs: {
        Glass: 'Borosilicate',
        Lids: 'Bamboo with replaceable silicone seal',
        Interchange: 'Lids fit every jar in the set',
      },
      facets: ['Glass', 'Lids'],
      axes: [
        ['piece_count', ['3 piece', '5 piece']],
        ['size', ['Small set', 'Large set']],
      ],
      price: [980_000, 3_800_000],
      stock: [8, 140],
      moq: 1,
      grams: 3_800,
      mrp: 0.15,
    },
  ]),

  shelf('home-appliances', [
    {
      key: 'home-app-mixer',
      type: 'Stand mixer',
      title: 'Die-Cast Stand Mixer with Planetary Action',
      brand: BRANDS.home,
      short:
        'Die-cast stand mixer with a planetary action, a tilting head and three attachments.',
      long: 'A die-cast stand mixer with a planetary action, so the beater travels round the bowl as well as turning. The head tilts and locks, three attachments are supplied, and an accessory hub on the front takes a mincer or a pasta roller.',
      img: 'stand mixer kitchen appliance',
      specs: {
        Body: 'Die cast',
        Action: 'Planetary',
        Head: 'Tilting with lock',
        Attachments: 'Beater, whisk and dough hook',
        Hub: 'Front accessory hub',
      },
      facets: ['Body', 'Action'],
      axes: [
        ['capacity', ['4.5 L', '5.5 L']],
        ['colour', ['Cream', 'Matt black', 'Sage']],
      ],
      price: [12_800_00, 42_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 11_500,
      featured: true,
    },
    {
      key: 'home-app-airfryer',
      type: 'Air fryer',
      title: 'Dual-Basket Air Fryer with Synchronised Finish',
      brand: BRANDS.home,
      short:
        'Dual-basket air fryer with independent zones and a synchronised finish setting.',
      long: 'A dual-basket air fryer with two independent zones, and a setting that staggers the start times so both finish together. The baskets and the crisper plates are dishwasher safe and the drawers slide out without tipping.',
      img: 'air fryer kitchen appliance countertop',
      specs: {
        Zones: 'Two independent baskets',
        Sync: 'Staggered start so both finish together',
        Cleaning: 'Baskets and plates dishwasher safe',
      },
      facets: ['Zones', 'Sync'],
      axes: [
        ['capacity', ['7.6 L', '9.5 L']],
        ['colour', ['Black', 'Grey']],
      ],
      price: [9_800_00, 24_000_00],
      stock: [3, 50],
      moq: 1,
      grams: 8_400,
    },
    {
      key: 'home-app-vacuumcleaner',
      type: 'Cordless vacuum cleaner',
      title: 'Cordless Stick Vacuum with Removable Battery',
      brand: BRANDS.home,
      short:
        'Cordless stick vacuum with a removable battery, a washable filter and a wall dock.',
      long: 'A cordless stick vacuum whose battery clips out, so a second one can be charged while the first is in use. The filter is washable, the bin empties without the hand going near the dust, and a wall dock is supplied with the charger through it.',
      img: 'cordless stick vacuum cleaner home appliance',
      specs: {
        Battery: 'Removable, second battery available',
        Filter: 'Washable',
        Bin: 'Hygienic empty',
        Dock: 'Wall dock with charging',
      },
      facets: ['Battery', 'Filter'],
      axes: [
        ['capacity', ['0.6 L bin', '0.8 L bin']],
        ['configuration', ['One battery', 'Two batteries']],
      ],
      price: [11_400_00, 34_000_00],
      stock: [3, 48],
      moq: 1,
      grams: 3_200,
      mrp: 0.12,
    },
  ]),

  shelf('bedding-bath', [
    {
      key: 'home-bed-sheetset',
      type: 'Bed sheet set',
      title: 'Percale Cotton Bed Sheet Set with Deep Fitted Corners',
      brand: BRANDS.textile,
      short:
        'Percale cotton bed sheet set with a crisp weave and a fitted sheet for deep mattresses.',
      long: 'A percale cotton sheet set - a plain over-under weave that feels crisp rather than smooth, and breathes better than a sateen. The fitted sheet is cut for a deep mattress and the elastic runs the whole way round rather than at the corners only.',
      img: 'bed sheet set cotton bedding home',
      specs: {
        Weave: 'Percale, plain weave',
        Fibre: '100% cotton',
        Fitted: 'Deep corners, full-perimeter elastic',
        Care: 'Machine washable at 60 C',
      },
      facets: ['Weave', 'Fibre'],
      axes: [
        ['bed_size', ['Single', 'Double', 'King', 'Super king']],
        ['colour', ['White', 'Grey', 'Sage', 'Navy']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [6, 110],
      moq: 1,
      grams: 1_600,
      featured: true,
    },
    {
      key: 'home-bed-towel',
      type: 'Bath towel',
      title: 'Combed Cotton Bath Towel with Double-Stitched Hem',
      brand: BRANDS.textile,
      short:
        'Combed cotton bath towel with a double-stitched hem and a stated weight per square metre.',
      long: 'A combed cotton bath towel with a double-stitched hem, which is the seam that fails first in a laundry. The weight per square metre is stated, because that and not the word "luxury" is what decides how a towel feels and how long it takes to dry.',
      img: 'bath towels cotton bathroom home',
      specs: {
        Fibre: 'Combed cotton',
        Hem: 'Double stitched',
        Weight: 'Stated in grams per square metre',
        Care: 'Machine washable at 60 C',
      },
      facets: ['Fibre', 'Hem'],
      axes: [
        ['dimensions', ['Hand towel', 'Bath towel', 'Bath sheet']],
        ['colour', ['White', 'Charcoal', 'Sand', 'Teal']],
        ['piece_count', ['Single', 'Pack of 4']],
      ],
      price: [380_000, 3_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 620,
    },
    {
      key: 'home-bed-duvet',
      type: 'Duvet',
      title: 'Microfibre Duvet with Box-Stitched Baffles',
      brand: BRANDS.textile,
      short:
        'Microfibre duvet with box-stitched baffles, so the filling stays where it is put.',
      long: 'A microfibre duvet quilted in box-stitched baffles rather than channels, which keeps the filling from migrating to one end over a winter. The cover is a soft-touch microfibre and the whole duvet washes at sixty degrees.',
      img: 'duvet bedding home bedroom',
      specs: {
        Filling: 'Microfibre',
        Quilting: 'Box-stitched baffles',
        Cover: 'Soft-touch microfibre',
        Care: 'Machine washable at 60 C',
      },
      facets: ['Filling', 'Quilting'],
      axes: [
        ['bed_size', ['Single', 'Double', 'King']],
        ['material', ['4.5 tog', '10.5 tog', '13.5 tog']],
      ],
      price: [1_280_00, 5_400_00],
      stock: [5, 90],
      moq: 1,
      grams: 2_400,
      mrp: 0.14,
    },
  ]),

  shelf('home-decor', [
    {
      key: 'home-dec-mirror',
      type: 'Wall mirror',
      title: 'Round Wall Mirror with a Powder-Coated Metal Frame',
      brand: BRANDS.textile,
      short:
        'Round wall mirror in a powder-coated metal frame, with a keyhole plate and a safety backing.',
      long: 'A round wall mirror in a powder-coated metal frame, with a keyhole plate already fitted on the back and a safety backing film so a break holds together. The glass is a true silver mirror rather than an aluminium one.',
      img: 'round wall mirror home decor interior',
      specs: {
        Frame: 'Powder-coated metal',
        Glass: 'Silvered, safety backed',
        Fixing: 'Keyhole plate fitted',
      },
      facets: ['Frame', 'Glass'],
      axes: [
        ['dimensions', ['500 mm', '700 mm', '900 mm']],
        ['colour', ['Matt black', 'Brass', 'Champagne']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [5, 90],
      moq: 1,
      grams: 4_200,
      featured: true,
    },
    {
      key: 'home-dec-vase',
      type: 'Ceramic vase',
      title: 'Reactive-Glaze Ceramic Vase with Sealed Interior',
      brand: BRANDS.textile,
      short:
        'Stoneware vase with a reactive glaze and a sealed interior, so every piece differs slightly.',
      long: 'A stoneware vase with a reactive glaze, which means every piece comes out of the kiln slightly differently and none of them match exactly. The interior is sealed so it holds water, and the base is felted.',
      img: 'ceramic vase home decor interior',
      specs: {
        Body: 'Stoneware',
        Glaze: 'Reactive - each piece differs',
        Interior: 'Sealed, holds water',
        Base: 'Felted',
      },
      facets: ['Body', 'Glaze'],
      axes: [
        ['dimensions', ['200 mm', '300 mm', '400 mm']],
        ['colour', ['Sand', 'Slate', 'Ochre']],
      ],
      price: [680_000, 2_800_000],
      stock: [8, 140],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'home-dec-cushion',
      type: 'Cushion cover',
      title: 'Woven Cushion Cover with a Concealed Zip',
      brand: BRANDS.textile,
      short:
        'Woven cushion cover with a concealed zip along one side and piped edges.',
      long: 'A woven cushion cover with a concealed zip along one side rather than a fold-over back, so the pad stays in and the cover comes off to wash. The edges are piped and the pattern is woven rather than printed.',
      img: 'cushion covers home decor textile',
      specs: {
        Weave: 'Woven pattern, not printed',
        Closure: 'Concealed zip',
        Edges: 'Piped',
        Care: 'Machine washable at 30 C',
      },
      facets: ['Weave', 'Closure'],
      axes: [
        ['dimensions', ['450 x 450 mm', '500 x 500 mm']],
        ['colour', ['Ochre', 'Slate', 'Sage', 'Rust']],
        ['piece_count', ['Single', 'Pair']],
      ],
      price: [280_000, 1_280_000],
      stock: [10, 180],
      moq: 1,
      grams: 320,
      mrp: 0.16,
    },
  ]),

  // =======================================================================
  // CLOTHING & TEXTILES
  // =======================================================================
  shelf('workwear-uniforms', [
    {
      key: 'cloth-work-polo',
      type: 'Workwear polo shirt',
      title: 'Heavyweight Piqué Polo Shirt for Workwear',
      brand: BRANDS.workwear,
      short:
        'Heavyweight piqué polo shirt with a reinforced placket and a taped neck seam.',
      long: 'A heavyweight piqué polo shirt cut for work rather than sport: a reinforced three-button placket, a taped neck seam so the collar keeps its shape through an industrial wash, and side vents. The fabric weight is stated because that is what decides how it wears.',
      img: 'polo shirt workwear uniform plain',
      specs: {
        Knit: 'Piqué',
        Placket: 'Reinforced, three button',
        Neck: 'Taped seam',
        Care: 'Industrial wash at 60 C',
      },
      facets: ['Knit', 'Care'],
      axes: [
        ['size', ['S', 'M', 'L', 'XL', 'XXL']],
        ['colour', ['Navy', 'Black', 'Bottle green']],
      ],
      price: [420_000, 1_280_000],
      stock: [10, 220],
      moq: 5,
      step: 5,
      grams: 260,
      featured: true,
    },
    {
      key: 'cloth-work-trouser',
      type: 'Work trouser',
      title: 'Holster-Pocket Work Trouser with Knee Pad Pockets',
      brand: BRANDS.workwear,
      short:
        'Work trouser with hanging holster pockets, knee pad pockets and a triple-stitched seat seam.',
      long: 'A work trouser with hanging holster pockets that tuck away when they are not wanted, knee pad pockets loaded from the top, and a triple-stitched seat seam. The main fabric is a poly-cotton and the wear points are reinforced with a heavier panel.',
      img: 'work trousers cargo workwear uniform',
      specs: {
        Pockets: 'Hanging holster pockets, tuck away',
        Knees: 'Top-loading knee pad pockets',
        Seams: 'Triple stitched seat',
        Fabric: 'Poly-cotton with reinforced panels',
      },
      facets: ['Pockets', 'Fabric'],
      axes: [
        ['size', ['30', '32', '34', '36', '38']],
        ['colour', ['Black', 'Navy', 'Grey']],
      ],
      price: [980_000, 3_400_000],
      stock: [8, 160],
      moq: 1,
      grams: 720,
    },
    {
      key: 'cloth-work-fleece',
      type: 'Work fleece',
      title: 'Full-Zip Work Fleece with Chin Guard',
      brand: BRANDS.workwear,
      short:
        'Full-zip anti-pill fleece with a chin guard, zipped side pockets and elasticated cuffs.',
      long: 'A full-zip fleece in an anti-pill knit, with a chin guard at the top of the zip, zipped side pockets so nothing falls out when bending, and elasticated cuffs and hem. Cut with room for a shirt underneath.',
      img: 'fleece jacket workwear uniform zip',
      specs: {
        Knit: 'Anti-pill fleece',
        Zip: 'Full zip with chin guard',
        Pockets: 'Zipped side pockets',
        Cuffs: 'Elasticated cuffs and hem',
      },
      facets: ['Knit', 'Zip'],
      axes: [
        ['size', ['S', 'M', 'L', 'XL', 'XXL']],
        ['colour', ['Black', 'Navy', 'Charcoal']],
      ],
      price: [1_280_00, 3_800_00],
      stock: [8, 160],
      moq: 1,
      grams: 580,
      mrp: 0.13,
    },
  ]),

  shelf('everyday-clothing', [
    {
      key: 'cloth-every-tshirt',
      type: 'Cotton T-shirt',
      title: 'Premium Cotton Crew-Neck T-Shirt',
      brand: BRANDS.apparel,
      short:
        'Combed ring-spun cotton crew-neck T-shirt with a ribbed collar and shoulder-to-shoulder tape.',
      long: 'A crew-neck T-shirt in combed ring-spun cotton, with a ribbed collar, shoulder-to-shoulder taping and twin-needle hems. The body is tubular, so there is no side seam to twist after washing.',
      img: 'cotton t shirt folded clothing plain',
      specs: {
        Fibre: 'Combed ring-spun cotton',
        Collar: 'Ribbed',
        Taping: 'Shoulder to shoulder',
        Body: 'Tubular, no side seam',
        Care: 'Machine washable at 40 C',
      },
      facets: ['Fibre', 'Body'],
      axes: [
        ['size', ['XS', 'S', 'M', 'L', 'XL', 'XXL']],
        ['colour', ['White', 'Black', 'Navy', 'Heather grey']],
      ],
      price: [180_000, 680_000],
      stock: [10, 260],
      moq: 1,
      grams: 180,
      featured: true,
    },
    {
      key: 'cloth-every-suit',
      type: 'Two-piece suit',
      title: 'Single-Breasted Two-Piece Suit in a Wool Blend',
      brand: BRANDS.apparel,
      short:
        'Single-breasted two-piece suit in a wool blend, with a half-canvas front and working sleeve buttons.',
      long: 'A single-breasted two-piece suit in a wool blend, with a half-canvas front rather than a fully fused one, so the chest keeps its shape. Notch lapels, two buttons, side vents, and trousers finished unhemmed so they can be set to length.',
      img: 'mens suit formal clothing tailored',
      specs: {
        Construction: 'Half canvas front',
        Fabric: 'Wool blend',
        Lapel: 'Notch, two button',
        Vents: 'Side vents',
        Trousers: 'Supplied unhemmed',
      },
      facets: ['Construction', 'Fabric'],
      axes: [
        ['chest_size', ['38', '40', '42', '44']],
        ['colour', ['Charcoal', 'Navy', 'Mid grey']],
        ['fit', ['Regular fit', 'Slim fit']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 1_800,
      leadDays: 3,
    },
    {
      key: 'cloth-every-lehenga',
      type: 'Embroidered lehenga set',
      title: 'Embroidered Bridal Lehenga Set with Dupatta',
      brand: BRANDS.apparel,
      short:
        'Three-piece embroidered lehenga set with a lined skirt, a padded blouse and a net dupatta.',
      long: 'A three-piece lehenga set: a fully lined embroidered skirt with a concealed side zip and a drawstring waist, a padded blouse with a hook-and-eye back, and a net dupatta with a worked border. The blouse is supplied with unstitched margins so it can be let out.',
      img: 'embroidered lehenga indian ethnic wear',
      specs: {
        Pieces: 'Skirt, blouse and dupatta',
        Skirt: 'Fully lined, concealed zip and drawstring',
        Blouse: 'Padded, hook-and-eye back, unstitched margins',
        Dupatta: 'Net with worked border',
        Care: 'Dry clean only',
      },
      facets: ['Pieces', 'Care'],
      axes: [
        ['size', ['S', 'M', 'L', 'XL']],
        ['colour', ['Crimson', 'Fuchsia', 'Emerald']],
      ],
      price: [11_400_00, 42_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 2_600,
      leadDays: 5,
      mrp: 0.18,
    },
  ]),

  shelf('footwear', [
    {
      key: 'cloth-foot-sneaker',
      type: 'Court sneaker',
      title: 'Leather Court Sneaker with Cupsole Construction',
      brand: BRANDS.apparel,
      short:
        'Leather court sneaker on a vulcanised cupsole, with a padded collar and a removable insole.',
      long: 'A leather court sneaker on a cupsole, where the upper is stitched into the sole wall rather than glued flat, which is the join that usually opens first. The collar is padded, the tongue is gusseted and the insole lifts out.',
      img: 'white leather sneakers shoes footwear',
      specs: {
        Upper: 'Leather',
        Sole: 'Vulcanised cupsole, stitched',
        Collar: 'Padded',
        Tongue: 'Gusseted',
        Insole: 'Removable',
      },
      facets: ['Upper', 'Sole'],
      axes: [
        ['size_system', ['UK', 'EU']],
        ['size', ['6', '7', '8', '9', '10', '11']],
        ['colour', ['White', 'Black', 'Off white']],
      ],
      price: [2_400_00, 8_400_00],
      stock: [4, 80],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'cloth-foot-chelsea',
      type: 'Chelsea boot',
      title: 'Leather Chelsea Boot with Elasticated Gussets',
      brand: BRANDS.apparel,
      short:
        'Full-grain leather Chelsea boot with elasticated gussets, a pull tab and a stitched welt.',
      long: 'A full-grain leather Chelsea boot with elasticated gussets both sides, a pull tab at the heel and a stitched welt, so the sole can be replaced rather than the boot. The lining is leather to the toe.',
      img: 'chelsea boots leather footwear',
      specs: {
        Upper: 'Full grain leather',
        Gussets: 'Elasticated both sides',
        Welt: 'Stitched, resoleable',
        Lining: 'Leather to the toe',
      },
      facets: ['Upper', 'Welt'],
      axes: [
        ['size_system', ['UK']],
        ['size', ['6', '7', '8', '9', '10', '11']],
        ['colour', ['Black', 'Tan', 'Dark brown']],
      ],
      price: [4_200_00, 14_800_00],
      stock: [3, 60],
      moq: 1,
      grams: 1_200,
    },
    {
      key: 'cloth-foot-sandal',
      type: 'Moulded sandal',
      title: 'Moulded EVA Sandal with Adjustable Straps',
      brand: BRANDS.apparel,
      short:
        'One-piece moulded EVA sandal with adjustable straps and a contoured footbed.',
      long: 'A one-piece moulded EVA sandal with a contoured footbed and adjustable straps on both bars. Being a single moulding, there is nothing to come unglued, and it rinses clean under a tap.',
      img: 'sandals footwear summer shoes',
      specs: {
        Construction: 'One-piece moulded EVA',
        Footbed: 'Contoured',
        Straps: 'Adjustable on both bars',
        Cleaning: 'Rinses clean',
      },
      facets: ['Construction', 'Footbed'],
      axes: [
        ['size_system', ['UK', 'EU']],
        ['size', ['5', '6', '7', '8', '9', '10']],
        ['colour', ['Black', 'Navy', 'Olive']],
      ],
      price: [680_000, 2_400_000],
      stock: [8, 140],
      moq: 1,
      grams: 420,
      mrp: 0.17,
    },
  ]),

  shelf('fabrics-trims', [
    {
      key: 'cloth-fab-cotton',
      type: 'Cotton dress fabric',
      title: 'Plain-Weave Cotton Dress Fabric on a Roll',
      brand: BRANDS.textile,
      short:
        'Plain-weave cotton dress fabric on a roll, sold by the metre with the weight stated.',
      long: 'A plain-weave cotton dress fabric on a roll, sold by the metre, with the weight in grams per square metre and the usable width stated rather than left to be measured. Pre-shrunk, so a garment cut from it keeps its size.',
      img: 'cotton fabric roll textile material',
      specs: {
        Weave: 'Plain weave',
        Fibre: '100% cotton',
        Finish: 'Pre-shrunk',
        Marking: 'Weight and usable width stated',
      },
      facets: ['Weave', 'Fibre'],
      axes: [
        ['colour', ['Ecru', 'Black', 'Indigo', 'Olive']],
        ['length', ['5 m', '10 m', 'Full roll']],
      ],
      price: [980_000, 9_800_000],
      stock: [5, 100],
      moq: 1,
      grams: 1_600,
      sold: { content: [10, 'm'], per: [1, 'm'] },
      featured: true,
    },
    {
      key: 'cloth-fab-canvas',
      type: 'Cotton canvas',
      title: 'Heavy Cotton Canvas for Bags and Upholstery',
      brand: BRANDS.textile,
      short:
        'Heavy cotton canvas with a tight weave, for bags, aprons and light upholstery.',
      long: 'A heavy cotton canvas with a tight plain weave, for bags, aprons and light upholstery. It takes a dye evenly and softens with use rather than going limp, and the selvedge is firm enough to use as an edge.',
      img: 'canvas fabric heavy textile roll',
      specs: {
        Weave: 'Tight plain weave',
        Fibre: '100% cotton',
        Use: 'Bags, aprons and light upholstery',
        Selvedge: 'Firm',
      },
      facets: ['Weave', 'Use'],
      axes: [
        ['gsm', ['280 gsm', '340 gsm', '400 gsm']],
        ['colour', ['Natural', 'Black', 'Olive']],
      ],
      price: [1_280_00, 6_800_00],
      stock: [5, 90],
      moq: 1,
      grams: 3_400,
      sold: { content: [10, 'm'], per: [1, 'm'] },
    },
    {
      key: 'cloth-fab-zip',
      type: 'Continuous zip chain',
      title: 'Continuous Nylon Zip Chain with Loose Sliders',
      brand: BRANDS.textile,
      short:
        'Continuous nylon zip chain sold by the metre, with loose sliders supplied to match.',
      long: 'A continuous nylon zip chain sold by the metre, with loose sliders in a bag, so a zip can be made to length rather than bought at a size. The tape is polyester and the coil is nylon.',
      img: 'zip chain haberdashery sewing trims',
      specs: {
        Coil: 'Nylon',
        Tape: 'Polyester',
        Sliders: 'Supplied loose to match',
        Supply: 'By the metre',
      },
      facets: ['Coil', 'Supply'],
      axes: [
        ['fabric_type', ['No. 3', 'No. 5', 'No. 8']],
        ['colour', ['Black', 'White', 'Navy']],
        ['length', ['5 m', '25 m']],
      ],
      price: [280_000, 2_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 320,
      sold: { content: [5, 'm'], per: [1, 'm'] },
      mrp: 0.14,
    },
  ]),

  // =======================================================================
  // BEAUTY & PERSONAL CARE
  // =======================================================================
  shelf('skin-hair-care', [
    {
      key: 'beau-skin-serum',
      type: 'Facial serum',
      title: 'Lightweight Facial Serum in an Amber Dropper Bottle',
      brand: BRANDS.beauty,
      short:
        'Lightweight facial serum in an amber glass dropper bottle, fragrance free.',
      long: 'A lightweight facial serum in an amber glass bottle with a glass dropper, which keeps light off the contents and lets a measured amount be taken. Fragrance free and dye free, with the full ingredient list printed on the carton rather than only on a leaflet.',
      img: 'facial serum dropper bottle skincare',
      specs: {
        Texture: 'Lightweight, non-greasy',
        Bottle: 'Amber glass with glass dropper',
        Fragrance: 'Fragrance free',
        Labelling: 'Full ingredient list on the carton',
      },
      facets: ['Texture', 'Fragrance'],
      axes: [
        ['net_volume', ['15 ml', '30 ml', '50 ml']],
        ['pack_count', ['Single', 'Duo pack']],
      ],
      price: [480_000, 2_800_000],
      stock: [10, 200],
      moq: 1,
      grams: 140,
      sold: { content: [30, 'ml'], per: [100, 'ml'] },
      featured: true,
    },
    {
      key: 'beau-skin-shampoo',
      type: 'Shampoo',
      title: 'Sulphate-Free Shampoo with a Pump Bottle',
      brand: BRANDS.beauty,
      short:
        'Sulphate-free shampoo in a pump bottle, with a mild surfactant base and no added colour.',
      long: 'A sulphate-free shampoo built on a mild surfactant base, so it lathers less than a sulphate shampoo and strips less with it. Supplied in a pump bottle, with no added colour and the ingredient list printed on the bottle itself.',
      img: 'shampoo bottle hair care product',
      specs: {
        Base: 'Mild surfactants, sulphate free',
        Colour: 'No added colour',
        Bottle: 'Pump',
        Labelling: 'Ingredient list printed on bottle',
      },
      facets: ['Base', 'Colour'],
      axes: [
        ['net_volume', ['300 ml', '500 ml', '1 L']],
        ['suitability', ['All hair types', 'Dry hair', 'Oily scalp']],
      ],
      price: [280_000, 1_280_000],
      stock: [12, 220],
      moq: 1,
      grams: 540,
      sold: { content: [500, 'ml'], per: [1, 'L'] },
    },
    {
      key: 'beau-skin-bodylotion',
      type: 'Body lotion',
      title: 'Unscented Body Lotion in a Pump Dispenser',
      brand: BRANDS.beauty,
      short:
        'Unscented body lotion in a lockable pump dispenser, with a light non-greasy texture.',
      long: 'An unscented body lotion with a light texture that absorbs without leaving a film, in a pump that locks by turning so it does not empty itself in a bag. No fragrance and no dye.',
      img: 'body lotion pump bottle personal care',
      specs: {
        Fragrance: 'Unscented',
        Texture: 'Light, non greasy',
        Pump: 'Locks by turning',
        Dye: 'No added colour',
      },
      facets: ['Fragrance', 'Texture'],
      axes: [
        ['net_volume', ['250 ml', '400 ml', '1 L']],
        ['pack_count', ['Single', 'Pack of 3']],
      ],
      price: [180_000, 1_480_000],
      stock: [12, 220],
      moq: 1,
      grams: 460,
      sold: { content: [400, 'ml'], per: [1, 'L'] },
      mrp: 0.15,
    },
  ]),

  shelf('cosmetics', [
    {
      key: 'beau-cos-lipstick',
      type: 'Lipstick',
      title: 'Satin-Finish Lipstick in a Magnetic-Close Bullet',
      brand: BRANDS.beauty,
      short:
        'Satin-finish lipstick in a magnetic-close bullet, with the shade printed on the base.',
      long: 'A satin-finish lipstick in a metal bullet whose cap closes on a magnet rather than a friction fit, so it does not work loose in a bag. The shade name and number are printed on the base, which is the only place that survives the carton being thrown away.',
      img: 'lipstick cosmetics makeup product',
      specs: {
        Finish: 'Satin',
        Case: 'Metal bullet, magnetic close',
        Marking: 'Shade name and number on the base',
      },
      facets: ['Finish', 'Case'],
      axes: [
        ['colour', ['Rosewood', 'Brick', 'Berry', 'Nude']],
        ['pack_count', ['Single', 'Duo set']],
      ],
      price: [280_000, 1_280_000],
      stock: [12, 220],
      moq: 1,
      grams: 60,
      featured: true,
    },
    {
      key: 'beau-cos-foundation',
      type: 'Liquid foundation',
      title: 'Buildable Liquid Foundation with a Pump',
      brand: BRANDS.beauty,
      short:
        'Buildable liquid foundation with a pump dispenser and an undertone stated on each shade.',
      long: 'A buildable liquid foundation in a glass bottle with a pump, where each shade states its undertone as well as its depth - which is the information that actually decides whether a shade matches. Fragrance free.',
      img: 'liquid foundation makeup cosmetics bottle',
      specs: {
        Coverage: 'Buildable',
        Dispenser: 'Pump',
        Shades: 'Undertone stated with each shade',
        Fragrance: 'Fragrance free',
      },
      facets: ['Coverage', 'Fragrance'],
      axes: [
        ['colour', ['Porcelain', 'Sand', 'Honey', 'Amber', 'Espresso']],
        ['undertone', ['Cool', 'Neutral', 'Warm']],
      ],
      price: [420_000, 1_680_000],
      stock: [10, 200],
      moq: 1,
      grams: 120,
      sold: { content: [30, 'ml'], per: [100, 'ml'] },
    },
    {
      key: 'beau-cos-brushset',
      type: 'Makeup brush set',
      title: 'Synthetic Makeup Brush Set in a Roll Case',
      brand: BRANDS.beauty,
      short:
        'Synthetic-bristle makeup brush set in a roll case, with crimped ferrules.',
      long: 'A synthetic-bristle makeup brush set in a roll case, with crimped ferrules rather than glued ones - the join that sheds bristles after a few washes. The handles are lacquered and the set washes with soap and water.',
      img: 'makeup brush set cosmetics beauty',
      specs: {
        Bristles: 'Synthetic',
        Ferrules: 'Crimped',
        Case: 'Roll case',
        Care: 'Washes with soap and water',
      },
      facets: ['Bristles', 'Ferrules'],
      axes: [
        ['pack_count', ['7 piece', '12 piece']],
        ['colour', ['Black', 'Rose']],
      ],
      price: [680_000, 2_800_000],
      stock: [8, 160],
      moq: 1,
      grams: 320,
      mrp: 0.16,
    },
  ]),

  shelf('personal-hygiene', [
    {
      key: 'beau-hyg-toothbrush',
      type: 'Toothbrush',
      title: 'Soft-Bristle Toothbrush with a Tapered Head',
      brand: BRANDS.beauty,
      short:
        'Soft-bristle toothbrush with a tapered head and a moulded non-slip grip.',
      long: 'A soft-bristle toothbrush with a tapered head that reaches behind the back teeth, end-rounded filaments and a moulded non-slip grip. Sold in multi-packs with a travel cap per brush.',
      img: 'toothbrush oral care hygiene',
      specs: {
        Bristles: 'Soft, end-rounded filaments',
        Head: 'Tapered',
        Handle: 'Moulded non-slip grip',
        Supplied: 'Travel cap per brush',
      },
      facets: ['Bristles', 'Head'],
      axes: [
        ['pack_count', ['Pack of 4', 'Pack of 12']],
        ['form', ['Flat trim', 'Tapered trim']],
      ],
      price: [96_000, 380_000],
      stock: [20, 360],
      moq: 1,
      grams: 120,
      sold: { content: [4, 'piece'], label: 'Pack of 4' },
      multipack: 4,
      featured: true,
    },
    {
      key: 'beau-hyg-razor',
      type: 'Safety razor',
      title: 'Double-Edge Safety Razor with a Knurled Handle',
      brand: BRANDS.beauty,
      short:
        'Brass double-edge safety razor with a knurled handle and a three-piece head.',
      long: 'A brass double-edge safety razor with a chrome finish, a knurled handle and a three-piece head that unscrews completely for cleaning. It takes standard double-edge blades, five of which are supplied.',
      img: 'safety razor shaving personal care',
      specs: {
        Body: 'Brass with chrome finish',
        Head: 'Three piece, fully removable',
        Blades: 'Standard double edge, five supplied',
        Handle: 'Knurled',
      },
      facets: ['Body', 'Head'],
      axes: [
        ['product_type', ['Razor only', 'Razor with blade pack', 'Razor with stand']],
        ['size', ['Standard handle', 'Long handle']],
      ],
      price: [680_000, 2_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 120,
    },
    {
      key: 'beau-hyg-sanitarypad',
      type: 'Sanitary pad',
      title: 'Cotton-Topsheet Sanitary Pad with Wings',
      brand: BRANDS.beauty,
      short:
        'Sanitary pad with a cotton topsheet, wings and an individually wrapped disposal sleeve.',
      long: 'A sanitary pad with a cotton topsheet rather than a plastic one, wings, and an individual wrapper that doubles as a disposal sleeve. Unfragranced, and the absorbency is shown on the wrapper as well as the pack.',
      img: 'sanitary pads hygiene personal care',
      specs: {
        Topsheet: 'Cotton',
        Wings: 'Yes',
        Wrapper: 'Individual, doubles as disposal sleeve',
        Fragrance: 'Unfragranced',
      },
      facets: ['Topsheet', 'Fragrance'],
      axes: [
        ['absorbency', ['Regular', 'Super', 'Night']],
        ['pack_count', ['Pack of 10', 'Pack of 30']],
      ],
      price: [96_000, 420_000],
      stock: [20, 360],
      moq: 1,
      grams: 260,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      mrp: 0.13,
    },
  ]),

  shelf('salon-spa-supplies', [
    {
      key: 'beau-salon-towel',
      type: 'Salon towel',
      title: 'Bleach-Resistant Salon Towel in a Dozen Pack',
      brand: BRANDS.beauty,
      short:
        'Bleach-resistant salon towel in a dozen pack, dyed to survive colour and peroxide.',
      long: 'A salon towel dyed to survive colour and peroxide without going patchy, which an ordinary bath towel does in a fortnight. Hemmed on all four sides and sized for a neck rather than a body.',
      img: 'salon towels spa supplies',
      specs: {
        Dye: 'Bleach resistant',
        Hem: 'All four sides',
        Size: 'Salon size, 40 x 70 cm',
        Fibre: 'Cotton',
      },
      facets: ['Dye', 'Fibre'],
      axes: [
        ['colour', ['Black', 'Charcoal', 'Burgundy']],
        ['pack_count', ['Pack of 12', 'Case of 60']],
      ],
      price: [980_000, 4_200_000],
      stock: [8, 160],
      moq: 1,
      grams: 1_800,
      sold: { content: [12, 'piece'], label: 'Pack of 12' },
      multipack: 12,
      featured: true,
    },
    {
      key: 'beau-salon-capes',
      type: 'Cutting cape',
      title: 'Lightweight Cutting Cape with Snap Closure',
      brand: BRANDS.beauty,
      short:
        'Lightweight cutting cape in a static-resistant fabric, with a multi-position snap closure.',
      long: 'A lightweight cutting cape in a static-resistant fabric, so hair clippings slide off instead of clinging. The neck closes on a row of snaps so it can be set to the client rather than one size.',
      img: 'salon cutting cape hairdressing supplies',
      specs: {
        Fabric: 'Static resistant',
        Closure: 'Multi-position snaps',
        Care: 'Machine washable at 40 C',
      },
      facets: ['Fabric', 'Closure'],
      axes: [
        ['colour', ['Black', 'Graphite']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [280_000, 1_680_000],
      stock: [10, 180],
      moq: 1,
      grams: 320,
    },
    {
      key: 'beau-salon-massageoil',
      type: 'Massage oil',
      title: 'Unscented Massage Oil in a Pump Bottle',
      brand: BRANDS.beauty,
      short:
        'Unscented massage oil with a long glide, in a pump bottle and a refill container.',
      long: 'An unscented massage oil with a long glide, so it does not need reapplying part way through a treatment, in a pump bottle with a matching refill container. No fragrance and no added colour.',
      img: 'massage oil bottle spa professional',
      specs: {
        Fragrance: 'Unscented',
        Glide: 'Long glide',
        Supply: 'Pump bottle and refill container',
        Colour: 'No added colour',
      },
      facets: ['Fragrance', 'Colour'],
      axes: [
        ['capacity', ['250 ml', '500 ml', '5 L']],
        ['application', ['Pump bottle', 'Refill container']],
      ],
      price: [280_000, 2_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 560,
      sold: { content: [500, 'ml'], per: [1, 'L'] },
      mrp: 0.14,
    },
  ]),
];
