/**
 * Electrical & Lighting, Electronics & Components, Computers & IT,
 * Phones & Communication.
 *
 * Twenty shelves, three products each. The same rule as everywhere else: the
 * axis keys are the ones the sub-category's variant template offers, and a
 * typo is a failing test rather than a broken selector.
 *
 * Two things this department group is careful about.
 *
 * **No real brand appears.** Not as a product name, not as a compatibility
 * claim, not in a specification. "Fits the common pen standard" says what a
 * buyer needs to know; naming somebody else's pen does not, and it is their
 * trade mark rather than ours to put on a card.
 *
 * **No performance claim that could not be measured.** A router has ports and
 * a radio standard; it does not have "blazing speed". A laptop has a
 * processor, memory and a panel; it does not have "the best value in its
 * class". Where a figure is quoted it is the kind of figure a data sheet
 * carries, and it is plainly synthetic like everything else here.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const ELECTRONICS_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // ELECTRICAL & LIGHTING
  // =======================================================================
  shelf('cables-wiring', [
    {
      key: 'elec-cable-armoured',
      type: 'Armoured power cable',
      title: 'Copper Armoured Power Cable, XLPE Insulated',
      brand: BRANDS.electrical,
      short:
        'XLPE-insulated copper power cable with a galvanised steel wire armour and a PVC outer sheath.',
      long: 'A power cable with stranded copper conductors, XLPE insulation, a bedding layer, a galvanised steel wire armour and a black PVC outer sheath. The armour is the mechanical protection that lets the cable be buried or clipped in a plant room without a separate conduit, and it doubles as the earth path.',
      img: 'industrial copper armoured electrical cable reel',
      specs: {
        Conductor: 'Stranded copper, Class 2',
        Insulation: 'XLPE',
        Armour: 'Galvanised steel wire',
        Sheath: 'PVC, black',
        'Operating temperature': '90 C conductor',
      },
      facets: ['Conductor', 'Insulation', 'Armour'],
      axes: [
        ['cores', ['2 core', '3 core', '4 core']],
        ['cross_section', ['1.5 mm2', '2.5 mm2', '4 mm2', '6 mm2']],
        ['length', ['50 m reel', '100 m reel']],
      ],
      price: [4_200_00, 68_000_00],
      stock: [4, 60],
      moq: 1,
      grams: 42_000,
      sold: { content: [100, 'm'], per: [1, 'm'], label: '100 m reel' },
      featured: true,
    },
    {
      key: 'elec-cable-flex',
      type: 'Flexible cable',
      title: 'Multi-Core Flexible Cable with PVC Sheath',
      brand: BRANDS.electrical,
      short:
        'Finely stranded flexible cable with PVC insulation and sheath, for appliance and panel wiring.',
      long: 'A flexible cable with finely stranded copper conductors, so it tolerates repeated movement without work-hardening. The cores are colour-coded to the harmonised scheme, and the sheath carries the type and the size printed at one-metre intervals.',
      img: 'flexible electrical cable coil pvc',
      specs: {
        Conductor: 'Finely stranded copper, Class 5',
        Insulation: 'PVC',
        Coding: 'Harmonised core colours',
        Marking: 'Type and size printed each metre',
      },
      facets: ['Conductor', 'Insulation'],
      axes: [
        ['cores', ['2 core', '3 core', '4 core', '5 core']],
        ['cross_section', ['0.75 mm2', '1.0 mm2', '1.5 mm2']],
        ['colour', ['White', 'Black']],
      ],
      price: [1_450_00, 12_800_00],
      stock: [8, 120],
      moq: 1,
      grams: 9_800,
      sold: { content: [100, 'm'], per: [1, 'm'], label: '100 m coil' },
    },
    {
      key: 'elec-cable-datacat6',
      type: 'Data cable',
      title: 'Cat 6 U/UTP Data Cable in a Pull Box',
      brand: BRANDS.network,
      short:
        'Solid-conductor Cat 6 U/UTP data cable with a cross-filler, supplied in a 305 m pull box.',
      long: 'A solid-conductor Cat 6 data cable with a cross-shaped filler holding the four pairs apart, which is what keeps crosstalk down at the higher frequencies. Supplied in a pull box with the remaining length printed along the sheath so an installer can see what is left.',
      img: 'cat6 network data cable box ethernet',
      specs: {
        Category: 'Cat 6 U/UTP',
        Conductor: 'Solid copper, 23 AWG',
        Filler: 'Cross filler between pairs',
        Marking: 'Sequential length printed on sheath',
      },
      facets: ['Category', 'Conductor'],
      axes: [
        ['length', ['100 m', '305 m']],
        ['colour', ['Grey', 'Blue', 'Violet']],
        ['insulation', ['PVC', 'LSZH']],
      ],
      price: [4_800_00, 22_000_00],
      stock: [5, 70],
      moq: 1,
      grams: 12_600,
      sold: { content: [305, 'm'], per: [1, 'm'], label: '305 m pull box' },
      mrp: 0.11,
    },
  ]),

  shelf('switches-sockets', [
    {
      key: 'elec-switch-modular',
      type: 'Modular switch',
      title: 'Modular Wall Switch with Soft-Touch Rocker',
      brand: BRANDS.electrical,
      short:
        'Modular one-way wall switch with a soft-touch rocker and screwless terminals.',
      long: 'A modular wall switch that clips into a standard grid plate, with a soft-touch rocker and screwless push terminals that take a stripped solid conductor without a driver. The module carries its rating moulded into the back.',
      img: 'modular wall switch electrical white',
      specs: {
        Mounting: 'Standard modular grid',
        Terminals: 'Screwless push terminals',
        Rocker: 'Soft touch',
        Marking: 'Rating moulded on rear',
      },
      facets: ['Mounting', 'Terminals'],
      axes: [
        ['module_size', ['1 module', '2 module']],
        ['current_rating', ['6 A', '10 A', '16 A']],
        ['colour', ['White', 'Ivory', 'Graphite']],
      ],
      price: [12_000, 96_000],
      stock: [40, 600],
      moq: 5,
      step: 5,
      grams: 60,
      featured: true,
    },
    {
      key: 'elec-socket-usb',
      type: 'Socket outlet with USB',
      title: 'Twin Socket Outlet with Integrated USB Charging',
      brand: BRANDS.electrical,
      short:
        'Twin switched socket outlet with two integrated USB charging ports and a shuttered face.',
      long: 'A twin switched socket outlet with two USB charging ports built into the face plate. The mains outlets are shuttered, the USB section is isolated from the mains section behind a barrier, and the rocker switches are individually marked.',
      img: 'wall socket outlet usb charging electrical',
      specs: {
        Outlets: 'Twin, switched and shuttered',
        USB: 'Two ports, isolated section',
        'Plate depth': '35 mm back box',
        Terminals: 'Screw terminals, captive',
      },
      facets: ['Outlets', 'USB'],
      axes: [
        ['ways', ['2 gang']],
        ['finish', ['Matt white', 'Brushed steel', 'Matt black']],
        ['current_rating', ['13 A', '16 A']],
      ],
      price: [82_000, 380_000],
      stock: [20, 300],
      moq: 1,
      grams: 240,
    },
    {
      key: 'elec-switch-industrial',
      type: 'Industrial socket',
      title: 'IP67 Industrial Interlocked Socket Outlet',
      brand: BRANDS.electrical,
      short:
        'IP67 industrial socket with a mechanical interlock that stops the plug being drawn under load.',
      long: 'An industrial socket outlet with a mechanical interlock: the switch cannot be closed until a plug is inserted and the plug cannot be withdrawn while the switch is closed. Rated IP67 with the lid shut, in a glass-reinforced polyester enclosure.',
      img: 'industrial socket outlet ip67 electrical blue',
      specs: {
        Protection: 'IP67 with lid closed',
        Interlock: 'Mechanical, switch and plug',
        Enclosure: 'Glass-reinforced polyester',
        Standard: 'IEC 60309 pin pattern',
      },
      facets: ['Protection', 'Interlock'],
      axes: [
        ['current_rating', ['16 A', '32 A', '63 A']],
        ['ways', ['3 pin', '4 pin', '5 pin']],
      ],
      price: [980_000, 6_400_000],
      stock: [6, 90],
      moq: 1,
      grams: 980,
      mrp: 0.12,
    },
  ]),

  shelf('circuit-protection', [
    {
      key: 'elec-prot-mcb',
      type: 'Miniature circuit breaker',
      title: 'Miniature Circuit Breaker, DIN Rail Mounting',
      brand: BRANDS.electrical,
      short:
        'DIN rail miniature circuit breaker with a trip-free mechanism and a captive terminal screw.',
      long: 'A DIN rail miniature circuit breaker with a trip-free mechanism, so holding the lever will not defeat a trip. The terminals are captive and take a busbar or a conductor, and the front carries a window showing the contact position rather than only the lever.',
      img: 'miniature circuit breaker mcb electrical din rail',
      specs: {
        Mounting: '35 mm DIN rail',
        Mechanism: 'Trip free',
        Terminals: 'Captive, busbar compatible',
        Indication: 'Contact position window',
      },
      facets: ['Mounting', 'Mechanism'],
      axes: [
        ['poles', ['1 pole', '2 pole', '3 pole']],
        ['current_rating', ['6 A', '10 A', '16 A', '32 A']],
        ['trip_curve', ['Type B', 'Type C']],
      ],
      price: [24_000, 420_000],
      stock: [25, 400],
      moq: 1,
      grams: 120,
      featured: true,
    },
    {
      key: 'elec-prot-rcbo',
      type: 'Residual current breaker with overload',
      title: 'RCBO with Earth Leakage and Overload Protection',
      brand: BRANDS.electrical,
      short:
        'Single-module RCBO combining earth leakage and overload protection with a test button.',
      long: 'An RCBO that puts earth leakage and overload protection in one module, so a consumer unit carries one device per circuit rather than a shared leakage device. The test button is on the face and the flag shows which of the two functions tripped.',
      img: 'rcbo electrical protection device consumer unit',
      specs: {
        Functions: 'Earth leakage and overload in one module',
        Test: 'Front test button',
        Indication: 'Trip cause flag',
        Mounting: '35 mm DIN rail',
      },
      facets: ['Functions', 'Mounting'],
      axes: [
        ['current_rating', ['6 A', '16 A', '32 A']],
        ['sensitivity', ['30 mA', '100 mA']],
        ['trip_curve', ['Type B', 'Type C']],
      ],
      price: [280_000, 980_000],
      stock: [12, 180],
      moq: 1,
      grams: 180,
    },
    {
      key: 'elec-prot-spd',
      type: 'Surge protection device',
      title: 'Type 2 Surge Protection Device with Status Window',
      brand: BRANDS.electrical,
      short:
        'Type 2 DIN rail surge protection device with pluggable modules and a mechanical status window.',
      long: 'A Type 2 surge protection device for a distribution board, with pluggable modules so a spent cartridge is replaced without rewiring. A mechanical window turns from green to red when a module has reached the end of its life.',
      img: 'surge protection device electrical din rail',
      specs: {
        Type: 'Type 2',
        Modules: 'Pluggable cartridges',
        Indication: 'Mechanical status window',
        Mounting: '35 mm DIN rail',
      },
      facets: ['Type', 'Modules'],
      axes: [
        ['poles', ['1+N', '3+N']],
        ['voltage_rating', ['275 V', '385 V']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [5, 70],
      moq: 1,
      grams: 420,
      mrp: 0.1,
    },
  ]),

  shelf('motors-drives', [
    {
      key: 'elec-motor-induction',
      type: 'Three-phase induction motor',
      title: 'Three-Phase Squirrel Cage Induction Motor, IE3',
      brand: BRANDS.drives,
      short:
        'IE3 three-phase induction motor in a cast iron frame, foot mounted with an IP55 enclosure.',
      long: 'A three-phase squirrel cage induction motor in a cast iron frame, foot mounted, with an IP55 enclosure and a terminal box that can be rotated in ninety degree steps. The shaft is keyed and the bearings are greased for life at the smaller frame sizes.',
      img: 'three phase electric motor industrial',
      specs: {
        Frame: 'Cast iron, foot mounted',
        Enclosure: 'IP55',
        'Efficiency class': 'IE3',
        'Terminal box': 'Rotatable in 90 degree steps',
        Insulation: 'Class F',
      },
      facets: ['Efficiency class', 'Enclosure', 'Frame'],
      axes: [
        ['output_power', ['0.75 kW', '1.5 kW', '3 kW', '5.5 kW']],
        ['speed', ['1,440 rpm', '2,880 rpm']],
      ],
      price: [9_800_00, 62_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 28_000,
      leadDays: 7,
      featured: true,
    },
    {
      key: 'elec-motor-vfd',
      type: 'Variable frequency drive',
      title: 'Variable Frequency Drive with Keypad and Modbus',
      brand: BRANDS.drives,
      short:
        'Wall-mounting variable frequency drive with a detachable keypad, Modbus RTU and a built-in filter.',
      long: 'A variable frequency drive for a three-phase motor, with a detachable keypad that can be panel mounted on a lead. Modbus RTU is on a screw terminal port, and an EMC filter is built into the drive rather than supplied as an accessory.',
      img: 'variable frequency drive inverter industrial',
      specs: {
        Keypad: 'Detachable, panel mountable',
        Communications: 'Modbus RTU',
        Filter: 'Integrated EMC filter',
        Mounting: 'Wall or panel',
      },
      facets: ['Communications', 'Filter'],
      axes: [
        ['output_power', ['0.75 kW', '1.5 kW', '2.2 kW', '4 kW']],
        ['voltage', ['230 V single phase', '415 V three phase']],
      ],
      price: [11_500_00, 48_000_00],
      stock: [2, 26],
      moq: 1,
      grams: 3_800,
      leadDays: 5,
    },
    {
      key: 'elec-motor-gearbox',
      type: 'Worm gearbox',
      title: 'Aluminium Worm Gearbox with Hollow Output Shaft',
      brand: BRANDS.drives,
      short:
        'Aluminium-cased worm gearbox with a hollow output shaft and a standard motor flange.',
      long: 'A worm gearbox in a die-cast aluminium case, with a hollow output shaft that slides over a driven shaft and a standard input flange for a motor. It is filled for life with synthetic oil and can be mounted in any of six positions.',
      img: 'worm gearbox industrial aluminium drive',
      specs: {
        Case: 'Die-cast aluminium',
        Output: 'Hollow shaft',
        Lubrication: 'Synthetic oil, filled for life',
        Mounting: 'Six positions',
      },
      facets: ['Case', 'Output'],
      axes: [
        ['frame_size', ['Size 63', 'Size 75', 'Size 90']],
        ['speed', ['7.5:1', '15:1', '30:1', '60:1']],
      ],
      price: [4_800_00, 24_000_00],
      stock: [3, 40],
      moq: 1,
      grams: 6_400,
      mrp: 0.12,
    },
  ]),

  shelf('lighting', [
    {
      key: 'elec-light-panel',
      type: 'LED ceiling panel',
      title: '24 W LED Ceiling Panel with Flicker-Free Driver',
      brand: BRANDS.lighting,
      short:
        'Recessed LED ceiling panel with an edge-lit diffuser and a flicker-free constant current driver.',
      long: 'A recessed LED ceiling panel with an edge-lit light guide behind an opal diffuser, so the face is evenly lit rather than dotted. The driver is constant current and flicker-free at full output, and it is supplied on a lead with a push-fit connector.',
      img: 'led ceiling panel light fixture office',
      specs: {
        Construction: 'Edge-lit light guide, opal diffuser',
        Driver: 'Constant current, flicker-free, supplied',
        'Colour rendering': 'Ra 80',
        Mounting: 'Recessed into a modular ceiling',
      },
      facets: ['Driver', 'Colour rendering'],
      axes: [
        ['wattage', ['18 W', '24 W', '36 W']],
        ['colour_temperature', ['3000 K', '4000 K', '6500 K']],
        ['size', ['600 x 600 mm', '1200 x 300 mm']],
      ],
      price: [780_000, 3_400_000],
      stock: [10, 160],
      moq: 1,
      grams: 2_600,
      featured: true,
    },
    {
      key: 'elec-light-battenled',
      type: 'LED batten',
      title: 'IP65 LED Batten with Stainless Clips',
      brand: BRANDS.lighting,
      short:
        'Weatherproof IP65 LED batten in a polycarbonate body with stainless steel closure clips.',
      long: 'A weatherproof LED batten in a polycarbonate body with a frosted diffuser and stainless steel closure clips, for a car park, a plant room or an unheated store. Through-wiring is on a push-fit block so a run can be linked without a junction box.',
      img: 'led batten light weatherproof industrial fixture',
      specs: {
        Protection: 'IP65',
        Body: 'Polycarbonate with stainless clips',
        Wiring: 'Push-fit through-wiring block',
        'Colour rendering': 'Ra 80',
      },
      facets: ['Protection', 'Body'],
      axes: [
        ['wattage', ['20 W', '40 W', '50 W']],
        ['size', ['1,200 mm', '1,500 mm']],
        ['colour_temperature', ['4000 K', '6500 K']],
      ],
      price: [1_180_00, 4_200_00],
      stock: [8, 120],
      moq: 1,
      grams: 2_200,
    },
    {
      key: 'elec-light-lamp',
      type: 'LED lamp',
      title: 'LED GLS Lamp with Frosted Glass Envelope',
      brand: BRANDS.lighting,
      short:
        'LED GLS lamp in a frosted glass envelope, sold singly or in trade packs.',
      long: 'An LED lamp in a traditional GLS shape with a frosted glass envelope rather than a plastic one, so it looks and feels like a lamp. Non-dimmable at the lower outputs and dimmable at the higher, which the box states plainly.',
      img: 'led light bulb lamp frosted glass',
      specs: {
        Envelope: 'Frosted glass',
        Shape: 'GLS',
        'Colour rendering': 'Ra 80',
        Life: 'Rated 15,000 hours',
      },
      facets: ['Envelope', 'Shape'],
      axes: [
        ['wattage', ['5 W', '8 W', '12 W']],
        ['base_type', ['E27', 'B22']],
        ['pack_count', ['Single', 'Pack of 4', 'Pack of 10']],
      ],
      price: [12_000, 420_000],
      stock: [30, 500],
      moq: 1,
      grams: 60,
      mrp: 0.18,
    },
  ]),

  shelf('batteries-power-supplies', [
    {
      key: 'elec-batt-alkaline',
      type: 'Alkaline battery',
      title: 'Alkaline Battery in an Industrial Trade Pack',
      brand: BRANDS.electrical,
      short:
        'Alkaline primary cells in a plain industrial trade pack, with the best-before date printed on each cell.',
      long: 'Alkaline primary cells in a plain trade pack rather than a retail blister, for a stores cupboard. The best-before date is printed on each cell and the pack carries a single batch code.',
      img: 'alkaline batteries industrial pack cells',
      specs: {
        Chemistry: 'Alkaline manganese',
        Packaging: 'Industrial trade pack',
        Marking: 'Best-before date on each cell',
        Rechargeable: 'No',
      },
      facets: ['Chemistry', 'Rechargeable'],
      axes: [
        ['form_factor', ['AA', 'AAA', 'C', 'D', '9 V']],
        ['pack_count', ['Pack of 10', 'Box of 40']],
      ],
      price: [32_000, 320_000],
      stock: [25, 400],
      moq: 1,
      grams: 480,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      featured: true,
    },
    {
      key: 'elec-batt-lifepo4',
      type: 'Lithium iron phosphate battery',
      title: 'LiFePO4 Battery with Integrated Management System',
      brand: BRANDS.energy,
      short:
        'Lithium iron phosphate battery with an integrated management system and a state-of-charge display.',
      long: 'A lithium iron phosphate battery in a sealed ABS case, with a management system that balances the cells and cuts off on over-current, over-temperature and low voltage. A push-button display shows the state of charge.',
      img: 'lithium battery pack energy storage',
      specs: {
        Chemistry: 'Lithium iron phosphate',
        Management: 'Integrated BMS with balancing and cut-offs',
        Display: 'Push-button state of charge',
        Terminals: 'M8 studs',
      },
      facets: ['Chemistry', 'Management'],
      axes: [
        ['voltage_rating', ['12.8 V', '25.6 V']],
        ['battery_capacity', ['50 Ah', '100 Ah', '200 Ah']],
      ],
      price: [22_000_00, 128_000_00],
      stock: [1, 18],
      moq: 1,
      grams: 12_500,
      leadDays: 10,
    },
    {
      key: 'elec-psu-dinrail',
      type: 'DIN rail power supply',
      title: 'DIN Rail Switch Mode Power Supply with Wide Input',
      brand: BRANDS.electrical,
      short:
        'DIN rail switch mode power supply with a wide AC input range and an adjustable output.',
      long: 'A DIN rail switch mode power supply with a wide AC input range, so one part number works on a 230 volt and a 110 volt supply. The output is adjustable over a small range with a recessed trimmer, and a green LED shows the DC is present.',
      img: 'din rail power supply industrial electrical',
      specs: {
        Input: 'Wide range AC',
        Output: 'Adjustable with recessed trimmer',
        Indication: 'DC-on LED',
        Mounting: '35 mm DIN rail',
        Protection: 'Short circuit, overload, over-temperature',
      },
      facets: ['Input', 'Mounting'],
      axes: [
        ['output_rating', ['12 V DC', '24 V DC']],
        ['battery_capacity', ['60 W', '120 W', '240 W']],
      ],
      price: [1_280_00, 6_400_00],
      stock: [6, 90],
      moq: 1,
      grams: 620,
      mrp: 0.11,
    },
  ]),

  // =======================================================================
  // ELECTRONICS & COMPONENTS
  // =======================================================================
  shelf('electronic-components', [
    {
      key: 'ecmp-resistor-kit',
      type: 'Resistor assortment',
      title: 'Metal Film Resistor Assortment in a Labelled Box',
      brand: BRANDS.electronics,
      short:
        'Metal film resistor assortment on labelled tapes in a compartmented box, one value per compartment.',
      long: 'A metal film resistor assortment supplied on cut tapes, one value to a labelled compartment, so a value is found rather than counted out of a bag. The box lid carries a printed index of the values inside.',
      img: 'resistor assortment kit electronic components',
      specs: {
        Type: 'Metal film, axial',
        Presentation: 'Cut tapes in labelled compartments',
        Index: 'Printed value index in lid',
        'Temperature coefficient': '100 ppm/K',
      },
      facets: ['Type', 'Temperature coefficient'],
      axes: [
        ['tolerance', ['1%', '5%']],
        ['power_rating', ['0.25 W', '0.5 W']],
        ['pack_count', ['600 piece', '1,280 piece']],
      ],
      price: [280_000, 980_000],
      stock: [10, 160],
      moq: 1,
      grams: 480,
      featured: true,
    },
    {
      key: 'ecmp-capacitor-electro',
      type: 'Electrolytic capacitor',
      title: 'Radial Aluminium Electrolytic Capacitor, 105 C',
      brand: BRANDS.electronics,
      short:
        'Radial aluminium electrolytic capacitor rated to 105 degrees, with a scored vent.',
      long: 'A radial aluminium electrolytic capacitor rated for 105 degrees, with a scored vent in the can so an over-pressure relieves upward rather than sideways. The sleeve carries the value, the voltage, the tolerance and the date code.',
      img: 'electrolytic capacitors electronic components',
      specs: {
        Type: 'Aluminium electrolytic, radial',
        'Temperature grade': '105 C',
        Vent: 'Scored can vent',
        Marking: 'Value, voltage, tolerance and date code',
      },
      facets: ['Type', 'Temperature grade'],
      axes: [
        ['value', ['100 uF', '470 uF', '1000 uF', '2200 uF']],
        ['voltage_rating', ['25 V', '35 V', '63 V']],
        ['pack_count', ['Pack of 25', 'Pack of 100']],
      ],
      price: [18_000, 280_000],
      stock: [20, 320],
      moq: 1,
      grams: 120,
    },
    {
      key: 'ecmp-mcu-board',
      type: 'Microcontroller development board',
      title: 'Microcontroller Development Board with USB-C',
      brand: BRANDS.electronics,
      short:
        'Microcontroller development board with USB-C, castellated edges and a 2.54 mm header pitch.',
      long: 'A microcontroller development board on a 2.54 mm header pitch with castellated edges, so it can be used on a breadboard during development and reflowed onto a carrier afterwards. Power and programming are both over USB-C, and a reset and a boot button are on the top face.',
      img: 'microcontroller development board pcb electronics',
      specs: {
        Interface: 'USB-C, power and programming',
        Pitch: '2.54 mm headers, castellated edges',
        Buttons: 'Reset and boot',
        'Supply voltage': '3.3 V logic',
      },
      facets: ['Interface', 'Pitch'],
      axes: [
        ['value', ['Base', 'With wireless']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [340_000, 2_400_000],
      stock: [12, 200],
      moq: 1,
      grams: 25,
      mrp: 0.13,
    },
  ]),

  shelf('sensors-automation', [
    {
      key: 'sens-proximity',
      type: 'Inductive proximity sensor',
      title: 'Inductive Proximity Sensor with M12 Connector',
      brand: BRANDS.electronics,
      short:
        'Barrel-form inductive proximity sensor with an M12 connector, an IP67 body and an output LED.',
      long: 'A barrel-form inductive proximity sensor in a nickel-plated brass body with an IP67 rating and an M12 connector on the tail. An LED on the barrel shows the output state so the switching point can be set without a meter.',
      img: 'inductive proximity sensor industrial automation',
      specs: {
        Body: 'Nickel-plated brass, IP67',
        Connection: 'M12 connector',
        Indication: 'Output state LED',
        Sensing: 'Inductive, ferrous and non-ferrous metals',
      },
      facets: ['Body', 'Connection'],
      axes: [
        ['sensing_range', ['2 mm', '4 mm', '8 mm']],
        ['output_type', ['PNP normally open', 'NPN normally open']],
        ['supply_voltage', ['10-30 V DC']],
      ],
      price: [380_000, 1_480_000],
      stock: [10, 160],
      moq: 1,
      grams: 90,
      featured: true,
    },
    {
      key: 'sens-temp-transmitter',
      type: 'Temperature transmitter',
      title: 'Loop-Powered Temperature Transmitter, Head Mounting',
      brand: BRANDS.electronics,
      short:
        'Loop-powered head-mounting temperature transmitter with a configurable input and a 4-20 mA output.',
      long: 'A loop-powered temperature transmitter that fits inside a sensor head, converting a resistance thermometer or a thermocouple to a 4-20 mA signal. The range is configured over a USB adapter and stored in the transmitter, so a spare can be swapped in already set.',
      img: 'temperature transmitter industrial sensor head',
      specs: {
        Power: 'Loop powered',
        Input: 'Resistance thermometer or thermocouple',
        Output: '4-20 mA',
        Configuration: 'USB adapter, stored in device',
      },
      facets: ['Power', 'Output'],
      axes: [
        ['sensing_range', ['-50 to 250 C', '0 to 600 C']],
        ['accuracy', ['+/- 0.2 C', '+/- 0.5 C']],
      ],
      price: [980_000, 3_800_000],
      stock: [6, 90],
      moq: 1,
      grams: 60,
    },
    {
      key: 'sens-relay-plc',
      type: 'Programmable logic controller',
      title: 'Compact Programmable Logic Controller with Relay Outputs',
      brand: BRANDS.electronics,
      short:
        'Compact DIN rail PLC with digital inputs, relay outputs and an Ethernet programming port.',
      long: 'A compact DIN rail programmable logic controller with digital inputs, relay outputs and an Ethernet port used for both programming and Modbus TCP. The terminal blocks are removable, so a unit can be swapped without disturbing the wiring.',
      img: 'plc controller industrial automation din rail',
      specs: {
        Mounting: '35 mm DIN rail',
        Outputs: 'Relay',
        Communications: 'Ethernet, Modbus TCP',
        Terminals: 'Removable blocks',
      },
      facets: ['Outputs', 'Communications'],
      axes: [
        ['sensing_range', ['8 in / 6 out', '16 in / 12 out']],
        ['supply_voltage', ['24 V DC', '230 V AC']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [3, 42],
      moq: 1,
      grams: 480,
      leadDays: 5,
      mrp: 0.1,
    },
  ]),

  shelf('test-measurement', [
    {
      key: 'test-multimeter',
      type: 'Digital multimeter',
      title: 'True RMS Digital Multimeter with CAT III Rating',
      brand: BRANDS.electronics,
      short:
        'True RMS digital multimeter with a CAT III safety rating, a backlit display and shrouded leads.',
      long: 'A true RMS digital multimeter with a CAT III safety rating, a backlit display and a bar graph under the digits. The leads are shrouded and CAT-rated to match the meter, and the input jacks are recessed.',
      img: 'digital multimeter electrical test instrument',
      specs: {
        Measurement: 'True RMS',
        'Safety category': 'CAT III',
        Display: 'Backlit with bar graph',
        Leads: 'Shrouded, CAT rated',
      },
      facets: ['Measurement', 'Safety category'],
      axes: [
        ['measurement_range', ['600 V', '1000 V']],
        ['kit_contents', ['Meter and leads', 'Meter, leads and clamp adapter']],
      ],
      price: [1_480_00, 8_900_00],
      stock: [6, 90],
      moq: 1,
      grams: 640,
      featured: true,
    },
    {
      key: 'test-oscilloscope',
      type: 'Digital storage oscilloscope',
      title: 'Two-Channel Digital Storage Oscilloscope',
      brand: BRANDS.electronics,
      short:
        'Two-channel benchtop digital storage oscilloscope with a colour display and USB export.',
      long: 'A two-channel benchtop digital storage oscilloscope with a colour display, automatic measurements and a USB port for exporting a screen or a waveform. Passive probes are supplied with each channel.',
      img: 'oscilloscope electronics test equipment bench',
      specs: {
        Channels: 'Two',
        Display: 'Colour TFT',
        Export: 'USB screen and waveform export',
        Probes: 'One passive probe per channel',
      },
      facets: ['Channels'],
      axes: [
        ['bandwidth', ['70 MHz', '100 MHz', '200 MHz']],
        ['kit_contents', ['Scope and probes', 'Scope, probes and carry case']],
      ],
      price: [28_000_00, 96_000_00],
      stock: [1, 16],
      moq: 1,
      grams: 3_600,
      leadDays: 7,
    },
    {
      key: 'test-clampmeter',
      type: 'Clamp meter',
      title: 'AC/DC Clamp Meter with Inrush Capture',
      brand: BRANDS.electronics,
      short:
        'AC and DC clamp meter with inrush capture, a flashlight in the jaw and a hold function.',
      long: 'A clamp meter reading both AC and DC current, with an inrush capture mode that records the starting current of a motor. A small light in the jaw shows the conductor in a dark panel, and the display holds the last reading.',
      img: 'clamp meter electrical measurement tool',
      specs: {
        Measurement: 'AC and DC current',
        Modes: 'Inrush capture, hold',
        Jaw: 'Integrated work light',
        'Safety category': 'CAT III',
      },
      facets: ['Measurement', 'Safety category'],
      axes: [
        ['measurement_range', ['400 A', '600 A', '1000 A']],
        ['kit_contents', ['Meter only', 'Meter with case']],
      ],
      price: [2_400_00, 9_800_00],
      stock: [5, 70],
      moq: 1,
      grams: 520,
      mrp: 0.12,
    },
  ]),

  shelf('enclosures-connectors', [
    {
      key: 'encl-abs-box',
      type: 'Electrical enclosure',
      title: 'IP66 ABS Enclosure with Clear Lid',
      brand: BRANDS.electrical,
      short:
        'IP66 ABS wall enclosure with a clear hinged lid, a moulded gasket and metal lid screws.',
      long: 'A wall-mounting ABS enclosure rated IP66, with a clear hinged lid so an indicator can be read without opening it. The gasket is moulded into the lid rather than glued in, and the lid screws are captive stainless.',
      img: 'electrical enclosure box ip66 industrial',
      specs: {
        Protection: 'IP66',
        Material: 'ABS, light grey',
        Lid: 'Clear, hinged, captive stainless screws',
        Gasket: 'Moulded in place',
      },
      facets: ['Protection', 'Material'],
      axes: [
        ['enclosure_size', ['150 x 110 x 70 mm', '200 x 150 x 100 mm', '300 x 220 x 120 mm']],
        ['knockouts', ['Plain', 'Pre-drilled glands']],
      ],
      price: [280_000, 1_280_000],
      stock: [10, 160],
      moq: 1,
      grams: 640,
      featured: true,
    },
    {
      key: 'encl-m12-connector',
      type: 'M12 circular connector',
      title: 'M12 Circular Connector with Moulded Cable Tail',
      brand: BRANDS.electronics,
      short:
        'Moulded M12 circular connector on a PUR cable tail, rated IP67 when mated.',
      long: 'An M12 circular connector overmoulded onto a PUR cable tail, so there is no field assembly and no route for water into the back of the connector. Rated IP67 when mated and coupled with a knurled nut.',
      img: 'm12 industrial connector cable automation',
      specs: {
        Protection: 'IP67 when mated',
        Termination: 'Overmoulded PUR cable tail',
        Coupling: 'Knurled nut',
        Contacts: 'Gold plated',
      },
      facets: ['Protection', 'Termination'],
      axes: [
        ['pin_count', ['3 pin', '4 pin', '5 pin']],
        ['gender', ['Male straight', 'Female straight', 'Female angled']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [140_000, 980_000],
      stock: [12, 200],
      moq: 1,
      grams: 120,
    },
    {
      key: 'encl-din-terminal',
      type: 'DIN rail terminal block',
      title: 'Spring-Clamp DIN Rail Terminal Block',
      brand: BRANDS.electrical,
      short:
        'Spring-clamp DIN rail terminal block with a test socket and a marker carrier.',
      long: 'A spring-clamp terminal block for DIN rail, which takes a stripped conductor without a screwdriver and holds it against vibration. A test socket takes a 2 mm probe and a marker carrier on the top face takes a printed strip.',
      img: 'terminal block din rail electrical connector',
      specs: {
        Clamp: 'Spring clamp',
        Test: '2 mm test socket',
        Marking: 'Marker carrier on top face',
        Mounting: '35 mm DIN rail',
      },
      facets: ['Clamp', 'Mounting'],
      axes: [
        ['enclosure_size', ['2.5 mm2', '4 mm2', '6 mm2']],
        ['colour', ['Grey', 'Blue', 'Green/yellow']],
        ['pack_count', ['Pack of 50', 'Pack of 100']],
      ],
      price: [96_000, 620_000],
      stock: [15, 240],
      moq: 1,
      grams: 480,
      mrp: 0.14,
    },
  ]),

  // =======================================================================
  // COMPUTERS & IT
  // =======================================================================
  shelf('laptops-desktops', [
    {
      key: 'comp-laptop-business',
      type: 'Business laptop',
      title: '14-Inch Business Laptop with Aluminium Chassis',
      brand: BRANDS.computing,
      short:
        'Fourteen-inch business laptop in an aluminium chassis, with a backlit keyboard and a fingerprint reader.',
      long: 'A fourteen inch business laptop in a machined aluminium chassis, with a matt IPS panel, a backlit keyboard and a fingerprint reader in the power button. The memory is on two slots and the drive is a standard M.2, so both can be changed without a special tool.',
      img: 'modern business laptop computer isolated',
      specs: {
        Chassis: 'Machined aluminium',
        Keyboard: 'Backlit, spill resistant',
        Security: 'Fingerprint reader in power button',
        Serviceability: 'Two memory slots, standard M.2 drive',
        Ports: 'Two USB-C, two USB-A, HDMI, card reader',
      },
      facets: ['Chassis', 'Serviceability'],
      axes: [
        ['ram', ['8 GB', '16 GB', '32 GB']],
        ['storage', ['512 GB SSD', '1 TB SSD']],
        ['colour', ['Silver', 'Graphite']],
      ],
      price: [48_000_00, 128_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 1_400,
      featured: true,
    },
    {
      key: 'comp-desktop-sff',
      type: 'Small form factor desktop',
      title: 'Small Form Factor Desktop with Tool-Free Chassis',
      brand: BRANDS.computing,
      short:
        'Small form factor desktop with a tool-free chassis, a vented front and a VESA mounting kit.',
      long: 'A small form factor desktop whose side panel releases with a thumb latch and whose drive cage lifts out without a screwdriver. A VESA kit is supplied so it can be hung behind a monitor, and the front is vented across its full width.',
      img: 'small form factor desktop computer office',
      specs: {
        Chassis: 'Tool-free side panel and drive cage',
        Mounting: 'VESA kit supplied',
        Cooling: 'Full-width front vent',
        Ports: 'Four USB-A, two USB-C, two DisplayPort',
      },
      facets: ['Chassis', 'Mounting'],
      axes: [
        ['ram', ['8 GB', '16 GB', '32 GB']],
        ['storage', ['512 GB SSD', '1 TB SSD', '2 TB SSD']],
        ['operating_system', ['No operating system', 'Preinstalled']],
      ],
      price: [38_000_00, 98_000_00],
      stock: [2, 26],
      moq: 1,
      grams: 4_800,
      leadDays: 5,
    },
    {
      key: 'comp-monitor',
      type: 'Desktop monitor',
      title: '27-Inch IPS Monitor with Height-Adjustable Stand',
      brand: BRANDS.computing,
      short:
        'Twenty-seven inch IPS monitor with a height, tilt, swivel and pivot stand and a matt coating.',
      long: 'A twenty-seven inch IPS monitor on a stand that adjusts for height, tilt, swivel and pivot, so it can be set for a desk rather than propped on a box. The coating is matt, the bezel is thin on three sides, and the stand detaches for VESA mounting.',
      img: 'computer monitor display screen office',
      specs: {
        Panel: 'IPS, matt coating',
        Stand: 'Height, tilt, swivel and pivot',
        Mounting: 'VESA 100 when stand removed',
        Inputs: 'DisplayPort, two HDMI, USB-C',
      },
      facets: ['Panel', 'Stand'],
      axes: [
        ['display_size', ['24 in', '27 in', '32 in']],
        ['screen_resolution', ['1920 x 1080', '2560 x 1440', '3840 x 2160']],
      ],
      price: [12_800_00, 58_000_00],
      stock: [4, 50],
      moq: 1,
      grams: 6_200,
      mrp: 0.12,
    },
  ]),

  shelf('computer-peripherals', [
    {
      key: 'comp-periph-keyboard',
      type: 'Mechanical keyboard',
      title: 'Mechanical Keyboard with Hot-Swappable Switches',
      brand: BRANDS.computing,
      short:
        'Full-size mechanical keyboard with hot-swappable switches, PBT keycaps and a detachable USB-C lead.',
      long: 'A full-size mechanical keyboard whose switches lift out of the plate without soldering, so a failed switch is replaced rather than the board. The keycaps are dye-sublimated PBT, the case has a two-stage tilt, and the lead detaches at a USB-C socket.',
      img: 'mechanical keyboard computer peripheral',
      specs: {
        Switches: 'Hot swappable, five-pin sockets',
        Keycaps: 'Dye-sublimated PBT',
        Cable: 'Detachable USB-C',
        Tilt: 'Two-stage feet',
      },
      facets: ['Switches', 'Keycaps'],
      axes: [
        ['layout', ['Full size', 'Tenkeyless', '75%']],
        ['switch_type', ['Linear', 'Tactile', 'Clicky']],
        ['colour', ['Black', 'White']],
      ],
      price: [4_800_00, 16_800_00],
      stock: [5, 70],
      moq: 1,
      grams: 1_100,
      featured: true,
    },
    {
      key: 'comp-periph-mouse',
      type: 'Wireless mouse',
      title: 'Wireless Mouse with Dual Connection',
      brand: BRANDS.computing,
      short:
        'Wireless mouse that pairs over Bluetooth or a USB receiver, with a rechargeable cell.',
      long: 'A wireless mouse that connects over Bluetooth or over a bundled USB receiver, with a switch on the base to choose. The cell is rechargeable over USB-C and the mouse stays usable while it charges.',
      img: 'wireless computer mouse peripheral',
      specs: {
        Connection: 'Bluetooth or bundled USB receiver',
        Power: 'Rechargeable, USB-C, usable while charging',
        Buttons: 'Six, with side buttons',
        Sensor: 'Adjustable up to 4,000 dpi',
      },
      facets: ['Connection', 'Power'],
      axes: [
        ['connectivity', ['Bluetooth', 'Bluetooth and USB receiver']],
        ['colour', ['Black', 'Graphite', 'White']],
        ['size', ['Standard', 'Compact']],
      ],
      price: [1_280_00, 5_400_00],
      stock: [10, 140],
      moq: 1,
      grams: 110,
    },
    {
      key: 'comp-periph-dock',
      type: 'USB-C docking station',
      title: 'USB-C Docking Station with Dual Display Output',
      brand: BRANDS.computing,
      short:
        'USB-C docking station driving two displays, with gigabit Ethernet and power delivery upstream.',
      long: 'A USB-C docking station that drives two displays and carries power back up the same cable to the laptop. Gigabit Ethernet, four USB-A ports and a card reader are on the dock, and the upstream lead is captive so it cannot go missing.',
      img: 'usb c docking station computer accessory',
      specs: {
        Displays: 'Two, HDMI and DisplayPort',
        Network: 'Gigabit Ethernet',
        Power: 'Power delivery upstream',
        Cable: 'Captive upstream USB-C lead',
      },
      facets: ['Displays', 'Network'],
      axes: [
        ['connectivity', ['USB-C', 'Thunderbolt compatible']],
        ['bundle', ['Dock only', 'Dock with power supply']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [4, 60],
      moq: 1,
      grams: 640,
      mrp: 0.11,
    },
  ]),

  shelf('networking', [
    {
      key: 'net-router-wifi',
      type: 'Wireless router',
      title: 'Dual-Band Gigabit Wi-Fi Router',
      brand: BRANDS.network,
      short:
        'Dual-band Wi-Fi router with four gigabit LAN ports, external antennas and a guest network.',
      long: 'A dual-band wireless router with four gigabit LAN ports, a gigabit WAN port and external antennas on reverse-polarity connectors. The web interface carries a guest network, a scheduler and a firmware updater, and the configuration exports to a file.',
      img: 'dual band wifi router networking device',
      specs: {
        Bands: 'Dual band, 2.4 and 5 GHz',
        'LAN ports': 'Four gigabit',
        Antennas: 'External, RP-SMA',
        Management: 'Web interface with configuration export',
      },
      facets: ['Bands', 'Management'],
      axes: [
        ['wifi_standard', ['Wi-Fi 5', 'Wi-Fi 6']],
        ['port_count', ['4 port', '8 port']],
      ],
      price: [3_400_00, 14_800_00],
      stock: [5, 80],
      moq: 1,
      grams: 720,
      featured: true,
    },
    {
      key: 'net-switch-poe',
      type: 'PoE network switch',
      title: 'Managed PoE+ Network Switch, Rack Mounting',
      brand: BRANDS.network,
      short:
        'Rack-mounting managed switch with PoE+ on every copper port and two SFP uplinks.',
      long: 'A managed network switch in a one-unit rack case, with PoE+ on every copper port and two SFP uplink cages. VLANs, link aggregation and port mirroring are configured over a web interface or a console port, and the power budget is shown per port.',
      img: 'network switch poe rack ethernet',
      specs: {
        PoE: 'PoE+ on every copper port',
        Uplinks: 'Two SFP cages',
        Management: 'Web interface and console port',
        Mounting: '1U rack, brackets supplied',
      },
      facets: ['PoE', 'Management'],
      axes: [
        ['port_count', ['8 port', '16 port', '24 port']],
        ['port_speed', ['Gigabit', '2.5 Gigabit']],
      ],
      price: [9_800_00, 68_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 3_200,
      leadDays: 5,
    },
    {
      key: 'net-ap-ceiling',
      type: 'Wireless access point',
      title: 'Ceiling-Mount Wireless Access Point with PoE',
      brand: BRANDS.network,
      short:
        'Ceiling-mount wireless access point powered over Ethernet, with a mounting bracket supplied.',
      long: 'A ceiling-mount wireless access point powered over Ethernet, supplied with a bracket that twists onto the mount so the unit can be taken down without a ladder full of screws. Multiple networks can be broadcast with separate VLAN tags.',
      img: 'wireless access point ceiling network device',
      specs: {
        Power: 'Power over Ethernet',
        Mounting: 'Twist-on ceiling bracket supplied',
        Networks: 'Multiple SSIDs with VLAN tags',
        Antennas: 'Internal',
      },
      facets: ['Power', 'Mounting'],
      axes: [
        ['wifi_standard', ['Wi-Fi 5', 'Wi-Fi 6']],
        ['mounting', ['Ceiling', 'Wall']],
      ],
      price: [6_400_00, 38_000_00],
      stock: [3, 48],
      moq: 1,
      grams: 480,
      mrp: 0.1,
    },
  ]),

  shelf('storage-media', [
    {
      key: 'stor-ssd-nvme',
      type: 'NVMe solid state drive',
      title: 'M.2 NVMe Solid State Drive with Heatsink',
      brand: BRANDS.network,
      short:
        'M.2 NVMe solid state drive supplied with a low-profile aluminium heatsink fitted.',
      long: 'An M.2 NVMe solid state drive with a low-profile aluminium heatsink already fitted, so it clears a graphics card in a desktop. The endurance rating and the warranty term are printed on the label rather than only in the data sheet.',
      img: 'nvme ssd solid state drive storage',
      specs: {
        Interface: 'PCIe NVMe',
        'Form factor': 'M.2 2280',
        Heatsink: 'Low-profile aluminium, fitted',
        Marking: 'Endurance and warranty printed on label',
      },
      facets: ['Interface', 'Form factor'],
      axes: [
        ['storage', ['500 GB', '1 TB', '2 TB', '4 TB']],
        ['speed_class', ['PCIe 3.0', 'PCIe 4.0']],
      ],
      price: [4_200_00, 38_000_00],
      stock: [6, 100],
      moq: 1,
      grams: 40,
      featured: true,
    },
    {
      key: 'stor-hdd-nas',
      type: 'NAS hard disk drive',
      title: 'NAS-Rated Hard Disk Drive, 7200 rpm',
      brand: BRANDS.network,
      short:
        'NAS-rated 3.5 inch hard disk drive at 7200 rpm, with rotational vibration sensors.',
      long: 'A 3.5 inch hard disk drive specified for continuous operation in a multi-bay enclosure, with rotational vibration sensors that compensate for the movement of the drives around it. Supplied in a padded antistatic pack rather than loose.',
      img: 'hard disk drive nas storage server',
      specs: {
        'Form factor': '3.5 in',
        Speed: '7,200 rpm',
        Sensors: 'Rotational vibration compensation',
        Packaging: 'Padded antistatic pack',
      },
      facets: ['Form factor', 'Speed'],
      axes: [
        ['storage', ['4 TB', '8 TB', '12 TB', '16 TB']],
        ['pack_count', ['Single', 'Pack of 2']],
      ],
      price: [8_400_00, 68_000_00],
      stock: [4, 60],
      moq: 1,
      grams: 690,
    },
    {
      key: 'stor-sdcard',
      type: 'Memory card',
      title: 'UHS-II SD Memory Card with Video Speed Class',
      brand: BRANDS.network,
      short:
        'UHS-II SD memory card rated to a video speed class, supplied in a rigid case.',
      long: 'A UHS-II SD memory card carrying a video speed class rating as well as a UHS class, which is the figure that matters for sustained recording. Supplied in a rigid case rather than a blister, so the card has somewhere to live.',
      img: 'sd memory card storage media',
      specs: {
        Interface: 'UHS-II',
        Rating: 'Video speed class marked on card',
        Case: 'Rigid card case supplied',
      },
      facets: ['Interface'],
      axes: [
        ['storage', ['64 GB', '128 GB', '256 GB', '512 GB']],
        ['speed_class', ['V30', 'V60', 'V90']],
      ],
      price: [980_000, 12_800_00],
      stock: [10, 160],
      moq: 1,
      grams: 20,
      mrp: 0.15,
    },
  ]),

  shelf('printers-scanners', [
    {
      key: 'print-laser-mono',
      type: 'Monochrome laser printer',
      title: 'Monochrome Laser Printer with Duplex and Network',
      brand: BRANDS.machines,
      short:
        'Monochrome laser printer with automatic duplex, gigabit Ethernet and a 250-sheet tray.',
      long: 'A monochrome laser printer with automatic two-sided printing, gigabit Ethernet and a 250-sheet cassette plus a single-sheet bypass. The toner and the drum are separate units, so only the one that is spent is replaced.',
      img: 'laser printer office machine',
      specs: {
        Technology: 'Monochrome laser',
        Duplex: 'Automatic',
        Network: 'Gigabit Ethernet',
        Paper: '250-sheet cassette plus bypass',
        Consumables: 'Separate toner and drum units',
      },
      facets: ['Technology', 'Duplex', 'Consumables'],
      axes: [
        ['print_speed', ['30 ppm', '40 ppm']],
        ['functions', ['Print only', 'Print, scan and copy']],
      ],
      price: [12_800_00, 42_000_00],
      stock: [3, 40],
      moq: 1,
      grams: 11_200,
      featured: true,
    },
    {
      key: 'print-inkjet-tank',
      type: 'Ink tank printer',
      title: 'Refillable Ink Tank Colour Printer',
      brand: BRANDS.machines,
      short:
        'Colour printer with refillable ink tanks, a flatbed scanner and wireless printing.',
      long: 'A colour printer with refillable ink tanks on the front rather than cartridges, so the level is visible without opening anything. A flatbed scanner sits on top and the printer joins a wireless network from its own panel.',
      img: 'ink tank colour printer office machine',
      specs: {
        'Ink system': 'Refillable tanks, front-facing level windows',
        Functions: 'Print, scan and copy',
        Connectivity: 'Wireless and USB',
        Paper: '100-sheet rear feed',
      },
      facets: ['Ink system', 'Connectivity'],
      axes: [
        ['paper_size', ['A4', 'A3']],
        ['duplex', ['Manual duplex', 'Automatic duplex']],
      ],
      price: [11_400_00, 38_000_00],
      stock: [4, 50],
      moq: 1,
      grams: 6_800,
    },
    {
      key: 'print-scanner-adf',
      type: 'Document scanner',
      title: 'Sheet-Fed Document Scanner with Duplex Feeder',
      brand: BRANDS.machines,
      short:
        'Sheet-fed document scanner with a duplex feeder, ultrasonic double-feed detection and USB-C.',
      long: 'A sheet-fed document scanner that captures both sides in one pass, with ultrasonic detection that stops the feed when two sheets go through together. It connects over USB-C and scans to a folder, an email or a searchable PDF.',
      img: 'document scanner office machine adf',
      specs: {
        Feeder: 'Duplex, single pass',
        Detection: 'Ultrasonic double-feed',
        Connectivity: 'USB-C',
        Output: 'Folder, email or searchable PDF',
      },
      facets: ['Feeder', 'Connectivity'],
      axes: [
        ['print_speed', ['30 ppm', '60 ppm']],
        ['paper_size', ['A4', 'A3 with carrier sheet']],
      ],
      price: [18_500_00, 62_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 3_400,
      leadDays: 5,
      mrp: 0.11,
    },
  ]),

  shelf('software-licences', [
    {
      key: 'soft-office-suite',
      type: 'Productivity suite licence',
      title: 'Productivity Suite Licence with Email Delivery',
      brand: BRANDS.software,
      short:
        'Productivity suite licence delivered by email, with a per-seat count and a fixed term.',
      long: 'A licence for a productivity suite, delivered as a key and a download link by email within one working day. The seat count and the term are what the licence is priced on, and a renewal notice is sent before the term ends.',
      img: 'software licence box digital delivery',
      specs: {
        Delivery: 'Email, within one working day',
        Contents: 'Licence key and download link',
        Renewal: 'Notice sent before term end',
      },
      facets: ['Delivery'],
      axes: [
        ['seat_count', ['1 user', '5 users', '10 users', '25 users']],
        ['term', ['1 year', '3 years']],
      ],
      price: [3_400_00, 68_000_00],
      stock: [50, 400],
      moq: 1,
      grams: 1,
      featured: true,
    },
    {
      key: 'soft-antivirus',
      type: 'Endpoint protection licence',
      title: 'Endpoint Protection Licence with Central Console',
      brand: BRANDS.software,
      short:
        'Endpoint protection licence with a central management console, priced per device and term.',
      long: 'An endpoint protection licence with a hosted management console, priced on the number of devices and the length of the term. The console is included in the licence rather than sold beside it.',
      img: 'security software licence digital',
      specs: {
        Console: 'Hosted management console included',
        Delivery: 'Email with activation details',
        Platforms: 'Windows, macOS and Linux agents',
      },
      facets: ['Console', 'Platforms'],
      axes: [
        ['seat_count', ['5 devices', '25 devices', '50 devices']],
        ['term', ['1 year', '2 years', '3 years']],
      ],
      price: [4_800_00, 82_000_00],
      stock: [50, 400],
      moq: 1,
      grams: 1,
    },
    {
      key: 'soft-cad-licence',
      type: 'CAD software licence',
      title: 'Technical Drawing Software Licence, Named User',
      brand: BRANDS.software,
      short:
        'Named-user technical drawing software licence with a support level chosen at purchase.',
      long: 'A named-user licence for technical drawing software, with the support level chosen at purchase rather than added later. Delivered by email with the download, the key and the activation instructions.',
      img: 'cad software licence technical drawing',
      specs: {
        'Licence type': 'Named user',
        Delivery: 'Email with download and key',
        Support: 'Support level selected at purchase',
      },
      facets: ['Licence type'],
      axes: [
        ['seat_count', ['1 user', '3 users', '10 users']],
        ['support_level', ['Standard', 'Priority']],
        ['term', ['1 year', '3 years']],
      ],
      price: [24_000_00, 380_000_00],
      stock: [20, 200],
      moq: 1,
      grams: 1,
      mrp: 0.08,
    },
  ]),

  // =======================================================================
  // PHONES & COMMUNICATION
  // =======================================================================
  shelf('mobile-phones', [
    {
      key: 'phon-smartphone-mid',
      type: 'Smartphone',
      title: 'Dual-SIM Smartphone with 6.5-Inch AMOLED Display',
      brand: BRANDS.comms,
      short:
        'Dual-SIM smartphone with a 6.5-inch AMOLED display, a triple camera and a side fingerprint reader.',
      long: 'A dual-SIM smartphone with a 6.5 inch AMOLED display, a triple rear camera and a fingerprint reader in the power button. The storage is expandable on a dedicated card slot rather than a shared SIM tray, and the charger is supplied in the box.',
      img: 'smartphone mobile phone isolated product',
      specs: {
        Display: '6.5 in AMOLED',
        SIM: 'Dual SIM with dedicated card slot',
        Security: 'Side fingerprint reader',
        'In the box': 'Charger, cable and case',
      },
      facets: ['Display', 'SIM'],
      axes: [
        ['ram', ['6 GB', '8 GB', '12 GB']],
        ['storage', ['128 GB', '256 GB']],
        ['colour', ['Midnight', 'Silver', 'Ocean']],
      ],
      price: [14_800_00, 42_000_00],
      stock: [4, 60],
      moq: 1,
      grams: 480,
      featured: true,
    },
    {
      key: 'phon-rugged',
      type: 'Rugged smartphone',
      title: 'Rugged Smartphone with IP68 Body and Glove Mode',
      brand: BRANDS.comms,
      short:
        'IP68-rated rugged smartphone with a reinforced frame, a glove-capable touchscreen and a programmable key.',
      long: 'A rugged smartphone in a reinforced frame with an IP68 rating and a touchscreen that works through gloves or with wet fingers. A programmable side key can be set to a push-to-talk application or a torch, and the battery is unusually large for the size.',
      img: 'rugged smartphone industrial waterproof phone',
      specs: {
        Protection: 'IP68',
        Touchscreen: 'Glove and wet-finger capable',
        Key: 'Programmable side key',
        Frame: 'Reinforced with corner bumpers',
      },
      facets: ['Protection', 'Touchscreen'],
      axes: [
        ['ram', ['6 GB', '8 GB']],
        ['storage', ['128 GB', '256 GB']],
        ['colour', ['Black', 'Safety orange']],
      ],
      price: [22_000_00, 48_000_00],
      stock: [3, 42],
      moq: 1,
      grams: 640,
    },
    {
      key: 'phon-feature',
      type: 'Feature phone',
      title: 'Dual-SIM Feature Phone with Long Standby',
      brand: BRANDS.comms,
      short:
        'Dual-SIM feature phone with a physical keypad, a torch and a removable battery.',
      long: 'A dual-SIM feature phone with a physical keypad, a torch on the top edge and a removable battery. The standby figure is long because the display is small and the radio is 2G and 4G rather than a full smartphone stack.',
      img: 'feature phone keypad mobile basic',
      specs: {
        Keypad: 'Physical',
        Battery: 'Removable',
        SIM: 'Dual SIM',
        Extras: 'Torch, FM radio',
      },
      facets: ['Keypad', 'Battery'],
      axes: [
        ['colour', ['Black', 'Blue']],
        ['sim_configuration', ['Dual SIM', 'Single SIM']],
      ],
      price: [1_680_00, 14_800_00],
      stock: [10, 160],
      moq: 1,
      grams: 180,
      mrp: 0.14,
    },
  ]),

  shelf('phone-accessories', [
    {
      key: 'phon-acc-cable',
      type: 'USB-C charging cable',
      title: 'Braided USB-C Charging Cable with 60 W Rating',
      brand: BRANDS.comms,
      short:
        'Nylon-braided USB-C cable rated for 60 W, with moulded strain relief at both ends.',
      long: 'A USB-C to USB-C cable in a nylon braid with a moulded strain relief at both ends, where a cable fails first. Rated for 60 watts of power delivery and for USB 2.0 data, which the packaging states rather than implying a data rate the cable does not carry.',
      img: 'usb c charging cable braided accessory',
      specs: {
        Rating: '60 W power delivery',
        Data: 'USB 2.0',
        Jacket: 'Nylon braid',
        Relief: 'Moulded strain relief both ends',
      },
      facets: ['Rating', 'Jacket'],
      axes: [
        ['length', ['0.5 m', '1 m', '2 m']],
        ['colour', ['Black', 'Grey', 'White']],
        ['pack_count', ['Single', 'Pack of 3']],
      ],
      price: [28_000, 240_000],
      stock: [25, 400],
      moq: 1,
      grams: 90,
      featured: true,
    },
    {
      key: 'phon-acc-powerbank',
      type: 'Power bank',
      title: 'Power Bank with USB-C Power Delivery and Display',
      brand: BRANDS.comms,
      short:
        'Power bank with USB-C power delivery in and out, plus a digital charge display.',
      long: 'A power bank that charges and discharges over the same USB-C port at power delivery rates, with a second USB-A output and a digital percentage display. The capacity is quoted at the cell voltage and at the output voltage, because the two figures are different.',
      img: 'power bank portable charger battery',
      specs: {
        Ports: 'USB-C in and out, USB-A out',
        Display: 'Digital percentage',
        Capacity: 'Quoted at cell and output voltage',
      },
      facets: ['Ports', 'Display'],
      axes: [
        ['output_power', ['10,000 mAh', '20,000 mAh']],
        ['colour', ['Black', 'Navy']],
      ],
      price: [1_280_00, 4_800_00],
      stock: [10, 160],
      moq: 1,
      grams: 380,
    },
    {
      key: 'phon-acc-case',
      type: 'Phone case',
      title: 'Shock-Absorbing Phone Case with Raised Bezel',
      brand: BRANDS.comms,
      short:
        'Shock-absorbing phone case with air-cushion corners and a bezel raised above the screen.',
      long: 'A phone case with air-cushion corners and a bezel raised above the screen and the camera, so a phone laid face down rests on the case rather than on the glass. The button covers are moulded in a firmer compound than the body.',
      img: 'phone case protective cover accessory',
      specs: {
        Corners: 'Air cushion',
        Bezel: 'Raised above screen and camera',
        Buttons: 'Firmer compound button covers',
      },
      facets: ['Corners'],
      axes: [
        ['compatibility', ['6.1 in models', '6.5 in models', '6.7 in models']],
        ['colour', ['Clear', 'Black', 'Smoke']],
      ],
      price: [38_000, 180_000],
      stock: [20, 320],
      moq: 1,
      grams: 60,
      mrp: 0.2,
    },
  ]),

  shelf('two-way-radios', [
    {
      key: 'radio-licence-free',
      type: 'Licence-free two-way radio',
      title: 'Licence-Free Two-Way Radio Twin Pack with Chargers',
      brand: BRANDS.comms,
      short:
        'Licence-free PMR two-way radio twin pack with a dual charging cradle and belt clips.',
      long: 'A twin pack of licence-free PMR handheld radios, supplied with a dual charging cradle, two rechargeable packs and belt clips. The channels are fixed by the licence-free allocation and cannot be reprogrammed outside it.',
      img: 'two way radio walkie talkie pair',
      specs: {
        Allocation: 'Licence-free PMR channels',
        Charging: 'Dual cradle supplied',
        Accessories: 'Belt clips and rechargeable packs',
      },
      facets: ['Allocation'],
      axes: [
        ['channel_count', ['8 channel', '16 channel']],
        ['pack_count', ['Twin pack', 'Quad pack']],
      ],
      price: [3_400_00, 12_800_00],
      stock: [5, 70],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'radio-uhf-business',
      type: 'UHF business radio',
      title: 'UHF Business Radio with Programmable Channels',
      brand: BRANDS.comms,
      short:
        'UHF business handheld radio with programmable channels, an IP54 body and a two-pin accessory socket.',
      long: 'A UHF business handheld with programmable channels, an IP54 body and a two-pin accessory socket for an earpiece. Programming requires the appropriate licence for the frequencies being used, which is the operator’s responsibility rather than something supplied with the radio.',
      img: 'uhf business radio handheld communication',
      specs: {
        Body: 'IP54',
        Accessory: 'Two-pin socket',
        Programming: 'Channels programmable by the licence holder',
      },
      facets: ['Body', 'Accessory'],
      axes: [
        ['transmit_power', ['2 W', '4 W']],
        ['channel_count', ['16 channel', '32 channel']],
        ['kit_contents', ['Radio and battery', 'Radio, battery and charger']],
      ],
      price: [5_400_00, 18_500_00],
      stock: [4, 60],
      moq: 1,
      grams: 480,
    },
    {
      key: 'radio-earpiece',
      type: 'Radio earpiece',
      title: 'Acoustic Tube Earpiece with In-Line Microphone',
      brand: BRANDS.comms,
      short:
        'Acoustic tube earpiece with an in-line push-to-talk microphone and a clothing clip.',
      long: 'An acoustic tube earpiece with an in-line push-to-talk microphone and a clip for a lapel. The tube is clear and detaches from the transducer so it can be replaced when it is passed between people.',
      img: 'radio earpiece acoustic tube communication',
      specs: {
        Type: 'Acoustic tube',
        Microphone: 'In-line with push-to-talk',
        Tube: 'Detachable, replaceable',
      },
      facets: ['Type'],
      axes: [
        ['kit_contents', ['Two-pin socket', 'M-type socket']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [420_000, 2_400_000],
      stock: [12, 180],
      moq: 1,
      grams: 60,
      mrp: 0.13,
    },
  ]),

  shelf('telephony', [
    {
      key: 'tel-voip-desk',
      type: 'VoIP desk telephone',
      title: 'VoIP Desk Telephone with Colour Display and PoE',
      brand: BRANDS.comms,
      short:
        'VoIP desk telephone with a colour display, power over Ethernet and a pass-through LAN port.',
      long: 'A VoIP desk telephone with a colour display, power over Ethernet and a pass-through LAN port so a computer shares the desk socket. The handset cord is on the underside and the stand sets two angles.',
      img: 'voip desk phone office telephone',
      specs: {
        Protocol: 'SIP',
        Power: 'Power over Ethernet',
        Ports: 'LAN and pass-through PC port',
        Display: 'Colour',
      },
      facets: ['Protocol', 'Power'],
      axes: [
        ['line_count', ['2 line', '4 line', '8 line']],
        ['colour', ['Black', 'Light grey']],
      ],
      price: [4_200_00, 16_800_00],
      stock: [5, 80],
      moq: 1,
      grams: 1_100,
      featured: true,
    },
    {
      key: 'tel-dect-base',
      type: 'DECT telephone system',
      title: 'DECT Base Station with Cordless Handsets',
      brand: BRANDS.comms,
      short:
        'DECT base station supplied with cordless handsets, chargers and a wall-mount plate.',
      long: 'A DECT base station with cordless handsets, each on its own charging cradle, and a wall-mount plate for the base. Additional handsets register to the same base without a second line.',
      img: 'dect cordless phone base station office',
      specs: {
        Standard: 'DECT',
        Mounting: 'Desk or wall plate supplied',
        Registration: 'Additional handsets register to the same base',
      },
      facets: ['Standard'],
      axes: [
        ['handset_count', ['1 handset', '2 handsets', '4 handsets']],
        ['answering_machine', ['Without answering machine', 'With answering machine']],
      ],
      price: [3_800_00, 14_200_00],
      stock: [4, 60],
      moq: 1,
      grams: 1_600,
    },
    {
      key: 'tel-headset',
      type: 'Telephone headset',
      title: 'Binaural Telephone Headset with Noise-Cancelling Boom',
      brand: BRANDS.comms,
      short:
        'Binaural headset with a noise-cancelling boom microphone and a quick-disconnect lead.',
      long: 'A binaural headset with a noise-cancelling boom microphone and a quick-disconnect in the lead, so the wearer can leave the desk without unplugging at the phone. Leatherette ear cushions are supplied fitted and foam ones in the box.',
      img: 'telephone headset call centre office',
      specs: {
        Wearing: 'Binaural',
        Microphone: 'Noise-cancelling boom',
        Lead: 'Quick disconnect',
        Cushions: 'Leatherette fitted, foam supplied',
      },
      facets: ['Wearing', 'Microphone'],
      axes: [
        ['system_type', ['Corded QD', 'USB']],
        ['colour', ['Black', 'Grey']],
      ],
      price: [2_400_00, 9_800_00],
      stock: [6, 90],
      moq: 1,
      grams: 320,
      mrp: 0.12,
    },
  ]),
];
