/**
 * Sports & Outdoors, Toys, Hobbies & Crafts, Books & Media,
 * Chemicals & Raw Materials, Energy & Environment.
 *
 * Nineteen shelves, three products each.
 *
 * TWO IDENTIFIERS THAT ARE NEVER INVENTED
 *
 * **No ISBN.** The books shelf describes formats, bindings and page counts and
 * carries no ISBN at all. An ISBN is issued by a national agency against a real
 * title; a made-up one either belongs to somebody else's book or is a
 * checksum failure, and both are worse than an empty field. The `isbn` axis
 * the template offers is left for a real bookseller.
 *
 * **No hazard classification.** The chemicals shelves describe grade, form,
 * concentration and container - facts about what is being supplied - and leave
 * `hazard_class` empty. A UN number and a transport class are regulatory
 * determinations, and a carrier that acts on a fabricated one has been
 * misinformed about what is on their vehicle. Storage advice here is the
 * generic "cool, dry, ventilated" that says nothing a label would not.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const LEISURE_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // SPORTS & OUTDOORS
  // =======================================================================
  shelf('fitness-equipment', [
    {
      key: 'sport-fit-dumbbell',
      type: 'Adjustable dumbbell',
      title: 'Adjustable Dumbbell with Dial Weight Selection',
      brand: BRANDS.sport,
      short:
        'Adjustable dumbbell with a dial selector and a moulded cradle, replacing a rack of fixed weights.',
      long: 'An adjustable dumbbell whose plates are picked up from a moulded cradle by turning a dial at each end, so one pair covers the range a rack of fixed dumbbells would. The handle is knurled and the plates cannot leave the cradle unless the dial is set.',
      img: 'adjustable dumbbell fitness equipment gym',
      specs: {
        Selection: 'Dial selector at each end',
        Cradle: 'Moulded, plates locked unless selected',
        Handle: 'Knurled steel',
        Supply: 'Sold as a pair',
      },
      facets: ['Selection', 'Handle'],
      axes: [
        ['resistance', ['2-12 kg', '2-24 kg', '4-32 kg']],
        ['piece_count', ['Single', 'Pair']],
      ],
      price: [8_400_00, 42_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 24_000,
      featured: true,
    },
    {
      key: 'sport-fit-mat',
      type: 'Exercise mat',
      title: 'Closed-Cell Exercise Mat with Carry Strap',
      brand: BRANDS.sport,
      short:
        'Closed-cell exercise mat with a textured top, a carry strap and a non-absorbent surface.',
      long: 'A closed-cell exercise mat, which means sweat stays on the surface and wipes off rather than soaking in. The top is textured for grip, the edges are sealed, and a carry strap is supplied.',
      img: 'exercise yoga mat fitness equipment',
      specs: {
        Foam: 'Closed cell, non absorbent',
        Surface: 'Textured top',
        Edges: 'Sealed',
        Supplied: 'Carry strap',
      },
      facets: ['Foam', 'Surface'],
      axes: [
        ['dimensions', ['6 mm', '10 mm', '15 mm']],
        ['colour', ['Charcoal', 'Teal', 'Plum']],
      ],
      price: [480_000, 2_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'sport-fit-resistanceband',
      type: 'Resistance band set',
      title: 'Layered Latex Resistance Band Set with Door Anchor',
      brand: BRANDS.sport,
      short:
        'Layered latex resistance band set with clip handles, ankle straps and a door anchor.',
      long: 'A resistance band set built from layered latex rather than a single moulding, so a nick does not run the length of the band. Clip handles, ankle straps and a door anchor are supplied, and the bands can be stacked for a heavier load.',
      img: 'resistance bands fitness equipment set',
      specs: {
        Construction: 'Layered latex',
        Supplied: 'Clip handles, ankle straps and door anchor',
        Stacking: 'Bands can be combined',
      },
      facets: ['Construction', 'Stacking'],
      axes: [
        ['resistance', ['Light set', 'Medium set', 'Heavy set']],
        ['piece_count', ['5 band set', '11 piece set']],
      ],
      price: [380_000, 1_680_000],
      stock: [12, 220],
      moq: 1,
      grams: 1_100,
      mrp: 0.16,
    },
  ]),

  shelf('team-sports', [
    {
      key: 'sport-team-football',
      type: 'Football',
      title: 'Machine-Stitched Training Football with Butyl Bladder',
      brand: BRANDS.sport,
      short:
        'Machine-stitched training football on a butyl bladder, for grass and artificial pitches.',
      long: 'A machine-stitched training football on a butyl bladder, which holds air considerably longer than a latex one. The casing is a textured PU with a four-layer backing, and it is supplied deflated with a needle.',
      img: 'football soccer ball sports equipment',
      specs: {
        Construction: 'Machine stitched, four-layer backing',
        Bladder: 'Butyl',
        Casing: 'Textured PU',
        Supply: 'Deflated with inflation needle',
      },
      facets: ['Construction', 'Bladder'],
      axes: [
        ['standard_size', ['Size 3', 'Size 4', 'Size 5']],
        ['pack_count', ['Single', 'Pack of 5', 'Pack of 10']],
      ],
      price: [480_000, 4_800_000],
      stock: [8, 160],
      moq: 1,
      grams: 440,
      featured: true,
    },
    {
      key: 'sport-team-cricketbat',
      type: 'Cricket bat',
      title: 'Kashmir Willow Cricket Bat with Toe Guard',
      brand: BRANDS.sport,
      short:
        'Kashmir willow cricket bat with a fitted toe guard, an anti-scuff sheet and a bound handle.',
      long: 'A Kashmir willow cricket bat supplied with the toe guard and anti-scuff sheet already fitted, and a cane handle bound and gripped. Willow is a natural material, so the grain count and the weight vary between bats of the same size.',
      img: 'cricket bat sports equipment willow',
      specs: {
        Willow: 'Kashmir willow',
        Handle: 'Cane, bound and gripped',
        Fitted: 'Toe guard and anti-scuff sheet',
        Variation: 'Grain and weight vary between bats',
      },
      facets: ['Willow', 'Handle'],
      axes: [
        ['standard_size', ['Size 5', 'Size 6', 'Harrow', 'Short handle']],
        ['weight', ['Light', 'Medium', 'Heavy']],
      ],
      price: [1_280_00, 6_800_00],
      stock: [4, 80],
      moq: 1,
      grams: 1_250,
    },
    {
      key: 'sport-team-bibs',
      type: 'Training bib set',
      title: 'Mesh Training Bib Set in a Drawstring Bag',
      brand: BRANDS.sport,
      short:
        'Mesh training bib set with numbered backs, in a drawstring bag.',
      long: 'A set of mesh training bibs with numbers on the back, in a drawstring bag that holds the whole set. The mesh is open enough to go over a kit without overheating and the sides are open from the armhole down.',
      img: 'training bibs sports team equipment',
      specs: {
        Fabric: 'Open mesh',
        Numbering: 'Numbered backs',
        Sides: 'Open from armhole',
        Supplied: 'Drawstring bag',
      },
      facets: ['Fabric', 'Numbering'],
      axes: [
        ['colour', ['Yellow', 'Orange', 'Blue', 'Red']],
        ['pack_count', ['Set of 10', 'Set of 15']],
        ['age_group', ['Junior', 'Adult']],
      ],
      price: [980_000, 3_400_000],
      stock: [6, 120],
      moq: 1,
      grams: 1_600,
      sold: { content: [10, 'piece'], label: 'Set of 10' },
      multipack: 10,
      mrp: 0.15,
    },
  ]),

  shelf('camping-outdoor', [
    {
      key: 'sport-camp-tent',
      type: 'Dome tent',
      title: 'Three-Person Dome Tent with Taped Seams',
      brand: BRANDS.sport,
      short:
        'Three-person dome tent with taped seams, a sewn-in groundsheet and colour-coded poles.',
      long: 'A three-person dome tent with taped seams, a sewn-in groundsheet and a porch big enough for boots. The poles are colour coded to their sleeves and the flysheet pitches first, so it can be put up in the rain without the inner getting wet.',
      img: 'camping dome tent outdoor equipment',
      specs: {
        Seams: 'Taped',
        Groundsheet: 'Sewn in',
        Poles: 'Colour coded to sleeves',
        Pitching: 'Flysheet first',
      },
      facets: ['Seams', 'Pitching'],
      axes: [
        ['person_capacity', ['2 person', '3 person', '4 person']],
        ['season_rating', ['2 season', '3 season']],
      ],
      price: [4_200_00, 18_500_00],
      stock: [3, 60],
      moq: 1,
      grams: 4_800,
      featured: true,
    },
    {
      key: 'sport-camp-sleepingbag',
      type: 'Sleeping bag',
      title: 'Mummy Sleeping Bag with Anti-Snag Zip Baffle',
      brand: BRANDS.sport,
      short:
        'Mummy-shaped sleeping bag with a draught collar and an anti-snag baffle along the zip.',
      long: 'A mummy-shaped sleeping bag with a draught collar at the shoulders and a stiffened baffle along the zip, which is what stops the lining being pulled into the slider in the dark. Supplied with a compression sack.',
      img: 'sleeping bag camping outdoor gear',
      specs: {
        Shape: 'Mummy',
        Collar: 'Draught collar at shoulders',
        Zip: 'Stiffened anti-snag baffle',
        Supplied: 'Compression sack',
      },
      facets: ['Shape', 'Zip'],
      axes: [
        ['season_rating', ['2 season', '3 season']],
        ['colour', ['Moss', 'Slate', 'Rust']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [5, 90],
      moq: 1,
      grams: 1_900,
    },
    {
      key: 'sport-camp-stove',
      type: 'Camping stove',
      title: 'Twin-Burner Camping Stove with Wind Shields',
      brand: BRANDS.sport,
      short:
        'Twin-burner gas camping stove with folding wind shields and a piezo igniter.',
      long: 'A twin-burner gas camping stove with folding wind shields on three sides and a piezo igniter on each burner. The pan supports lift out and the drip tray is enamelled, so it cleans rather than stains.',
      img: 'camping stove burner outdoor cooking',
      specs: {
        Burners: 'Two, independently controlled',
        Shields: 'Folding, three sides',
        Ignition: 'Piezo per burner',
        Tray: 'Enamelled, removable pan supports',
      },
      facets: ['Burners', 'Ignition'],
      axes: [
        ['product_type', ['Stove only', 'Stove with regulator and hose']],
        ['kit_configuration', ['Standard', 'With carry case']],
      ],
      price: [2_400_00, 8_400_00],
      stock: [4, 70],
      moq: 1,
      grams: 4_200,
      mrp: 0.13,
    },
  ]),

  shelf('cycling', [
    {
      key: 'sport-cyc-hybridbike',
      type: 'Hybrid bicycle',
      title: 'Aluminium Hybrid Bicycle with Hydraulic Disc Brakes',
      brand: BRANDS.sport,
      short:
        'Aluminium hybrid bicycle with hydraulic disc brakes, a rigid fork and rack and guard mounts.',
      long: 'An aluminium hybrid bicycle with hydraulic disc brakes and a rigid fork, built around mounts for a rack and full guards - which is what makes it a commuting bike rather than a mountain bike with narrow tyres. Supplied ninety per cent assembled.',
      img: 'hybrid bicycle commuter bike cycling',
      specs: {
        Frame: 'Aluminium with rack and guard mounts',
        Brakes: 'Hydraulic disc',
        Fork: 'Rigid',
        Assembly: 'Supplied 90% assembled',
      },
      facets: ['Frame', 'Brakes'],
      axes: [
        ['frame_size', ['S (17 in)', 'M (19 in)', 'L (21 in)']],
        ['gear_count', ['8 speed', '9 speed']],
        ['colour', ['Matt black', 'Deep blue']],
      ],
      price: [24_000_00, 68_000_00],
      stock: [1, 24],
      moq: 1,
      grams: 14_500,
      leadDays: 5,
      featured: true,
    },
    {
      key: 'sport-cyc-helmet',
      type: 'Cycling helmet',
      title: 'In-Mould Cycling Helmet with Dial Retention',
      brand: BRANDS.sport,
      short:
        'In-mould cycling helmet with a dial retention system, vents and a removable visor.',
      long: 'An in-mould cycling helmet, where the shell is bonded to the liner during moulding rather than glued on afterwards. A dial at the back adjusts the retention one-handed, the pads are washable and the visor clips off.',
      img: 'cycling helmet bike safety gear',
      specs: {
        Construction: 'In-mould shell',
        Retention: 'Rear dial, one-handed',
        Pads: 'Removable and washable',
        Visor: 'Clip-off',
      },
      facets: ['Construction', 'Retention'],
      axes: [
        ['frame_size', ['S (52-56 cm)', 'M (55-59 cm)', 'L (58-62 cm)']],
        ['colour', ['Matt black', 'White', 'Fluoro yellow']],
      ],
      price: [1_280_00, 5_400_00],
      stock: [5, 100],
      moq: 1,
      grams: 320,
    },
    {
      key: 'sport-cyc-lightset',
      type: 'Bicycle light set',
      title: 'USB Rechargeable Bicycle Light Set with Bracket Mounts',
      brand: BRANDS.sport,
      short:
        'USB rechargeable front and rear bicycle light set with tool-free bracket mounts.',
      long: 'A front and rear bicycle light set, both USB rechargeable and both on brackets that fit without a tool. The front has a cut-off beam so it lights the road rather than the oncoming traffic, and each light shows its charge state.',
      img: 'bicycle lights cycling safety accessories',
      specs: {
        Charging: 'USB rechargeable',
        Mounts: 'Tool-free brackets',
        Beam: 'Front light has a cut-off beam',
        Indication: 'Charge state shown on each light',
      },
      facets: ['Charging', 'Mounts'],
      axes: [
        ['product_type', ['Front and rear set', 'Front only', 'Rear only']],
        ['colour', ['Black']],
      ],
      price: [680_000, 3_400_000],
      stock: [8, 160],
      moq: 1,
      grams: 220,
      mrp: 0.15,
    },
  ]),

  // =======================================================================
  // TOYS, HOBBIES & CRAFTS
  // =======================================================================
  shelf('toys-games', [
    {
      key: 'toy-game-blocks',
      type: 'Wooden building blocks',
      title: 'Wooden Building Block Set in a Cotton Storage Bag',
      brand: BRANDS.play,
      short:
        'Solid beech building block set with sanded edges, in a cotton drawstring bag.',
      long: 'A building block set in solid beech with every edge sanded, finished in a water-based non-toxic lacquer. The blocks are cut to a single module so they stack true, and the set comes in a cotton drawstring bag rather than a box that falls apart.',
      img: 'wooden building blocks toy children',
      specs: {
        Wood: 'Solid beech',
        Finish: 'Water-based lacquer',
        Edges: 'Sanded',
        Module: 'Single dimensional module throughout',
        Storage: 'Cotton drawstring bag',
      },
      facets: ['Wood', 'Finish'],
      axes: [
        ['piece_count', ['50 piece', '100 piece', '150 piece']],
        ['age_group', ['3 years and over']],
      ],
      price: [980_000, 3_400_000],
      stock: [6, 120],
      moq: 1,
      grams: 2_400,
      featured: true,
    },
    {
      key: 'toy-game-boardgame',
      type: 'Family board game',
      title: 'Family Strategy Board Game with Insert Tray',
      brand: BRANDS.play,
      short:
        'Family strategy board game with a moulded insert tray and a folding board.',
      long: 'A family strategy board game with a moulded insert tray, so the pieces go back where they came from and the box closes flat. The board folds in four, the rules are a single folded sheet, and the game plays in about forty minutes.',
      img: 'board game family games box',
      specs: {
        Board: 'Folds in four',
        Insert: 'Moulded tray',
        Rules: 'Single folded sheet',
        Length: 'About 40 minutes',
      },
      facets: ['Insert'],
      axes: [
        ['player_count', ['2-4 players', '2-6 players']],
        ['age_group', ['8 years and over', '10 years and over']],
      ],
      price: [980_000, 3_800_000],
      stock: [6, 120],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'toy-game-rcbuggy',
      type: 'Radio controlled buggy',
      title: 'Radio Controlled Buggy with Proportional Steering',
      brand: BRANDS.play,
      short:
        'Radio controlled buggy with proportional steering and throttle, and a removable battery pack.',
      long: 'A radio controlled buggy with proportional steering and throttle rather than full-lock switching, so it can be driven rather than aimed. The battery pack comes out for charging and a USB charger is supplied.',
      img: 'radio controlled car toy buggy',
      specs: {
        Control: 'Proportional steering and throttle',
        Battery: 'Removable pack, USB charger supplied',
        Suspension: 'Independent, four wheel',
      },
      facets: ['Control', 'Battery'],
      axes: [
        ['toy_type', ['1:16 scale', '1:12 scale']],
        ['colour', ['Blue', 'Red', 'Green']],
        ['age_group', ['8 years and over']],
      ],
      price: [1_680_00, 5_400_00],
      stock: [4, 80],
      moq: 1,
      grams: 1_600,
      mrp: 0.15,
    },
  ]),

  shelf('craft-materials', [
    {
      key: 'craft-mat-acrylicpaint',
      type: 'Acrylic paint set',
      title: 'Heavy-Body Acrylic Paint Set in Screw-Top Tubes',
      brand: BRANDS.play,
      short:
        'Heavy-body acrylic paint set in screw-top tubes, with the pigment index on each label.',
      long: 'A heavy-body acrylic paint set that holds a brush mark, in screw-top tubes rather than flip caps that crack. Each label carries the pigment index and the lightfastness, which is the information that decides whether a painting still looks the same in ten years.',
      img: 'acrylic paint tubes art supplies',
      specs: {
        Body: 'Heavy body, holds a brush mark',
        Tubes: 'Screw top',
        Labelling: 'Pigment index and lightfastness per colour',
      },
      facets: ['Body', 'Labelling'],
      axes: [
        ['pack_count', ['12 colour set', '24 colour set']],
        ['net_weight', ['12 ml tubes', '22 ml tubes']],
      ],
      price: [480_000, 2_400_000],
      stock: [8, 160],
      moq: 1,
      grams: 620,
      featured: true,
    },
    {
      key: 'craft-mat-yarn',
      type: 'Knitting yarn',
      title: 'Double Knitting Yarn with Matched Dye Lot',
      brand: BRANDS.textile,
      short:
        'Double knitting yarn supplied in matched dye lots, with a printed tension and needle size.',
      long: 'A double knitting yarn supplied in matched dye lots when bought as a pack, because two balls from different lots do not match in a finished garment. The band carries the tension, the needle size and the wash symbols.',
      img: 'knitting yarn wool craft materials',
      specs: {
        Weight: 'Double knitting',
        'Dye lot': 'Matched within a pack',
        Band: 'Tension, needle size and wash symbols',
      },
      facets: ['Weight', 'Dye lot'],
      axes: [
        ['colour', ['Ecru', 'Charcoal', 'Mustard', 'Teal']],
        ['pack_count', ['Single ball', 'Pack of 10']],
      ],
      price: [96_000, 980_000],
      stock: [10, 200],
      moq: 1,
      grams: 1_000,
      sold: { content: [100, 'g'], per: [1, 'kg'] },
    },
    {
      key: 'craft-mat-card',
      type: 'Craft card',
      title: 'Textured Craft Card in a Mixed-Colour Pack',
      brand: BRANDS.office,
      short:
        'Textured craft card in a mixed-colour pack, cut square and sold by weight.',
      long: 'A textured craft card in a mixed-colour pack, cut square so it registers in a trimmer, and sold by weight in grams per square metre rather than by a vague description. It scores and folds without cracking along the grain.',
      img: 'craft card paper coloured art supplies',
      specs: {
        Texture: 'Textured surface',
        Cut: 'Square cut',
        Folding: 'Scores and folds along the grain',
      },
      facets: ['Texture'],
      axes: [
        ['size', ['A4', 'A3']],
        ['gsm', ['160 gsm', '220 gsm', '300 gsm']],
        ['pack_count', ['Pack of 50', 'Pack of 100']],
      ],
      price: [140_000, 780_000],
      stock: [10, 200],
      moq: 1,
      grams: 1_400,
      mrp: 0.14,
    },
  ]),

  shelf('musical-instruments', [
    {
      key: 'music-inst-acousticguitar',
      type: 'Acoustic guitar',
      title: 'Dreadnought Acoustic Guitar with a Solid Spruce Top',
      brand: BRANDS.music,
      short:
        'Dreadnought acoustic guitar with a solid spruce top, scalloped bracing and a bone nut.',
      long: 'A dreadnought acoustic guitar with a solid spruce top over scalloped bracing, laminated back and sides, and a bone nut and saddle rather than plastic. Supplied set up, with the action measured and adjusted before it ships.',
      img: 'acoustic guitar musical instrument',
      specs: {
        Top: 'Solid spruce',
        Bracing: 'Scalloped',
        'Back and sides': 'Laminated',
        'Nut and saddle': 'Bone',
        Setup: 'Action measured and adjusted before dispatch',
      },
      facets: ['Top', 'Nut and saddle'],
      axes: [
        ['instrument_size', ['Full size', '3/4 size']],
        ['finish', ['Natural satin', 'Sunburst']],
        ['handing', ['Right handed', 'Left handed']],
      ],
      price: [11_400_00, 42_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 2_400,
      leadDays: 3,
      featured: true,
    },
    {
      key: 'music-inst-keyboard',
      type: 'Digital keyboard',
      title: 'Digital Keyboard with Touch-Sensitive Keys and USB',
      brand: BRANDS.music,
      short:
        'Digital keyboard with touch-sensitive keys, a USB MIDI port and a sustain pedal socket.',
      long: 'A digital keyboard with touch-sensitive keys, a USB port that carries MIDI without a driver, and a socket for a standard sustain pedal. The speakers face forward and it runs on mains or batteries.',
      img: 'digital keyboard piano musical instrument',
      specs: {
        Keys: 'Touch sensitive',
        USB: 'Class-compliant MIDI, no driver',
        Pedal: 'Standard sustain pedal socket',
        Power: 'Mains or batteries',
      },
      facets: ['Keys', 'USB'],
      axes: [
        ['instrument_size', ['61 key', '76 key']],
        ['bundle', ['Keyboard only', 'With stand and pedal']],
      ],
      price: [12_800_00, 42_000_00],
      stock: [2, 36],
      moq: 1,
      grams: 6_800,
    },
    {
      key: 'music-inst-cajon',
      type: 'Cajon',
      title: 'Birch Cajon with Adjustable Snare Wires',
      brand: BRANDS.music,
      short:
        'Birch cajon with adjustable internal snare wires and a padded playing surface.',
      long: 'A birch cajon with internal snare wires that adjust from the back, so the snare buzz can be taken off entirely for a bass tone. The playing surface is bolted rather than glued at the top corners and the feet are rubber.',
      img: 'cajon drum percussion musical instrument',
      specs: {
        Body: 'Birch',
        Snares: 'Internal, adjustable from the back',
        Surface: 'Bolted top corners',
        Feet: 'Rubber',
      },
      facets: ['Body', 'Snares'],
      axes: [
        ['instrument_size', ['Standard', 'Compact']],
        ['finish', ['Natural', 'Walnut', 'Black']],
      ],
      price: [4_800_00, 16_800_00],
      stock: [3, 60],
      moq: 1,
      grams: 5_400,
      mrp: 0.13,
    },
  ]),

  shelf('gifts-party', [
    {
      key: 'gift-party-balloons',
      type: 'Latex balloon pack',
      title: 'Matt Latex Balloon Pack in a Colour Palette',
      brand: BRANDS.play,
      short:
        'Matt-finish latex balloon pack in a chosen palette, with a matched ribbon roll.',
      long: 'A pack of matt-finish latex balloons in a chosen colour palette, with a roll of ribbon matched to it. Matt rather than metallic, which photographs without hotspots, and the neck is thick enough to knot by hand.',
      img: 'party balloons decoration celebration',
      specs: {
        Finish: 'Matt latex',
        Supplied: 'Matched ribbon roll',
        Neck: 'Thick, hand knot',
      },
      facets: ['Finish'],
      axes: [
        ['theme', ['Neutral', 'Pastel', 'Jewel']],
        ['pack_count', ['Pack of 50', 'Pack of 100']],
      ],
      price: [96_000, 480_000],
      stock: [15, 280],
      moq: 1,
      grams: 320,
      sold: { content: [50, 'piece'], label: 'Pack of 50' },
      multipack: 50,
      featured: true,
    },
    {
      key: 'gift-party-giftbox',
      type: 'Rigid gift box',
      title: 'Rigid Gift Box with a Magnetic Lid and Ribbon Pull',
      brand: BRANDS.packaging,
      short:
        'Rigid gift box with a magnetic lid, a ribbon pull and a fitted paper shred.',
      long: 'A rigid gift box with a magnetic lid closure and a ribbon pull tab, supplied flat and assembled by folding the panels in. A shred of matching paper is included to pack the void.',
      img: 'gift box packaging present rigid',
      specs: {
        Closure: 'Magnetic lid',
        Pull: 'Ribbon tab',
        Assembly: 'Supplied flat, folds up',
        Supplied: 'Paper shred included',
      },
      facets: ['Closure', 'Assembly'],
      axes: [
        ['size', ['Small', 'Medium', 'Large']],
        ['colour', ['Kraft', 'Matt black', 'Ivory']],
        ['pack_count', ['Pack of 5', 'Pack of 20']],
      ],
      price: [180_000, 1_280_000],
      stock: [10, 200],
      moq: 1,
      grams: 900,
    },
    {
      key: 'gift-party-tableware',
      type: 'Party tableware set',
      title: 'Coordinated Party Tableware Set for Twelve',
      brand: BRANDS.play,
      short:
        'Coordinated party tableware set for twelve: plates, cups, napkins and a table cover.',
      long: 'A coordinated party tableware set for twelve - plates, cups, napkins and a table cover in one theme, so nothing has to be matched up. The plates are board rather than plastic and the cover is a printed paper with a thin lining.',
      img: 'party tableware plates cups celebration',
      specs: {
        Contents: 'Plates, cups, napkins and table cover',
        Serves: 'Twelve',
        Plates: 'Board, not plastic',
      },
      facets: ['Contents', 'Plates'],
      axes: [
        ['theme', ['Birthday', 'Celebration', 'Neutral']],
        ['colour', ['Gold', 'Rose', 'Blue']],
      ],
      price: [280_000, 980_000],
      stock: [10, 200],
      moq: 1,
      grams: 900,
      mrp: 0.16,
    },
  ]),

  // =======================================================================
  // BOOKS & MEDIA
  // =======================================================================
  shelf('books', [
    {
      key: 'book-ref-handbook',
      type: 'Technical handbook',
      title: 'Engineering Workshop Handbook, Sewn Hardback',
      brand: BRANDS.media,
      short:
        'Sewn hardback engineering workshop handbook with a ribbon marker and printed thumb tabs.',
      long: 'A sewn hardback workshop handbook, which is the binding that survives being opened flat on a bench every day for a decade. It carries a ribbon marker, printed thumb tabs down the fore edge and tables printed on a coated stock.',
      img: 'hardcover technical handbook book',
      specs: {
        Binding: 'Sewn hardback',
        Marker: 'Ribbon',
        Navigation: 'Printed thumb tabs',
        Paper: 'Coated stock for tables',
      },
      facets: ['Binding', 'Paper'],
      axes: [
        ['format', ['Hardback', 'Paperback']],
        ['language', ['English', 'Hindi']],
      ],
      price: [980_000, 2_800_000],
      stock: [6, 120],
      moq: 1,
      grams: 1_400,
      featured: true,
    },
    {
      key: 'book-ref-paperback',
      type: 'Trade paperback',
      title: 'Trade Paperback with a Perfect Binding and French Flaps',
      brand: BRANDS.media,
      short:
        'Trade paperback with a perfect binding, French flaps and a cream book paper.',
      long: 'A trade paperback with a perfect binding, French flaps that fold in at both covers, and a cream book paper that is easier on the eye than a bright white. The spine is squared rather than rounded.',
      img: 'paperback book trade publishing',
      specs: {
        Binding: 'Perfect bound, squared spine',
        Cover: 'French flaps',
        Paper: 'Cream book paper',
      },
      facets: ['Binding', 'Paper'],
      axes: [
        ['format', ['Paperback']],
        ['language', ['English', 'Hindi']],
      ],
      price: [280_000, 980_000],
      stock: [10, 200],
      moq: 1,
      grams: 380,
    },
    {
      key: 'book-ref-notecompanion',
      type: 'Workbook',
      title: 'Spiral-Bound Workbook with Perforated Pages',
      brand: BRANDS.media,
      short:
        'Spiral-bound workbook with perforated pages and a laminated cover.',
      long: 'A spiral-bound workbook whose pages are perforated at the gutter, so completed sheets come out without tearing the ones on either side. The cover is laminated board and the wire is at the head rather than the side.',
      img: 'spiral bound workbook educational book',
      specs: {
        Binding: 'Spiral, wire at the head',
        Pages: 'Perforated at the gutter',
        Cover: 'Laminated board',
      },
      facets: ['Binding', 'Pages'],
      axes: [
        ['format', ['A4', 'A5']],
        ['page_count', ['96 pages', '160 pages']],
      ],
      price: [180_000, 680_000],
      stock: [10, 200],
      moq: 1,
      grams: 420,
      mrp: 0.14,
    },
  ]),

  shelf('educational-materials', [
    {
      key: 'edu-mat-sciencekit',
      type: 'Science activity kit',
      title: 'Classroom Science Activity Kit with Teacher Notes',
      brand: BRANDS.media,
      short:
        'Classroom science activity kit with apparatus for a group of six and printed teacher notes.',
      long: 'A classroom science activity kit holding the apparatus for a group of six, a set of consumables and printed teacher notes with the expected results as well as the method. The tray is compartmented so a missing item is visible before the lesson.',
      img: 'science education kit classroom learning',
      specs: {
        'Group size': 'Six',
        Notes: 'Printed teacher notes with expected results',
        Tray: 'Compartmented',
      },
      facets: ['Group size', 'Notes'],
      axes: [
        ['grade_level', ['Primary', 'Lower secondary', 'Upper secondary']],
        ['subject', ['Physics', 'Chemistry', 'Biology']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [4, 80],
      moq: 1,
      grams: 3_400,
      featured: true,
    },
    {
      key: 'edu-mat-wallchart',
      type: 'Classroom wall chart',
      title: 'Laminated Classroom Wall Chart Set with Eyelets',
      brand: BRANDS.media,
      short:
        'Laminated classroom wall chart set with brass eyelets in the corners.',
      long: 'A set of laminated classroom wall charts with brass eyelets at the corners, so they hang rather than being taped to a wall and torn when they come down. Printed on a matt laminate that does not glare under a projector.',
      img: 'classroom wall charts educational posters',
      specs: {
        Lamination: 'Matt, non-glare',
        Eyelets: 'Brass, four corners',
        Supply: 'Rolled in a tube',
      },
      facets: ['Lamination', 'Eyelets'],
      axes: [
        ['subject', ['Mathematics', 'Science', 'Language']],
        ['piece_count', ['Set of 4', 'Set of 8']],
      ],
      price: [680_000, 2_400_000],
      stock: [6, 120],
      moq: 1,
      grams: 900,
    },
    {
      key: 'edu-mat-whiteboard',
      type: 'Classroom whiteboard',
      title: 'Magnetic Dry-Wipe Whiteboard with an Aluminium Frame',
      brand: BRANDS.media,
      short:
        'Magnetic dry-wipe whiteboard in an aluminium frame, with a pen tray and wall fixings.',
      long: 'A magnetic dry-wipe whiteboard with a steel-backed surface in an aluminium frame, a full-width pen tray and wall fixings supplied. The surface takes a magnet as well as a pen, which a melamine board does not.',
      img: 'whiteboard classroom office magnetic',
      specs: {
        Surface: 'Steel backed, magnetic and dry wipe',
        Frame: 'Aluminium',
        Tray: 'Full width pen tray',
        Supplied: 'Wall fixings',
      },
      facets: ['Surface', 'Frame'],
      axes: [
        ['material_type', ['900 x 600 mm', '1,200 x 900 mm', '1,800 x 1,200 mm']],
        ['board', ['Magnetic', 'Non-magnetic']],
      ],
      price: [1_280_00, 6_800_00],
      stock: [4, 70],
      moq: 1,
      grams: 6_200,
      mrp: 0.12,
    },
  ]),

  shelf('audio-video', [
    {
      key: 'av-media-bluetoothspeaker',
      type: 'Portable speaker',
      title: 'Portable Bluetooth Speaker with a Passive Radiator',
      brand: BRANDS.comms,
      short:
        'Portable Bluetooth speaker with a passive radiator, USB-C charging and a fabric grille.',
      long: 'A portable Bluetooth speaker with a passive radiator on the rear, which is what lets a small cabinet produce a low end without a port chuffing. USB-C charging, a fabric grille over a steel mesh, and a strap lug at each end.',
      img: 'bluetooth portable speaker audio',
      specs: {
        Driver: 'Full range with rear passive radiator',
        Charging: 'USB-C',
        Grille: 'Fabric over steel mesh',
        Fixing: 'Strap lug at each end',
      },
      facets: ['Driver', 'Charging'],
      axes: [
        ['format', ['Compact', 'Standard']],
        ['packaging', ['Boxed', 'Boxed with carry strap']],
      ],
      price: [2_400_00, 9_800_00],
      stock: [5, 100],
      moq: 1,
      grams: 620,
      featured: true,
    },
    {
      key: 'av-media-headphones',
      type: 'Over-ear headphones',
      title: 'Over-Ear Headphones with a Detachable Cable',
      brand: BRANDS.comms,
      short:
        'Over-ear headphones with a detachable cable, replaceable pads and a folding headband.',
      long: 'Over-ear headphones with a detachable cable and replaceable ear pads, which between them are the two parts that fail and the reason most headphones get thrown away. The headband folds and the cups rotate flat.',
      img: 'over ear headphones audio equipment',
      specs: {
        Cable: 'Detachable',
        Pads: 'Replaceable',
        Headband: 'Folding, cups rotate flat',
      },
      facets: ['Cable', 'Pads'],
      axes: [
        ['format', ['Wired', 'Wireless']],
        ['packaging', ['Boxed', 'Boxed with hard case']],
      ],
      price: [2_800_00, 14_800_00],
      stock: [4, 80],
      moq: 1,
      grams: 320,
    },
    {
      key: 'av-media-projector',
      type: 'Portable projector',
      title: 'Portable Projector with Keystone and HDMI',
      brand: BRANDS.comms,
      short:
        'Portable projector with vertical keystone correction, HDMI and a tripod thread.',
      long: 'A portable projector with vertical keystone correction, an HDMI input and a standard tripod thread in the base, so it can be set on a tripod rather than propped on books. The focus is a manual ring and the fan runs on a low setting for a quiet room.',
      img: 'portable projector home cinema av',
      specs: {
        Keystone: 'Vertical correction',
        Inputs: 'HDMI and USB',
        Mounting: 'Standard tripod thread',
        Focus: 'Manual ring',
      },
      facets: ['Keystone', 'Mounting'],
      axes: [
        ['resolution', ['720p', '1080p']],
        ['format', ['Projector only', 'Projector with screen']],
      ],
      price: [9_800_00, 38_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 1_400,
      mrp: 0.12,
    },
  ]),

  // =======================================================================
  // CHEMICALS & RAW MATERIALS
  // =======================================================================
  shelf('industrial-chemicals', [
    {
      key: 'chem-ind-caustic',
      type: 'Industrial alkali',
      title: 'Sodium Hydroxide Flakes in a Lined Drum',
      brand: BRANDS.chemical,
      short:
        'Sodium hydroxide flakes in a lined drum with a tamper-evident closure and a batch label.',
      long: 'Sodium hydroxide supplied as flakes in a lined drum with a tamper-evident closure. The label carries the grade, the batch and the assay; the safety data sheet travels with the order and should be read before the drum is opened.',
      img: 'industrial chemical drum container',
      specs: {
        Form: 'Flakes',
        Container: 'Lined drum, tamper-evident closure',
        Label: 'Grade, batch and assay',
        Storage: 'Cool, dry and ventilated; keep closed',
      },
      facets: ['Form', 'Container'],
      axes: [
        ['grade', ['Technical grade', 'Analytical reagent']],
        ['net_weight', ['5 kg', '25 kg']],
      ],
      price: [280_000, 1_680_000],
      stock: [6, 100],
      moq: 1,
      grams: 25_400,
      sold: { content: [25, 'kg'], per: [1, 'kg'] },
      featured: true,
    },
    {
      key: 'chem-ind-ipa',
      type: 'Industrial solvent',
      title: 'Isopropyl Alcohol in a Steel Drum',
      brand: BRANDS.chemical,
      short:
        'Isopropyl alcohol in a lined steel drum with a bung closure and a batch certificate reference.',
      long: 'Isopropyl alcohol in a lined steel drum with a standard bung closure, so a drum pump fits without an adapter. The label carries the batch number and a reference for the certificate of analysis.',
      img: 'solvent drum industrial chemical storage',
      specs: {
        Container: 'Lined steel drum, standard bung',
        Label: 'Batch number and certificate reference',
        Storage: 'Cool, ventilated, away from ignition sources',
      },
      facets: ['Container'],
      axes: [
        ['grade', ['Technical grade', 'Analytical reagent']],
        ['net_volume', ['5 L', '20 L', '200 L']],
      ],
      price: [480_000, 9_800_000],
      stock: [4, 80],
      moq: 1,
      grams: 16_800,
      sold: { content: [20, 'L'], per: [1, 'L'] },
      leadDays: 3,
    },
    {
      key: 'chem-ind-descaler',
      type: 'Process descaler',
      title: 'Inhibited Acid Descaler Concentrate',
      brand: BRANDS.chemical,
      short:
        'Inhibited acid descaler concentrate, with the inhibitor already in the formulation.',
      long: 'An acid descaler concentrate with a corrosion inhibitor already in the formulation, so the scale is attacked and the metal under it is not. The dilution table on the drum gives a ratio per material rather than a single figure.',
      img: 'chemical descaler drum industrial',
      specs: {
        Inhibitor: 'Included in the formulation',
        Dilution: 'Ratio per material on the label',
        Container: 'Lined drum',
        Storage: 'Cool, dry and ventilated',
      },
      facets: ['Inhibitor'],
      axes: [
        ['concentration', ['Standard', 'Concentrated']],
        ['net_volume', ['5 L', '25 L']],
      ],
      price: [380_000, 1_980_000],
      stock: [5, 90],
      moq: 1,
      grams: 26_000,
      sold: { content: [25, 'L'], per: [1, 'L'] },
      mrp: 0.11,
    },
  ]),

  shelf('plastics-polymers', [
    {
      key: 'chem-poly-hdpegranule',
      type: 'HDPE granule',
      title: 'HDPE Injection Moulding Granule in a Lined Sack',
      brand: BRANDS.chemical,
      short:
        'HDPE injection moulding granule in a lined sack, with the melt flow index on the label.',
      long: 'An HDPE injection moulding granule in a lined sack, with the melt flow index and the density printed on the label - the two figures a moulder actually sets a machine from. Supplied dry and sealed.',
      img: 'plastic granules polymer raw material',
      specs: {
        Process: 'Injection moulding',
        Label: 'Melt flow index and density',
        Sack: 'Lined, sealed',
      },
      facets: ['Process'],
      axes: [
        ['grade', ['General purpose', 'High flow']],
        ['colour', ['Natural', 'Black']],
        ['net_weight', ['25 kg']],
      ],
      price: [1_280_00, 3_400_00],
      stock: [6, 120],
      moq: 1,
      grams: 25_400,
      sold: { content: [25, 'kg'], per: [1, 'kg'] },
      featured: true,
    },
    {
      key: 'chem-poly-acrylicsheet',
      type: 'Cast acrylic sheet',
      title: 'Cast Acrylic Sheet with Protective Masking',
      brand: BRANDS.chemical,
      short:
        'Cast acrylic sheet supplied with protective masking on both faces, cut square.',
      long: 'A cast acrylic sheet with protective masking on both faces, cut square so it registers against a fence. Cast rather than extruded, which machines and laser-cuts cleanly where extruded sheet gums the tool.',
      img: 'acrylic sheet plastic material clear',
      specs: {
        Process: 'Cast',
        Masking: 'Both faces',
        Cutting: 'Machines and laser cuts cleanly',
        'Sheet size': '1000 x 500 mm',
      },
      facets: ['Process', 'Masking'],
      axes: [
        ['form', ['3 mm', '5 mm', '8 mm', '10 mm']],
        ['colour', ['Clear', 'Opal white', 'Black']],
      ],
      price: [480_000, 3_400_000],
      stock: [6, 110],
      moq: 1,
      grams: 3_600,
    },
    {
      key: 'chem-poly-nylonrod',
      type: 'Nylon rod',
      title: 'Extruded Nylon Rod for Machining',
      brand: BRANDS.chemical,
      short:
        'Extruded nylon rod for machining, supplied in cut lengths with the grade on the end.',
      long: 'An extruded nylon rod for machining, supplied in cut lengths with the grade marked on the end face so an offcut in a rack can still be identified. It machines without melting at sensible speeds and takes a thread.',
      img: 'nylon rod plastic engineering material',
      specs: {
        Process: 'Extruded',
        Marking: 'Grade marked on the end face',
        Machining: 'Turns and threads at moderate speeds',
      },
      facets: ['Process'],
      axes: [
        ['form', ['20 mm', '30 mm', '50 mm', '80 mm']],
        ['colour', ['Natural', 'Black']],
      ],
      price: [280_000, 2_400_000],
      stock: [8, 140],
      moq: 1,
      grams: 1_600,
      sold: { content: [1, 'm'], per: [1, 'm'] },
      mrp: 0.12,
    },
  ]),

  shelf('metals-alloys', [
    {
      key: 'chem-met-ssheet',
      type: 'Stainless steel sheet',
      title: 'Stainless Steel Sheet with a Brushed Finish',
      brand: BRANDS.metals,
      short:
        'Stainless steel sheet with a brushed finish and a protective film on the finished face.',
      long: 'A stainless steel sheet with a brushed finish and a peelable protective film on the finished face, supplied guillotined square. The grain direction runs along the length, which matters when two sheets are fitted side by side.',
      img: 'stainless steel sheet metal material',
      specs: {
        Finish: 'Brushed, grain along the length',
        Protection: 'Peelable film on the finished face',
        Cut: 'Guillotined square',
        'Sheet size': '1000 x 500 mm',
      },
      facets: ['Finish', 'Protection'],
      axes: [
        ['grade', ['304', '316']],
        ['thickness', ['0.9 mm', '1.2 mm', '1.5 mm', '2.0 mm']],
      ],
      price: [980_000, 6_800_000],
      stock: [5, 90],
      moq: 1,
      grams: 6_400,
      featured: true,
    },
    {
      key: 'chem-met-albar',
      type: 'Aluminium flat bar',
      title: 'Aluminium Flat Bar in Mill Finish',
      brand: BRANDS.metals,
      short:
        'Extruded aluminium flat bar in mill finish, supplied in cut lengths with square edges.',
      long: 'An extruded aluminium flat bar in a mill finish with square edges, supplied in cut lengths. Mill finish rather than anodised, because a bar that is going to be machined and then finished does not want a coating on it first.',
      img: 'aluminium flat bar metal material',
      specs: {
        Process: 'Extruded',
        Finish: 'Mill finish',
        Edges: 'Square',
      },
      facets: ['Process', 'Finish'],
      axes: [
        ['dimensions', ['25 x 3 mm', '40 x 5 mm', '50 x 6 mm']],
        ['length', ['1 m', '2 m', '3 m']],
      ],
      price: [180_000, 1_680_000],
      stock: [8, 140],
      moq: 1,
      grams: 1_400,
      sold: { content: [1, 'm'], per: [1, 'm'] },
    },
    {
      key: 'chem-met-brassrod',
      type: 'Brass round bar',
      title: 'Free-Cutting Brass Round Bar',
      brand: BRANDS.metals,
      short:
        'Free-cutting brass round bar, drawn to size and supplied in cut lengths.',
      long: 'A free-cutting brass round bar drawn to size, supplied in cut lengths with the ends faced. Free cutting, so it chips rather than strings on a lathe and holds a thread cleanly.',
      img: 'brass round bar metal material',
      specs: {
        Alloy: 'Free cutting brass',
        Process: 'Drawn to size',
        Ends: 'Faced',
      },
      facets: ['Alloy', 'Process'],
      axes: [
        ['dimensions', ['10 mm', '16 mm', '25 mm', '40 mm']],
        ['length', ['500 mm', '1 m']],
      ],
      price: [280_000, 3_400_000],
      stock: [8, 140],
      moq: 1,
      grams: 1_800,
      sold: { content: [1, 'm'], per: [1, 'm'] },
      mrp: 0.11,
    },
  ]),

  shelf('rubber-sealing', [
    {
      key: 'chem-rub-oring',
      type: 'O-ring assortment',
      title: 'Nitrile O-Ring Assortment in a Labelled Case',
      brand: BRANDS.metals,
      short:
        'Nitrile O-ring assortment in a labelled case, one size per compartment.',
      long: 'A nitrile O-ring assortment in a labelled case with one size to a compartment and a printed index in the lid, so a size is found rather than measured against a card. Nitrile, which suits mineral oils and does not suit brake fluid.',
      img: 'o rings rubber seals assortment',
      specs: {
        Material: 'Nitrile',
        Case: 'Labelled compartments with a printed index',
        Suitability: 'Mineral oils and greases',
      },
      facets: ['Material'],
      axes: [
        ['hardness', ['70 Shore A', '90 Shore A']],
        ['pack_count', ['225 piece', '419 piece']],
      ],
      price: [480_000, 1_680_000],
      stock: [8, 140],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'chem-rub-sheet',
      type: 'Rubber sheet',
      title: 'Insertion Rubber Sheet for Gasket Cutting',
      brand: BRANDS.metals,
      short:
        'Fabric-reinforced insertion rubber sheet for cutting gaskets, supplied on a roll.',
      long: 'A fabric-reinforced insertion rubber sheet for cutting gaskets, supplied on a roll. The fabric ply is what stops a cut gasket stretching as it is bolted up, which is why a plain sheet extrudes out of a flange and this does not.',
      img: 'rubber sheet roll industrial material',
      specs: {
        Reinforcement: 'Fabric insertion ply',
        Use: 'Gasket cutting',
        Supply: 'Roll',
      },
      facets: ['Reinforcement', 'Use'],
      axes: [
        ['thickness', ['1.5 mm', '3 mm', '5 mm']],
        ['material', ['Nitrile', 'EPDM']],
      ],
      price: [680_000, 4_200_000],
      stock: [5, 90],
      moq: 1,
      grams: 6_800,
      sold: { content: [1, 'm'], per: [1, 'm'] },
    },
    {
      key: 'chem-rub-extrusion',
      type: 'Rubber edge trim',
      title: 'Self-Gripping Rubber Edge Trim on a Coil',
      brand: BRANDS.metals,
      short:
        'Self-gripping rubber edge trim with a steel core, pushed onto a panel edge without adhesive.',
      long: 'A self-gripping rubber edge trim with a segmented steel core, which pushes onto a panel edge and stays there without adhesive. It takes a curve in one plane and can be cut with a knife.',
      img: 'rubber edge trim seal extrusion',
      specs: {
        Core: 'Segmented steel',
        Fitting: 'Push on, no adhesive',
        Cutting: 'Knife',
      },
      facets: ['Core', 'Fitting'],
      axes: [
        ['product_type', ['1-2 mm edge', '2-4 mm edge', '4-6 mm edge']],
        ['pack_count', ['5 m coil', '25 m coil']],
      ],
      price: [280_000, 2_400_000],
      stock: [8, 140],
      moq: 1,
      grams: 900,
      sold: { content: [5, 'm'], per: [1, 'm'] },
      mrp: 0.13,
    },
  ]),

  // =======================================================================
  // ENERGY & ENVIRONMENT
  // =======================================================================
  shelf('solar-renewables', [
    {
      key: 'ener-sol-panel',
      type: 'Solar photovoltaic panel',
      title: 'Monocrystalline Solar Panel with a Framed Glass Laminate',
      brand: BRANDS.energy,
      short:
        'Monocrystalline solar panel in an anodised frame, with a junction box and MC4 leads.',
      long: 'A monocrystalline solar panel in an anodised aluminium frame with drainage slots, a sealed junction box and factory-fitted MC4 leads. The glass is tempered and the frame carries mounting slots on the long sides.',
      img: 'solar panel photovoltaic renewable energy',
      specs: {
        Cells: 'Monocrystalline',
        Frame: 'Anodised aluminium with drainage slots',
        Junction: 'Sealed box with factory-fitted MC4 leads',
        Glass: 'Tempered',
      },
      facets: ['Cells', 'Frame'],
      axes: [
        ['power_rating', ['200 W', '350 W', '450 W']],
        ['voltage_rating', ['12 V system', '24 V system']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [3, 60],
      moq: 1,
      grams: 22_000,
      leadDays: 7,
      featured: true,
    },
    {
      key: 'ener-sol-inverter',
      type: 'Solar hybrid inverter',
      title: 'Hybrid Solar Inverter with Battery Port and Display',
      brand: BRANDS.energy,
      short:
        'Hybrid solar inverter with a battery port, an MPPT tracker and a graphical display.',
      long: 'A hybrid solar inverter with a battery port and an MPPT tracker, and a graphical display showing where the power is coming from and going at that moment. Wall mounting, with the terminals behind a removable cover.',
      img: 'solar inverter energy equipment',
      specs: {
        Tracker: 'MPPT',
        Battery: 'Battery port',
        Display: 'Graphical power-flow display',
        Mounting: 'Wall, terminals behind a cover',
      },
      facets: ['Tracker', 'Battery'],
      axes: [
        ['power_rating', ['3 kW', '5 kW']],
        ['system_configuration', ['Single phase']],
      ],
      price: [42_000_00, 96_000_00],
      stock: [1, 22],
      moq: 1,
      grams: 14_500,
      leadDays: 10,
    },
    {
      key: 'ener-sol-mount',
      type: 'Solar mounting kit',
      title: 'Roof Mounting Kit for Solar Panels with Adjustable Rails',
      brand: BRANDS.energy,
      short:
        'Roof mounting kit with adjustable rails, end clamps, mid clamps and stainless fixings.',
      long: 'A roof mounting kit with anodised rails, splices, end and mid clamps and stainless steel fixings. The rail slot takes the clamp anywhere along its length, so a panel does not have to land on a fixed hole.',
      img: 'solar panel mounting rails roof kit',
      specs: {
        Rails: 'Anodised aluminium with a continuous slot',
        Clamps: 'End and mid clamps',
        Fixings: 'Stainless steel',
      },
      facets: ['Rails', 'Fixings'],
      axes: [
        ['product_type', ['2 panel kit', '4 panel kit', '6 panel kit']],
        ['system_configuration', ['Pitched roof', 'Flat roof']],
      ],
      price: [4_800_00, 22_000_00],
      stock: [3, 50],
      moq: 1,
      grams: 12_000,
      mrp: 0.11,
    },
  ]),

  shelf('generators-backup-power', [
    {
      key: 'ener-gen-petrol',
      type: 'Portable generator',
      title: 'Petrol Portable Generator with Recoil and Electric Start',
      brand: BRANDS.energy,
      short:
        'Petrol portable generator with recoil and electric start, a low-oil cut-out and a fuel gauge.',
      long: 'A petrol portable generator with both recoil and electric start, a low-oil cut-out that shuts it down rather than letting it seize, and a fuel gauge on the tank. The outlets are on a panel with individual breakers.',
      img: 'portable petrol generator backup power',
      specs: {
        Start: 'Recoil and electric',
        Protection: 'Low-oil cut-out, breaker per outlet',
        Tank: 'Fuel gauge fitted',
        Frame: 'Tubular with anti-vibration mounts',
      },
      facets: ['Start', 'Protection'],
      axes: [
        ['power_rating', ['2.5 kVA', '5 kVA', '7.5 kVA']],
        ['enclosure', ['Open frame', 'Silenced canopy']],
      ],
      price: [28_000_00, 128_000_00],
      stock: [1, 20],
      moq: 1,
      grams: 58_000,
      leadDays: 10,
      featured: true,
    },
    {
      key: 'ener-gen-ups',
      type: 'Line-interactive UPS',
      title: 'Line-Interactive UPS with an LCD and Replaceable Battery',
      brand: BRANDS.energy,
      short:
        'Line-interactive UPS with automatic voltage regulation, an LCD and a user-replaceable battery.',
      long: 'A line-interactive UPS with automatic voltage regulation, so a brown-out is corrected without going to battery. The LCD shows load and runtime, and the battery is replaceable behind a front panel rather than requiring the unit to be opened.',
      img: 'ups uninterruptible power supply backup',
      specs: {
        Topology: 'Line interactive with AVR',
        Display: 'LCD showing load and runtime',
        Battery: 'User replaceable behind a front panel',
        Communications: 'USB for shutdown software',
      },
      facets: ['Topology', 'Battery'],
      axes: [
        ['power_rating', ['650 VA', '1,000 VA', '1,500 VA']],
        ['capacity', ['Standard runtime', 'Extended runtime']],
      ],
      price: [4_800_00, 24_000_00],
      stock: [3, 60],
      moq: 1,
      grams: 9_600,
    },
    {
      key: 'ener-gen-transferswitch',
      type: 'Manual transfer switch',
      title: 'Manual Changeover Transfer Switch in an Enclosure',
      brand: BRANDS.energy,
      short:
        'Manual changeover transfer switch in a steel enclosure, mechanically interlocked.',
      long: 'A manual changeover transfer switch in a steel enclosure, mechanically interlocked so mains and generator cannot be connected at the same time. The handle is on the door and the position is marked on the escutcheon.',
      img: 'transfer switch electrical enclosure generator',
      specs: {
        Interlock: 'Mechanical, mains and generator cannot connect together',
        Enclosure: 'Steel with door handle',
        Marking: 'Position marked on the escutcheon',
      },
      facets: ['Interlock', 'Enclosure'],
      axes: [
        ['power_rating', ['63 A', '100 A']],
        ['phase', ['Single phase', 'Three phase']],
      ],
      price: [9_800_00, 34_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 8_400,
      mrp: 0.1,
    },
  ]),

  shelf('water-treatment', [
    {
      key: 'ener-water-rosystem',
      type: 'Reverse osmosis system',
      title: 'Under-Sink Reverse Osmosis System with Pre-Filters',
      brand: BRANDS.energy,
      short:
        'Under-sink reverse osmosis system with staged pre-filters and quick-change cartridges.',
      long: 'An under-sink reverse osmosis system with staged pre-filters ahead of the membrane, all on quick-change cartridges that twist out without tools or a bucket. The tank, the tap and the tubing are supplied.',
      img: 'reverse osmosis water filter system',
      specs: {
        Stages: 'Staged pre-filters ahead of the membrane',
        Cartridges: 'Quick change, twist out',
        Supplied: 'Tank, tap and tubing',
      },
      facets: ['Stages', 'Cartridges'],
      axes: [
        ['filtration_stage', ['4 stage', '5 stage', '6 stage']],
        ['tank_capacity', ['8 L tank', '12 L tank']],
      ],
      price: [9_800_00, 28_000_00],
      stock: [3, 50],
      moq: 1,
      grams: 9_800,
      featured: true,
    },
    {
      key: 'ener-water-sedimentfilter',
      type: 'Sediment filter cartridge',
      title: 'Spun Polypropylene Sediment Filter Cartridge',
      brand: BRANDS.energy,
      short:
        'Spun polypropylene sediment filter cartridge with a graded density through the wall.',
      long: 'A spun polypropylene sediment cartridge with a graded density through the wall - coarser on the outside and finer inside - so it holds more before it blinds than a uniform cartridge of the same rating.',
      img: 'water filter cartridge sediment treatment',
      specs: {
        Media: 'Spun polypropylene, graded density',
        Format: 'Standard 10 in housing',
        Binder: 'Thermally bonded, no binder',
      },
      facets: ['Media', 'Format'],
      axes: [
        ['micron_rating', ['1 micron', '5 micron', '20 micron']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [96_000, 780_000],
      stock: [12, 220],
      moq: 1,
      grams: 260,
    },
    {
      key: 'ener-water-uvsteriliser',
      type: 'UV water steriliser',
      title: 'In-Line UV Water Steriliser with a Lamp Change Indicator',
      brand: BRANDS.energy,
      short:
        'In-line UV water steriliser in a stainless chamber, with a lamp-hours indicator.',
      long: 'An in-line UV steriliser in a stainless steel chamber, with an hours counter on the ballast that says when the lamp is due rather than leaving it to be guessed. The quartz sleeve comes out for cleaning without breaking the plumbing.',
      img: 'uv water steriliser treatment equipment',
      specs: {
        Chamber: 'Stainless steel',
        Indicator: 'Lamp hours counter on ballast',
        Sleeve: 'Quartz, removable for cleaning',
      },
      facets: ['Chamber', 'Indicator'],
      axes: [
        ['flow_capacity', ['2 gpm', '6 gpm', '12 gpm']],
        ['mounting', ['Horizontal', 'Vertical']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [2, 44],
      moq: 1,
      grams: 4_200,
      mrp: 0.12,
    },
  ]),

  shelf('air-quality', [
    {
      key: 'ener-air-purifier',
      type: 'Air purifier',
      title: 'HEPA Air Purifier with a Filter Change Indicator',
      brand: BRANDS.energy,
      short:
        'HEPA air purifier with a pre-filter, a carbon layer and a filter change indicator.',
      long: 'An air purifier with a washable pre-filter, a carbon layer and a HEPA filter, and an indicator that counts running hours rather than guessing. The fan has a night setting and the filter compartment opens without a tool.',
      img: 'air purifier hepa filter home',
      specs: {
        Filters: 'Washable pre-filter, carbon layer and HEPA',
        Indicator: 'Running-hours filter change indicator',
        Fan: 'Night setting',
        Access: 'Tool-free filter compartment',
      },
      facets: ['Filters', 'Indicator'],
      axes: [
        ['coverage_area', ['25 m2', '45 m2', '70 m2']],
        ['colour', ['White', 'Graphite']],
      ],
      price: [9_800_00, 32_000_00],
      stock: [3, 50],
      moq: 1,
      grams: 6_400,
      featured: true,
    },
    {
      key: 'ener-air-dehumidifier',
      type: 'Dehumidifier',
      title: 'Refrigerant Dehumidifier with a Continuous Drain Port',
      brand: BRANDS.energy,
      short:
        'Refrigerant dehumidifier with a humidistat, a continuous drain port and a full-tank cut-out.',
      long: 'A refrigerant dehumidifier with a humidistat, so it holds a level rather than running continuously, a continuous drain port for a hose, and a cut-out that stops it when the tank is full. Castors and a top handle are fitted.',
      img: 'dehumidifier air quality appliance',
      specs: {
        Control: 'Humidistat',
        Drain: 'Continuous drain port',
        Safety: 'Full-tank cut-out',
        Handling: 'Castors and top handle',
      },
      facets: ['Control', 'Drain'],
      axes: [
        ['coverage_area', ['12 L/day', '20 L/day', '30 L/day']],
        ['colour', ['White', 'Graphite']],
      ],
      price: [14_800_00, 38_000_00],
      stock: [2, 40],
      moq: 1,
      grams: 14_000,
    },
    {
      key: 'ener-air-co2monitor',
      type: 'Air quality monitor',
      title: 'Desktop CO2 and Air Quality Monitor with Logging',
      brand: BRANDS.energy,
      short:
        'Desktop CO2 and air quality monitor with a colour display and exportable logging.',
      long: 'A desktop monitor reading carbon dioxide, temperature and humidity, with a colour display and a log that exports over USB. The sensor is an NDIR type, which is the kind that can be calibrated rather than estimated from a proxy.',
      img: 'co2 air quality monitor device',
      specs: {
        Sensor: 'NDIR carbon dioxide',
        Measured: 'CO2, temperature and relative humidity',
        Logging: 'Exportable over USB',
        Display: 'Colour',
      },
      facets: ['Sensor', 'Logging'],
      axes: [
        ['device_type', ['Desktop', 'Wall mounted']],
        ['pack_count', ['Single', 'Pack of 3']],
      ],
      price: [4_800_00, 22_000_00],
      stock: [4, 70],
      moq: 1,
      grams: 380,
      mrp: 0.13,
    },
  ]),
];
