/**
 * Medical Devices: twenty-six shelves, three products each.
 *
 * The strictest department in the registry, and the rules are worth stating
 * before the data because every entry below was written under them.
 *
 * **NOTHING HERE MAKES A CLINICAL CLAIM.** No indication, no dose, no drug
 * strength, no outcome, no "safe for", no "prevents". A gauge is a dimension,
 * a length is a dimension, a connector standard is a fact about a fitting.
 * "Reduces infection" is a claim about a patient, and there is not one of them
 * in this file.
 *
 * **NOTHING HERE FABRICATES A REGULATORY STATUS.** No CE mark, no FDA
 * clearance, no notified body number, no MDR class, no ISO certificate. Those
 * are statements about documents that exist or do not, and a demonstration
 * catalogue that invents one is a demonstration catalogue that could get an
 * operator into real trouble the first time somebody screenshots it. The
 * schema HAS somewhere to put a device class and a UDI - `ProductDeviceInfo` -
 * and this seed deliberately writes nothing into it.
 *
 * **THE AXES ARE FREE-FORM, ON PURPOSE.** This department has no variant
 * template (see `domain/variants/registry.ts`) because its variants are
 * authored as free-form options and a hospital buyer picks several sizes at
 * once rather than narrowing to one. Giving it a template would replace a
 * working purchasing flow with a different one nobody asked for, so these
 * blueprints author their own keys - `volume`, `needle_gauge`, `pack_count` -
 * exactly as the department already does.
 *
 * The prices are in paise and are openly synthetic. They are in the right
 * order of magnitude for Indian hospital consumables so that a demonstration
 * basket adds up to a believable figure, and they are not a price list.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const MEDICAL_SHELVES: readonly Shelf[] = [
  // -----------------------------------------------------------------------
  shelf('abg-kit', [
    {
      key: 'med-abg-kit-1ml',
      type: 'Arterial blood gas sampling kit',
      title: '1 ml Arterial Blood Gas Sampling Kit with Dry Heparin',
      brand: BRANDS.medline,
      short:
        'Pre-assembled arterial sampling kit with a 1 ml dry balanced heparin syringe, safety needle and vented plunger.',
      long: 'A pre-assembled sampling kit supplied ready for use at the bedside. The 1 ml syringe is coated with dry balanced lithium heparin, the plunger is self-filling and vented so the barrel stops at the set volume, and a luer cap is included for transport. Packed sterile in a peel pouch with a safety needle and an alcohol swab.',
      img: 'arterial blood gas syringe sampling kit isolated',
      specs: {
        'Syringe volume': '1 ml',
        Anticoagulant: 'Dry balanced lithium heparin',
        Plunger: 'Self-filling, vented',
        'Needle supplied': '23G x 25 mm safety needle',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
        'Shelf life': '36 months from manufacture',
      },
      facets: ['Anticoagulant', 'Sterilisation method'],
      axes: [
        ['needle_gauge', ['22G', '23G', '25G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [78_000, 168_000],
      stock: [40, 420],
      moq: 1,
      grams: 620,
      packing: { type: 'Peel pouch', perInner: 25, innersPerOuter: 8, innerName: 'Box', outerName: 'Carton' },
      featured: true,
    },
    {
      key: 'med-abg-kit-3ml',
      type: 'Arterial blood gas sampling kit',
      title: '3 ml Arterial Blood Gas Kit with Filter Cap',
      brand: BRANDS.medline,
      short:
        'Three millilitre arterial sampling kit with a filtered vent cap and a needle safety shield.',
      long: 'A three millilitre kit for larger arterial draws. The filtered vent cap lets air leave the barrel while the sample is drawn and closes once the syringe is full, and the needle carries a hinged shield that locks over the bevel after use. Supplied sterile with a swab and a transport cap.',
      img: 'arterial blood gas syringe with filter cap',
      specs: {
        'Syringe volume': '3 ml',
        Anticoagulant: 'Dry balanced lithium heparin',
        Cap: 'Filtered vent cap',
        'Needle supplied': '22G x 32 mm shielded needle',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
      },
      facets: ['Anticoagulant', 'Sterilisation method'],
      axes: [
        ['needle_gauge', ['20G', '22G', '23G']],
        ['pack_count', ['Box of 25', 'Box of 50', 'Box of 100']],
      ],
      price: [96_000, 320_000],
      stock: [25, 300],
      moq: 1,
      grams: 900,
      mrp: 0.14,
    },
    {
      key: 'med-abg-kit-paed',
      type: 'Arterial blood gas sampling kit',
      title: 'Paediatric Arterial Sampling Kit, 0.5 ml Low Dead Space',
      brand: BRANDS.vascular,
      short:
        'Low dead-space 0.5 ml sampling kit for small-volume arterial draws, with a fine-gauge safety needle.',
      long: 'A small-volume kit built around a 0.5 ml barrel with a low dead-space hub, so the volume drawn is close to the volume delivered to the analyser. Supplied with a fine-gauge safety needle, a luer transport cap and an alcohol swab, sterile in a peel pouch.',
      img: 'small paediatric syringe medical sterile pouch',
      specs: {
        'Syringe volume': '0.5 ml',
        'Dead space': 'Low dead-space hub',
        Anticoagulant: 'Dry balanced lithium heparin',
        'Needle supplied': '25G x 16 mm safety needle',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Sterilisation method'],
      axes: [
        ['needle_gauge', ['25G', '27G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [88_000, 190_000],
      stock: [18, 200],
      moq: 1,
      grams: 480,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('abg-syringe', [
    {
      key: 'med-abg-syr-dry',
      type: 'Arterial blood gas syringe',
      title: 'Dry Heparin Arterial Blood Gas Syringe',
      brand: BRANDS.medline,
      short:
        'Self-filling arterial syringe pre-coated with dry balanced heparin, supplied sterile and capped.',
      long: 'An arterial syringe with the heparin already dried onto the barrel wall, so there is no liquid to displace and no dilution step at the bedside. The plunger is self-filling against arterial pressure and stops at the mark set by the operator. Supplied sterile with a luer transport cap.',
      img: 'blood gas syringe medical isolated white',
      specs: {
        Anticoagulant: 'Dry balanced lithium heparin',
        Plunger: 'Self-filling',
        Tip: 'Luer slip with transport cap',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
        'Shelf life': '36 months from manufacture',
      },
      facets: ['Anticoagulant', 'Tip'],
      axes: [
        ['volume', ['1 ml', '2 ml', '3 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [52_000, 178_000],
      stock: [60, 500],
      moq: 1,
      grams: 540,
      featured: true,
    },
    {
      key: 'med-abg-syr-liq',
      type: 'Arterial blood gas syringe',
      title: 'Liquid Heparin Arterial Syringe with Luer Lock',
      brand: BRANDS.vascular,
      short: 'Arterial syringe pre-filled with liquid heparin and a luer lock tip.',
      long: 'A luer lock arterial syringe supplied with liquid heparin already in the barrel. The lock fitting holds a needle or a transport cap securely through handling, and the barrel carries a clear graduation scale down to a tenth of a millilitre. Sterile, single use.',
      img: 'luer lock syringe medical product photography',
      specs: {
        Anticoagulant: 'Liquid sodium heparin',
        Tip: 'Luer lock',
        Graduation: '0.1 ml',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
      },
      facets: ['Anticoagulant', 'Tip'],
      axes: [
        ['volume', ['1 ml', '3 ml', '5 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [46_000, 165_000],
      stock: [45, 380],
      moq: 1,
      grams: 560,
      mrp: 0.12,
    },
    {
      key: 'med-abg-syr-safety',
      type: 'Arterial blood gas syringe',
      title: 'Arterial Syringe with Integrated Needle Shield',
      brand: BRANDS.medline,
      short:
        'Arterial syringe with a hinged shield that folds over the bevel one-handed after the draw.',
      long: 'An arterial syringe whose needle carries a hinged shield on the hub. The shield folds forward one-handed and clicks over the bevel, and the needle cannot be re-exposed once it has. The barrel is dry-heparinised and self-filling; the shield is supplied assembled.',
      img: 'safety syringe needle shield medical device',
      specs: {
        Anticoagulant: 'Dry balanced lithium heparin',
        'Safety feature': 'Hinged shield, one-handed activation',
        Tip: 'Luer slip',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
      },
      facets: ['Safety feature'],
      axes: [
        ['volume', ['1 ml', '3 ml']],
        ['needle_gauge', ['22G', '23G', '25G']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [72_000, 245_000],
      stock: [30, 320],
      moq: 1,
      grams: 620,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('adult-diaper', [
    {
      key: 'med-diaper-tape',
      type: 'Adult tape-style brief',
      title: 'Adult Tape-Style Brief with Refastenable Tabs',
      brand: BRANDS.medline,
      short:
        'Tape-style adult brief with four refastenable tabs, a breathable back sheet and a wetness indicator.',
      long: 'A tape-style brief for bedside changes, with two tabs a side that can be undone and refastened while checking fit. The back sheet is breathable across the hip panels, the core is a wood-pulp and superabsorbent blend, and a printed line along the outside fades as the core fills.',
      img: 'adult incontinence brief pack product',
      specs: {
        Style: 'Tape brief, refastenable',
        'Back sheet': 'Breathable side panels',
        Core: 'Wood pulp with superabsorbent polymer',
        Indicator: 'Wetness indicator strip',
        Latex: 'Latex-free',
      },
      facets: ['Style', 'Latex'],
      axes: [
        ['size', ['Medium', 'Large', 'Extra large']],
        ['absorbency', ['Day', 'Night']],
        ['pack_count', ['Pack of 10', 'Pack of 30']],
      ],
      price: [38_000, 165_000],
      stock: [40, 600],
      moq: 1,
      grams: 1_800,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      featured: true,
    },
    {
      key: 'med-diaper-pull',
      type: 'Adult pull-up pant',
      title: 'Adult Pull-Up Pant with Elasticated Waist',
      brand: BRANDS.medline,
      short:
        'Underwear-style pull-up pant with a fully elasticated waist and tear-away side seams.',
      long: 'A pull-up pant for someone who dresses themselves. The waist is elasticated the whole way round and the side seams tear open so the pant can be taken off without stepping out of it. The core is thinner than a tape brief at the same absorbency and the outer layer is cloth-like rather than film.',
      img: 'adult pull up incontinence pants package',
      specs: {
        Style: 'Pull-up pant, tear-away seams',
        Outer: 'Cloth-like non-woven',
        Core: 'Wood pulp with superabsorbent polymer',
        Latex: 'Latex-free',
      },
      facets: ['Style', 'Latex'],
      axes: [
        ['size', ['Small', 'Medium', 'Large', 'Extra large']],
        ['pack_count', ['Pack of 10', 'Pack of 20']],
      ],
      price: [42_000, 138_000],
      stock: [50, 520],
      moq: 1,
      grams: 1_500,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      mrp: 0.15,
    },
    {
      key: 'med-diaper-underpad',
      type: 'Disposable underpad',
      title: 'Disposable Bed Underpad, 60 x 90 cm',
      brand: BRANDS.medline,
      short: 'Fluff-cored disposable underpad with a non-slip polyethylene backing.',
      long: 'A disposable pad laid over a mattress or a chair. The fluff core spreads liquid across the sheet rather than letting it pool, and the polyethylene backing is embossed so the pad grips the surface under it. Supplied flat-packed in sealed bags.',
      img: 'disposable bed underpad medical stack',
      specs: {
        Size: '60 x 90 cm',
        Backing: 'Embossed polyethylene, non-slip',
        Core: 'Fluff pulp',
        Latex: 'Latex-free',
      },
      facets: ['Latex'],
      axes: [
        ['size', ['60 x 60 cm', '60 x 90 cm']],
        ['absorbency', ['Standard', 'Extra']],
        ['pack_count', ['Pack of 25', 'Pack of 50']],
      ],
      price: [34_000, 128_000],
      stock: [60, 700],
      moq: 1,
      grams: 2_400,
      sold: { content: [25, 'piece'], label: 'Pack of 25' },
      multipack: 25,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('closed-iv-cannula', [
    {
      key: 'med-closed-cannula-port',
      type: 'Closed IV cannula',
      title: 'Closed IV Cannula with Injection Port and Wings',
      brand: BRANDS.vascular,
      short:
        'Closed-system peripheral cannula with a pre-attached extension, an injection port and fixation wings.',
      long: 'A closed-system peripheral cannula supplied with its extension line already attached, so the hub is not opened at insertion. The injection port sits on the extension rather than on the hub, the wings are flexible and carry suture eyes, and the catheter is radiopaque along its length.',
      img: 'closed iv cannula catheter medical device',
      specs: {
        System: 'Closed system with pre-attached extension',
        'Catheter material': 'Polyurethane, radiopaque',
        Port: 'Injection port on extension line',
        Wings: 'Flexible with suture eyes',
        'Sterilisation method': 'Ethylene oxide',
        Latex: 'Latex-free',
      },
      facets: ['System', 'Catheter material', 'Latex'],
      axes: [
        ['gauge', ['24G', '22G', '20G', '18G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [220_000, 780_000],
      stock: [20, 240],
      moq: 1,
      grams: 750,
      featured: true,
    },
    {
      key: 'med-closed-cannula-safety',
      type: 'Closed IV cannula',
      title: 'Closed IV Cannula with Passive Needle Guard',
      brand: BRANDS.vascular,
      short:
        'Closed-system cannula whose needle guard engages automatically as the stylet is withdrawn.',
      long: 'A closed-system cannula with a passive guard: the shield travels over the needle tip as the stylet leaves the catheter, without a separate step. The extension line and blood-control septum are pre-assembled, and the hub is colour-coded to the gauge.',
      img: 'safety iv cannula needle guard sterile',
      specs: {
        System: 'Closed system, blood-control septum',
        'Safety feature': 'Passive needle guard',
        'Catheter material': 'Polyurethane, radiopaque',
        'Colour coding': 'Hub colour-coded to gauge',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['System', 'Safety feature'],
      axes: [
        ['gauge', ['22G', '20G', '18G', '16G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [260_000, 880_000],
      stock: [15, 200],
      moq: 1,
      grams: 780,
      mrp: 0.11,
    },
    {
      key: 'med-closed-cannula-dual',
      type: 'Closed IV cannula',
      title: 'Dual-Port Closed IV Cannula with Extension',
      brand: BRANDS.vascular,
      short:
        'Closed cannula with two injection ports on a 200 mm extension and a slide clamp.',
      long: 'A closed cannula whose extension carries two injection ports and a slide clamp, so a second line can be added without breaking the connection at the hub. The extension is 200 mm of clear tubing with a printed priming volume, and the catheter is radiopaque.',
      img: 'iv cannula extension line dual port medical',
      specs: {
        System: 'Closed system with dual-port extension',
        'Extension length': '200 mm',
        'Catheter material': 'Polyurethane, radiopaque',
        Clamp: 'Slide clamp on extension',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['System'],
      axes: [
        ['gauge', ['22G', '20G', '18G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [290_000, 920_000],
      stock: [12, 180],
      moq: 1,
      grams: 820,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('dc-flush-syringe-swab-cap', [
    {
      key: 'med-dc-flush-swab',
      type: 'Pre-filled flush syringe with swab cap',
      title: 'Pre-Filled Saline Flush Syringe with Disinfecting Swab Cap',
      brand: BRANDS.vascular,
      short:
        'Pre-filled sodium chloride flush syringe supplied with a disinfecting cap on the luer.',
      long: 'A single-use flush syringe filled with sterile sodium chloride solution and capped with a disinfecting swab cap. The cap stays on the luer until the syringe is used and is discarded with it. The barrel is graduated and the plunger rod is scored so it cannot be refilled.',
      img: 'prefilled saline flush syringe medical',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Cap: 'Disinfecting swab cap, single use',
        Barrel: 'Graduated, non-refillable plunger',
        Tip: 'Luer lock',
        'Sterilisation method': 'Steam',
      },
      facets: ['Solution', 'Tip'],
      axes: [
        ['volume', ['3 ml', '5 ml', '10 ml']],
        ['pack_count', ['Box of 30', 'Box of 60']],
      ],
      price: [180_000, 520_000],
      stock: [25, 280],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'med-dc-flush-twin',
      type: 'Pre-filled flush syringe with swab cap',
      title: 'Twin-Pack Flush Syringe with Swab Caps',
      brand: BRANDS.vascular,
      short: 'Two pre-filled saline flush syringes in one pouch, each with its own swab cap.',
      long: 'Two flush syringes sealed in one peel pouch so a line can be flushed before and after a dose without opening a second pack. Each syringe carries its own disinfecting swab cap and its own graduation scale.',
      img: 'twin pack prefilled syringe sterile pouch',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Configuration: 'Two syringes per pouch',
        Cap: 'Disinfecting swab cap on each',
        Tip: 'Luer lock',
        'Sterilisation method': 'Steam',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['5 ml', '10 ml']],
        ['pack_count', ['Box of 30', 'Box of 60']],
      ],
      price: [240_000, 640_000],
      stock: [20, 220],
      moq: 1,
      grams: 1_050,
    },
    {
      key: 'med-dc-flush-luerslip',
      type: 'Pre-filled flush syringe with swab cap',
      title: 'Luer Slip Flush Syringe with Protective Swab Cap',
      brand: BRANDS.medline,
      short: 'Luer slip pre-filled flush syringe with a swab cap, for connectors without a lock.',
      long: 'A pre-filled flush syringe with a luer slip tip for connectors that take a push fit rather than a thread. The swab cap seats on the slip and is removed at the point of use. Filled with sterile sodium chloride solution and graduated along the barrel.',
      img: 'luer slip syringe saline flush product',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Tip: 'Luer slip',
        Cap: 'Disinfecting swab cap',
        'Sterilisation method': 'Steam',
      },
      facets: ['Tip', 'Solution'],
      axes: [
        ['volume', ['3 ml', '5 ml', '10 ml']],
        ['pack_count', ['Box of 30', 'Box of 60']],
      ],
      price: [165_000, 480_000],
      stock: [22, 260],
      moq: 1,
      grams: 880,
      mrp: 0.1,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('disinfectant-cap', [
    {
      key: 'med-disinfect-cap-needlefree',
      type: 'Disinfecting port cap',
      title: 'Disinfecting Cap for Needle-Free Connectors',
      brand: BRANDS.vascular,
      short:
        'Single-use cap holding an alcohol-saturated pad, for needle-free luer connectors.',
      long: 'A twist-on cap containing a pad saturated with 70% isopropyl alcohol, for the septum of a needle-free connector. The cap stays in place between accesses and is discarded when removed. Supplied on a strip that peels one cap at a time.',
      img: 'disinfecting port cap medical alcohol',
      specs: {
        Compatibility: 'Needle-free luer connectors',
        Agent: '70% isopropyl alcohol pad',
        Fitting: 'Twist-on, single use',
        Presentation: 'Peel strip',
      },
      facets: ['Compatibility', 'Agent'],
      axes: [['pack_count', ['Strip of 10', 'Box of 100', 'Box of 250']]],
      price: [42_000, 380_000],
      stock: [40, 500],
      moq: 1,
      grams: 320,
      featured: true,
    },
    {
      key: 'med-disinfect-cap-male',
      type: 'Disinfecting port cap',
      title: 'Disinfecting Cap for Male Luer Ends',
      brand: BRANDS.vascular,
      short: 'Alcohol-saturated cap for the male luer end of an administration set.',
      long: 'A cap for the male luer at the end of an administration set, so a line that is disconnected between infusions has its tip covered rather than left open. Contains an alcohol-saturated sponge and threads onto the luer.',
      img: 'male luer cap disinfectant medical strip',
      specs: {
        Compatibility: 'Male luer ends',
        Agent: '70% isopropyl alcohol sponge',
        Fitting: 'Threaded, single use',
      },
      facets: ['Compatibility', 'Agent'],
      axes: [['pack_count', ['Box of 100', 'Box of 250']]],
      price: [140_000, 340_000],
      stock: [30, 380],
      moq: 1,
      grams: 300,
    },
    {
      key: 'med-disinfect-cap-combi',
      type: 'Disinfecting port cap',
      title: 'Combination Disinfecting Cap Pack, Male and Female',
      brand: BRANDS.medline,
      short: 'Mixed pack of male and female disinfecting caps for a full line changeover.',
      long: 'A mixed pack carrying both cap types, so a line changeover can be done from one box rather than two. Each cap holds an alcohol-saturated pad and is individually sealed on its strip.',
      img: 'medical disinfecting caps assorted pack',
      specs: {
        Compatibility: 'Male luer ends and needle-free connectors',
        Agent: '70% isopropyl alcohol pad',
        Configuration: 'Mixed pack',
      },
      facets: ['Compatibility'],
      axes: [['pack_count', ['Box of 100', 'Box of 200']]],
      price: [180_000, 320_000],
      stock: [25, 260],
      moq: 1,
      grams: 340,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('enfit-syringe', [
    {
      key: 'med-enfit-dosing',
      type: 'ENFit dosing syringe',
      title: 'ENFit Enteral Dosing Syringe, Sterile',
      brand: BRANDS.enteral,
      short:
        'Sterile enteral dosing syringe with an ENFit connector, printed graduations and a low dead-space tip.',
      long: 'An enteral syringe with an ENFit connector, which does not mate with a luer fitting. The graduations are printed rather than moulded so they stay legible after handling, and the tip is low dead-space so the volume drawn is close to the volume delivered.',
      img: 'enteral feeding syringe enfit medical',
      specs: {
        Connector: 'ENFit, ISO 80369-3',
        Graduation: 'Printed scale',
        'Dead space': 'Low dead-space tip',
        Sterility: 'Sterile, single use',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Connector', 'Sterility'],
      axes: [
        ['volume', ['1 ml', '5 ml', '20 ml', '60 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [110_000, 420_000],
      stock: [30, 340],
      moq: 1,
      grams: 700,
      featured: true,
    },
    {
      key: 'med-enfit-reusable',
      type: 'ENFit dosing syringe',
      title: 'Reusable ENFit Syringe with Purple Barrel',
      brand: BRANDS.enteral,
      short:
        'Non-sterile reusable ENFit syringe in a purple barrel, for repeat dosing over a single patient stay.',
      long: 'A reusable enteral syringe for repeat doses on one patient. The purple barrel is the convention that distinguishes an enteral device from a parenteral one at a glance, and the ENFit connector cannot be joined to a luer. Supplied non-sterile in bulk.',
      img: 'purple enteral syringe reusable medical',
      specs: {
        Connector: 'ENFit, ISO 80369-3',
        'Barrel colour': 'Purple',
        Sterility: 'Non-sterile',
        Reuse: 'Reusable, single patient',
      },
      facets: ['Connector', 'Sterility'],
      axes: [
        ['volume', ['5 ml', '20 ml', '60 ml']],
        ['pack_count', ['Bag of 25', 'Box of 100']],
      ],
      price: [70_000, 300_000],
      stock: [35, 400],
      moq: 1,
      grams: 640,
      mrp: 0.12,
    },
    {
      key: 'med-enfit-bolus',
      type: 'ENFit dosing syringe',
      title: '60 ml ENFit Bolus Syringe with Catheter Tip Adapter',
      brand: BRANDS.enteral,
      short:
        'Sixty millilitre ENFit bolus syringe supplied with a transition adapter for legacy catheter tips.',
      long: 'A sixty millilitre bolus syringe with an ENFit connector, supplied with a transition adapter so it can be used on a tube that still carries a legacy catheter tip. The barrel has a wide finger flange for one-handed delivery.',
      img: 'large bolus enteral feeding syringe 60ml',
      specs: {
        Connector: 'ENFit with catheter tip transition adapter',
        Volume: '60 ml',
        Flange: 'Wide finger flange',
        Sterility: 'Sterile, single use',
      },
      facets: ['Connector', 'Sterility'],
      axes: [['pack_count', ['Box of 20', 'Box of 50', 'Box of 100']]],
      price: [150_000, 620_000],
      stock: [20, 240],
      moq: 1,
      grams: 900,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('flush-syringe', [
    {
      key: 'med-flush-saline',
      type: 'Pre-filled saline flush syringe',
      title: 'Pre-Filled Sodium Chloride Flush Syringe',
      brand: BRANDS.vascular,
      short: 'Single-use pre-filled flush syringe with sterile 0.9% sodium chloride.',
      long: 'A pre-filled flush syringe for maintaining a vascular access line. The barrel is graduated, the plunger cannot be drawn back past its stop, and the luer lock carries a tamper-evident tip cap. Supplied sterile inside and out.',
      img: 'prefilled saline syringe flush sterile',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Tip: 'Luer lock with tamper-evident cap',
        Barrel: 'Graduated',
        Sterility: 'Sterile fluid path and outer surface',
      },
      facets: ['Solution', 'Tip'],
      axes: [
        ['volume', ['3 ml', '5 ml', '10 ml']],
        ['pack_count', ['Box of 30', 'Box of 100']],
      ],
      price: [140_000, 620_000],
      stock: [35, 420],
      moq: 1,
      grams: 950,
      featured: true,
    },
    {
      key: 'med-flush-lowvol',
      type: 'Pre-filled saline flush syringe',
      title: 'Low-Volume Flush Syringe for Paediatric Lines',
      brand: BRANDS.vascular,
      short:
        'Small-volume pre-filled flush syringe with a fine graduation scale for paediatric lines.',
      long: 'A small-volume flush syringe with graduations at a fifth of a millilitre, so a small line can be flushed to a measured volume. Filled with sterile sodium chloride solution and supplied with a luer lock tip cap.',
      img: 'small volume prefilled syringe medical paediatric',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Graduation: '0.2 ml',
        Tip: 'Luer lock',
        Sterility: 'Sterile fluid path',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['1 ml', '2 ml', '3 ml']],
        ['pack_count', ['Box of 30', 'Box of 60']],
      ],
      price: [130_000, 400_000],
      stock: [25, 300],
      moq: 1,
      grams: 720,
    },
    {
      key: 'med-flush-bulk',
      type: 'Pre-filled saline flush syringe',
      title: 'Bulk Case of Pre-Filled Flush Syringes',
      brand: BRANDS.medline,
      short:
        'Case quantity of pre-filled saline flush syringes for a ward store, in tray-packed boxes.',
      long: 'A case of pre-filled flush syringes packed in trays of thirty, for a ward or theatre store rather than a trolley. Each syringe is the same sterile sodium chloride flush supplied singly; the difference is the outer.',
      img: 'case of prefilled syringes medical warehouse',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Presentation: 'Tray-packed, 30 per tray',
        Tip: 'Luer lock',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['5 ml', '10 ml']],
        ['pack_count', ['Case of 240', 'Case of 480']],
      ],
      price: [980_000, 3_600_000],
      stock: [6, 60],
      moq: 1,
      step: 1,
      grams: 9_800,
      sold: { content: [240, 'piece'], label: 'Case of 240' },
      multipack: 240,
      packing: { type: 'Tray', perInner: 30, innersPerOuter: 8, innerName: 'Tray', outerName: 'Case' },
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('infant-feeding-tube', [
    {
      key: 'med-infant-tube-graduated',
      type: 'Infant feeding tube',
      title: 'Graduated Infant Feeding Tube with ENFit Connector',
      brand: BRANDS.enteral,
      short:
        'Radiopaque infant feeding tube with centimetre graduations along the shaft and an ENFit connector.',
      long: 'A soft feeding tube for neonatal and infant use, marked in centimetres along the shaft so depth can be read at the lip. The tip is closed and rounded with two lateral eyes, the shaft carries a radiopaque line, and the proximal end is an ENFit connector.',
      img: 'infant feeding tube medical graduated',
      specs: {
        Connector: 'ENFit, ISO 80369-3',
        Tip: 'Closed rounded tip, two lateral eyes',
        Marking: 'Centimetre graduations',
        Radiopacity: 'Radiopaque line along shaft',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Connector', 'Radiopacity'],
      axes: [
        ['french_size', ['Fr 5', 'Fr 6', 'Fr 8']],
        ['length', ['40 cm', '50 cm']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [190_000, 680_000],
      stock: [20, 240],
      moq: 1,
      grams: 620,
      featured: true,
    },
    {
      key: 'med-infant-tube-pvcfree',
      type: 'Infant feeding tube',
      title: 'PVC-Free Infant Feeding Tube, Polyurethane',
      brand: BRANDS.enteral,
      short: 'Polyurethane infant feeding tube with a thin wall and a wide internal bore.',
      long: 'A polyurethane feeding tube with a thinner wall than a PVC tube of the same outside diameter, so the internal bore is wider at the same French size. Supplied sterile with a closed rounded tip and centimetre markings.',
      img: 'polyurethane feeding tube neonatal medical',
      specs: {
        Material: 'Polyurethane, PVC-free',
        Connector: 'ENFit, ISO 80369-3',
        Wall: 'Thin wall, wide bore',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Material', 'Connector'],
      axes: [
        ['french_size', ['Fr 5', 'Fr 6', 'Fr 8']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [240_000, 720_000],
      stock: [15, 180],
      moq: 1,
      grams: 540,
      mrp: 0.13,
    },
    {
      key: 'med-infant-tube-weighted',
      type: 'Infant feeding tube',
      title: 'Weighted-Tip Infant Feeding Tube with Stylet',
      brand: BRANDS.enteral,
      short:
        'Infant feeding tube with a tungsten-weighted tip and a removable stylet, supplied sterile.',
      long: 'A feeding tube whose distal tip carries a tungsten weight, supplied with a removable stylet inside the lumen. The stylet is withdrawn once the tube is in position and discarded. Centimetre graduations run the length of the shaft.',
      img: 'weighted feeding tube stylet medical sterile',
      specs: {
        Tip: 'Tungsten-weighted',
        Stylet: 'Removable, supplied in lumen',
        Connector: 'ENFit, ISO 80369-3',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Connector'],
      axes: [
        ['french_size', ['Fr 6', 'Fr 8']],
        ['length', ['50 cm', '90 cm']],
        ['pack_count', ['Box of 10', 'Box of 25']],
      ],
      price: [320_000, 980_000],
      stock: [10, 120],
      moq: 1,
      grams: 480,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('infusion-set', [
    {
      key: 'med-infusion-gravity',
      type: 'Gravity infusion set',
      title: 'Gravity Infusion Set with Roller Clamp, 20 Drops/ml',
      brand: BRANDS.vascular,
      short:
        'Vented gravity infusion set with a 20 drops per millilitre chamber, roller clamp and injection port.',
      long: 'A gravity administration set with a vented spike, a transparent drip chamber calibrated at twenty drops to the millilitre, a roller clamp on the line and a latex-free Y injection port. The tubing is 180 cm of clear PVC with a luer lock at the patient end.',
      img: 'iv infusion set drip chamber medical',
      specs: {
        'Drip rate': '20 drops/ml',
        Chamber: 'Transparent, vented spike',
        'Flow control': 'Roller clamp',
        Port: 'Y injection port',
        'Tubing length': '180 cm',
        Latex: 'Latex-free',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Drip rate', 'Latex', 'Flow control'],
      axes: [
        ['drop_factor', ['20 drops/ml', '60 drops/ml']],
        ['tubing_length', ['150 cm', '180 cm', '210 cm']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [95_000, 420_000],
      stock: [30, 400],
      moq: 1,
      grams: 1_100,
      featured: true,
    },
    {
      key: 'med-infusion-burette',
      type: 'Burette infusion set',
      title: 'Burette Infusion Set, 150 ml Graduated Chamber',
      brand: BRANDS.vascular,
      short:
        'Paediatric burette set with a 150 ml graduated chamber, micro-drip and an air vent with filter.',
      long: 'A burette set for measured-volume delivery. The chamber holds 150 ml, is graduated in millilitres and carries a filtered air vent at the top and a floating valve at the bottom. The drip is micro-calibrated at sixty drops to the millilitre.',
      img: 'burette infusion set graduated chamber medical',
      specs: {
        'Chamber volume': '150 ml, graduated',
        'Drip rate': '60 drops/ml',
        Vent: 'Filtered air vent',
        Valve: 'Floating shut-off valve',
        Latex: 'Latex-free',
      },
      facets: ['Drip rate', 'Latex'],
      axes: [
        ['chamber_volume', ['100 ml', '150 ml']],
        ['pack_count', ['Box of 10', 'Box of 25']],
      ],
      price: [180_000, 560_000],
      stock: [15, 180],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'med-infusion-filtered',
      type: 'Filtered infusion set',
      title: 'Infusion Set with 0.2 Micron In-Line Filter',
      brand: BRANDS.vascular,
      short:
        'Gravity infusion set with a 0.2 micron in-line filter and a low-sorbing PVC-free line.',
      long: 'A gravity set with a 0.2 micron filter housing in the line. The tubing is PVC-free and low-sorbing, the chamber is vented, and the filter housing carries its own priming port so the line can be cleared before connection.',
      img: 'in line filter infusion set medical tubing',
      specs: {
        Filter: '0.2 micron in-line',
        'Tubing material': 'PVC-free, low-sorbing',
        'Drip rate': '20 drops/ml',
        Latex: 'Latex-free',
      },
      facets: ['Filter', 'Tubing material', 'Latex'],
      axes: [
        ['tubing_length', ['180 cm', '210 cm']],
        ['pack_count', ['Box of 10', 'Box of 25']],
      ],
      price: [280_000, 720_000],
      stock: [12, 140],
      moq: 1,
      grams: 1_250,
      mrp: 0.12,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('insulin-syringe', [
    {
      key: 'med-insulin-u100',
      type: 'Insulin syringe',
      title: 'U-100 Insulin Syringe with Fixed Needle',
      brand: BRANDS.medline,
      short:
        'Single-use U-100 insulin syringe with a permanently attached needle and a unit-marked barrel.',
      long: 'A single-use insulin syringe whose needle is bonded to the barrel, so there is no hub dead space between them. The barrel is printed in units on a U-100 scale, the plunger seal is siliconised for a smooth stroke, and the needle carries a protective sheath.',
      img: 'insulin syringe unit scale medical isolated',
      specs: {
        Scale: 'U-100 unit markings',
        Needle: 'Permanently attached, siliconised',
        'Dead space': 'No hub dead space',
        'Sterilisation method': 'Ethylene oxide',
        Reuse: 'Single use',
      },
      facets: ['Scale', 'Sterilisation method'],
      axes: [
        ['capacity', ['0.3 ml', '0.5 ml', '1 ml']],
        ['needle_gauge', ['29G', '30G', '31G']],
        ['pack_count', ['Box of 100']],
      ],
      price: [48_000, 150_000],
      stock: [40, 500],
      moq: 1,
      grams: 380,
      featured: true,
    },
    {
      key: 'med-insulin-safety',
      type: 'Insulin syringe',
      title: 'U-100 Insulin Syringe with Retractable Needle',
      brand: BRANDS.medline,
      short: 'Insulin syringe whose needle retracts into the barrel when the plunger is fully depressed.',
      long: 'An insulin syringe with a retraction mechanism in the plunger: pressing past the last graduation draws the needle back into the barrel, and it cannot be pushed out again. The barrel is printed on a U-100 scale.',
      img: 'retractable safety insulin syringe medical',
      specs: {
        Scale: 'U-100 unit markings',
        'Safety feature': 'Needle retracts into barrel',
        Reuse: 'Single use',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Safety feature', 'Scale'],
      axes: [
        ['capacity', ['0.5 ml', '1 ml']],
        ['needle_gauge', ['29G', '30G']],
        ['pack_count', ['Box of 100']],
      ],
      price: [96_000, 220_000],
      stock: [25, 300],
      moq: 1,
      grams: 420,
    },
    {
      key: 'med-insulin-pen-needle',
      type: 'Pen needle',
      title: 'Pen Needle for Insulin Pens, Thin Wall',
      brand: BRANDS.medline,
      short:
        'Thin-wall pen needle with a universal thread, supplied sterile with inner and outer shields.',
      long: 'A pen needle with a thin wall, so the internal bore is wider at the same outside gauge. The thread fits the pens that use the common standard, and each needle is supplied with an inner shield and an outer cover in a sealed blister.',
      img: 'insulin pen needle box medical device',
      specs: {
        Fitting: 'Universal pen thread',
        Wall: 'Thin wall',
        Shields: 'Inner shield and outer cover',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Fitting'],
      axes: [
        ['needle_gauge', ['31G', '32G', '33G']],
        ['needle_length', ['4 mm', '5 mm', '8 mm']],
        ['pack_count', ['Box of 100']],
      ],
      price: [52_000, 175_000],
      stock: [35, 420],
      moq: 1,
      grams: 260,
      mrp: 0.14,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('iv-cannula', [
    {
      key: 'med-iv-cannula-ported',
      type: 'Peripheral IV cannula',
      title: 'Ported IV Cannula with Wings and Flashback Chamber',
      brand: BRANDS.vascular,
      short:
        'Winged peripheral cannula with an injection port, a transparent flashback chamber and a radiopaque catheter.',
      long: 'A winged peripheral cannula with an injection port on the hub and a clear flashback chamber behind it. The catheter is radiopaque polyurethane with a tapered tip, the wings are soft and carry suture eyes, and the hub is colour-coded to the gauge.',
      img: 'iv cannula intravenous catheter medical device',
      specs: {
        Port: 'Injection port on hub',
        'Catheter material': 'Polyurethane, radiopaque',
        Wings: 'Soft wings with suture eyes',
        'Colour coding': 'Hub colour-coded to gauge',
        'Sterilisation method': 'Ethylene oxide',
        Latex: 'Latex-free',
      },
      facets: ['Port', 'Catheter material', 'Latex'],
      axes: [
        ['gauge', ['24G', '22G', '20G', '18G', '16G']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [120_000, 520_000],
      stock: [30, 400],
      moq: 1,
      grams: 640,
      featured: true,
    },
    {
      key: 'med-iv-cannula-nonported',
      type: 'Peripheral IV cannula',
      title: 'Non-Ported IV Cannula, Straight Hub',
      brand: BRANDS.vascular,
      short: 'Straight-hub peripheral cannula without an injection port, for a dedicated line.',
      long: 'A straight-hub cannula with no injection port, for a line that will carry one infusion. The absence of the port shortens the hub and removes a septum from the fluid path. Radiopaque catheter, colour-coded hub, supplied sterile.',
      img: 'straight hub iv cannula catheter sterile',
      specs: {
        Port: 'No injection port',
        'Catheter material': 'FEP, radiopaque',
        'Colour coding': 'Hub colour-coded to gauge',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Port', 'Catheter material'],
      axes: [
        ['gauge', ['22G', '20G', '18G', '16G']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [98_000, 420_000],
      stock: [30, 420],
      moq: 1,
      grams: 580,
      mrp: 0.11,
    },
    {
      key: 'med-iv-cannula-safety-wing',
      type: 'Peripheral IV cannula',
      title: 'Safety Winged IV Cannula with Passive Guard',
      brand: BRANDS.vascular,
      short:
        'Winged cannula whose needle guard closes over the bevel automatically as the stylet is withdrawn.',
      long: 'A winged cannula with a passive guard on the stylet: the shield closes over the bevel as the needle leaves the catheter, without a separate action. The hub carries an injection port, and the catheter is radiopaque polyurethane.',
      img: 'safety winged iv cannula medical device sterile',
      specs: {
        'Safety feature': 'Passive needle guard',
        Port: 'Injection port on hub',
        'Catheter material': 'Polyurethane, radiopaque',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Safety feature', 'Port'],
      axes: [
        ['gauge', ['22G', '20G', '18G']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [180_000, 640_000],
      stock: [20, 260],
      moq: 1,
      grams: 620,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('line-access', [
    {
      key: 'med-line-access-needlefree',
      type: 'Needle-free connector',
      title: 'Needle-Free Luer Access Connector, Neutral Displacement',
      brand: BRANDS.vascular,
      short:
        'Neutral-displacement needle-free connector with a flat, swabbable septum and a clear housing.',
      long: 'A needle-free connector that sits on a line or a hub and is accessed with a plain luer. The septum is flush with the housing so it can be swabbed flat, the internal path is straight and visible through the clear body, and displacement at disconnection is neutral.',
      img: 'needle free luer connector medical device',
      specs: {
        Displacement: 'Neutral',
        Septum: 'Flat swabbable septum',
        Housing: 'Transparent',
        'Priming volume': '0.09 ml',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Displacement', 'Septum'],
      axes: [['pack_count', ['Box of 50', 'Box of 100', 'Box of 200']]],
      price: [220_000, 780_000],
      stock: [20, 240],
      moq: 1,
      grams: 520,
      featured: true,
    },
    {
      key: 'med-line-access-extension',
      type: 'Extension line',
      title: 'Extension Line with Slide Clamp, 100 cm',
      brand: BRANDS.vascular,
      short: 'One metre extension line with a luer lock at both ends and a slide clamp.',
      long: 'A length of clear microbore tubing with a male luer lock at one end and a female at the other, plus a slide clamp. The priming volume is printed on the packaging so a line changeover can be planned.',
      img: 'medical extension line tubing luer lock',
      specs: {
        Length: '100 cm',
        Bore: 'Microbore',
        Clamp: 'Slide clamp',
        Connectors: 'Male and female luer lock',
      },
      facets: ['Bore'],
      axes: [
        ['length', ['50 cm', '100 cm', '150 cm']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [140_000, 480_000],
      stock: [22, 280],
      moq: 1,
      grams: 640,
    },
    {
      key: 'med-line-access-3way',
      type: 'Three-way stopcock',
      title: 'Three-Way Stopcock with Rotating Male Luer',
      brand: BRANDS.vascular,
      short:
        'Three-way stopcock with a rotating male luer lock and an arrow-marked handle.',
      long: 'A three-way stopcock whose male luer rotates independently of the body, so it can be tightened without twisting the line. The handle is arrow-marked to show the open port at a glance and clicks at each position.',
      img: 'three way stopcock medical luer device',
      specs: {
        Ports: 'Three',
        'Male luer': 'Rotating luer lock',
        Handle: 'Arrow-marked, detented',
        'Pressure rating': '4.5 bar',
      },
      facets: ['Ports'],
      axes: [['pack_count', ['Box of 50', 'Box of 100']]],
      price: [180_000, 380_000],
      stock: [25, 300],
      moq: 1,
      grams: 480,
      mrp: 0.1,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('line-conditioning', [
    {
      key: 'med-line-cond-lock',
      type: 'Locking solution syringe',
      title: 'Pre-Filled Line Lock Syringe, Sodium Chloride',
      brand: BRANDS.vascular,
      short:
        'Pre-filled sodium chloride syringe for locking a line between uses, with a luer lock tip.',
      long: 'A pre-filled syringe of sterile sodium chloride for locking a vascular access line between uses. Supplied capped, graduated and with a plunger that cannot be drawn back past its stop.',
      img: 'prefilled locking syringe medical sterile',
      specs: {
        Solution: '0.9% sodium chloride, sterile',
        Tip: 'Luer lock',
        Barrel: 'Graduated, non-refillable',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['3 ml', '5 ml', '10 ml']],
        ['pack_count', ['Box of 30', 'Box of 60']],
      ],
      price: [150_000, 460_000],
      stock: [25, 300],
      moq: 1,
      grams: 880,
      featured: true,
    },
    {
      key: 'med-line-cond-swabcap',
      type: 'Port protector',
      title: 'Port Protector Strip for Line Conditioning',
      brand: BRANDS.vascular,
      short: 'Peel strip of port protectors, each holding an alcohol-saturated pad.',
      long: 'A peel strip of port protectors for covering a connector between accesses. Each protector holds a pad saturated with 70% isopropyl alcohol and twists onto the septum; the strip dispenses one at a time from a wall rail or a trolley drawer.',
      img: 'port protector strip medical alcohol caps',
      specs: {
        Agent: '70% isopropyl alcohol pad',
        Presentation: 'Peel strip',
        Fitting: 'Twist-on, single use',
      },
      facets: ['Agent'],
      axes: [['pack_count', ['Box of 100', 'Box of 250']]],
      price: [160_000, 380_000],
      stock: [22, 260],
      moq: 1,
      grams: 340,
    },
    {
      key: 'med-line-cond-kit',
      type: 'Line care pack',
      title: 'Line Care Pack with Flush, Protector and Dressing',
      brand: BRANDS.medline,
      short:
        'Procedure pack holding a flush syringe, a port protector, a transparent dressing and swabs.',
      long: 'A procedure pack that puts a line dressing change into one pouch: a pre-filled flush syringe, a port protector, a transparent film dressing, a pair of alcohol swabs and a sterile field. Packed sterile and opened onto the trolley.',
      img: 'medical procedure pack sterile tray dressing',
      specs: {
        Contents: 'Flush syringe, port protector, film dressing, swabs, sterile field',
        Sterility: 'Sterile, single use',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Sterility'],
      axes: [['pack_count', ['Box of 20', 'Box of 40']]],
      price: [420_000, 860_000],
      stock: [10, 120],
      moq: 1,
      grams: 2_400,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('iv-administration-sets', [
    {
      key: 'med-admin-pump',
      type: 'Volumetric pump administration set',
      title: 'Volumetric Pump Administration Set with Anti-Free-Flow Clamp',
      brand: BRANDS.vascular,
      short:
        'Pump administration set with an anti-free-flow clamp, a vented spike and a luer lock end.',
      long: 'An administration set for a volumetric pump, with an anti-free-flow clamp that closes when the set is removed from the pump door. The spike is vented, the chamber is transparent, and the patient end is a luer lock with a protective cap.',
      img: 'iv administration set pump tubing medical',
      specs: {
        'Flow control': 'Anti-free-flow clamp',
        Spike: 'Vented',
        'Tubing length': '260 cm',
        Latex: 'Latex-free',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Flow control', 'Latex'],
      axes: [
        ['tubing_length', ['220 cm', '260 cm']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [280_000, 880_000],
      stock: [15, 180],
      moq: 1,
      grams: 1_300,
      featured: true,
    },
    {
      key: 'med-admin-blood',
      type: 'Blood administration set',
      title: 'Blood Administration Set with 200 Micron Filter',
      brand: BRANDS.vascular,
      short:
        'Blood administration set with a 200 micron filter chamber and a wide-bore drip.',
      long: 'A blood administration set whose chamber holds a 200 micron filter across the full width of the drip. The tubing is wide-bore clear PVC and the roller clamp has a coarse thread for slow, controlled adjustment.',
      img: 'blood transfusion administration set medical',
      specs: {
        Filter: '200 micron chamber filter',
        Bore: 'Wide bore',
        'Flow control': 'Roller clamp',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Filter', 'Bore'],
      axes: [['pack_count', ['Box of 25', 'Box of 50']]],
      price: [220_000, 520_000],
      stock: [15, 180],
      moq: 1,
      grams: 1_150,
    },
    {
      key: 'med-admin-extension-set',
      type: 'Administration extension set',
      title: 'Y-Site Administration Extension Set with Two Ports',
      brand: BRANDS.vascular,
      short: 'Extension set carrying two Y injection sites and a slide clamp between them.',
      long: 'An extension set with two Y injection sites along its length and a slide clamp between them, so one branch can be closed while the other runs. Male and female luer locks at the ends, clear tubing throughout.',
      img: 'y site extension set medical tubing ports',
      specs: {
        'Y sites': 'Two',
        Clamp: 'Slide clamp',
        Connectors: 'Male and female luer lock',
        Latex: 'Latex-free',
      },
      facets: ['Latex'],
      axes: [
        ['length', ['75 cm', '120 cm']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [190_000, 520_000],
      stock: [18, 220],
      moq: 1,
      grams: 900,
      mrp: 0.12,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('oral-dosing-syringe', [
    {
      key: 'med-oral-dosing-purple',
      type: 'Oral dosing syringe',
      title: 'Purple Oral Dosing Syringe with Bottle Adapter',
      brand: BRANDS.enteral,
      short:
        'Purple oral dosing syringe supplied with a press-in bottle adapter and a printed scale.',
      long: 'An oral dosing syringe in the purple that distinguishes an oral or enteral device from a parenteral one. The tip will not mate with a luer connector, and a press-in bottle adapter is supplied so the dose is drawn from the bottle rather than poured.',
      img: 'purple oral dosing syringe bottle adapter',
      specs: {
        'Barrel colour': 'Purple',
        Tip: 'Oral tip, not luer compatible',
        Adapter: 'Press-in bottle adapter supplied',
        Graduation: 'Printed scale',
      },
      facets: ['Tip', 'Barrel colour'],
      axes: [
        ['volume', ['1 ml', '3 ml', '5 ml', '10 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [60_000, 260_000],
      stock: [30, 380],
      moq: 1,
      grams: 460,
      featured: true,
    },
    {
      key: 'med-oral-dosing-lowdose',
      type: 'Oral dosing syringe',
      title: 'Low-Dose Oral Syringe with 0.1 ml Graduations',
      brand: BRANDS.enteral,
      short: 'One millilitre oral syringe graduated at a tenth of a millilitre.',
      long: 'A one millilitre oral syringe with graduations every tenth of a millilitre, for small measured doses. The scale is printed and the plunger carries a contrasting seal so the reading edge is easy to see.',
      img: 'small oral syringe graduated medical dosing',
      specs: {
        Volume: '1 ml',
        Graduation: '0.1 ml, printed',
        Tip: 'Oral tip, not luer compatible',
      },
      facets: ['Tip'],
      axes: [['pack_count', ['Box of 100', 'Box of 250']]],
      price: [70_000, 180_000],
      stock: [25, 300],
      moq: 1,
      grams: 320,
    },
    {
      key: 'med-oral-dosing-cup',
      type: 'Oral dosing cup',
      title: 'Graduated Oral Dosing Cup, 30 ml',
      brand: BRANDS.enteral,
      short: 'Thirty millilitre dosing cup with moulded graduations in ml and teaspoons.',
      long: 'A thirty millilitre polypropylene dosing cup with graduations moulded into the wall in millilitres and in teaspoons. Stackable and supplied in bulk bags.',
      img: 'medicine dosing cup graduated plastic',
      specs: {
        Volume: '30 ml',
        Graduation: 'Moulded, ml and teaspoons',
        Material: 'Polypropylene',
      },
      facets: ['Material'],
      axes: [['pack_count', ['Bag of 100', 'Bag of 500']]],
      price: [28_000, 110_000],
      stock: [40, 600],
      moq: 1,
      grams: 900,
      mrp: 0.15,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('oral-syiringe', [
    {
      key: 'med-oral-syr-sterile',
      type: 'Oral syringe',
      title: 'Sterile Oral Syringe with Tip Cap',
      brand: BRANDS.enteral,
      short: 'Individually wrapped sterile oral syringe with a tip cap, in a purple barrel.',
      long: 'An oral syringe supplied sterile and individually wrapped, with a tip cap for a dose drawn up in advance. The purple barrel and the non-luer tip are what keep an oral dose out of a parenteral line.',
      img: 'sterile oral syringe wrapped medical purple',
      specs: {
        Sterility: 'Sterile, individually wrapped',
        'Barrel colour': 'Purple',
        Tip: 'Oral tip with cap',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Sterility', 'Tip'],
      axes: [
        ['volume', ['3 ml', '5 ml', '10 ml', '20 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [75_000, 300_000],
      stock: [28, 340],
      moq: 1,
      grams: 500,
      featured: true,
    },
    {
      key: 'med-oral-syr-nonsterile',
      type: 'Oral syringe',
      title: 'Non-Sterile Oral Syringe, Bulk Bag',
      brand: BRANDS.enteral,
      short: 'Bulk-bagged non-sterile oral syringes for ward dispensing.',
      long: 'Oral syringes supplied non-sterile in bulk bags, for ward dispensing where the dose is drawn and given immediately. Purple barrel, printed scale, non-luer tip.',
      img: 'bulk oral syringes bag medical supplies',
      specs: {
        Sterility: 'Non-sterile',
        'Barrel colour': 'Purple',
        Tip: 'Oral tip, not luer compatible',
      },
      facets: ['Sterility'],
      axes: [
        ['volume', ['5 ml', '10 ml', '20 ml']],
        ['pack_count', ['Bag of 100', 'Bag of 500']],
      ],
      price: [45_000, 260_000],
      stock: [35, 420],
      moq: 1,
      grams: 900,
    },
    {
      key: 'med-oral-syr-adapter',
      type: 'Oral syringe bottle adapter',
      title: 'Press-In Bottle Adapter for Oral Syringes',
      brand: BRANDS.enteral,
      short: 'Press-in bottle adapter that seats in a bottle neck and takes an oral syringe tip.',
      long: 'A press-in adapter for a medicine bottle neck. It stays in the bottle between doses and accepts an oral syringe tip, so the dose is drawn through the adapter rather than poured into a cup.',
      img: 'bottle adapter oral syringe medical plastic',
      specs: {
        Fitting: 'Press-in, bottle neck',
        Material: 'LDPE',
        Compatibility: 'Oral syringe tips',
      },
      facets: ['Compatibility'],
      axes: [
        ['neck_size', ['18 mm', '20 mm', '24 mm', '28 mm']],
        ['pack_count', ['Bag of 100', 'Bag of 500']],
      ],
      price: [22_000, 120_000],
      stock: [40, 600],
      moq: 1,
      grams: 400,
      mrp: 0.16,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('prefilled-heparin-syringe', [
    {
      key: 'med-heparin-lock',
      type: 'Pre-filled heparin lock syringe',
      title: 'Pre-Filled Heparin Lock Flush Syringe',
      brand: BRANDS.vascular,
      short:
        'Pre-filled heparin lock flush syringe with a luer lock tip and a tamper-evident cap.',
      long: 'A pre-filled syringe of heparin lock flush solution for maintaining a vascular access device. The luer lock carries a tamper-evident cap, the barrel is graduated, and the plunger rod is scored so the syringe cannot be refilled.',
      img: 'prefilled heparin syringe medical sterile',
      specs: {
        Solution: 'Heparin lock flush solution',
        Tip: 'Luer lock with tamper-evident cap',
        Barrel: 'Graduated, non-refillable',
        Sterility: 'Sterile fluid path',
      },
      facets: ['Solution', 'Tip'],
      axes: [
        ['volume', ['3 ml', '5 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [320_000, 820_000],
      stock: [12, 140],
      moq: 1,
      grams: 760,
      featured: true,
    },
    {
      key: 'med-heparin-tray',
      type: 'Pre-filled heparin lock syringe',
      title: 'Heparin Lock Flush Syringe, Tray Pack',
      brand: BRANDS.vascular,
      short: 'Tray-packed heparin lock flush syringes for a ward store.',
      long: 'The same heparin lock flush syringe supplied in trays rather than individually boxed, for a ward store that restocks a trolley daily. Each syringe is capped, graduated and non-refillable.',
      img: 'heparin syringes tray pack medical supply',
      specs: {
        Solution: 'Heparin lock flush solution',
        Presentation: 'Tray-packed',
        Tip: 'Luer lock',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['3 ml', '5 ml']],
        ['pack_count', ['Tray of 24', 'Case of 96']],
      ],
      price: [560_000, 2_100_000],
      stock: [6, 60],
      moq: 1,
      grams: 3_400,
      sold: { content: [24, 'piece'], label: 'Tray of 24' },
      multipack: 24,
    },
    {
      key: 'med-heparin-swabcap',
      type: 'Pre-filled heparin lock syringe',
      title: 'Heparin Lock Syringe with Disinfecting Cap',
      brand: BRANDS.vascular,
      short: 'Heparin lock flush syringe supplied with a disinfecting cap on the luer.',
      long: 'A heparin lock flush syringe whose luer carries a disinfecting cap, so the connector is covered from the moment the pouch is opened until the flush is given.',
      img: 'heparin lock syringe disinfecting cap medical',
      specs: {
        Solution: 'Heparin lock flush solution',
        Cap: 'Disinfecting swab cap',
        Tip: 'Luer lock',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['3 ml', '5 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [380_000, 920_000],
      stock: [10, 120],
      moq: 1,
      grams: 800,
      mrp: 0.1,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('ryles-tube', [
    {
      key: 'med-ryles-pvc',
      type: 'Ryles tube',
      title: 'Ryles Nasogastric Tube with Radiopaque Line',
      brand: BRANDS.enteral,
      short:
        'PVC Ryles tube with four lateral eyes, a radiopaque line and centimetre markings.',
      long: 'A nasogastric Ryles tube in medical-grade PVC, with a rounded closed tip, four lateral eyes and a radiopaque line the full length. Centimetre markings run from the tip so insertion depth can be read at the nostril. Supplied sterile in a peel pouch.',
      img: 'ryles nasogastric tube medical sterile',
      specs: {
        Material: 'Medical-grade PVC',
        Eyes: 'Four lateral eyes',
        Radiopacity: 'Radiopaque line, full length',
        Marking: 'Centimetre markings from tip',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Material', 'Radiopacity'],
      axes: [
        ['french_size', ['Fr 10', 'Fr 12', 'Fr 14', 'Fr 16', 'Fr 18']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [160_000, 620_000],
      stock: [22, 280],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'med-ryles-silicone',
      type: 'Ryles tube',
      title: 'Silicone Ryles Tube for Extended Placement',
      brand: BRANDS.enteral,
      short: 'Silicone nasogastric tube with a soft wall and an ENFit connector.',
      long: 'A silicone nasogastric tube for placements that last longer than a PVC tube is intended for. The wall is softer, the tube does not stiffen with use, and the proximal end is an ENFit connector with a closure cap.',
      img: 'silicone nasogastric feeding tube medical',
      specs: {
        Material: 'Silicone',
        Connector: 'ENFit, ISO 80369-3',
        Cap: 'Integral closure cap',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Material', 'Connector'],
      axes: [
        ['french_size', ['Fr 12', 'Fr 14', 'Fr 16']],
        ['length', ['90 cm', '110 cm']],
        ['pack_count', ['Box of 10', 'Box of 25']],
      ],
      price: [420_000, 1_180_000],
      stock: [8, 100],
      moq: 1,
      grams: 620,
    },
    {
      key: 'med-ryles-levin',
      type: 'Levin tube',
      title: 'Levin Nasogastric Tube, Single Lumen',
      brand: BRANDS.enteral,
      short: 'Single-lumen Levin tube with a funnel end and centimetre graduations.',
      long: 'A single-lumen Levin tube with a funnel-shaped proximal end and centimetre graduations along the shaft. The tip is closed and rounded with lateral eyes, and the shaft carries a radiopaque stripe.',
      img: 'levin nasogastric tube medical single lumen',
      specs: {
        Lumen: 'Single',
        'Proximal end': 'Funnel',
        Radiopacity: 'Radiopaque stripe',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Lumen'],
      axes: [
        ['french_size', ['Fr 12', 'Fr 14', 'Fr 16', 'Fr 18']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [140_000, 540_000],
      stock: [20, 260],
      moq: 1,
      grams: 860,
      mrp: 0.12,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('safety-needle', [
    {
      key: 'med-safety-needle-hinged',
      type: 'Safety hypodermic needle',
      title: 'Hypodermic Needle with Hinged Safety Shield',
      brand: BRANDS.medline,
      short:
        'Sterile hypodermic needle with a hinged shield that locks over the bevel one-handed.',
      long: 'A sterile hypodermic needle whose hub carries a hinged shield. The shield folds forward against a flat surface or a thumb and clicks over the bevel, and it cannot be reopened. The cannula is siliconised and tri-bevelled.',
      img: 'safety hypodermic needle hinged shield medical',
      specs: {
        'Safety feature': 'Hinged shield, one-handed activation',
        Bevel: 'Tri-bevel, siliconised',
        Hub: 'Colour-coded luer lock',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Safety feature', 'Hub'],
      axes: [
        ['needle_gauge', ['18G', '21G', '23G', '25G']],
        ['needle_length', ['16 mm', '25 mm', '38 mm']],
        ['pack_count', ['Box of 100']],
      ],
      price: [62_000, 195_000],
      stock: [35, 460],
      moq: 1,
      grams: 380,
      featured: true,
    },
    {
      key: 'med-safety-needle-retract',
      type: 'Safety hypodermic needle',
      title: 'Retracting Safety Needle with Spring Mechanism',
      brand: BRANDS.medline,
      short: 'Safety needle whose cannula retracts into the hub when the button is pressed.',
      long: 'A safety needle with a sprung retraction mechanism in the hub: pressing the button draws the cannula fully inside, and it cannot be pushed back out. Supplied sterile with a luer lock fitting.',
      img: 'retractable safety needle medical device',
      specs: {
        'Safety feature': 'Spring retraction into hub',
        Fitting: 'Luer lock',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Safety feature'],
      axes: [
        ['needle_gauge', ['21G', '23G', '25G']],
        ['needle_length', ['25 mm', '38 mm']],
        ['pack_count', ['Box of 100']],
      ],
      price: [98_000, 240_000],
      stock: [25, 320],
      moq: 1,
      grams: 420,
    },
    {
      key: 'med-safety-needle-blunt',
      type: 'Blunt fill needle',
      title: 'Blunt Fill Needle with Filter',
      brand: BRANDS.medline,
      short: 'Blunt fill needle with a 5 micron filter, for drawing from a vial or an ampoule.',
      long: 'A blunt-tipped fill needle with a 5 micron filter in the hub, for drawing a solution into a syringe. The blunt tip is not intended to pierce skin and the hub is a distinct colour so it is not confused with a sharp on a tray.',
      img: 'blunt fill needle filter medical vial',
      specs: {
        Tip: 'Blunt fill',
        Filter: '5 micron',
        Hub: 'Distinct colour coding',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Tip', 'Filter'],
      axes: [
        ['needle_gauge', ['18G', '19G']],
        ['pack_count', ['Box of 100']],
      ],
      price: [72_000, 165_000],
      stock: [28, 340],
      moq: 1,
      grams: 340,
      mrp: 0.11,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('sodium-citrate-prefilled-syringe', [
    {
      key: 'med-citrate-4pc',
      type: 'Pre-filled sodium citrate syringe',
      title: 'Pre-Filled Sodium Citrate Lock Syringe, 4%',
      brand: BRANDS.vascular,
      short:
        'Pre-filled 4% sodium citrate lock syringe with a luer lock tip and a graduated barrel.',
      long: 'A pre-filled syringe of 4% sodium citrate solution for locking a catheter lumen. The barrel is graduated, the luer lock carries a tamper-evident cap, and the plunger is scored so the syringe cannot be refilled.',
      img: 'prefilled citrate lock syringe medical',
      specs: {
        Solution: '4% sodium citrate',
        Tip: 'Luer lock with tamper-evident cap',
        Barrel: 'Graduated, non-refillable',
        Sterility: 'Sterile fluid path',
      },
      facets: ['Solution', 'Tip'],
      axes: [
        ['volume', ['3 ml', '5 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [380_000, 980_000],
      stock: [10, 120],
      moq: 1,
      grams: 780,
      featured: true,
    },
    {
      key: 'med-citrate-46pc',
      type: 'Pre-filled sodium citrate syringe',
      title: 'Pre-Filled Sodium Citrate Lock Syringe, 46.7%',
      brand: BRANDS.vascular,
      short: 'Pre-filled high-concentration sodium citrate lock syringe with a coloured plunger.',
      long: 'A pre-filled syringe of 46.7% sodium citrate solution with a distinctly coloured plunger rod, so it is not confused with the 4% presentation on the same trolley. Graduated barrel, luer lock, tamper-evident cap.',
      img: 'sodium citrate syringe medical prefilled coloured',
      specs: {
        Solution: '46.7% sodium citrate',
        'Plunger colour': 'Distinct from 4% presentation',
        Tip: 'Luer lock with tamper-evident cap',
      },
      facets: ['Solution'],
      axes: [
        ['volume', ['3 ml', '5 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [460_000, 1_180_000],
      stock: [8, 100],
      moq: 1,
      grams: 800,
    },
    {
      key: 'med-citrate-tray',
      type: 'Pre-filled sodium citrate syringe',
      title: 'Sodium Citrate Lock Syringe, Dialysis Tray Pack',
      brand: BRANDS.vascular,
      short: 'Tray pack of sodium citrate lock syringes for a dialysis unit store.',
      long: 'The same sodium citrate lock syringe supplied tray-packed for a dialysis unit store. Each syringe is individually capped and graduated; the tray holds twenty-four.',
      img: 'dialysis tray syringes medical pack',
      specs: {
        Solution: '4% sodium citrate',
        Presentation: 'Tray-packed, 24 per tray',
        Tip: 'Luer lock',
      },
      facets: ['Solution'],
      axes: [['pack_count', ['Tray of 24', 'Case of 96']]],
      price: [820_000, 3_200_000],
      stock: [5, 50],
      moq: 1,
      grams: 3_600,
      sold: { content: [24, 'piece'], label: 'Tray of 24' },
      multipack: 24,
      mrp: 0.09,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('sterile-water', [
    {
      key: 'med-sterile-water-amp',
      type: 'Sterile water ampoule',
      title: 'Sterile Water for Irrigation, Snap-Top Ampoule',
      brand: BRANDS.medline,
      short: 'Snap-top plastic ampoule of sterile water for irrigation, single use.',
      long: 'A blow-fill-seal plastic ampoule of sterile water for irrigation. The top twists off without a blade, the ampoule is single use, and the strip tears one ampoule at a time. Latex-free and free of preservatives.',
      img: 'sterile water ampoule medical plastic strip',
      specs: {
        Contents: 'Sterile water for irrigation',
        Container: 'Blow-fill-seal plastic ampoule',
        Opening: 'Twist-off top, no blade',
        Preservative: 'Preservative-free',
        Latex: 'Latex-free',
      },
      facets: ['Container', 'Preservative', 'Latex'],
      axes: [
        ['volume', ['5 ml', '10 ml', '20 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [72_000, 320_000],
      stock: [30, 400],
      moq: 1,
      grams: 1_400,
      featured: true,
    },
    {
      key: 'med-sterile-water-bottle',
      type: 'Sterile water bottle',
      title: 'Sterile Water for Irrigation, 500 ml Pour Bottle',
      brand: BRANDS.medline,
      short: 'Five hundred millilitre pour bottle of sterile water with a tamper-evident closure.',
      long: 'A pour bottle of sterile water for irrigation, with a tamper-evident closure and a moulded pouring lip. The bottle is graduated down the side so a measured volume can be taken.',
      img: 'sterile water irrigation bottle medical 500ml',
      specs: {
        Contents: 'Sterile water for irrigation',
        Container: 'Graduated pour bottle',
        Closure: 'Tamper-evident',
        Preservative: 'Preservative-free',
      },
      facets: ['Container', 'Preservative'],
      axes: [
        ['volume', ['250 ml', '500 ml', '1 L']],
        ['pack_count', ['Case of 12', 'Case of 24']],
      ],
      price: [180_000, 720_000],
      stock: [12, 160],
      moq: 1,
      grams: 6_800,
      sold: { content: [500, 'ml'], per: [1, 'L'], label: 'Case of 12' },
      multipack: 12,
    },
    {
      key: 'med-sterile-water-vial',
      type: 'Sterile water vial',
      title: 'Sterile Water for Injection, 10 ml Vial',
      brand: BRANDS.medline,
      short: 'Ten millilitre rubber-stoppered vial of sterile water for injection.',
      long: 'A ten millilitre glass vial of sterile water for injection with a rubber stopper and an aluminium seal. Supplied in cartons with a tear-off flip cap on each vial.',
      img: 'sterile water injection vial medical glass',
      specs: {
        Contents: 'Sterile water for injection',
        Container: 'Glass vial, rubber stopper',
        Closure: 'Aluminium seal with flip cap',
        Preservative: 'Preservative-free',
      },
      facets: ['Container', 'Preservative'],
      axes: [
        ['volume', ['5 ml', '10 ml', '20 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [96_000, 360_000],
      stock: [20, 260],
      moq: 1,
      grams: 1_800,
      mrp: 0.1,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('sterile-water-with-10-glycerine', [
    {
      key: 'med-glycerine-amp',
      type: 'Sterile water with glycerine ampoule',
      title: 'Sterile Water with 10% Glycerine, Snap-Top Ampoule',
      brand: BRANDS.medline,
      short:
        'Snap-top ampoule of sterile water with 10% glycerine, single use and preservative-free.',
      long: 'A blow-fill-seal ampoule of sterile water with ten per cent glycerine. The twist-off top opens without a blade and the ampoule is discarded after one use. Supplied on a tear strip.',
      img: 'sterile water glycerine ampoule medical',
      specs: {
        Contents: 'Sterile water with 10% glycerine',
        Container: 'Blow-fill-seal plastic ampoule',
        Preservative: 'Preservative-free',
        Latex: 'Latex-free',
      },
      facets: ['Container', 'Preservative'],
      axes: [
        ['volume', ['5 ml', '10 ml']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [88_000, 300_000],
      stock: [25, 320],
      moq: 1,
      grams: 1_300,
      featured: true,
    },
    {
      key: 'med-glycerine-bottle',
      type: 'Sterile water with glycerine bottle',
      title: 'Sterile Water with 10% Glycerine, 500 ml Bottle',
      brand: BRANDS.medline,
      short: 'Graduated 500 ml bottle of sterile water with 10% glycerine.',
      long: 'A graduated pour bottle of sterile water with ten per cent glycerine, with a tamper-evident closure. Supplied in cases for a department store rather than singly.',
      img: 'glycerine solution bottle medical sterile',
      specs: {
        Contents: 'Sterile water with 10% glycerine',
        Container: 'Graduated pour bottle',
        Closure: 'Tamper-evident',
      },
      facets: ['Container'],
      axes: [
        ['volume', ['250 ml', '500 ml']],
        ['pack_count', ['Case of 12', 'Case of 24']],
      ],
      price: [220_000, 780_000],
      stock: [10, 140],
      moq: 1,
      grams: 6_900,
      sold: { content: [500, 'ml'], per: [1, 'L'], label: 'Case of 12' },
      multipack: 12,
    },
    {
      key: 'med-glycerine-sachet',
      type: 'Sterile water with glycerine sachet',
      title: 'Sterile Water with 10% Glycerine, Single-Dose Sachet',
      brand: BRANDS.medline,
      short: 'Single-dose foil sachet of sterile water with 10% glycerine.',
      long: 'A single-dose foil sachet, for a trolley or a procedure pack where an ampoule would be bulky. Tear-notched at one corner and discarded after use.',
      img: 'single dose sachet medical sterile solution',
      specs: {
        Contents: 'Sterile water with 10% glycerine',
        Container: 'Foil sachet, tear-notched',
        Reuse: 'Single use',
      },
      facets: ['Container'],
      axes: [
        ['volume', ['5 ml', '10 ml']],
        ['pack_count', ['Box of 100', 'Box of 250']],
      ],
      price: [96_000, 340_000],
      stock: [20, 280],
      moq: 1,
      grams: 1_100,
      mrp: 0.12,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('suction-catheter', [
    {
      key: 'med-suction-thumb',
      type: 'Suction catheter',
      title: 'Suction Catheter with Thumb Control Vent',
      brand: BRANDS.medline,
      short:
        'Sterile suction catheter with a thumb control vent, a rounded tip and two lateral eyes.',
      long: 'A sterile suction catheter with a thumb control vent on the connector, so suction is applied by closing the vent rather than by switching the source. The tip is rounded and carries two lateral eyes, and the connector is colour-coded to the French size.',
      img: 'suction catheter thumb control medical sterile',
      specs: {
        'Control type': 'Thumb control vent',
        Tip: 'Rounded, two lateral eyes',
        'Colour coding': 'Connector colour-coded to French size',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Control type', 'Colour coding'],
      axes: [
        ['french_size', ['Fr 8', 'Fr 10', 'Fr 12', 'Fr 14', 'Fr 16']],
        ['pack_count', ['Box of 50', 'Box of 100']],
      ],
      price: [120_000, 480_000],
      stock: [25, 320],
      moq: 1,
      grams: 850,
      featured: true,
    },
    {
      key: 'med-suction-closed',
      type: 'Closed suction catheter',
      title: 'Closed Suction Catheter with Irrigation Port',
      brand: BRANDS.medline,
      short:
        'Closed suction catheter in a protective sleeve, with an irrigation port and a lock.',
      long: 'A closed suction catheter enclosed in a transparent sleeve, with an irrigation port for clearing the lumen and a rotating lock that holds the catheter withdrawn. Depth markings run along the catheter.',
      img: 'closed suction catheter system medical sleeve',
      specs: {
        System: 'Closed, transparent sleeve',
        Port: 'Irrigation port',
        Lock: 'Rotating withdrawal lock',
        Marking: 'Depth markings',
      },
      facets: ['System'],
      axes: [
        ['french_size', ['Fr 10', 'Fr 12', 'Fr 14']],
        ['length', ['30 cm', '54 cm']],
        ['pack_count', ['Box of 10', 'Box of 20']],
      ],
      price: [620_000, 1_850_000],
      stock: [8, 90],
      moq: 1,
      grams: 1_200,
    },
    {
      key: 'med-suction-yankauer',
      type: 'Yankauer suction handle',
      title: 'Yankauer Suction Handle with Bulbous Tip',
      brand: BRANDS.medline,
      short: 'Sterile Yankauer suction handle with a bulbous tip and a thumb vent.',
      long: 'A rigid Yankauer suction handle with a bulbous tip and side eyes, and a thumb vent along the shaft. Supplied sterile, with or without a length of connecting tubing.',
      img: 'yankauer suction handle medical sterile',
      specs: {
        Tip: 'Bulbous with side eyes',
        Vent: 'Thumb vent',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Tip'],
      axes: [
        ['tubing', ['Handle only', 'With 180 cm tubing', 'With 300 cm tubing']],
        ['pack_count', ['Box of 20', 'Box of 50']],
      ],
      price: [180_000, 720_000],
      stock: [12, 160],
      moq: 1,
      grams: 1_400,
      mrp: 0.13,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('surgical-gloves', [
    {
      key: 'med-gloves-latex-sterile',
      type: 'Sterile surgical glove',
      title: 'Sterile Latex Surgical Glove, Powder-Free',
      brand: BRANDS.safety,
      short:
        'Powder-free sterile latex surgical glove with a beaded cuff and a textured fingertip.',
      long: 'A powder-free sterile latex surgical glove, anatomically shaped with a beaded cuff and a micro-textured fingertip. Supplied in pairs, folded into an inner wrap inside a sealed outer.',
      img: 'sterile surgical gloves box medical',
      specs: {
        Material: 'Natural rubber latex',
        Powder: 'Powder-free',
        Cuff: 'Beaded',
        Finish: 'Micro-textured fingertips',
        Sterility: 'Sterile, single use',
        'Sterilisation method': 'Gamma irradiation',
      },
      facets: ['Material', 'Powder', 'Sterility'],
      axes: [
        ['size', ['6.0', '6.5', '7.0', '7.5', '8.0', '8.5']],
        ['pack_count', ['Box of 50 pairs']],
      ],
      price: [240_000, 380_000],
      stock: [20, 280],
      moq: 1,
      grams: 1_900,
      sold: { content: [50, 'pair'], label: 'Box of 50 pairs' },
      multipack: 50,
      featured: true,
    },
    {
      key: 'med-gloves-nitrile-sterile',
      type: 'Sterile surgical glove',
      title: 'Sterile Nitrile Surgical Glove, Latex-Free',
      brand: BRANDS.safety,
      short: 'Latex-free sterile nitrile surgical glove with a textured surface and a rolled cuff.',
      long: 'A sterile nitrile surgical glove for a theatre that works latex-free. The wall is thinner than a general-purpose examination glove at the same size, the surface is textured across the palm, and the cuff is rolled.',
      img: 'nitrile surgical gloves sterile medical blue',
      specs: {
        Material: 'Nitrile',
        Latex: 'Latex-free',
        Powder: 'Powder-free',
        Finish: 'Textured palm',
        Sterility: 'Sterile, single use',
      },
      facets: ['Material', 'Latex', 'Sterility'],
      axes: [
        ['size', ['6.5', '7.0', '7.5', '8.0', '8.5']],
        ['pack_count', ['Box of 50 pairs']],
      ],
      price: [300_000, 460_000],
      stock: [18, 240],
      moq: 1,
      grams: 1_850,
      sold: { content: [50, 'pair'], label: 'Box of 50 pairs' },
      multipack: 50,
    },
    {
      key: 'med-gloves-exam-nitrile',
      type: 'Examination glove',
      title: 'Non-Sterile Nitrile Examination Glove',
      brand: BRANDS.safety,
      short: 'Ambidextrous non-sterile nitrile examination glove, powder-free, in a dispenser box.',
      long: 'An ambidextrous nitrile examination glove supplied non-sterile in a dispenser box of one hundred. Powder-free, textured at the fingertips, with a beaded cuff.',
      img: 'nitrile examination gloves dispenser box',
      specs: {
        Material: 'Nitrile',
        Latex: 'Latex-free',
        Powder: 'Powder-free',
        Sterility: 'Non-sterile',
        Handing: 'Ambidextrous',
      },
      facets: ['Material', 'Latex', 'Sterility'],
      axes: [
        ['size', ['Small', 'Medium', 'Large', 'Extra large']],
        ['colour', ['Blue', 'Black']],
      ],
      price: [46_000, 92_000],
      stock: [40, 700],
      moq: 1,
      grams: 1_100,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
      mrp: 0.15,
    },
  ]),

  // -----------------------------------------------------------------------
  shelf('syringes', [
    {
      key: 'med-syringe-3part',
      type: 'Hypodermic syringe',
      title: 'Three-Part Hypodermic Syringe with Needle',
      brand: BRANDS.medline,
      short:
        'Sterile three-part hypodermic syringe with a rubber plunger seal and a needle supplied.',
      long: 'A three-part hypodermic syringe: barrel, plunger and a rubber seal, which gives a smoother stroke than a two-part design. Graduated on both sides of the barrel and supplied sterile with a needle in place and a protective sheath over it.',
      img: 'hypodermic syringe with needle medical sterile',
      specs: {
        Construction: 'Three-part with rubber plunger seal',
        Graduation: 'Both sides of barrel',
        Sterility: 'Sterile, single use',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Construction', 'Sterility'],
      axes: [
        ['volume', ['1 ml', '2 ml', '5 ml', '10 ml']],
        ['needle_gauge', ['21G', '23G', '25G']],
      ],
      price: [38_000, 120_000],
      stock: [50, 700],
      moq: 1,
      grams: 900,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
      featured: true,
    },
    {
      key: 'med-syringe-luerlock',
      type: 'Hypodermic syringe',
      title: 'Luer Lock Hypodermic Syringe, Needle Not Supplied',
      brand: BRANDS.medline,
      short:
        'Sterile luer lock syringe supplied without a needle, for use with a safety needle of choice.',
      long: 'A sterile luer lock syringe supplied on its own, for a department that fits its own choice of safety needle. The lock holds a needle through a firm injection, and the barrel is graduated on both sides.',
      img: 'luer lock syringe without needle medical',
      specs: {
        Tip: 'Luer lock',
        'Needle supplied': 'No',
        Sterility: 'Sterile, single use',
        'Sterilisation method': 'Ethylene oxide',
      },
      facets: ['Tip', 'Sterility'],
      axes: [
        ['volume', ['1 ml', '3 ml', '5 ml', '10 ml', '20 ml']],
        ['pack_count', ['Box of 100']],
      ],
      price: [34_000, 145_000],
      stock: [45, 650],
      moq: 1,
      grams: 950,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
    },
    {
      key: 'med-syringe-catheter-tip',
      type: 'Catheter tip syringe',
      title: 'Catheter Tip Syringe, 50 ml',
      brand: BRANDS.medline,
      short: 'Fifty millilitre catheter tip syringe with a wide flange and a graduated barrel.',
      long: 'A fifty millilitre syringe with a catheter tip, for irrigation and drainage. The flange is wide enough for one-handed delivery and the barrel is graduated in millilitres. Supplied sterile in a peel pouch.',
      img: 'catheter tip syringe 50ml medical irrigation',
      specs: {
        Tip: 'Catheter tip',
        Volume: '50 ml',
        Flange: 'Wide finger flange',
        Sterility: 'Sterile, single use',
      },
      facets: ['Tip', 'Sterility'],
      axes: [
        ['volume', ['50 ml', '60 ml']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [140_000, 420_000],
      stock: [20, 240],
      moq: 1,
      grams: 1_200,
      mrp: 0.12,
    },
  ]),
];
