/**
 * Laboratory & Scientific, Industrial Supplies, Tools & Hardware.
 *
 * Eighteen shelves, three products each. Every axis key below is one the
 * sub-category's own variant template offers - `registry.ts` is the list, and
 * `assertRegistryIsSound` refuses anything that is not on it, so an axis
 * renamed in a template is a failing test rather than a product whose selector
 * the storefront cannot draw.
 *
 * Prices are in paise and openly synthetic. They are banded so that the cheap
 * end of a shelf is plausibly cheap and the dear end plausibly dear - a pack
 * of washers and a pallet truck are four orders of magnitude apart, and a
 * catalogue that prices them within one of each other is a catalogue whose
 * price filter does nothing.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const TECHNICAL_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // LABORATORY & SCIENTIFIC
  // =======================================================================
  shelf('lab-instruments', [
    {
      key: 'lab-inst-balance',
      type: 'Precision analytical balance',
      title: 'Precision Analytical Balance with Draught Shield',
      brand: BRANDS.lab,
      short:
        'Analytical balance with a glass draught shield, internal calibration and an RS-232 output.',
      long: 'A bench analytical balance with a four-sided glass draught shield and a motorised internal calibration weight. The pan is stainless steel on a cast base, the display is backlit, and an RS-232 port sends each stable reading to a printer or a logger.',
      img: 'analytical laboratory balance precision scale',
      specs: {
        Pan: 'Stainless steel, 90 mm',
        Calibration: 'Motorised internal weight',
        Interface: 'RS-232',
        Display: 'Backlit LCD',
        Housing: 'Cast base with glass draught shield',
      },
      facets: ['Calibration', 'Interface'],
      axes: [
        ['capacity', ['120 g', '220 g', '320 g']],
        ['accuracy', ['0.1 mg', '1 mg']],
        ['plug_type', ['Type D (IN)', 'Type G (UK)', 'Type C (EU)']],
      ],
      price: [8_500_00, 32_000_00],
      stock: [2, 24],
      moq: 1,
      grams: 7_200,
      leadDays: 5,
      featured: true,
    },
    {
      key: 'lab-inst-centrifuge',
      type: 'Benchtop centrifuge',
      title: 'Benchtop Centrifuge with Swing-Out Rotor',
      brand: BRANDS.lab,
      short:
        'Benchtop centrifuge with a swing-out rotor, a lid interlock and a digital speed and timer display.',
      long: 'A benchtop centrifuge with a swing-out rotor and an imbalance cut-out. The lid locks while the rotor is turning and releases when it has stopped, the speed and time are set on a digital panel, and the last ten programmes are stored.',
      img: 'benchtop laboratory centrifuge machine',
      specs: {
        Rotor: 'Swing-out, interchangeable',
        Safety: 'Lid interlock and imbalance cut-out',
        Control: 'Digital speed and timer, 10 stored programmes',
        Housing: 'Powder-coated steel',
      },
      facets: ['Rotor', 'Control'],
      axes: [
        ['measurement_range', ['4,000 rpm', '6,000 rpm']],
        ['sample_capacity', ['8', '12', '24']],
        ['voltage', ['230 V', '110 V']],
      ],
      price: [24_000_00, 96_000_00],
      stock: [1, 14],
      moq: 1,
      grams: 18_500,
      leadDays: 10,
    },
    {
      key: 'lab-inst-hotplate',
      type: 'Magnetic stirrer hotplate',
      title: 'Magnetic Stirrer Hotplate with Ceramic Top',
      brand: BRANDS.lab,
      short:
        'Combined hotplate and magnetic stirrer with a chemical-resistant ceramic top and a probe socket.',
      long: 'A combined hotplate and magnetic stirrer on a chemical-resistant ceramic top. Heat and stirring are set independently on two dials with digital readouts, and a socket takes a temperature probe so the plate holds a measured temperature rather than a dial position.',
      img: 'magnetic stirrer hotplate laboratory equipment',
      specs: {
        Top: 'Chemical-resistant ceramic',
        Control: 'Independent heat and stir, digital readout',
        Probe: 'External temperature probe socket',
        'Plate size': '180 x 180 mm',
      },
      facets: ['Top', 'Probe'],
      axes: [
        ['measurement_range', ['340 C', '550 C']],
        ['capacity', ['5 L', '10 L', '20 L']],
        ['voltage', ['230 V', '110 V']],
      ],
      price: [9_800_00, 34_000_00],
      stock: [3, 30],
      moq: 1,
      grams: 4_600,
      mrp: 0.15,
    },
  ]),

  shelf('lab-glassware-plasticware', [
    {
      key: 'lab-glass-cylinder',
      type: 'Measuring cylinder',
      title: 'Borosilicate Glass Measuring Cylinder, Class A',
      brand: BRANDS.reagent,
      short:
        'Class A borosilicate measuring cylinder with a hexagonal base and printed white graduations.',
      long: 'A Class A measuring cylinder in borosilicate 3.3 glass, with a hexagonal base that resists tipping and a spout formed into the rim. The graduations are printed in white enamel and fired on, so they survive repeated autoclaving and solvent cleaning.',
      img: 'borosilicate glass measuring cylinder laboratory',
      specs: {
        Material: 'Borosilicate 3.3',
        Class: 'Class A',
        Base: 'Hexagonal',
        Graduations: 'Fired white enamel',
        Autoclavable: 'Yes, 121 C',
      },
      facets: ['Material', 'Class', 'Autoclavable'],
      axes: [
        ['capacity', ['10 ml', '25 ml', '50 ml', '100 ml', '250 ml', '500 ml', '1000 ml']],
        ['pack_count', ['Single', 'Pack of 6']],
      ],
      price: [32_000, 480_000],
      stock: [15, 220],
      moq: 1,
      grams: 480,
      featured: true,
    },
    {
      key: 'lab-glass-beaker',
      type: 'Laboratory beaker',
      title: 'Low-Form Borosilicate Beaker with Spout',
      brand: BRANDS.reagent,
      short:
        'Low-form borosilicate beaker with a moulded spout and a printed graduation scale.',
      long: 'A low-form beaker in borosilicate 3.3 with a heavy rolled rim and a moulded spout. The graduation scale is approximate, as a beaker scale is, and there is a matt writing patch on the side for a marker.',
      img: 'laboratory glass beaker borosilicate',
      specs: {
        Material: 'Borosilicate 3.3',
        Form: 'Low form, spouted',
        Rim: 'Heavy rolled',
        Marking: 'Matt writing patch',
        Autoclavable: 'Yes, 121 C',
      },
      facets: ['Material', 'Autoclavable'],
      axes: [
        ['capacity', ['50 ml', '100 ml', '250 ml', '400 ml', '600 ml', '1000 ml']],
        ['pack_count', ['Single', 'Pack of 10']],
      ],
      price: [18_000, 320_000],
      stock: [20, 300],
      moq: 1,
      grams: 260,
    },
    {
      key: 'lab-plastic-bottle',
      type: 'Reagent bottle',
      title: 'HDPE Narrow-Neck Reagent Bottle with Tamper Ring',
      brand: BRANDS.reagent,
      short:
        'Narrow-neck HDPE reagent bottle with a tamper-evident ring and a leak-tight liner.',
      long: 'A narrow-neck reagent bottle in natural HDPE, with a screw cap carrying a tamper ring and a wadded liner. The neck is moulded to a standard thread so caps are interchangeable across the range, and the shoulder carries a blank label panel.',
      img: 'hdpe laboratory reagent bottle plastic',
      specs: {
        Material: 'HDPE, natural',
        Neck: 'Narrow neck, standard thread',
        Closure: 'Screw cap with tamper ring and liner',
        Autoclavable: 'No - HDPE',
      },
      facets: ['Material', 'Autoclavable'],
      axes: [
        ['capacity', ['125 ml', '250 ml', '500 ml', '1000 ml']],
        ['colour', ['Natural', 'Amber']],
        ['pack_count', ['Pack of 10', 'Case of 50']],
      ],
      price: [68_000, 480_000],
      stock: [18, 260],
      moq: 1,
      grams: 900,
      mrp: 0.13,
    },
  ]),

  shelf('lab-reagents-chemicals', [
    {
      key: 'lab-reagent-acetone',
      type: 'Laboratory solvent',
      title: 'Acetone, Analytical Reagent Grade',
      brand: BRANDS.reagent,
      short: 'Analytical reagent grade acetone in an amber glass winchester with a batch label.',
      long: 'Analytical reagent grade acetone supplied in an amber glass winchester with a polycone cap. Each bottle carries a batch number and a certificate of analysis reference on the label. Stored and shipped upright in a compartmented carton.',
      img: 'laboratory chemical solvent bottle amber glass',
      specs: {
        Grade: 'Analytical reagent',
        Assay: 'Minimum 99.5%',
        Container: 'Amber glass winchester, polycone cap',
        Batch: 'Batch number printed on label',
        Storage: 'Cool, ventilated, away from ignition sources',
      },
      facets: ['Grade', 'Container'],
      axes: [
        ['net_volume', ['500 ml', '1 L', '2.5 L']],
        ['container_type', ['Amber glass winchester', 'Coated glass winchester']],
      ],
      price: [46_000, 680_000],
      stock: [10, 120],
      moq: 1,
      grams: 1_300,
      sold: { content: [1, 'L'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'lab-reagent-buffer',
      type: 'pH buffer solution',
      title: 'pH Buffer Solution Set, Colour Coded',
      brand: BRANDS.reagent,
      short:
        'Colour-coded pH buffer solutions at 4.01, 7.00 and 10.01, with the batch value on the label.',
      long: 'Buffer solutions for calibrating a pH meter, colour coded so the wrong bottle is obvious on the bench. The value measured for the batch at 25 degrees is printed on each label rather than the nominal figure alone.',
      img: 'ph buffer solution bottles laboratory',
      specs: {
        Values: 'pH 4.01, 7.00 and 10.01 at 25 C',
        Coding: 'Colour coded per value',
        Container: 'HDPE bottle with tamper ring',
        Batch: 'Measured value printed per batch',
      },
      facets: ['Coding'],
      axes: [
        ['concentration', ['pH 4.01', 'pH 7.00', 'pH 10.01']],
        ['net_volume', ['500 ml', '1 L']],
      ],
      price: [28_000, 96_000],
      stock: [20, 240],
      moq: 1,
      grams: 1_100,
      sold: { content: [500, 'ml'], per: [1, 'L'] },
    },
    {
      key: 'lab-reagent-agar',
      type: 'Culture medium',
      title: 'Dehydrated Nutrient Agar Powder',
      brand: BRANDS.reagent,
      short: 'Dehydrated nutrient agar powder in a moisture-sealed jar with a scoop.',
      long: 'A dehydrated culture medium supplied as a free-flowing powder in a moisture-sealed jar. The label carries the batch, the preparation quantity per litre and the sterilisation cycle. A polypropylene scoop is included under the cap.',
      img: 'dehydrated agar powder laboratory jar',
      specs: {
        Form: 'Free-flowing dehydrated powder',
        Container: 'Moisture-sealed jar with scoop',
        Preparation: 'Quantity per litre printed on label',
        Storage: 'Dry, below 25 C',
      },
      facets: ['Form'],
      axes: [['net_weight', ['100 g', '500 g']]],
      price: [92_000, 340_000],
      stock: [12, 140],
      moq: 1,
      grams: 620,
      sold: { content: [500, 'g'], per: [1, 'kg'] },
      mrp: 0.11,
    },
  ]),

  shelf('lab-consumables-sampling', [
    {
      key: 'lab-cons-tips',
      type: 'Pipette tip',
      title: 'Filtered Pipette Tips in Racked Trays',
      brand: BRANDS.reagent,
      short:
        'Sterile filtered pipette tips in racked trays, moulded from virgin polypropylene.',
      long: 'Pipette tips with an integral hydrophobic filter, racked in trays so the pipette is loaded without touching the tip. Moulded from virgin polypropylene and supplied sterile, with a peel lid over each rack.',
      img: 'pipette tips rack laboratory sterile',
      specs: {
        Material: 'Virgin polypropylene',
        Filter: 'Integral hydrophobic filter',
        Presentation: 'Racked trays with peel lid',
        Sterility: 'Sterile',
      },
      facets: ['Filter', 'Sterility'],
      axes: [
        ['volume', ['10 ul', '200 ul', '1000 ul']],
        ['pack_count', ['Rack of 96', 'Case of 960']],
      ],
      price: [98_000, 820_000],
      stock: [15, 200],
      moq: 1,
      grams: 480,
      featured: true,
    },
    {
      key: 'lab-cons-tubes',
      type: 'Centrifuge tube',
      title: 'Conical Centrifuge Tube with Printed Graduations',
      brand: BRANDS.reagent,
      short:
        'Conical polypropylene centrifuge tube with printed graduations and a writing panel.',
      long: 'A conical centrifuge tube in polypropylene, rated for the speeds a benchtop rotor reaches. The graduations and the writing panel are printed, and the cap has a flat top so a rack of tubes can be stood on their lids.',
      img: 'conical centrifuge tubes laboratory plastic',
      specs: {
        Material: 'Polypropylene',
        Form: 'Conical with flat-top cap',
        Marking: 'Printed graduations and writing panel',
        Sterility: 'Sterile',
      },
      facets: ['Material', 'Sterility'],
      axes: [
        ['volume', ['15 ml', '50 ml']],
        ['sterility', ['Sterile', 'Non-sterile']],
        ['pack_count', ['Bag of 50', 'Case of 500']],
      ],
      price: [64_000, 640_000],
      stock: [18, 240],
      moq: 1,
      grams: 900,
    },
    {
      key: 'lab-cons-petri',
      type: 'Petri dish',
      title: 'Vented Petri Dish, 90 mm, Sterile',
      brand: BRANDS.reagent,
      short: 'Ninety millimetre vented Petri dish in optically clear polystyrene, sterile.',
      long: 'A ninety millimetre Petri dish in optically clear polystyrene, with three moulded vents in the lid and stacking rings on the base. Supplied sterile in sleeves of twenty.',
      img: 'petri dish stack laboratory sterile plastic',
      specs: {
        Diameter: '90 mm',
        Material: 'Optically clear polystyrene',
        Vents: 'Three moulded vents',
        Sterility: 'Sterile, sleeved',
      },
      facets: ['Sterility', 'Material'],
      axes: [
        ['dimensions', ['55 mm', '90 mm', '140 mm']],
        ['pack_count', ['Sleeve of 20', 'Case of 500']],
      ],
      price: [38_000, 560_000],
      stock: [20, 300],
      moq: 1,
      grams: 1_200,
      mrp: 0.14,
    },
  ]),

  shelf('measurement-calibration', [
    {
      key: 'cal-thermometer',
      type: 'Digital thermometer',
      title: 'Digital Thermometer with Interchangeable Probe',
      brand: BRANDS.lab,
      short:
        'Handheld digital thermometer with an interchangeable probe socket and a hold function.',
      long: 'A handheld thermometer with a socket for an interchangeable probe, so one instrument covers a surface, an immersion and a penetration measurement. The display holds the last reading and shows the minimum and maximum since the meter was switched on.',
      img: 'digital thermometer probe measurement instrument',
      specs: {
        Probe: 'Interchangeable, socket fitting',
        Functions: 'Hold, minimum and maximum',
        Display: 'Backlit LCD',
        Power: 'AAA cells',
      },
      facets: ['Probe'],
      axes: [
        ['measurement_range', ['-50 to 300 C', '-200 to 1372 C']],
        ['accuracy_class', ['Class 1', 'Class 2']],
        ['probe_type', ['Penetration', 'Surface', 'Immersion']],
      ],
      price: [280_000, 1_450_000],
      stock: [8, 90],
      moq: 1,
      grams: 320,
      featured: true,
    },
    {
      key: 'cal-weight-set',
      type: 'Calibration weight set',
      title: 'Stainless Steel Calibration Weight Set in Case',
      brand: BRANDS.lab,
      short:
        'Stainless steel calibration weight set in a fitted case, with tweezers and a certificate option.',
      long: 'A set of stainless steel calibration weights in a fitted case, with a pair of plastic-tipped tweezers. The weights are polished and unmarked, and a traceable calibration certificate can be supplied against the set on request.',
      img: 'calibration weight set stainless steel case',
      specs: {
        Material: 'Polished stainless steel',
        Case: 'Fitted case with tweezers',
        Handling: 'Plastic-tipped tweezers supplied',
      },
      facets: ['Material'],
      axes: [
        ['accuracy_class', ['Class F1', 'Class F2', 'Class M1']],
        ['measurement_range', ['1 mg to 100 g', '1 g to 1 kg']],
        ['calibration_option', ['Without certificate', 'With calibration certificate']],
      ],
      price: [1_200_00, 14_800_00],
      stock: [4, 40],
      moq: 1,
      grams: 2_400,
      leadDays: 7,
    },
    {
      key: 'cal-datalogger',
      type: 'Data logger',
      title: 'Temperature and Humidity Data Logger with USB',
      brand: BRANDS.lab,
      short:
        'Standalone temperature and humidity logger with a USB connector and a configurable interval.',
      long: 'A standalone logger that records temperature and relative humidity to internal memory at an interval the user sets. It plugs directly into a USB port to configure and to download, and a status light shows when a recorded value went outside the set limits.',
      img: 'usb temperature humidity data logger device',
      specs: {
        Measured: 'Temperature and relative humidity',
        Interface: 'USB-A direct plug',
        Memory: '32,000 readings',
        Alarm: 'Status light on limit breach',
      },
      facets: ['Measured', 'Interface'],
      axes: [
        ['measurement_range', ['-30 to 70 C', '-40 to 85 C']],
        ['accuracy_class', ['+/- 0.5 C', '+/- 0.3 C']],
        ['power_source', ['Internal cell', 'Replaceable cell']],
      ],
      price: [340_000, 2_400_000],
      stock: [6, 80],
      moq: 1,
      grams: 60,
      mrp: 0.12,
    },
  ]),

  // =======================================================================
  // INDUSTRIAL SUPPLIES
  // =======================================================================
  shelf('fasteners-fixings', [
    {
      key: 'ind-fast-hexbolt',
      type: 'Hexagon head bolt',
      title: 'Hexagon Head Bolt, Zinc Plated, Grade 8.8',
      brand: BRANDS.industrial,
      short:
        'Grade 8.8 hexagon head bolt with a full metric coarse thread and a zinc-plated finish.',
      long: 'A hexagon head bolt in grade 8.8 medium carbon steel, zinc plated and clear passivated. The thread is metric coarse to the full length under the head, the head is marked with the grade, and the bearing face is machined flat.',
      img: 'hexagon head bolts zinc plated fasteners',
      specs: {
        Grade: '8.8 medium carbon steel',
        Finish: 'Zinc plated, clear passivated',
        'Thread system': 'Metric coarse',
        'Head marking': 'Grade marked',
        Standard: 'DIN 933 form',
      },
      facets: ['Grade', 'Finish', 'Thread system'],
      axes: [
        ['diameter', ['M6', 'M8', 'M10', 'M12']],
        ['length', ['20 mm', '40 mm', '60 mm']],
        ['pack_count', ['Box of 100', 'Box of 500']],
      ],
      price: [24_000, 380_000],
      stock: [25, 400],
      moq: 1,
      grams: 1_400,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
      featured: true,
    },
    {
      key: 'ind-fast-socketcap',
      type: 'Socket cap screw',
      title: 'Socket Cap Screw, Black Oxide, Grade 12.9',
      brand: BRANDS.industrial,
      short:
        'Grade 12.9 socket cap screw with a hexagon socket drive and a black oxide finish.',
      long: 'A socket cap screw in grade 12.9 alloy steel with a black oxide finish. The hexagon socket is broached to depth so a key seats fully, and the head is knurled on its outside diameter for grip when starting by hand.',
      img: 'socket cap screws black oxide fasteners',
      specs: {
        Grade: '12.9 alloy steel',
        Finish: 'Black oxide',
        Drive: 'Hexagon socket, broached',
        Head: 'Knurled outside diameter',
        Standard: 'DIN 912 form',
      },
      facets: ['Grade', 'Finish', 'Drive'],
      axes: [
        ['diameter', ['M4', 'M5', 'M6', 'M8']],
        ['length', ['16 mm', '25 mm', '40 mm']],
        ['pack_count', ['Box of 100', 'Box of 200']],
      ],
      price: [32_000, 320_000],
      stock: [20, 360],
      moq: 1,
      grams: 900,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
    },
    {
      key: 'ind-fast-anchor',
      type: 'Through-bolt anchor',
      title: 'Through-Bolt Anchor for Concrete, Hot-Dip Galvanised',
      brand: BRANDS.industrial,
      short:
        'Hot-dip galvanised through-bolt anchor with an expanding sleeve for solid concrete.',
      long: 'A through-bolt anchor for solid concrete: the hole is drilled through the fixture, the bolt is driven home and tightening draws the cone into the expanding sleeve. Hot-dip galvanised for external use, with the embedment depth marked on the shank.',
      img: 'concrete anchor bolts galvanised fixings',
      specs: {
        Base: 'Solid concrete',
        Finish: 'Hot-dip galvanised',
        Mechanism: 'Expanding sleeve, torque set',
        Marking: 'Embedment depth marked on shank',
      },
      facets: ['Base', 'Finish'],
      axes: [
        ['diameter', ['M8', 'M10', 'M12']],
        ['length', ['75 mm', '100 mm', '130 mm']],
        ['pack_count', ['Box of 25', 'Box of 50']],
      ],
      price: [78_000, 480_000],
      stock: [15, 220],
      moq: 1,
      grams: 2_200,
      sold: { content: [25, 'piece'], label: 'Box of 25' },
      multipack: 25,
      mrp: 0.12,
    },
  ]),

  shelf('bearings-power-transmission', [
    {
      key: 'ind-bear-deepgroove',
      type: 'Deep groove ball bearing',
      title: 'Deep Groove Ball Bearing, Sealed Both Sides',
      brand: BRANDS.industrial,
      short:
        'Single-row deep groove ball bearing with contact seals on both sides and grease for life.',
      long: 'A single-row deep groove ball bearing with contact seals both sides and a lithium grease fill rated for the life of the bearing. The cage is pressed steel, the rings are through-hardened, and each bearing is supplied in an individual carton.',
      img: 'deep groove ball bearing industrial metal',
      specs: {
        Rows: 'Single row',
        'Seal type': 'Contact seal, both sides',
        Lubrication: 'Lithium grease, filled for life',
        Cage: 'Pressed steel',
        'Precision class': 'Normal (P0)',
      },
      facets: ['Seal type', 'Precision class'],
      axes: [
        ['bore_diameter', ['15 mm', '20 mm', '25 mm', '30 mm']],
        ['series', ['6000 series', '6200 series', '6300 series']],
      ],
      price: [38_000, 420_000],
      stock: [12, 180],
      moq: 1,
      grams: 260,
      featured: true,
    },
    {
      key: 'ind-bear-pillowblock',
      type: 'Pillow block bearing unit',
      title: 'Cast Iron Pillow Block Bearing Unit with Grease Nipple',
      brand: BRANDS.industrial,
      short:
        'Cast iron pillow block housing a self-aligning insert bearing, with a grease nipple and grub screw lock.',
      long: 'A cast iron pillow block housing a self-aligning insert bearing, locked to the shaft with two grub screws at ninety degrees. A grease nipple on the housing feeds the bearing directly, and the spherical outside diameter of the insert takes up shaft misalignment.',
      img: 'pillow block bearing unit cast iron industrial',
      specs: {
        Housing: 'Cast iron, two-bolt',
        Insert: 'Self-aligning with grub screw lock',
        Lubrication: 'Grease nipple on housing',
        Alignment: 'Spherical outer, static misalignment',
      },
      facets: ['Housing', 'Insert'],
      axes: [
        ['bore_diameter', ['20 mm', '25 mm', '30 mm', '35 mm']],
        ['seal_type', ['Standard', 'Triple lip']],
      ],
      price: [98_000, 680_000],
      stock: [8, 120],
      moq: 1,
      grams: 1_200,
    },
    {
      key: 'ind-bear-vbelt',
      type: 'V-belt',
      title: 'Wrapped V-Belt, Classical Section',
      brand: BRANDS.industrial,
      short:
        'Wrapped classical-section V-belt with a polyester cord tensile member and an oil-resistant cover.',
      long: 'A wrapped V-belt on a classical section, built on a polyester cord tensile member with a fabric cover treated to resist oil and heat. The section and the datum length are printed along the back so a replacement can be read off the belt.',
      img: 'v belt industrial rubber power transmission',
      specs: {
        Construction: 'Wrapped, polyester cord',
        Cover: 'Oil and heat resistant fabric',
        Marking: 'Section and datum length printed',
        'Temperature range': '-30 to 80 C',
      },
      facets: ['Construction', 'Cover'],
      axes: [
        ['component_type', ['A section', 'B section', 'C section']],
        ['width', ['1000 mm', '1250 mm', '1600 mm', '2000 mm']],
      ],
      price: [28_000, 240_000],
      stock: [15, 220],
      moq: 1,
      grams: 480,
      mrp: 0.14,
    },
  ]),

  shelf('hydraulics-pneumatics', [
    {
      key: 'ind-hyd-cylinder',
      type: 'Pneumatic cylinder',
      title: 'Double-Acting Pneumatic Cylinder, ISO 15552',
      brand: BRANDS.fluid,
      short:
        'Double-acting ISO 15552 pneumatic cylinder with adjustable end cushioning and magnetic piston.',
      long: 'A double-acting pneumatic cylinder to the ISO 15552 profile, with adjustable cushioning at both ends and a magnetic piston for position sensing. The barrel is anodised aluminium, the rod is hard-chromed steel, and the end caps take standard mounting kits.',
      img: 'pneumatic cylinder industrial actuator',
      specs: {
        Standard: 'ISO 15552',
        Action: 'Double acting',
        Cushioning: 'Adjustable both ends',
        Piston: 'Magnetic, for position sensing',
        Rod: 'Hard-chromed steel',
      },
      facets: ['Standard', 'Action'],
      axes: [
        ['bore', ['32 mm', '40 mm', '50 mm', '63 mm']],
        ['stroke', ['100 mm', '200 mm', '320 mm']],
      ],
      price: [280_000, 1_480_000],
      stock: [6, 90],
      moq: 1,
      grams: 1_800,
      featured: true,
    },
    {
      key: 'ind-hyd-hose',
      type: 'Hydraulic hose assembly',
      title: 'Two-Wire Braided Hydraulic Hose Assembly',
      brand: BRANDS.fluid,
      short:
        'Two-wire braided hydraulic hose assembly, crimped both ends with BSP male fittings.',
      long: 'A hydraulic hose assembly built on two-wire braided hose and crimped at both ends. The cover is abrasion-resistant and pin-pricked, the fittings are BSP male with a sixty degree cone seat, and each assembly carries a crimp tag with its date and pressure rating.',
      img: 'hydraulic hose assembly industrial fittings',
      specs: {
        Construction: 'Two-wire braid',
        Cover: 'Abrasion resistant, pin-pricked',
        Fittings: 'BSP male, 60 degree cone',
        Traceability: 'Crimp tag with date and rating',
      },
      facets: ['Construction', 'Fittings'],
      axes: [
        ['port_size', ['1/4 in', '3/8 in', '1/2 in']],
        ['bore', ['600 mm', '1000 mm', '1500 mm', '2000 mm']],
      ],
      price: [96_000, 620_000],
      stock: [10, 140],
      moq: 1,
      grams: 1_100,
      leadDays: 3,
    },
    {
      key: 'ind-hyd-frl',
      type: 'Air preparation unit',
      title: 'Filter-Regulator-Lubricator Unit with Gauge',
      brand: BRANDS.fluid,
      short:
        'Three-stage filter, regulator and lubricator unit with a pressure gauge and a bowl guard.',
      long: 'A three-stage air preparation unit: a filter with a manual drain, a regulator with a locking adjuster and a gauge, and a lubricator with a sight dome. The bowls carry metal guards and the whole assembly comes on a mounting bracket.',
      img: 'pneumatic filter regulator lubricator unit',
      specs: {
        Stages: 'Filter, regulator, lubricator',
        Gauge: 'Pressure gauge fitted',
        Drain: 'Manual drain on filter bowl',
        Bowls: 'Metal bowl guards',
      },
      facets: ['Stages'],
      axes: [
        ['port_size', ['1/4 in', '3/8 in', '1/2 in']],
        ['pressure_rating', ['10 bar', '16 bar']],
      ],
      price: [340_000, 1_180_000],
      stock: [5, 70],
      moq: 1,
      grams: 2_400,
      mrp: 0.13,
    },
  ]),

  shelf('pumps-valves', [
    {
      key: 'ind-pump-centrifugal',
      type: 'Centrifugal pump',
      title: 'Cast Iron End-Suction Centrifugal Pump',
      brand: BRANDS.fluid,
      short:
        'Close-coupled end-suction centrifugal pump in cast iron with a mechanical seal.',
      long: 'A close-coupled end-suction centrifugal pump with a cast iron casing, a bronze impeller and a mechanical seal on a stainless shaft. The casing drains from a plugged boss at the bottom and the suction and discharge are flanged.',
      img: 'centrifugal water pump industrial cast iron',
      specs: {
        Casing: 'Cast iron, flanged',
        Impeller: 'Bronze',
        Seal: 'Mechanical seal, carbon-ceramic',
        Shaft: 'Stainless steel',
        Mounting: 'Close coupled',
      },
      facets: ['Casing', 'Seal'],
      axes: [
        ['port_size', ['1 in', '1.5 in', '2 in']],
        ['voltage', ['230 V', '415 V']],
        ['phase', ['Single phase', 'Three phase']],
      ],
      price: [11_500_00, 68_000_00],
      stock: [3, 36],
      moq: 1,
      grams: 24_000,
      leadDays: 7,
      featured: true,
    },
    {
      key: 'ind-valve-ball',
      type: 'Ball valve',
      title: 'Full-Bore Brass Ball Valve with Lever Handle',
      brand: BRANDS.fluid,
      short:
        'Full-bore brass ball valve with a chrome-plated ball, PTFE seats and a lever handle.',
      long: 'A full-bore brass ball valve with a chrome-plated ball and PTFE seats. The bore matches the pipe, so pressure drop across the open valve is small, and the lever is set at ninety degrees to the flow so its position shows the valve state.',
      img: 'brass ball valve industrial plumbing lever',
      specs: {
        Bore: 'Full bore',
        Body: 'Forged brass',
        Ball: 'Chrome plated',
        Seats: 'PTFE',
        'Pressure rating': 'PN25',
      },
      facets: ['Bore', 'Body', 'Pressure rating'],
      axes: [
        ['port_size', ['1/2 in', '3/4 in', '1 in', '1.5 in', '2 in']],
        ['actuation', ['Lever handle', 'Butterfly handle']],
      ],
      price: [42_000, 620_000],
      stock: [15, 220],
      moq: 1,
      grams: 640,
    },
    {
      key: 'ind-pump-diaphragm',
      type: 'Diaphragm dosing pump',
      title: 'Solenoid Diaphragm Dosing Pump with Digital Control',
      brand: BRANDS.fluid,
      short:
        'Solenoid-driven diaphragm dosing pump with a digital stroke rate control and a PVDF head.',
      long: 'A solenoid-driven diaphragm dosing pump with a PVDF head, ceramic ball valves and a PTFE diaphragm. Stroke rate and length are set digitally and the pump can be driven from an external pulse input.',
      img: 'chemical dosing pump industrial diaphragm',
      specs: {
        Drive: 'Solenoid',
        Head: 'PVDF with ceramic ball valves',
        Diaphragm: 'PTFE',
        Control: 'Digital stroke rate and length, external pulse input',
      },
      facets: ['Head', 'Control'],
      axes: [
        ['flow_rate', ['5 l/h', '12 l/h', '20 l/h']],
        ['pressure_rating', ['5 bar', '10 bar']],
      ],
      price: [18_500_00, 52_000_00],
      stock: [2, 24],
      moq: 1,
      grams: 4_200,
      leadDays: 10,
      mrp: 0.1,
    },
  ]),

  shelf('abrasives', [
    {
      key: 'ind-abr-cuttingdisc',
      type: 'Cutting disc',
      title: 'Reinforced Cutting Disc for Steel',
      brand: BRANDS.abrasive,
      short:
        'Fibreglass-reinforced thin cutting disc for steel, with a depressed centre and a printed expiry.',
      long: 'A thin cutting disc for steel, reinforced with two layers of fibreglass mesh. The thin section cuts with less heat into the workpiece, and the label carries the maximum speed and the expiry date that an abrasive disc is sold against.',
      img: 'abrasive cutting disc angle grinder steel',
      specs: {
        Reinforcement: 'Two-layer fibreglass mesh',
        Material: 'Aluminium oxide, for steel',
        Marking: 'Maximum speed and expiry printed',
        Form: 'Flat, Type 41',
      },
      facets: ['Material', 'Form'],
      axes: [
        ['diameter', ['115 mm', '125 mm', '180 mm', '230 mm']],
        ['thickness', ['1.0 mm', '1.6 mm', '2.5 mm']],
        ['pack_count', ['Pack of 10', 'Box of 25']],
      ],
      price: [32_000, 380_000],
      stock: [20, 320],
      moq: 1,
      grams: 900,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      featured: true,
    },
    {
      key: 'ind-abr-flapdisc',
      type: 'Flap disc',
      title: 'Zirconia Flap Disc with Fibreglass Backing',
      brand: BRANDS.abrasive,
      short:
        'Zirconia alumina flap disc on a fibreglass backing plate, for blending and weld dressing.',
      long: 'A flap disc built from overlapping zirconia alumina cloth flaps on a fibreglass backing plate, so the plate can be ground into without damaging the machine. The flaps wear back evenly and expose fresh grain as they do.',
      img: 'flap disc abrasive grinding zirconia',
      specs: {
        Grain: 'Zirconia alumina',
        Backing: 'Fibreglass plate',
        Form: 'Conical, Type 29',
        Marking: 'Maximum speed printed',
      },
      facets: ['Grain', 'Backing'],
      axes: [
        ['diameter', ['115 mm', '125 mm', '180 mm']],
        ['grit', ['P40', 'P60', 'P80', 'P120']],
        ['pack_count', ['Single', 'Pack of 10']],
      ],
      price: [12_000, 280_000],
      stock: [22, 340],
      moq: 1,
      grams: 220,
    },
    {
      key: 'ind-abr-sandpaper',
      type: 'Abrasive sheet',
      title: 'Aluminium Oxide Abrasive Sheet, Wet and Dry',
      brand: BRANDS.abrasive,
      short:
        'Latex-backed aluminium oxide abrasive sheet for wet or dry use, in mixed-grit packs.',
      long: 'An aluminium oxide abrasive sheet on a flexible latex-impregnated paper backing, so it can be used wet or dry and folded without cracking the grain. Supplied in single-grit packs or in a mixed pack across the range.',
      img: 'sandpaper abrasive sheets stack',
      specs: {
        Grain: 'Aluminium oxide',
        Backing: 'Latex-impregnated paper',
        Use: 'Wet or dry',
        'Sheet size': '230 x 280 mm',
      },
      facets: ['Grain', 'Use'],
      axes: [
        ['grit', ['P120', 'P240', 'P400', 'P800', 'Mixed grit']],
        ['pack_count', ['Pack of 10', 'Pack of 50']],
      ],
      price: [14_000, 140_000],
      stock: [25, 400],
      moq: 1,
      grams: 320,
      sold: { content: [10, 'sheet'], label: 'Pack of 10' },
      multipack: 10,
      mrp: 0.16,
    },
  ]),

  shelf('lubricants-adhesives', [
    {
      key: 'ind-lub-gearoil',
      type: 'Industrial gear oil',
      title: 'EP Industrial Gear Oil, Mineral Base',
      brand: BRANDS.abrasive,
      short:
        'Extreme-pressure mineral gear oil for enclosed industrial gearboxes, in a sealed pail.',
      long: 'An extreme-pressure mineral gear oil for enclosed industrial gearboxes. The additive package carries load without attacking yellow metals, and the pail carries a tamper-evident lid and a batch code on the shoulder.',
      img: 'industrial gear oil drum lubricant',
      specs: {
        Base: 'Mineral',
        Additive: 'Extreme pressure, yellow-metal safe',
        Container: 'Sealed pail with tamper lid',
        'Temperature range': '-10 to 100 C',
      },
      facets: ['Base', 'Additive'],
      axes: [
        ['grade', ['ISO VG 68', 'ISO VG 100', 'ISO VG 220', 'ISO VG 320']],
        ['net_volume', ['5 L', '20 L']],
      ],
      price: [280_000, 1_650_000],
      stock: [8, 100],
      moq: 1,
      grams: 19_000,
      sold: { content: [20, 'L'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'ind-lub-threadlock',
      type: 'Threadlocking adhesive',
      title: 'Medium-Strength Threadlocking Adhesive',
      brand: BRANDS.abrasive,
      short:
        'Medium-strength anaerobic threadlocker for fasteners that may need to come apart again.',
      long: 'An anaerobic threadlocking adhesive of medium strength, for fasteners that are expected to be removed with hand tools later. It cures in the absence of air between engaged threads and stays liquid in the bottle.',
      img: 'threadlocker adhesive bottle industrial',
      specs: {
        Chemistry: 'Anaerobic methacrylate',
        Strength: 'Medium - removable with hand tools',
        'Curing type': 'Anaerobic, metal contact',
        'Temperature range': '-55 to 150 C',
      },
      facets: ['Chemistry', 'Strength'],
      axes: [
        ['net_volume', ['10 ml', '50 ml', '250 ml']],
        ['container_type', ['Bottle', 'Bottle with brush cap']],
      ],
      price: [42_000, 620_000],
      stock: [15, 200],
      moq: 1,
      grams: 120,
    },
    {
      key: 'ind-lub-grease',
      type: 'Lithium complex grease',
      title: 'Lithium Complex Grease, NLGI 2',
      brand: BRANDS.abrasive,
      short:
        'NLGI 2 lithium complex grease for bearings and general plant, in cartridges or a tub.',
      long: 'A lithium complex grease at NLGI grade 2, for rolling element bearings and general plant lubrication. It holds its consistency at higher temperatures than a simple lithium soap and does not soften under working.',
      img: 'grease cartridge industrial lubricant',
      specs: {
        Thickener: 'Lithium complex',
        Grade: 'NLGI 2',
        'Temperature range': '-20 to 150 C',
        Colour: 'Amber',
      },
      facets: ['Thickener', 'Grade'],
      axes: [
        ['net_weight', ['400 g', '1 kg', '18 kg']],
        ['container_type', ['Cartridge', 'Tub', 'Keg']],
      ],
      price: [32_000, 1_480_000],
      stock: [12, 180],
      moq: 1,
      grams: 480,
      sold: { content: [400, 'g'], per: [1, 'kg'] },
      mrp: 0.12,
    },
  ]),

  shelf('welding-soldering', [
    {
      key: 'ind-weld-mig-wire',
      type: 'MIG welding wire',
      title: 'Copper-Coated MIG Welding Wire on a Spool',
      brand: BRANDS.abrasive,
      short:
        'Copper-coated solid MIG wire, layer-wound on a spool with the grade printed on the flange.',
      long: 'A solid copper-coated MIG wire for mild steel, layer-wound so it feeds without tangling to the last turn. The spool flange carries the grade, the diameter and the batch, and the wire end is secured in a hole in the flange rather than tucked under a turn.',
      img: 'mig welding wire spool industrial',
      specs: {
        Coating: 'Copper coated',
        'Compatible material': 'Mild steel',
        Winding: 'Layer wound',
        Marking: 'Grade, diameter and batch on flange',
      },
      facets: ['Compatible material', 'Coating'],
      axes: [
        ['diameter', ['0.6 mm', '0.8 mm', '1.0 mm', '1.2 mm']],
        ['net_weight', ['5 kg', '15 kg']],
      ],
      price: [98_000, 720_000],
      stock: [10, 140],
      moq: 1,
      grams: 15_400,
      sold: { content: [15, 'kg'], per: [1, 'kg'] },
      featured: true,
    },
    {
      key: 'ind-weld-electrode',
      type: 'Welding electrode',
      title: 'Rutile Welding Electrode in a Sealed Tin',
      brand: BRANDS.abrasive,
      short:
        'Rutile-coated welding electrode supplied in a moisture-sealed tin, for general steel fabrication.',
      long: 'A rutile-coated electrode for general steel fabrication, supplied in a moisture-sealed tin so the coating does not take up damp on the shelf. It strikes easily, runs in all positions and the slag lifts cleanly.',
      img: 'welding electrodes rods box industrial',
      specs: {
        Coating: 'Rutile',
        Positions: 'All positions',
        Packaging: 'Moisture-sealed tin',
        Polarity: 'AC or DC',
      },
      facets: ['Coating', 'Polarity'],
      axes: [
        ['diameter', ['2.5 mm', '3.2 mm', '4.0 mm']],
        ['net_weight', ['2.5 kg', '5 kg']],
      ],
      price: [48_000, 280_000],
      stock: [15, 200],
      moq: 1,
      grams: 5_200,
      sold: { content: [5, 'kg'], per: [1, 'kg'] },
    },
    {
      key: 'ind-weld-solder',
      type: 'Solder wire',
      title: 'Lead-Free Flux-Cored Solder Wire',
      brand: BRANDS.electronics,
      short: 'Lead-free flux-cored solder wire on a reel, for electronics assembly and repair.',
      long: 'A lead-free tin-copper-silver solder wire with a rosin flux core, on a plastic reel. The flux is contained in three cores rather than one, so it is delivered evenly as the wire melts.',
      img: 'solder wire reel electronics soldering',
      specs: {
        Alloy: 'Tin-copper-silver, lead-free',
        Flux: 'Rosin, three cores',
        Reel: 'Plastic reel',
        'Melting range': '217 to 221 C',
      },
      facets: ['Alloy', 'Flux'],
      axes: [
        ['diameter', ['0.5 mm', '0.8 mm', '1.0 mm']],
        ['net_weight', ['100 g', '250 g', '500 g']],
      ],
      price: [38_000, 320_000],
      stock: [18, 240],
      moq: 1,
      grams: 280,
      sold: { content: [250, 'g'], per: [1, 'kg'] },
      mrp: 0.11,
    },
  ]),

  shelf('material-handling', [
    {
      key: 'ind-mh-pallettruck',
      type: 'Hand pallet truck',
      title: 'Hydraulic Hand Pallet Truck with Nylon Wheels',
      brand: BRANDS.industrial,
      short:
        'Hydraulic hand pallet truck with nylon wheels, a three-position handle and an overload valve.',
      long: 'A hand pallet truck with a sealed hydraulic unit and a three-position handle for lift, lower and neutral. The forks are reinforced along their length, the entry rollers are tandem, and an overload valve stops the pump above the rated capacity.',
      img: 'hand pallet truck warehouse equipment',
      specs: {
        Hydraulics: 'Sealed unit with overload valve',
        Handle: 'Three-position lift, lower, neutral',
        Wheels: 'Nylon, tandem entry rollers',
        'Fork width': '540 mm overall',
      },
      facets: ['Wheels', 'Hydraulics'],
      axes: [
        ['load_capacity', ['2,000 kg', '2,500 kg', '3,000 kg']],
        ['fork_dimensions', ['1,150 mm', '1,500 mm']],
      ],
      price: [14_500_00, 32_000_00],
      stock: [2, 26],
      moq: 1,
      grams: 78_000,
      leadDays: 5,
      featured: true,
    },
    {
      key: 'ind-mh-sacktruck',
      type: 'Sack truck',
      title: 'Folding Sack Truck with Pneumatic Wheels',
      brand: BRANDS.industrial,
      short:
        'Steel sack truck with a folding toe plate and pneumatic wheels, for uneven ground.',
      long: 'A steel sack truck whose toe plate folds up against the frame for storage. The wheels are pneumatic on sealed bearings, which is what makes it usable on a yard rather than only on a smooth floor, and the handles are sleeved.',
      img: 'sack truck hand trolley warehouse',
      specs: {
        Frame: 'Welded steel, powder coated',
        'Toe plate': 'Folding',
        Wheels: 'Pneumatic on sealed bearings',
        Handles: 'Sleeved grips',
      },
      facets: ['Wheels', 'Toe plate'],
      axes: [
        ['load_capacity', ['150 kg', '250 kg']],
        ['material', ['Steel', 'Aluminium']],
      ],
      price: [4_200_00, 11_800_00],
      stock: [4, 48],
      moq: 1,
      grams: 14_000,
    },
    {
      key: 'ind-mh-shelftrolley',
      type: 'Platform trolley',
      title: 'Two-Shelf Platform Trolley with Braked Castors',
      brand: BRANDS.industrial,
      short:
        'Two-shelf steel platform trolley with a push handle and two braked swivel castors.',
      long: 'A two-shelf platform trolley in powder-coated steel, with lipped shelves so a load does not slide off. Two of the four castors swivel and brake; the other two are fixed, which is what makes the trolley track straight when it is pushed.',
      img: 'platform trolley warehouse shelves steel',
      specs: {
        Shelves: 'Two, lipped',
        Castors: 'Two braked swivel, two fixed',
        Finish: 'Powder coated steel',
        'Shelf size': '850 x 500 mm',
      },
      facets: ['Castors', 'Finish'],
      axes: [
        ['load_capacity', ['150 kg', '300 kg']],
        ['fork_dimensions', ['850 x 500 mm', '1,000 x 600 mm']],
      ],
      price: [6_800_00, 16_500_00],
      stock: [3, 40],
      moq: 1,
      grams: 22_000,
      mrp: 0.12,
    },
  ]),

  // =======================================================================
  // TOOLS & HARDWARE
  // =======================================================================
  shelf('hand-tools', [
    {
      key: 'tool-hand-socketset',
      type: 'Socket set',
      title: 'Chrome Vanadium Socket Set in a Blow-Moulded Case',
      brand: BRANDS.tools,
      short:
        'Chrome vanadium socket set with a quick-release ratchet, in a blow-moulded case with a moulded tray.',
      long: 'A socket set in chrome vanadium steel with a mirror-polished finish, supplied in a blow-moulded case with a moulded tray so a missing socket is obvious. The ratchet is quick-release with a fine tooth count, and the sockets are bi-hexagonal.',
      img: 'socket set chrome vanadium hand tools case',
      specs: {
        Material: 'Chrome vanadium steel',
        Finish: 'Mirror polished',
        Ratchet: 'Quick release, 72 tooth',
        Sockets: 'Bi-hexagonal',
        Case: 'Blow-moulded with moulded tray',
      },
      facets: ['Material', 'Ratchet'],
      axes: [
        ['drive_size', ['1/4 in', '3/8 in', '1/2 in']],
        ['piece_count', ['24 piece', '40 piece', '94 piece']],
      ],
      price: [1_450_00, 8_900_00],
      stock: [6, 80],
      moq: 1,
      grams: 4_800,
      featured: true,
    },
    {
      key: 'tool-hand-spannerset',
      type: 'Combination spanner set',
      title: 'Combination Spanner Set with Ratcheting Ring End',
      brand: BRANDS.tools,
      short:
        'Combination spanner set with a ratcheting ring end and a fifteen degree offset open jaw.',
      long: 'A combination spanner set whose ring end ratchets, so a fastener in a confined space can be turned without lifting the spanner off. The open jaw is offset fifteen degrees and the size is stamped on both ends.',
      img: 'combination spanner set wrench tools',
      specs: {
        'Ring end': 'Ratcheting, 72 tooth',
        'Open end': '15 degree offset',
        Material: 'Chrome vanadium steel',
        Marking: 'Size stamped both ends',
      },
      facets: ['Ring end', 'Material'],
      axes: [
        ['tool_type', ['Metric set', 'Imperial set']],
        ['piece_count', ['8 piece', '12 piece', '16 piece']],
      ],
      price: [1_180_00, 5_400_00],
      stock: [8, 100],
      moq: 1,
      grams: 2_600,
    },
    {
      key: 'tool-hand-pliers',
      type: 'Insulated pliers set',
      title: 'VDE Insulated Pliers Set, 1000 V Rated',
      brand: BRANDS.tools,
      short:
        'Three-piece insulated pliers set with two-colour handles, individually tested to 1000 V.',
      long: 'A three-piece insulated pliers set - combination, long nose and side cutters - with two-colour handle insulation, so wear through the outer layer shows as a contrasting stripe before it becomes a hazard. Each tool is individually tested.',
      img: 'insulated electrician pliers set vde tools',
      specs: {
        Insulation: 'Two-colour, wear-indicating',
        Rating: '1000 V AC, individually tested',
        Contents: 'Combination, long nose, side cutters',
        Material: 'Drop-forged steel',
      },
      facets: ['Insulation', 'Rating'],
      axes: [
        ['piece_count', ['3 piece', '5 piece']],
        ['length', ['160 mm', '180 mm', '200 mm']],
      ],
      price: [1_680_00, 4_900_00],
      stock: [7, 90],
      moq: 1,
      grams: 1_400,
      mrp: 0.13,
    },
  ]),

  shelf('power-tools', [
    {
      key: 'tool-pwr-drill',
      type: 'Cordless drill driver',
      title: '18 V Brushless Cordless Drill Driver Kit',
      brand: BRANDS.tools,
      short:
        'Brushless 18 V drill driver with a 13 mm keyless chuck, a two-speed gearbox and a 20-stage clutch.',
      long: 'A brushless cordless drill driver on an 18 volt platform. The gearbox has two speeds and the clutch twenty settings plus a drill position, the chuck is 13 mm all-metal keyless, and an LED under the chuck lights the work rather than the operator. Supplied in a moulded case.',
      img: 'cordless electric drill driver power tool isolated',
      specs: {
        Motor: 'Brushless',
        Chuck: '13 mm all-metal keyless',
        Gearbox: 'Two speed',
        Clutch: '20 stages plus drill',
        'Battery platform': 'Kestrel 18 V',
        Light: 'LED under chuck',
      },
      facets: ['Motor', 'Battery platform'],
      axes: [
        ['voltage', ['12 V', '18 V']],
        ['battery_capacity', ['2.0 Ah', '4.0 Ah', '5.0 Ah']],
        ['kit_contents', ['Bare tool', 'One battery and charger', 'Two batteries and charger']],
      ],
      price: [3_200_00, 18_900_00],
      stock: [5, 70],
      moq: 1,
      grams: 3_400,
      featured: true,
    },
    {
      key: 'tool-pwr-grinder',
      type: 'Angle grinder',
      title: 'Corded Angle Grinder with Paddle Switch',
      brand: BRANDS.tools,
      short:
        'Corded angle grinder with a paddle switch, a restart lock and a tool-free guard adjustment.',
      long: 'A corded angle grinder with a paddle switch that must be held closed, a restart lock so it cannot start on its own after a power cut, and a guard that rotates and locks without a tool. The gearcase is cast aluminium and the side handle takes three positions.',
      img: 'angle grinder power tool workshop',
      specs: {
        Switch: 'Paddle with restart lock',
        Guard: 'Tool-free rotating guard',
        Gearcase: 'Cast aluminium',
        'Side handle': 'Three positions',
      },
      facets: ['Switch', 'Guard'],
      axes: [
        ['chuck_size', ['115 mm', '125 mm', '230 mm']],
        ['power', ['900 W', '1,400 W', '2,200 W']],
      ],
      price: [2_400_00, 9_800_00],
      stock: [6, 80],
      moq: 1,
      grams: 2_600,
    },
    {
      key: 'tool-pwr-impact',
      type: 'Impact driver',
      title: 'Brushless Impact Driver with Three-Speed Selector',
      brand: BRANDS.tools,
      short:
        'Brushless impact driver with a three-speed selector, a self-tapping screw mode and a belt hook.',
      long: 'A brushless impact driver with a three-speed selector and a fourth mode that runs slowly until a self-tapping screw bites and then speeds up. The chuck is a one-handed quarter inch hex, and the belt hook mounts on either side.',
      img: 'impact driver cordless power tool',
      specs: {
        Motor: 'Brushless',
        Chuck: '1/4 in hex, one-handed',
        Modes: 'Three speeds plus self-tapping screw mode',
        'Belt hook': 'Left or right mounting',
        'Battery platform': 'Kestrel 18 V',
      },
      facets: ['Motor', 'Battery platform'],
      axes: [
        ['voltage', ['12 V', '18 V']],
        ['battery_capacity', ['2.0 Ah', '4.0 Ah']],
        ['kit_contents', ['Bare tool', 'One battery and charger', 'Two batteries and charger']],
      ],
      price: [3_600_00, 16_800_00],
      stock: [5, 65],
      moq: 1,
      grams: 2_900,
      mrp: 0.12,
    },
  ]),

  shelf('cutting-tools', [
    {
      key: 'tool-cut-hssdrill',
      type: 'Twist drill set',
      title: 'HSS Cobalt Twist Drill Set in a Metal Index',
      brand: BRANDS.precision,
      short:
        'Cobalt-alloyed HSS twist drill set with split points, in a hinged metal index case.',
      long: 'A twist drill set in cobalt-alloyed high speed steel, ground with a split point so the drill starts without a centre punch. Supplied in a hinged metal index with the sizes stamped into the case rather than printed on a label.',
      img: 'twist drill bit set metal index case',
      specs: {
        Material: 'HSS with 5% cobalt',
        Point: 'Split point, 135 degree',
        Flute: 'Right hand, 118 degree helix',
        Case: 'Hinged metal index, sizes stamped',
      },
      facets: ['Material', 'Point'],
      axes: [
        ['diameter', ['1-6 mm', '1-10 mm', '1-13 mm']],
        ['pack_count', ['19 piece', '25 piece', '29 piece']],
      ],
      price: [980_00, 6_400_00],
      stock: [8, 110],
      moq: 1,
      grams: 1_400,
      featured: true,
    },
    {
      key: 'tool-cut-endmill',
      type: 'End mill',
      title: 'TiAlN-Coated Carbide End Mill, Four Flute',
      brand: BRANDS.precision,
      short:
        'Four-flute solid carbide end mill with a TiAlN coating, for steel and stainless.',
      long: 'A four-flute solid carbide end mill with a TiAlN coating for cutting steel and stainless at higher surface speeds. The shank is plain and the flute length is marked on the shank along with the diameter.',
      img: 'carbide end mill cutting tool machining',
      specs: {
        Substrate: 'Solid carbide',
        Coating: 'TiAlN',
        Flutes: 'Four',
        'Helix angle': '30 degrees',
        Shank: 'Plain, h6',
      },
      facets: ['Substrate', 'Coating', 'Flutes'],
      axes: [
        ['diameter', ['4 mm', '6 mm', '8 mm', '10 mm', '12 mm']],
        ['cutting_length', ['Standard', 'Long series']],
      ],
      price: [420_000, 2_800_000],
      stock: [10, 140],
      moq: 1,
      grams: 90,
    },
    {
      key: 'tool-cut-holesaw',
      type: 'Hole saw set',
      title: 'Bi-Metal Hole Saw Set with Quick-Change Arbor',
      brand: BRANDS.precision,
      short:
        'Bi-metal hole saw set with a quick-change arbor and an ejection spring, in a carry case.',
      long: 'A bi-metal hole saw set with variable-pitch teeth and a quick-change arbor that releases with a collar rather than a spanner. An ejection spring pushes the slug out of the saw, which is the part of hole sawing that otherwise takes a screwdriver and a minute.',
      img: 'hole saw set bi metal cutting tools',
      specs: {
        Construction: 'Bi-metal, variable pitch',
        Arbor: 'Quick change with ejection spring',
        'Cutting depth': '38 mm',
        Case: 'Moulded carry case',
      },
      facets: ['Construction', 'Arbor'],
      axes: [
        ['diameter', ['19-64 mm', '19-127 mm']],
        ['pack_count', ['9 piece', '14 piece']],
      ],
      price: [1_280_00, 5_600_00],
      stock: [6, 80],
      moq: 1,
      grams: 2_200,
      mrp: 0.14,
    },
  ]),

  shelf('measuring-layout', [
    {
      key: 'tool-meas-caliper',
      type: 'Digital caliper',
      title: 'Digital Vernier Caliper with IP54 Housing',
      brand: BRANDS.precision,
      short:
        'Stainless steel digital caliper with an IP54-sealed housing and a data output port.',
      long: 'A stainless steel digital caliper with a sealed housing rated IP54, so coolant mist and swarf do not reach the scale. It reads in millimetres and inches, zeroes anywhere along the beam, and has a data port for a foot switch or a logger.',
      img: 'digital vernier caliper measuring instrument',
      specs: {
        Body: 'Hardened stainless steel',
        Sealing: 'IP54',
        Readout: 'Millimetres and inches, absolute or incremental',
        Output: 'Data port',
      },
      facets: ['Sealing', 'Body'],
      axes: [
        ['range', ['150 mm', '200 mm', '300 mm']],
        ['resolution', ['0.01 mm', '0.001 mm']],
      ],
      price: [980_00, 6_800_00],
      stock: [8, 100],
      moq: 1,
      grams: 320,
      featured: true,
    },
    {
      key: 'tool-meas-tape',
      type: 'Measuring tape',
      title: 'Nylon-Coated Measuring Tape with Magnetic Hook',
      brand: BRANDS.precision,
      short:
        'Nylon-coated steel measuring tape with a magnetic double-sided hook and a standout of over two metres.',
      long: 'A steel measuring tape with a nylon coating over the first section, where it wears fastest. The end hook is magnetic and reads from either face, and the blade stands out over two metres unsupported.',
      img: 'measuring tape steel construction tool',
      specs: {
        Blade: 'Nylon-coated steel',
        Hook: 'Magnetic, double sided',
        Standout: 'Over 2 m',
        Case: 'Rubber over-moulded',
      },
      facets: ['Blade', 'Hook'],
      axes: [
        ['range', ['5 m', '8 m', '10 m']],
        ['unit_system', ['Metric', 'Metric and imperial']],
      ],
      price: [280_000, 980_000],
      stock: [15, 220],
      moq: 1,
      grams: 380,
    },
    {
      key: 'tool-meas-level',
      type: 'Spirit level',
      title: 'Box-Section Aluminium Spirit Level with Milled Base',
      brand: BRANDS.precision,
      short:
        'Box-section aluminium spirit level with three acrylic vials and a milled measuring base.',
      long: 'A box-section aluminium spirit level with a milled base, so it sits flat rather than on an extruded finish. Three shock-absorbing acrylic vials read horizontal, vertical and forty-five degrees, and the end caps are rubber.',
      img: 'spirit level aluminium measuring tool',
      specs: {
        Section: 'Box-section aluminium',
        Base: 'Milled',
        Vials: 'Three acrylic, shock absorbing',
        Accuracy: '0.5 mm/m',
      },
      facets: ['Section', 'Base'],
      axes: [
        ['range', ['600 mm', '1,200 mm', '1,800 mm']],
        ['material', ['Aluminium', 'Magnetic aluminium']],
      ],
      price: [680_000, 3_400_000],
      stock: [8, 120],
      moq: 1,
      grams: 1_400,
      mrp: 0.11,
    },
  ]),

  shelf('tool-storage', [
    {
      key: 'tool-stor-rollcab',
      type: 'Roller cabinet',
      title: 'Seven-Drawer Roller Cabinet with Ball-Bearing Slides',
      brand: BRANDS.tools,
      short:
        'Seven-drawer steel roller cabinet on ball-bearing slides, with a central lock and braked castors.',
      long: 'A seven-drawer roller cabinet in powder-coated steel. Every drawer runs on ball-bearing slides and carries an EVA liner, a central lock secures all seven at once, and two of the four castors brake.',
      img: 'tool roller cabinet drawers workshop storage',
      specs: {
        Drawers: 'Seven, ball-bearing slides',
        Lock: 'Central locking',
        Castors: 'Four, two braked',
        Liner: 'EVA drawer liners',
        Finish: 'Powder coated steel',
      },
      facets: ['Lock', 'Finish'],
      axes: [
        ['external_dimensions', ['680 mm wide', '900 mm wide']],
        ['colour', ['Blue', 'Red', 'Graphite']],
      ],
      price: [18_500_00, 46_000_00],
      stock: [2, 22],
      moq: 1,
      grams: 62_000,
      leadDays: 7,
      featured: true,
    },
    {
      key: 'tool-stor-toolbox',
      type: 'Cantilever tool box',
      title: 'Cantilever Tool Box with Metal Latches',
      brand: BRANDS.tools,
      short:
        'Three-tier cantilever tool box in impact-resistant polypropylene with metal latches.',
      long: 'A cantilever tool box whose trays swing out on steel linkages as the lid opens, so everything is visible at once. The shell is impact-resistant polypropylene, the latches are metal rather than moulded, and the handle folds flat.',
      img: 'cantilever tool box plastic storage',
      specs: {
        Tiers: 'Three cantilever trays',
        Shell: 'Impact-resistant polypropylene',
        Latches: 'Metal',
        Handle: 'Folding',
      },
      facets: ['Shell', 'Latches'],
      axes: [
        ['external_dimensions', ['460 mm', '560 mm']],
        ['colour', ['Black', 'Red']],
      ],
      price: [1_680_00, 4_200_00],
      stock: [8, 110],
      moq: 1,
      grams: 3_200,
    },
    {
      key: 'tool-stor-bin',
      type: 'Parts storage bin rack',
      title: 'Louvre Panel with Stacking Parts Bins',
      brand: BRANDS.tools,
      short:
        'Wall-mounted louvre panel supplied with a set of stacking open-fronted parts bins.',
      long: 'A steel louvre panel that mounts to a wall or a rack upright, with a set of open-fronted polypropylene bins that hook onto the louvres. The bins can be moved along the panel without tools and carry a card slot on the front.',
      img: 'parts storage bins louvre panel workshop',
      specs: {
        Panel: 'Powder-coated steel louvre',
        Bins: 'Open fronted polypropylene with card slot',
        Mounting: 'Wall or rack upright',
      },
      facets: ['Panel', 'Mounting'],
      axes: [
        ['capacity', ['12 bins', '24 bins', '36 bins']],
        ['colour', ['Blue', 'Red', 'Yellow']],
      ],
      price: [2_400_00, 9_600_00],
      stock: [5, 60],
      moq: 1,
      grams: 8_400,
      mrp: 0.13,
    },
  ]),
];
