/**
 * Building & Construction, Automotive & Transport, Agriculture & Gardening,
 * Food Service & Catering.
 *
 * Seventeen shelves, three products each.
 *
 * TWO DELIBERATE OMISSIONS
 *
 * **No vehicle make or model is named.** The `vehicle_make`, `vehicle_model`
 * and `year_range` axes exist in the template and are exactly right for a
 * genuine parts seller, who knows what their part fits. This catalogue does
 * not, and a fabricated fitment is the one error in a parts catalogue that
 * ends with somebody's wheel coming off. So these blueprints describe the part
 * and leave fitment to whoever lists a real one.
 *
 * **No organic or provenance claim.** "Organic", "single origin" and "grown
 * without pesticides" are certifications and audit trails, not adjectives. The
 * `organic_status` axis is left unused here for the same reason the safety
 * department leaves its conformity axes unused.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const TRADE_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // BUILDING & CONSTRUCTION
  // =======================================================================
  shelf('building-materials', [
    {
      key: 'bld-mat-plywood',
      type: 'Structural plywood sheet',
      title: 'Exterior Grade Plywood Sheet, Hardwood Faced',
      brand: BRANDS.building,
      short:
        'Exterior grade hardwood-faced plywood sheet with a weather and boil proof glue line.',
      long: 'An exterior grade plywood sheet with hardwood faces and a weather and boil proof glue line, for hoardings, site boxes and formwork. The edges are sealed at the mill and the face is sanded on both sides.',
      img: 'plywood sheets construction building materials',
      specs: {
        Faces: 'Hardwood, sanded both sides',
        Glue: 'Weather and boil proof',
        Edges: 'Mill sealed',
        'Sheet size': '2440 x 1220 mm',
      },
      facets: ['Glue', 'Faces'],
      axes: [
        ['thickness', ['9 mm', '12 mm', '18 mm', '25 mm']],
        ['sale_unit', ['Per sheet', 'Pack of 5 sheets']],
      ],
      price: [1_680_00, 14_800_00],
      stock: [5, 90],
      moq: 1,
      grams: 28_000,
      featured: true,
    },
    {
      key: 'bld-mat-cementboard',
      type: 'Fibre cement board',
      title: 'Fibre Cement Board for Wet Areas',
      brand: BRANDS.building,
      short:
        'Fibre cement board for wet areas, cut with a scoring knife and fixed with standard screws.',
      long: 'A fibre cement board for wet-area linings, which scores and snaps rather than needing a saw, and takes a standard board screw. It does not soften if it gets wet before the tiling goes on.',
      img: 'cement board construction material sheet',
      specs: {
        Composition: 'Fibre cement',
        Cutting: 'Score and snap',
        Fixing: 'Standard board screws',
        'Sheet size': '1200 x 800 mm',
      },
      facets: ['Composition', 'Cutting'],
      axes: [
        ['thickness', ['6 mm', '9 mm', '12 mm']],
        ['sale_unit', ['Per board', 'Pallet of 40']],
      ],
      price: [980_000, 48_000_00],
      stock: [4, 70],
      moq: 1,
      grams: 14_000,
      leadDays: 3,
    },
    {
      key: 'bld-mat-insulation',
      type: 'Insulation slab',
      title: 'Mineral Wool Insulation Slab, Friction Fit',
      brand: BRANDS.building,
      short:
        'Mineral wool insulation slab sized for a friction fit between standard stud centres.',
      long: 'A mineral wool insulation slab cut to sit by friction between standard stud centres, so it stays where it is put without a fixing. Supplied compressed in a polythene wrap that expands on opening.',
      img: 'mineral wool insulation slabs building',
      specs: {
        Material: 'Mineral wool',
        Fit: 'Friction fit between standard stud centres',
        Packaging: 'Compressed polythene wrap',
        'Slab size': '1200 x 600 mm',
      },
      facets: ['Material', 'Fit'],
      axes: [
        ['thickness', ['50 mm', '75 mm', '100 mm']],
        ['sale_unit', ['Per pack', 'Pallet']],
      ],
      price: [680_000, 32_000_00],
      stock: [5, 80],
      moq: 1,
      grams: 9_600,
      mrp: 0.11,
    },
  ]),

  shelf('plumbing-sanitary', [
    {
      key: 'bld-plumb-pushfit',
      type: 'Push-fit pipe fitting',
      title: 'Push-Fit Plumbing Fitting with Demountable Collet',
      brand: BRANDS.plumbing,
      short:
        'Push-fit plumbing fitting with a demountable collet, so a joint can be taken apart and remade.',
      long: 'A push-fit plumbing fitting with a collet that can be released with a plastic tool and the joint remade, rather than a fitting that has to be cut out. The O-ring is retained in a groove and the body takes both copper and plastic pipe.',
      img: 'push fit plumbing fittings pipe',
      specs: {
        Joint: 'Push fit with demountable collet',
        Pipe: 'Copper and plastic',
        Seal: 'Retained O-ring',
      },
      facets: ['Joint', 'Pipe'],
      axes: [
        ['component_type', ['Straight coupler', 'Elbow', 'Tee', 'Stop end']],
        ['nominal_size', ['15 mm', '22 mm', '28 mm']],
        ['pack_count', ['Single', 'Bag of 10']],
      ],
      price: [12_000, 320_000],
      stock: [25, 420],
      moq: 1,
      grams: 60,
      featured: true,
    },
    {
      key: 'bld-plumb-tap',
      type: 'Mixer tap',
      title: 'Single-Lever Basin Mixer Tap with Ceramic Cartridge',
      brand: BRANDS.plumbing,
      short:
        'Single-lever basin mixer with a ceramic disc cartridge and flexible tails fitted.',
      long: 'A single-lever basin mixer with a ceramic disc cartridge, which is what gives a quarter-turn action that does not drip as a washer would. Flexible tails are already fitted and the aerator unscrews for cleaning.',
      img: 'basin mixer tap chrome bathroom',
      specs: {
        Cartridge: 'Ceramic disc',
        Tails: 'Flexible, fitted',
        Aerator: 'Removable for cleaning',
        Body: 'Brass',
      },
      facets: ['Cartridge', 'Body'],
      axes: [
        ['finish', ['Chrome', 'Brushed nickel', 'Matt black']],
        ['component_type', ['Basin mixer', 'Bath filler']],
      ],
      price: [1_480_00, 9_800_00],
      stock: [5, 80],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'bld-plumb-trap',
      type: 'Waste trap',
      title: 'Bottle Trap with Removable Cup for Cleaning',
      brand: BRANDS.plumbing,
      short:
        'Bottle trap with a removable cup and an adjustable inlet height.',
      long: 'A bottle trap whose cup unscrews so it can be emptied without breaking the pipe joints, and whose inlet height adjusts to suit the waste outlet. The seals are moulded rather than washers that fall out during assembly.',
      img: 'bottle trap waste plumbing fitting',
      specs: {
        Cup: 'Removable for cleaning',
        Inlet: 'Adjustable height',
        Seals: 'Moulded, captive',
      },
      facets: ['Cup', 'Inlet'],
      axes: [
        ['nominal_size', ['32 mm', '40 mm']],
        ['finish', ['White', 'Chrome']],
      ],
      price: [180_000, 980_000],
      stock: [15, 240],
      moq: 1,
      grams: 320,
      mrp: 0.13,
    },
  ]),

  shelf('heating-ventilation-cooling', [
    {
      key: 'bld-hvac-splitac',
      type: 'Split air conditioner',
      title: 'Inverter Split Air Conditioner with Wall Unit',
      brand: BRANDS.plumbing,
      short:
        'Inverter split air conditioner with a wall-mounted indoor unit and a washable filter.',
      long: 'An inverter split air conditioner with a wall-mounted indoor unit, a washable pre-filter behind a hinged front and a remote with a weekly timer. The inverter compressor holds a temperature rather than cycling on and off.',
      img: 'split air conditioner wall unit hvac',
      specs: {
        Compressor: 'Inverter',
        Filter: 'Washable pre-filter, hinged front',
        Control: 'Remote with weekly timer',
        Installation: 'Requires a competent installer',
      },
      facets: ['Compressor', 'Filter'],
      axes: [
        ['capacity', ['1.0 ton', '1.5 ton', '2.0 ton']],
        ['voltage', ['230 V']],
      ],
      price: [28_000_00, 62_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 42_000,
      leadDays: 7,
      featured: true,
    },
    {
      key: 'bld-hvac-extractfan',
      type: 'Extract fan',
      title: 'Inline Extract Fan with Backdraught Shutter',
      brand: BRANDS.plumbing,
      short:
        'Inline duct extract fan with a backdraught shutter and a serviceable motor cartridge.',
      long: 'An inline duct extract fan with a backdraught shutter, so cold air is not drawn back down the duct when it is off. The motor is a cartridge that lifts out of the housing without disturbing the ductwork.',
      img: 'inline extract fan ventilation duct',
      specs: {
        Shutter: 'Backdraught shutter',
        Motor: 'Removable cartridge',
        Mounting: 'Inline in duct',
      },
      facets: ['Shutter', 'Motor'],
      axes: [
        ['dimensions', ['100 mm duct', '125 mm duct', '150 mm duct']],
        ['capacity', ['Standard', 'High flow']],
      ],
      price: [980_000, 4_800_000],
      stock: [6, 100],
      moq: 1,
      grams: 1_200,
    },
    {
      key: 'bld-hvac-radiator',
      type: 'Panel radiator',
      title: 'Double Panel Steel Radiator with Fitting Pack',
      brand: BRANDS.plumbing,
      short:
        'Double panel steel radiator supplied with brackets, plugs and an air vent.',
      long: 'A double panel steel radiator with convector fins, supplied with wall brackets, a blanking plug and an air vent in the box. The finish is a baked white and the top grille and side panels are fitted.',
      img: 'panel radiator heating steel white',
      specs: {
        Construction: 'Double panel with convector fins',
        Supplied: 'Brackets, blanking plug and air vent',
        Finish: 'Baked white',
        Grilles: 'Top grille and side panels fitted',
      },
      facets: ['Construction', 'Finish'],
      axes: [
        ['dimensions', ['600 x 800 mm', '600 x 1200 mm', '600 x 1600 mm']],
        ['capacity', ['Type 21', 'Type 22']],
      ],
      price: [2_400_00, 9_800_00],
      stock: [4, 60],
      moq: 1,
      grams: 24_000,
      mrp: 0.12,
    },
  ]),

  shelf('paint-surface-finishing', [
    {
      key: 'bld-paint-emulsion',
      type: 'Interior emulsion paint',
      title: 'Matt Interior Emulsion Paint, Low Odour',
      brand: BRANDS.building,
      short:
        'Low-odour matt interior emulsion with the coverage per litre printed on the tin.',
      long: 'A low-odour matt interior emulsion with the coverage per litre printed on the tin rather than only in a brochure. It touches in without flashing, which is what matters on a wall that gets marked, and recoats in four hours.',
      img: 'interior emulsion paint tin white',
      specs: {
        Finish: 'Matt',
        Odour: 'Low odour, water based',
        Coverage: 'Printed on tin',
        Recoat: 'Four hours',
      },
      facets: ['Finish', 'Odour'],
      axes: [
        ['net_volume', ['2.5 L', '5 L', '10 L']],
        ['colour', ['Brilliant white', 'Magnolia', 'Soft grey']],
      ],
      price: [420_000, 2_800_000],
      stock: [10, 180],
      moq: 1,
      grams: 6_400,
      sold: { content: [5, 'L'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'bld-paint-metal',
      type: 'Metal paint',
      title: 'Direct-to-Metal Paint with Rust Inhibitor',
      brand: BRANDS.building,
      short:
        'Direct-to-metal paint with a rust inhibitor, applied over sound rust without a primer.',
      long: 'A direct-to-metal paint carrying a rust inhibitor, so it goes over sound rust without a separate primer coat. It brushes, rolls or sprays and is touch dry in two hours.',
      img: 'metal paint tin rust protection',
      specs: {
        Use: 'Direct to metal, over sound rust',
        Inhibitor: 'Rust inhibiting pigment',
        Application: 'Brush, roller or spray',
        'Touch dry': 'Two hours',
      },
      facets: ['Use', 'Application'],
      axes: [
        ['net_volume', ['750 ml', '2.5 L', '5 L']],
        ['finish', ['Gloss', 'Satin', 'Hammered']],
        ['colour', ['Black', 'Dark grey', 'Green']],
      ],
      price: [280_000, 2_400_000],
      stock: [10, 160],
      moq: 1,
      grams: 3_200,
      sold: { content: [2.5, 'L'], per: [1, 'L'] },
    },
    {
      key: 'bld-paint-rollerset',
      type: 'Paint roller set',
      title: 'Paint Roller Set with Tray, Frame and Sleeves',
      brand: BRANDS.building,
      short:
        'Paint roller set with a cage frame, a ribbed tray and two microfibre sleeves.',
      long: 'A roller set with a cage frame that takes a standard sleeve, a ribbed tray that lets the sleeve be worked out evenly, and two microfibre sleeves. The frame handle takes an extension pole thread.',
      img: 'paint roller set tray decorating tools',
      specs: {
        Frame: 'Cage frame, extension pole thread',
        Tray: 'Ribbed',
        Sleeves: 'Two microfibre',
      },
      facets: ['Frame', 'Sleeves'],
      axes: [
        ['product_type', ['9 in set', '12 in set']],
        ['application_method', ['Smooth surfaces', 'Textured surfaces']],
      ],
      price: [180_000, 980_000],
      stock: [15, 260],
      moq: 1,
      grams: 900,
      mrp: 0.15,
    },
  ]),

  shelf('doors-windows-ironmongery', [
    {
      key: 'bld-iron-lever',
      type: 'Door lever handle',
      title: 'Door Lever Handle on a Rose with Concealed Fixings',
      brand: BRANDS.ironmongery,
      short:
        'Door lever handle on a round rose with concealed fixings and a sprung mechanism.',
      long: 'A door lever on a round rose with concealed fixings, so no screw heads are visible on the face. The rose contains a spring, which is what keeps the lever horizontal rather than sagging over time, and a bolt-through fixing is supplied.',
      img: 'door lever handle ironmongery hardware',
      specs: {
        Rose: 'Round, concealed fixings',
        Mechanism: 'Sprung rose',
        Fixing: 'Bolt-through supplied',
        Spindle: '8 mm',
      },
      facets: ['Rose', 'Mechanism'],
      axes: [
        ['finish', ['Satin stainless', 'Polished chrome', 'Matt black', 'Antique brass']],
        ['pack_count', ['Pair', 'Trade pack of 5 pairs']],
      ],
      price: [280_000, 2_400_000],
      stock: [12, 220],
      moq: 1,
      grams: 640,
      featured: true,
    },
    {
      key: 'bld-iron-hinge',
      type: 'Butt hinge',
      title: 'Ball-Bearing Butt Hinge in Stainless Steel',
      brand: BRANDS.ironmongery,
      short:
        'Stainless steel ball-bearing butt hinge with countersunk holes and matching screws.',
      long: 'A stainless steel butt hinge with ball races between the knuckles, so a heavy door swings without the squeak and wear a plain knuckle develops. Countersunk holes and matching screws are supplied.',
      img: 'stainless steel door hinges hardware',
      specs: {
        Bearings: 'Ball races between knuckles',
        Material: 'Stainless steel',
        Holes: 'Countersunk, screws supplied',
      },
      facets: ['Bearings', 'Material'],
      axes: [
        ['dimensions', ['76 mm', '100 mm']],
        ['pack_count', ['Pair', 'Box of 10 pairs']],
      ],
      price: [96_000, 780_000],
      stock: [15, 260],
      moq: 1,
      grams: 380,
    },
    {
      key: 'bld-iron-closer',
      type: 'Overhead door closer',
      title: 'Adjustable Overhead Door Closer with Backcheck',
      brand: BRANDS.ironmongery,
      short:
        'Overhead door closer with adjustable power, latch speed and backcheck.',
      long: 'An overhead door closer with independent adjustment of closing speed, latch speed and backcheck, all on valves under a cover. It can be fitted to either hand of door and the arm is supplied.',
      img: 'door closer overhead ironmongery hardware',
      specs: {
        Adjustment: 'Closing speed, latch speed and backcheck',
        Handing: 'Either hand',
        Arm: 'Standard arm supplied',
        Cover: 'Slip-on cover',
      },
      facets: ['Adjustment', 'Handing'],
      axes: [
        ['product_type', ['Power size 2-4', 'Power size 3-6']],
        ['finish', ['Silver', 'Matt black']],
      ],
      price: [980_000, 3_800_000],
      stock: [8, 140],
      moq: 1,
      grams: 2_600,
      mrp: 0.12,
    },
  ]),

  // =======================================================================
  // AUTOMOTIVE & TRANSPORT
  // =======================================================================
  shelf('vehicle-parts', [
    {
      key: 'auto-part-airfilter',
      type: 'Engine air filter',
      title: 'Panel Engine Air Filter with Moulded Seal',
      brand: BRANDS.automotive,
      short:
        'Panel engine air filter with a pleated media and a moulded polyurethane seal.',
      long: 'A panel engine air filter with a pleated media on a wire support and a moulded polyurethane seal round the edge, so it beds into the housing without a separate gasket. The pleat count and the frame dimensions are printed on the filter.',
      img: 'engine air filter automotive part',
      specs: {
        Media: 'Pleated, wire supported',
        Seal: 'Moulded polyurethane',
        Marking: 'Dimensions printed on the frame',
      },
      facets: ['Media', 'Seal'],
      axes: [
        ['part_type', ['Panel filter']],
        ['pack_count', ['Single', 'Trade pack of 10']],
      ],
      price: [280_000, 2_400_000],
      stock: [12, 220],
      moq: 1,
      grams: 380,
      featured: true,
    },
    {
      key: 'auto-part-brakepad',
      type: 'Brake pad set',
      title: 'Ceramic Brake Pad Set with Shims and Grease',
      brand: BRANDS.automotive,
      short:
        'Ceramic brake pad set supplied with shims, a wear sensor clip and a sachet of grease.',
      long: 'A ceramic brake pad set supplied with the shims, the anti-rattle clips and a sachet of caliper grease, so the fitting is complete from one box. The friction material is chamfered and slotted at the factory.',
      img: 'brake pads automotive parts set',
      specs: {
        Friction: 'Ceramic',
        Supplied: 'Shims, clips and grease sachet',
        Preparation: 'Chamfered and slotted',
      },
      facets: ['Friction', 'Supplied'],
      axes: [
        ['position', ['Front axle', 'Rear axle']],
        ['pack_count', ['Axle set', 'Pair of axle sets']],
      ],
      price: [980_000, 5_400_000],
      stock: [8, 140],
      moq: 1,
      grams: 2_400,
    },
    {
      key: 'auto-part-wiper',
      type: 'Wiper blade',
      title: 'Flat Wiper Blade with Multi-Fit Adapter Set',
      brand: BRANDS.automotive,
      short:
        'Flat wiper blade supplied with a set of adapters for the common arm fittings.',
      long: 'A flat wiper blade with a graphite-coated rubber and an integrated spoiler, supplied with a set of adapters covering the common arm fittings. The adapters clip on rather than needing a tool.',
      img: 'windscreen wiper blades automotive',
      specs: {
        Construction: 'Flat blade with integrated spoiler',
        Rubber: 'Graphite coated',
        Adapters: 'Multi-fit set supplied, clip on',
      },
      facets: ['Construction', 'Adapters'],
      axes: [
        ['part_type', ['400 mm', '480 mm', '550 mm', '650 mm']],
        ['pack_count', ['Single', 'Pair']],
      ],
      price: [280_000, 1_280_000],
      stock: [15, 260],
      moq: 1,
      grams: 260,
      mrp: 0.14,
    },
  ]),

  shelf('tyres-wheels', [
    {
      key: 'auto-tyre-passenger',
      type: 'Passenger car tyre',
      title: 'Tubeless Passenger Car Tyre with Asymmetric Tread',
      brand: BRANDS.automotive,
      short:
        'Tubeless radial passenger car tyre with an asymmetric tread and a moulded rim protector.',
      long: 'A tubeless radial passenger car tyre with an asymmetric tread pattern, a moulded rim protector rib and the date code on the sidewall. The outside face is marked so it cannot be fitted the wrong way round.',
      img: 'car tyre automotive wheel rubber',
      specs: {
        Construction: 'Tubeless radial',
        Tread: 'Asymmetric, outside face marked',
        Sidewall: 'Rim protector rib and date code',
      },
      facets: ['Construction', 'Tread'],
      axes: [
        ['rim_diameter', ['R14', 'R15', 'R16']],
        ['section_width', ['175', '185', '195', '205']],
        ['pack_count', ['Single', 'Set of 4']],
      ],
      price: [3_400_00, 42_000_00],
      stock: [4, 70],
      moq: 1,
      grams: 8_600,
      featured: true,
    },
    {
      key: 'auto-tyre-steelwheel',
      type: 'Steel wheel rim',
      title: 'Steel Wheel Rim with Powder-Coated Finish',
      brand: BRANDS.automotive,
      short:
        'Powder-coated steel wheel rim supplied with a centre cap and a balance-weight-ready flange.',
      long: 'A powder-coated steel wheel rim with a clean flange for balance weights and a centre cap supplied. Steel rather than alloy because a steel rim bends where an alloy cracks, which is why they are what a winter set is usually built on.',
      img: 'steel wheel rim automotive black',
      specs: {
        Material: 'Pressed steel',
        Finish: 'Powder coated',
        Supplied: 'Centre cap included',
      },
      facets: ['Material', 'Finish'],
      axes: [
        ['rim_diameter', ['14 in', '15 in', '16 in']],
        ['wheel_width', ['5.5J', '6.0J', '6.5J']],
      ],
      price: [1_680_00, 6_800_00],
      stock: [6, 90],
      moq: 1,
      grams: 8_200,
    },
    {
      key: 'auto-tyre-valve',
      type: 'Tyre valve',
      title: 'Snap-In Rubber Tyre Valve with Chrome Cap',
      brand: BRANDS.automotive,
      short:
        'Snap-in rubber tyre valve with a brass insert and a chrome-plated dust cap.',
      long: 'A snap-in rubber tyre valve with a brass insert and a chrome-plated dust cap with a seal in it. Supplied in bulk bags for a tyre bay rather than singly.',
      img: 'tyre valves automotive rubber parts',
      specs: {
        Type: 'Snap-in rubber',
        Insert: 'Brass',
        Cap: 'Chrome plated with seal',
      },
      facets: ['Type', 'Insert'],
      axes: [
        ['tyre_size', ['TR413', 'TR414']],
        ['pack_count', ['Bag of 100', 'Box of 500']],
      ],
      price: [96_000, 420_000],
      stock: [15, 240],
      moq: 1,
      grams: 900,
      sold: { content: [100, 'piece'], label: 'Bag of 100' },
      multipack: 100,
      mrp: 0.15,
    },
  ]),

  shelf('garage-equipment', [
    {
      key: 'auto-gar-trolleyjack',
      type: 'Trolley jack',
      title: 'Low-Profile Trolley Jack with Dual Pump',
      brand: BRANDS.automotive,
      short:
        'Low-profile hydraulic trolley jack with a dual pump, a rubber saddle pad and a safety valve.',
      long: 'A low-profile hydraulic trolley jack with a dual pump that reaches the load in fewer strokes. The saddle carries a rubber pad, the release is on a twist handle and an overload safety valve stops the pump above the rated capacity.',
      img: 'trolley jack garage equipment automotive',
      specs: {
        Profile: 'Low profile',
        Pump: 'Dual pump',
        Saddle: 'Rubber pad',
        Safety: 'Overload safety valve',
      },
      facets: ['Profile', 'Safety'],
      axes: [
        ['load_capacity', ['2 tonne', '3 tonne']],
        ['kit_contents', ['Jack only', 'Jack with axle stands']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [3, 48],
      moq: 1,
      grams: 32_000,
      featured: true,
    },
    {
      key: 'auto-gar-compressor',
      type: 'Air compressor',
      title: 'Belt-Driven Air Compressor with Cast Iron Pump',
      brand: BRANDS.automotive,
      short:
        'Belt-driven air compressor with a cast iron pump, a receiver drain and a pressure switch.',
      long: 'A belt-driven air compressor with a cast iron pump, which runs slower and cooler than a direct-drive unit and is rebuildable. The receiver has a drain at its lowest point and the pressure switch has an unloader.',
      img: 'air compressor garage equipment workshop',
      specs: {
        Drive: 'Belt driven',
        Pump: 'Cast iron, rebuildable',
        Receiver: 'Drain at lowest point',
        Switch: 'Pressure switch with unloader',
      },
      facets: ['Drive', 'Pump'],
      axes: [
        ['load_capacity', ['50 L', '100 L', '200 L']],
        ['voltage', ['230 V', '415 V']],
      ],
      price: [24_000_00, 96_000_00],
      stock: [1, 22],
      moq: 1,
      grams: 78_000,
      leadDays: 10,
    },
    {
      key: 'auto-gar-creeper',
      type: 'Garage creeper',
      title: 'Padded Garage Creeper with Recessed Castors',
      brand: BRANDS.automotive,
      short:
        'Padded garage creeper on recessed castors, with a contoured headrest.',
      long: 'A padded garage creeper with the castors recessed into the frame, so the deck sits low and clears an exhaust. The headrest is contoured and the padding is a wipe-clean vinyl over foam.',
      img: 'garage creeper mechanic equipment',
      specs: {
        Castors: 'Recessed into frame',
        Padding: 'Wipe-clean vinyl over foam',
        Headrest: 'Contoured',
      },
      facets: ['Castors', 'Padding'],
      axes: [
        ['dimensions', ['1,000 mm', '1,050 mm']],
        ['operation', ['Fixed', 'Folding to a seat']],
      ],
      price: [2_400_00, 8_400_00],
      stock: [4, 60],
      moq: 1,
      grams: 8_600,
      mrp: 0.13,
    },
  ]),

  shelf('vehicle-care', [
    {
      key: 'auto-care-shampoo',
      type: 'Car shampoo',
      title: 'pH-Neutral Car Shampoo with High Foam',
      brand: BRANDS.carcare,
      short:
        'pH-neutral high-foam car shampoo that does not strip an existing wax layer.',
      long: 'A pH-neutral car shampoo that foams heavily and rinses clean, and does not strip an existing wax or sealant the way a detergent does. The dilution is printed on the bottle in capfuls as well as in millilitres.',
      img: 'car shampoo bottle vehicle care',
      specs: {
        'pH type': 'Neutral',
        Foam: 'High foam',
        Effect: 'Does not strip existing wax or sealant',
        Dilution: 'Printed in capfuls and millilitres',
      },
      facets: ['pH type', 'Foam'],
      axes: [
        ['net_volume', ['1 L', '5 L']],
        ['fragrance', ['Unfragranced', 'Cherry']],
      ],
      price: [46_000, 420_000],
      stock: [15, 260],
      moq: 1,
      grams: 1_100,
      sold: { content: [1, 'L'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'auto-care-microfibre',
      type: 'Microfibre cloth',
      title: 'Edgeless Microfibre Cloth in a Multi-Pack',
      brand: BRANDS.carcare,
      short:
        'Edgeless microfibre cloth with a laser-cut border, in a colour-coded multi-pack.',
      long: 'An edgeless microfibre cloth with a laser-cut border rather than a stitched one, so there is no seam to drag across a panel. Supplied in a colour-coded pack, which is what keeps a wheel cloth away from a paintwork cloth.',
      img: 'microfibre cloths car cleaning pack',
      specs: {
        Edge: 'Laser cut, edgeless',
        Pack: 'Colour coded',
        Wash: 'Machine washable at 40 C',
      },
      facets: ['Edge', 'Pack'],
      axes: [
        ['product_type', ['Buffing cloth', 'Drying towel', 'Wheel cloth']],
        ['pack_count', ['Pack of 5', 'Pack of 10']],
      ],
      price: [38_000, 280_000],
      stock: [20, 340],
      moq: 1,
      grams: 320,
      sold: { content: [5, 'piece'], label: 'Pack of 5' },
      multipack: 5,
    },
    {
      key: 'auto-care-tyredressing',
      type: 'Tyre dressing',
      title: 'Water-Based Tyre Dressing with Applicator',
      brand: BRANDS.carcare,
      short:
        'Water-based tyre dressing supplied with a foam applicator, for a satin rather than a wet finish.',
      long: 'A water-based tyre dressing that leaves a satin finish instead of the wet-look gloss a solvent dressing gives, and does not sling onto the paintwork as it dries. A foam applicator is supplied in the pack.',
      img: 'tyre dressing bottle car care',
      specs: {
        Base: 'Water based',
        Finish: 'Satin',
        Applicator: 'Foam applicator supplied',
      },
      facets: ['Base', 'Finish'],
      axes: [
        ['net_volume', ['500 ml', '1 L']],
        ['applicator', ['With applicator', 'Refill only']],
      ],
      price: [46_000, 320_000],
      stock: [15, 260],
      moq: 1,
      grams: 620,
      sold: { content: [500, 'ml'], per: [1, 'L'] },
      mrp: 0.14,
    },
  ]),

  // =======================================================================
  // AGRICULTURE & GARDENING
  // =======================================================================
  shelf('farm-equipment', [
    {
      key: 'agri-farm-sprayer',
      type: 'Knapsack sprayer',
      title: 'Battery Knapsack Sprayer with Adjustable Pressure',
      brand: BRANDS.agri,
      short:
        'Battery knapsack sprayer with adjustable pressure, padded straps and a lance with three nozzles.',
      long: 'A battery knapsack sprayer with a pressure dial rather than a single setting, padded shoulder straps and a waist belt, and a lance supplied with three nozzles. The tank has a moulded filter in the filler neck.',
      img: 'knapsack sprayer agriculture equipment',
      specs: {
        Power: 'Rechargeable battery',
        Pressure: 'Adjustable dial',
        Harness: 'Padded straps and waist belt',
        Nozzles: 'Three supplied with the lance',
      },
      facets: ['Power', 'Pressure'],
      axes: [
        ['tank_capacity', ['12 L', '16 L', '20 L']],
        ['power_source', ['Battery', 'Manual lever']],
      ],
      price: [2_800_00, 11_400_00],
      stock: [5, 80],
      moq: 1,
      grams: 5_400,
      featured: true,
    },
    {
      key: 'agri-farm-chaffcutter',
      type: 'Chaff cutter',
      title: 'Motorised Chaff Cutter with Guarded Feed',
      brand: BRANDS.agri,
      short:
        'Motorised chaff cutter with a guarded feed throat, adjustable blades and a hopper.',
      long: 'A motorised chaff cutter with a guarded feed throat and an adjustable blade clearance, on a welded steel frame. The blades are reversible and the discharge can be turned to either side.',
      img: 'chaff cutter farm machinery agriculture',
      specs: {
        Feed: 'Guarded throat with hopper',
        Blades: 'Reversible, adjustable clearance',
        Frame: 'Welded steel',
        Discharge: 'Turns to either side',
      },
      facets: ['Feed', 'Blades'],
      axes: [
        ['power', ['1 hp', '2 hp', '3 hp']],
        ['power_source', ['Electric motor', 'Without motor']],
      ],
      price: [18_500_00, 52_000_00],
      stock: [1, 20],
      moq: 1,
      grams: 62_000,
      leadDays: 10,
    },
    {
      key: 'agri-farm-cultivator',
      type: 'Hand cultivator',
      title: 'Wheel Hoe Cultivator with Interchangeable Tines',
      brand: BRANDS.agri,
      short:
        'Wheel hoe cultivator with interchangeable tines and an adjustable handle height.',
      long: 'A wheel hoe cultivator with a tool bar that takes interchangeable tines, sweeps and a plough body. The handle height adjusts and the wheel can be set forward or back to change the angle of attack.',
      img: 'wheel hoe cultivator garden farm tool',
      specs: {
        'Tool bar': 'Interchangeable tines, sweeps and plough body',
        Handle: 'Adjustable height',
        Wheel: 'Adjustable position',
      },
      facets: ['Tool bar', 'Handle'],
      axes: [
        ['working_width', ['300 mm', '450 mm']],
        ['attachments', ['Tines only', 'Tines, sweeps and plough']],
      ],
      price: [4_200_00, 14_800_00],
      stock: [3, 48],
      moq: 1,
      grams: 12_000,
      mrp: 0.12,
    },
  ]),

  shelf('irrigation', [
    {
      key: 'agri-irr-driptape',
      type: 'Drip irrigation tape',
      title: 'Inline Drip Irrigation Tape with Pressure-Compensating Emitters',
      brand: BRANDS.agri,
      short:
        'Inline drip tape with pressure-compensating emitters at a fixed spacing, on a coil.',
      long: 'An inline drip tape with pressure-compensating emitters moulded into the wall at a fixed spacing, so the last emitter on a long run delivers what the first does. UV stabilised for the season it is laid in.',
      img: 'drip irrigation tape agriculture water',
      specs: {
        Emitters: 'Pressure compensating, inline',
        Stabilisation: 'UV stabilised',
        Supply: 'Coiled',
      },
      facets: ['Emitters', 'Stabilisation'],
      axes: [
        ['diameter', ['16 mm']],
        ['spacing', ['200 mm', '300 mm', '400 mm']],
        ['length', ['500 m', '1,000 m']],
      ],
      price: [2_800_00, 14_800_00],
      stock: [4, 70],
      moq: 1,
      grams: 22_000,
      sold: { content: [1000, 'm'], per: [1, 'm'] },
      featured: true,
    },
    {
      key: 'agri-irr-sprinkler',
      type: 'Impact sprinkler',
      title: 'Brass Impact Sprinkler with Adjustable Arc',
      brand: BRANDS.agri,
      short:
        'Brass impact sprinkler with an adjustable arc and a replaceable nozzle.',
      long: 'A brass impact sprinkler with a collar that sets the arc anywhere from a segment to a full circle, and a nozzle that unscrews so the throw can be changed without replacing the sprinkler.',
      img: 'impact sprinkler irrigation brass garden',
      specs: {
        Body: 'Brass',
        Arc: 'Adjustable, segment to full circle',
        Nozzle: 'Replaceable',
      },
      facets: ['Body', 'Arc'],
      axes: [
        ['connection_type', ['1/2 in male', '3/4 in male']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [280_000, 1_680_000],
      stock: [12, 200],
      moq: 1,
      grams: 320,
    },
    {
      key: 'agri-irr-hdpepipe',
      type: 'HDPE irrigation pipe',
      title: 'HDPE Irrigation Pipe Coil with Printed Metre Marks',
      brand: BRANDS.agri,
      short:
        'HDPE irrigation pipe on a coil, with metre marks printed along the wall.',
      long: 'An HDPE irrigation pipe supplied on a coil with metre marks printed along the wall, so a length can be cut without a tape. The pressure class and the manufacturing date are printed alongside them.',
      img: 'hdpe irrigation pipe coil agriculture',
      specs: {
        Material: 'HDPE',
        Marking: 'Metre marks, pressure class and date printed',
        Supply: 'Coiled',
      },
      facets: ['Material', 'Marking'],
      axes: [
        ['diameter', ['20 mm', '25 mm', '32 mm', '50 mm']],
        ['pressure_rating', ['PN6', 'PN10']],
      ],
      price: [1_280_00, 12_800_00],
      stock: [5, 90],
      moq: 1,
      grams: 24_000,
      sold: { content: [100, 'm'], per: [1, 'm'] },
      mrp: 0.11,
    },
  ]),

  shelf('seeds-feed-fertiliser', [
    {
      key: 'agri-seed-vegetable',
      type: 'Vegetable seed',
      title: 'Hybrid Vegetable Seed in a Foil-Sealed Packet',
      brand: BRANDS.seed,
      short:
        'Hybrid vegetable seed in a foil-sealed packet, with the lot and the test date printed on it.',
      long: 'A hybrid vegetable seed in a foil-sealed packet, with the lot number, the germination test date and the packed-for season printed on the packet rather than only on the outer. The foil is what keeps the seed viable through a warm store.',
      img: 'vegetable seeds packet agriculture sowing',
      specs: {
        Packaging: 'Foil sealed',
        Marking: 'Lot number and germination test date on packet',
        Storage: 'Cool and dry, sealed until sowing',
      },
      facets: ['Packaging'],
      axes: [
        ['variety', ['Tomato', 'Chilli', 'Okra', 'Cucumber']],
        ['net_weight', ['10 g', '50 g', '250 g']],
      ],
      price: [46_000, 980_000],
      stock: [20, 320],
      moq: 1,
      grams: 60,
      sold: { content: [50, 'g'], per: [1, 'kg'] },
      featured: true,
    },
    {
      key: 'agri-seed-fertiliser',
      type: 'Compound fertiliser',
      title: 'Granular Compound Fertiliser with Even Prill Size',
      brand: BRANDS.seed,
      short:
        'Granular compound fertiliser with an even prill size, for spreader application.',
      long: 'A granular compound fertiliser screened to an even prill size, which is what makes a spreader throw it evenly instead of separating the fines to one side. Supplied in a moisture-barrier sack with a printed analysis.',
      img: 'fertiliser granules bag agriculture',
      specs: {
        Form: 'Granular, screened prill',
        Sack: 'Moisture barrier',
        Analysis: 'Printed on sack',
      },
      facets: ['Form'],
      axes: [
        ['grade', ['Balanced', 'High nitrogen', 'High potash']],
        ['net_weight', ['5 kg', '25 kg', '50 kg']],
      ],
      price: [180_000, 2_400_000],
      stock: [10, 180],
      moq: 1,
      grams: 25_000,
      sold: { content: [25, 'kg'], per: [1, 'kg'] },
    },
    {
      key: 'agri-seed-cattlefeed',
      type: 'Cattle feed concentrate',
      title: 'Pelleted Cattle Feed Concentrate in a Woven Sack',
      brand: BRANDS.seed,
      short:
        'Pelleted cattle feed concentrate in a woven sack, with the feeding rate printed on the label.',
      long: 'A pelleted cattle feed concentrate in a laminated woven sack, with the feeding rate and the ingredient declaration printed on the label. The pellet is firm enough not to break down to dust in transit.',
      img: 'cattle feed pellets sack agriculture',
      specs: {
        Form: 'Pelleted',
        Sack: 'Laminated woven',
        Label: 'Feeding rate and ingredient declaration',
      },
      facets: ['Form'],
      axes: [
        ['grade', ['Maintenance', 'Production']],
        ['net_weight', ['25 kg', '50 kg']],
      ],
      price: [680_000, 2_800_000],
      stock: [8, 160],
      moq: 1,
      grams: 50_000,
      sold: { content: [50, 'kg'], per: [1, 'kg'] },
      mrp: 0.08,
    },
  ]),

  shelf('garden-tools-outdoor', [
    {
      key: 'agri-gard-pruner',
      type: 'Bypass pruning shear',
      title: 'Bypass Pruning Shear with Replaceable Blade',
      brand: BRANDS.agri,
      short:
        'Bypass pruning shear with a replaceable blade, a sap groove and a one-handed lock.',
      long: 'A bypass pruning shear whose blade can be replaced rather than the whole tool, with a sap groove along the cutting edge and a lock that can be worked with the same hand that holds it. The handles are aluminium with a moulded grip.',
      img: 'hand pruning shears garden tool',
      specs: {
        Action: 'Bypass',
        Blade: 'Replaceable, sap groove',
        Lock: 'One-handed',
        Handles: 'Aluminium with moulded grip',
      },
      facets: ['Action', 'Blade'],
      axes: [
        ['size', ['Standard', 'Small hands']],
        ['handle_type', ['Straight', 'Rotating handle']],
      ],
      price: [680_000, 3_400_000],
      stock: [12, 200],
      moq: 1,
      grams: 260,
      featured: true,
    },
    {
      key: 'agri-gard-hose',
      type: 'Garden hose',
      title: 'Reinforced Garden Hose with Anti-Kink Braid',
      brand: BRANDS.agri,
      short:
        'Reinforced garden hose with a knitted braid between the layers, so it does not kink.',
      long: 'A garden hose with a knitted braid between the inner and outer layers, which is what keeps it from kinking and closing off when it is pulled round a corner. Supplied on a card with the internal bore printed on the hose.',
      img: 'garden hose reel watering outdoor',
      specs: {
        Construction: 'Three layer with knitted braid',
        Marking: 'Internal bore printed on hose',
        Fittings: 'Not supplied',
      },
      facets: ['Construction'],
      axes: [
        ['size', ['12.5 mm', '19 mm']],
        ['capacity', ['15 m', '25 m', '50 m']],
      ],
      price: [480_000, 3_800_000],
      stock: [10, 180],
      moq: 1,
      grams: 4_200,
      sold: { content: [25, 'm'], per: [1, 'm'] },
    },
    {
      key: 'agri-gard-hedgetrimmer',
      type: 'Cordless hedge trimmer',
      title: 'Cordless Hedge Trimmer with Dual-Action Blade',
      brand: BRANDS.agri,
      short:
        'Cordless hedge trimmer with a dual-action blade, a two-handed switch and a tip guard.',
      long: 'A cordless hedge trimmer with a dual-action blade, where both blades move and cancel much of the vibration a single-action blade puts through the handles. A two-handed switch is required to run it and the blade tip is guarded.',
      img: 'cordless hedge trimmer garden tool',
      specs: {
        Blade: 'Dual action',
        Switch: 'Two-handed',
        Guard: 'Blade tip guard',
      },
      facets: ['Blade', 'Switch'],
      axes: [
        ['cutting_width', ['450 mm', '550 mm']],
        ['kit_configuration', ['Bare tool', 'With battery and charger']],
      ],
      price: [3_400_00, 12_800_00],
      stock: [4, 60],
      moq: 1,
      grams: 3_400,
      mrp: 0.13,
    },
  ]),

  // =======================================================================
  // FOOD SERVICE & CATERING
  // =======================================================================
  shelf('commercial-kitchen-equipment', [
    {
      key: 'food-kit-stockpot',
      type: 'Commercial stock pot',
      title: 'Stainless Steel Commercial Stock Pot with Sandwich Base',
      brand: BRANDS.catering,
      short:
        'Stainless steel commercial stock pot with an encapsulated sandwich base and riveted handles.',
      long: 'A stainless steel stock pot with an aluminium core encapsulated in the base, which spreads the heat instead of letting it concentrate under the burner. The handles are riveted rather than spot welded, and the rim is rolled.',
      img: 'stainless steel commercial stock pot kitchen',
      specs: {
        Body: 'Stainless steel',
        Base: 'Encapsulated aluminium sandwich',
        Handles: 'Riveted',
        Rim: 'Rolled',
        Induction: 'Induction compatible',
      },
      facets: ['Base', 'Induction'],
      axes: [
        ['capacity', ['12 L', '20 L', '32 L', '50 L']],
        ['configuration', ['Pot only', 'Pot with lid']],
      ],
      price: [2_400_00, 12_800_00],
      stock: [5, 80],
      moq: 1,
      grams: 4_800,
      featured: true,
    },
    {
      key: 'food-kit-convection',
      type: 'Convection oven',
      title: 'Countertop Convection Oven with Steam Injection',
      brand: BRANDS.catering,
      short:
        'Countertop convection oven with steam injection, a double-glazed door and a removable rack set.',
      long: 'A countertop convection oven with a steam injection button, a double-glazed drop-down door and a rack set that lifts out for cleaning. The fan reverses, which is what evens out the browning across a full tray.',
      img: 'commercial convection oven kitchen equipment',
      specs: {
        Fan: 'Reversing',
        Steam: 'Manual steam injection',
        Door: 'Double glazed, drop down',
        Racks: 'Removable rack set',
      },
      facets: ['Fan', 'Steam'],
      axes: [
        ['capacity', ['4 tray', '6 tray']],
        ['voltage', ['230 V', '415 V']],
      ],
      price: [48_000_00, 148_000_00],
      stock: [1, 16],
      moq: 1,
      grams: 62_000,
      leadDays: 14,
    },
    {
      key: 'food-kit-worktable',
      type: 'Stainless steel work table',
      title: 'Stainless Steel Work Table with Undershelf',
      brand: BRANDS.catering,
      short:
        'Stainless steel work table with an undershelf, adjustable feet and a rolled front edge.',
      long: 'A stainless steel work table with an undershelf, adjustable feet for an uneven floor and a rolled front edge so nothing catches on it. The top is braced underneath, which is what stops the drumming a thin unbraced top makes.',
      img: 'stainless steel work table commercial kitchen',
      specs: {
        Top: 'Stainless steel, braced underneath',
        Shelf: 'Undershelf',
        Feet: 'Adjustable',
        Edge: 'Rolled front edge',
      },
      facets: ['Top', 'Shelf'],
      axes: [
        ['dimensions', ['1,200 x 600 mm', '1,500 x 700 mm', '1,800 x 700 mm']],
        ['castors', ['Adjustable feet', 'Castors']],
      ],
      price: [11_400_00, 32_000_00],
      stock: [2, 30],
      moq: 1,
      grams: 28_000,
      leadDays: 7,
      mrp: 0.11,
    },
  ]),

  shelf('tableware-serving', [
    {
      key: 'food-table-plates',
      type: 'Vitrified porcelain plate',
      title: 'Vitrified Porcelain Plate with Rolled Edge',
      brand: BRANDS.tableware,
      short:
        'Vitrified porcelain plate with a rolled edge, for commercial dishwashing and stacking.',
      long: 'A vitrified porcelain plate with a rolled edge, which is the part that chips first and the reason a catering plate is made this way. Fully glazed including the foot, so it does not scratch the plate beneath it in a stack.',
      img: 'white porcelain plates restaurant tableware',
      specs: {
        Body: 'Vitrified porcelain',
        Edge: 'Rolled',
        Glaze: 'Fully glazed including foot',
        'Dishwasher safe': 'Yes, commercial dishwasher',
      },
      facets: ['Body', 'Dishwasher safe'],
      axes: [
        ['size', ['170 mm', '230 mm', '270 mm', '310 mm']],
        ['pack_count', ['Box of 6', 'Case of 24']],
      ],
      price: [280_000, 1_680_000],
      stock: [10, 180],
      moq: 1,
      grams: 4_200,
      sold: { content: [6, 'piece'], label: 'Box of 6' },
      multipack: 6,
      featured: true,
    },
    {
      key: 'food-table-cutlery',
      type: 'Cutlery set',
      title: 'Stainless Steel Cutlery Set with Satin Finish',
      brand: BRANDS.tableware,
      short:
        'Eighteen-ten stainless steel cutlery set with a satin finish and a balanced weight.',
      long: 'An eighteen-ten stainless steel cutlery set with a satin finish, which hides the marks a mirror polish shows after a hundred washes. The handles are weighted so a knife sits balanced in the hand.',
      img: 'stainless steel cutlery set restaurant',
      specs: {
        Steel: '18/10 stainless',
        Finish: 'Satin',
        Balance: 'Weighted handles',
        'Dishwasher safe': 'Yes',
      },
      facets: ['Steel', 'Finish'],
      axes: [
        ['item_type', ['Table knife', 'Table fork', 'Dessert spoon', 'Teaspoon']],
        ['pack_count', ['Box of 12', 'Case of 60']],
      ],
      price: [280_000, 1_980_000],
      stock: [10, 180],
      moq: 1,
      grams: 1_400,
      sold: { content: [12, 'piece'], label: 'Box of 12' },
      multipack: 12,
    },
    {
      key: 'food-table-gastronorm',
      type: 'Gastronorm pan',
      title: 'Stainless Steel Gastronorm Pan with Reinforced Rim',
      brand: BRANDS.catering,
      short:
        'Stainless steel gastronorm pan with a reinforced rim and rounded internal corners.',
      long: 'A stainless steel gastronorm pan on the standard module, with a reinforced rim so it does not distort when it is lifted full, and rounded internal corners so it can actually be cleaned out. Stacks with a lid or with another pan.',
      img: 'gastronorm pans stainless steel catering',
      specs: {
        Standard: 'Gastronorm module',
        Rim: 'Reinforced',
        Corners: 'Rounded internally',
        Stacking: 'Stacks with lid or pan',
      },
      facets: ['Standard', 'Rim'],
      axes: [
        ['size', ['1/1', '1/2', '1/3', '1/6']],
        ['item_type', ['65 mm deep', '100 mm deep', '150 mm deep']],
      ],
      price: [280_000, 1_680_000],
      stock: [12, 200],
      moq: 1,
      grams: 1_100,
      mrp: 0.12,
    },
  ]),

  shelf('disposables-takeaway', [
    {
      key: 'food-disp-container',
      type: 'Takeaway container',
      title: 'Kraft Takeaway Container with a PE Lining',
      brand: BRANDS.tableware,
      short:
        'Kraft board takeaway container with a thin PE lining and a fold-in lid.',
      long: 'A kraft board takeaway container with a thin polyethylene lining so it holds a sauce, and a lid that folds in from the board rather than being a separate piece. Stacks nested and goes in a microwave.',
      img: 'kraft takeaway food containers disposable',
      specs: {
        Board: 'Kraft with PE lining',
        Lid: 'Fold-in from the board',
        'Microwave safe': 'Yes',
        Stacking: 'Nests',
      },
      facets: ['Board', 'Microwave safe'],
      axes: [
        ['capacity', ['500 ml', '750 ml', '1,000 ml']],
        ['pack_count', ['Pack of 50', 'Case of 300']],
      ],
      price: [140_000, 980_000],
      stock: [15, 280],
      moq: 1,
      grams: 2_600,
      sold: { content: [50, 'piece'], label: 'Pack of 50' },
      multipack: 50,
      featured: true,
    },
    {
      key: 'food-disp-cup',
      type: 'Hot drink cup',
      title: 'Double-Wall Hot Drink Cup with Rolled Rim',
      brand: BRANDS.tableware,
      short:
        'Double-wall paper hot drink cup with a rolled rim, so it is held without a sleeve.',
      long: 'A double-wall paper hot drink cup, where the air gap between the walls does what a separate sleeve would, and a rolled rim that a lid seats on properly. Lids are sold separately and are sized to the rim rather than to the volume.',
      img: 'paper coffee cups disposable takeaway',
      specs: {
        Wall: 'Double wall',
        Rim: 'Rolled',
        Lids: 'Sold separately, sized to rim',
      },
      facets: ['Wall', 'Rim'],
      axes: [
        ['capacity', ['8 oz', '12 oz', '16 oz']],
        ['pack_count', ['Sleeve of 25', 'Case of 500']],
      ],
      price: [96_000, 980_000],
      stock: [15, 280],
      moq: 1,
      grams: 1_800,
      sold: { content: [25, 'piece'], label: 'Sleeve of 25' },
      multipack: 25,
    },
    {
      key: 'food-disp-cutlery',
      type: 'Disposable cutlery',
      title: 'Wooden Disposable Cutlery, Individually Wrapped',
      brand: BRANDS.tableware,
      short:
        'Birch wood disposable cutlery, individually wrapped and sanded smooth.',
      long: 'Birch wood disposable cutlery, sanded smooth so there is nothing to catch on the lip, and individually wrapped so it can be handed out rather than taken from an open tub. Compostable as a single material.',
      img: 'wooden disposable cutlery compostable',
      specs: {
        Material: 'Birch wood',
        Finish: 'Sanded smooth',
        Wrapping: 'Individually wrapped',
        Compostable: 'Single material',
      },
      facets: ['Material', 'Compostable'],
      axes: [
        ['item_type', ['Fork', 'Knife', 'Spoon', 'Mixed']],
        ['pack_count', ['Pack of 100', 'Case of 1,000']],
      ],
      price: [96_000, 780_000],
      stock: [15, 280],
      moq: 1,
      grams: 1_200,
      sold: { content: [100, 'piece'], label: 'Pack of 100' },
      multipack: 100,
      mrp: 0.14,
    },
  ]),

  shelf('food-storage-refrigeration', [
    {
      key: 'food-stor-undercounter',
      type: 'Undercounter refrigerator',
      title: 'Undercounter Refrigerator with Stainless Interior',
      brand: BRANDS.catering,
      short:
        'Undercounter commercial refrigerator with a stainless interior, a digital controller and castors.',
      long: 'An undercounter commercial refrigerator with a stainless steel interior coved at the corners, a digital controller with an accessible probe and castors so it rolls out for cleaning. The door is self-closing under about thirty degrees.',
      img: 'undercounter commercial refrigerator kitchen',
      specs: {
        Interior: 'Stainless steel, coved corners',
        Controller: 'Digital with accessible probe',
        Castors: 'Fitted',
        Door: 'Self closing',
      },
      facets: ['Interior', 'Controller'],
      axes: [
        ['capacity', ['150 L', '280 L']],
        ['door_count', ['1 door', '2 door']],
      ],
      price: [42_000_00, 96_000_00],
      stock: [1, 18],
      moq: 1,
      grams: 62_000,
      leadDays: 10,
      featured: true,
    },
    {
      key: 'food-stor-container',
      type: 'Food storage container',
      title: 'Polycarbonate Food Storage Container with Sealing Lid',
      brand: BRANDS.catering,
      short:
        'Clear polycarbonate food storage container with a sealing lid and moulded graduations.',
      long: 'A clear polycarbonate food storage container with graduations moulded into the side and a lid that seals on a gasket rather than a friction fit. It stacks with the lid on and nests with it off.',
      img: 'food storage containers commercial kitchen',
      specs: {
        Material: 'Clear polycarbonate',
        Lid: 'Gasket sealing',
        Graduations: 'Moulded into the side',
        Stacking: 'Stacks with lid, nests without',
      },
      facets: ['Material', 'Lid'],
      axes: [
        ['capacity', ['6 L', '12 L', '21 L']],
        ['configuration', ['Container only', 'Container with lid']],
      ],
      price: [280_000, 1_680_000],
      stock: [10, 180],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'food-stor-blastchiller',
      type: 'Blast chiller',
      title: 'Countertop Blast Chiller with Core Probe',
      brand: BRANDS.catering,
      short:
        'Countertop blast chiller with a core probe, a cycle log and a removable rack set.',
      long: 'A countertop blast chiller with a core temperature probe, so a cycle ends on the food reaching a temperature rather than on a timer. Each cycle is logged and can be exported, and the rack set lifts out.',
      img: 'blast chiller commercial kitchen equipment',
      specs: {
        Probe: 'Core temperature probe',
        Logging: 'Cycle log, exportable',
        Racks: 'Removable',
      },
      facets: ['Probe', 'Logging'],
      axes: [
        ['capacity', ['3 tray', '5 tray']],
        ['temperature_range', ['Chill only', 'Chill and freeze']],
      ],
      price: [98_000_00, 280_000_00],
      stock: [1, 10],
      moq: 1,
      grams: 84_000,
      leadDays: 21,
      mrp: 0.08,
    },
  ]),
];
