/**
 * Office & Stationery, Packaging & Shipping, Safety & Protective Equipment,
 * Cleaning & Hygiene.
 *
 * Twenty-two shelves, three products each.
 *
 * ONE THING THIS FILE DOES NOT DO, AND IT IS THE SAFETY DEPARTMENT
 *
 * Personal protective equipment is sold on its conformity. A glove is bought
 * because of what its EN 388 mark says, a boot because of its S-rating, a
 * respirator because of its filtration class - and every one of those is a
 * statement about a test somebody ran and a certificate somebody issued.
 *
 * This catalogue has no certificates. So it does not name any of those marks,
 * on any product, anywhere. A protective-clothing blueprint here describes the
 * fabric, the seams, the cuffs and the sizes - facts about the garment that can
 * be checked by holding it - and says nothing at all about what it is approved
 * to protect against. The `protection_rating` and `safety_rating` axes the
 * templates offer are deliberately left unused for exactly this reason: a
 * fabricated conformity mark on a demonstration catalogue is the one piece of
 * generated data that could get somebody hurt.
 *
 * Where a real operator lists these products they will fill those axes in from
 * their supplier's declaration, and the template is waiting for them.
 */
import { BRANDS } from '../brands.js';
import { shelf, type Shelf } from '../types.js';

export const WORKPLACE_SHELVES: readonly Shelf[] = [
  // =======================================================================
  // OFFICE & STATIONERY
  // =======================================================================
  shelf('paper-notebooks', [
    {
      key: 'off-paper-copier',
      type: 'Copier paper',
      title: 'Multipurpose Copier Paper, 75 gsm',
      brand: BRANDS.office,
      short:
        'Seventy-five gram multipurpose copier paper in sealed reams, cut square for reliable feeding.',
      long: 'A multipurpose office paper for copiers, laser and inkjet printers. The sheets are cut square and the ream is sealed in a moisture-resistant wrapper, which is what keeps a stack feeding cleanly through a machine in a humid month.',
      img: 'copier paper reams office stationery stack',
      specs: {
        Substance: '75 gsm',
        Finish: 'Uncoated, both sides printable',
        Wrapper: 'Moisture-resistant sealed ream',
        Grain: 'Long grain',
      },
      facets: ['Substance', 'Finish'],
      axes: [
        ['paper_size', ['A4', 'A3', 'Legal']],
        ['gsm', ['70 gsm', '75 gsm', '80 gsm']],
        ['pack_count', ['Ream of 500', 'Box of 5 reams']],
      ],
      price: [28_000, 320_000],
      stock: [30, 500],
      moq: 1,
      grams: 2_400,
      sold: { content: [500, 'sheet'], label: 'Ream of 500' },
      multipack: 500,
      featured: true,
    },
    {
      key: 'off-paper-notebook',
      type: 'Casebound notebook',
      title: 'Casebound Notebook with Sewn Binding and Elastic Closure',
      brand: BRANDS.office,
      short:
        'Casebound notebook with a sewn binding that opens flat, an elastic closure and a ribbon marker.',
      long: 'A casebound notebook whose sections are sewn rather than glued, so it opens flat at any page and stays open. The cover is a laminated board, there is an expanding pocket inside the back, and a ribbon marker is bound in.',
      img: 'notebook hardcover journal stationery',
      specs: {
        Binding: 'Sewn sections, opens flat',
        Cover: 'Laminated board with elastic closure',
        Extras: 'Ribbon marker and rear pocket',
        Paper: '90 gsm, ink resistant',
      },
      facets: ['Binding', 'Cover'],
      axes: [
        ['paper_size', ['A5', 'A4']],
        ['ruling', ['Ruled', 'Squared', 'Dotted', 'Plain']],
        ['colour', ['Black', 'Navy', 'Forest']],
      ],
      price: [180_000, 620_000],
      stock: [20, 300],
      moq: 1,
      grams: 420,
    },
    {
      key: 'off-paper-recycled',
      type: 'Recycled office paper',
      title: 'Recycled Office Paper from Post-Consumer Waste',
      brand: BRANDS.office,
      short:
        'Office paper made from post-consumer waste fibre, with the recycled content stated on the wrapper.',
      long: 'An office paper made from post-consumer waste fibre. The percentage of recycled content is printed on the wrapper rather than implied by the colour, and the sheet is slightly warmer in tone than a bleached paper because it has not been bleached to match one.',
      img: 'recycled paper ream office environmental',
      specs: {
        Content: 'Post-consumer waste fibre, percentage stated on wrapper',
        Tone: 'Natural, unbleached to white',
        Finish: 'Uncoated, both sides printable',
      },
      facets: ['Content', 'Tone'],
      axes: [
        ['paper_size', ['A4', 'A3']],
        ['gsm', ['80 gsm', '100 gsm']],
        ['pack_count', ['Ream of 500', 'Box of 5 reams']],
      ],
      price: [34_000, 340_000],
      stock: [20, 320],
      moq: 1,
      grams: 2_500,
      sold: { content: [500, 'sheet'], label: 'Ream of 500' },
      multipack: 500,
      mrp: 0.12,
    },
  ]),

  shelf('writing-correction', [
    {
      key: 'off-write-rollerball',
      type: 'Rollerball pen',
      title: 'Retractable Rollerball Pen with Rubber Grip',
      brand: BRANDS.office,
      short:
        'Retractable rollerball pen with a contoured rubber grip and a refillable cartridge.',
      long: 'A retractable rollerball with a contoured rubber grip and a metal clip. The cartridge is refillable rather than the pen being disposable, and the barrel is printed with the ink colour so a drawer of them can be sorted at a glance.',
      img: 'rollerball pens office stationery writing',
      specs: {
        Mechanism: 'Retractable',
        Grip: 'Contoured rubber',
        Refill: 'Refillable cartridge',
        'Ink type': 'Liquid ink',
      },
      facets: ['Mechanism', 'Ink type', 'Refill'],
      axes: [
        ['colour', ['Black', 'Blue', 'Red', 'Green']],
        ['tip_size', ['0.5 mm', '0.7 mm']],
        ['pack_count', ['Pack of 10', 'Box of 50']],
      ],
      price: [22_000, 180_000],
      stock: [30, 500],
      moq: 1,
      grams: 140,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      featured: true,
    },
    {
      key: 'off-write-marker',
      type: 'Permanent marker',
      title: 'Permanent Marker with Chisel Tip and Alcohol Ink',
      brand: BRANDS.office,
      short:
        'Alcohol-based permanent marker with a chisel tip that writes two line widths.',
      long: 'A permanent marker with an alcohol-based ink and a chisel tip, which gives a broad stroke on its face and a narrow one on its edge. The cap clicks audibly so a marker left on a desk is less likely to dry out.',
      img: 'permanent markers chisel tip stationery',
      specs: {
        'Ink type': 'Alcohol based, permanent',
        Tip: 'Chisel, two line widths',
        Cap: 'Audible click closure',
      },
      facets: ['Ink type', 'Tip'],
      axes: [
        ['colour', ['Black', 'Blue', 'Red', 'Assorted']],
        ['pack_count', ['Pack of 4', 'Box of 12']],
      ],
      price: [18_000, 120_000],
      stock: [25, 420],
      moq: 1,
      grams: 120,
    },
    {
      key: 'off-write-correction',
      type: 'Correction tape',
      title: 'Side-Applied Correction Tape with Refill Cartridge',
      brand: BRANDS.office,
      short:
        'Side-applied correction tape with a protective cap and a replaceable cartridge.',
      long: 'A correction tape applied from the side rather than the end, which is easier to run along a line of type. The tape is writable immediately, the tip is protected by a sliding cap, and the cartridge can be replaced rather than the whole applicator thrown away.',
      img: 'correction tape office stationery',
      specs: {
        Application: 'Side applied',
        Refill: 'Replaceable cartridge',
        Tip: 'Sliding protective cap',
      },
      facets: ['Application', 'Refill'],
      axes: [
        ['tip_size', ['4.2 mm', '5 mm']],
        ['pack_count', ['Single', 'Pack of 4', 'Box of 12']],
      ],
      price: [14_000, 96_000],
      stock: [25, 400],
      moq: 1,
      grams: 60,
      mrp: 0.16,
    },
  ]),

  shelf('filing-organisation', [
    {
      key: 'off-file-leverarch',
      type: 'Lever arch file',
      title: 'Lever Arch File with Board Cover and Metal Shoe',
      brand: BRANDS.office,
      short:
        'Board lever arch file with a metal shoe on the lower edge and a replaceable spine label.',
      long: 'A lever arch file with a board cover, a metal shoe protecting the lower edge and a finger hole in the spine. The spine label slides into a clear pocket so it can be changed without peeling anything off.',
      img: 'lever arch files office filing shelf',
      specs: {
        Cover: 'Laminated board',
        Shoe: 'Metal, lower edge',
        Label: 'Slide-in spine label pocket',
        Mechanism: 'Lever arch with compressor bar',
      },
      facets: ['Cover', 'Mechanism'],
      axes: [
        ['paper_size', ['A4', 'Foolscap']],
        ['spine_width', ['50 mm', '75 mm']],
        ['colour', ['Black', 'Blue', 'Red', 'Green']],
      ],
      price: [24_000, 96_000],
      stock: [25, 420],
      moq: 1,
      grams: 620,
      featured: true,
    },
    {
      key: 'off-file-suspension',
      type: 'Suspension file',
      title: 'Suspension File with Adjustable Tab Rail',
      brand: BRANDS.office,
      short:
        'Manila suspension file with a full-width tab rail and reinforced base creases.',
      long: 'A manila suspension file with a tab rail running the full width, so a tab can be set anywhere along it rather than at three fixed points. The base is creased in three places, which is what lets it take a thick file without splaying.',
      img: 'suspension files filing cabinet office',
      specs: {
        Material: 'Manila, recycled fibre',
        Rail: 'Full-width tab rail',
        Base: 'Three reinforced creases',
      },
      facets: ['Material'],
      axes: [
        ['paper_size', ['A4', 'Foolscap']],
        ['colour', ['Buff', 'Green', 'Blue']],
        ['pack_count', ['Pack of 25', 'Box of 50']],
      ],
      price: [68_000, 280_000],
      stock: [20, 320],
      moq: 1,
      grams: 1_600,
      sold: { content: [25, 'piece'], label: 'Pack of 25' },
      multipack: 25,
    },
    {
      key: 'off-file-archivebox',
      type: 'Archive storage box',
      title: 'Flat-Packed Archive Storage Box with Lid',
      brand: BRANDS.packaging,
      short:
        'Flat-packed corrugated archive box with a separate lid and hand holes both ends.',
      long: 'A corrugated archive box supplied flat and assembled without tape, with a separate lift-off lid and hand holes punched in both ends. Sized to take foolscap suspension files upright with a little room to get fingers in.',
      img: 'archive storage boxes cardboard office',
      specs: {
        Assembly: 'Flat packed, no tape needed',
        Lid: 'Separate lift-off lid',
        Handles: 'Hand holes both ends',
        Capacity: 'Foolscap suspension files upright',
      },
      facets: ['Assembly', 'Lid'],
      axes: [
        ['material', ['Standard board', 'Heavy duty board']],
        ['pack_count', ['Pack of 10', 'Pack of 20']],
      ],
      price: [96_000, 380_000],
      stock: [15, 240],
      moq: 1,
      grams: 4_200,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
      mrp: 0.13,
    },
  ]),

  shelf('office-machines', [
    {
      key: 'off-mach-shredder',
      type: 'Cross-cut shredder',
      title: 'Cross-Cut Office Shredder with Pull-Out Bin',
      brand: BRANDS.machines,
      short:
        'Cross-cut office shredder with a pull-out bin, a reverse control and a staple-capable throat.',
      long: 'A cross-cut shredder for an office, with a pull-out bin on runners and a window showing the fill level. The throat takes stapled sheets and a credit card, and a reverse control clears a jam without opening anything.',
      img: 'paper shredder office machine',
      specs: {
        Cut: 'Cross cut',
        Bin: 'Pull-out on runners with fill window',
        Throat: 'Staples and cards accepted',
        Controls: 'Forward, reverse and auto start',
      },
      facets: ['Cut', 'Bin'],
      axes: [
        ['performance', ['8 sheet', '12 sheet', '18 sheet']],
        ['feed_capacity', ['18 L bin', '26 L bin']],
      ],
      price: [4_800_00, 18_500_00],
      stock: [3, 42],
      moq: 1,
      grams: 8_600,
      featured: true,
    },
    {
      key: 'off-mach-laminator',
      type: 'Pouch laminator',
      title: 'Four-Roller Pouch Laminator with Cold Setting',
      brand: BRANDS.machines,
      short:
        'Four-roller pouch laminator with a cold setting, a reverse control and a ready indicator.',
      long: 'A four-roller pouch laminator, which is what gives an even finish without the ripple a two-roller machine leaves at the leading edge. A cold setting takes self-adhesive pouches, and a reverse control backs a misfed pouch out.',
      img: 'laminator office machine pouch',
      specs: {
        Rollers: 'Four',
        Settings: 'Hot and cold',
        Controls: 'Reverse and ready indicator',
      },
      facets: ['Rollers', 'Settings'],
      axes: [
        ['paper_size', ['A4', 'A3']],
        ['performance', ['80 micron', '80-125 micron', '80-250 micron']],
      ],
      price: [2_800_00, 12_400_00],
      stock: [4, 60],
      moq: 1,
      grams: 4_200,
    },
    {
      key: 'off-mach-binder',
      type: 'Comb binding machine',
      title: 'Comb Binding Machine with Adjustable Margin',
      brand: BRANDS.machines,
      short:
        'Manual comb binding machine with a disengageable punch and an adjustable margin setting.',
      long: 'A manual comb binding machine whose punching pins can be disengaged individually, so a narrow document is punched without a hole hanging off the edge. The margin adjusts for the comb size and a waste tray pulls out of the base.',
      img: 'comb binding machine office equipment',
      specs: {
        Punch: 'Individually disengageable pins',
        Margin: 'Adjustable for comb size',
        Waste: 'Pull-out tray in base',
      },
      facets: ['Punch', 'Margin'],
      axes: [
        ['performance', ['12 sheet punch', '20 sheet punch']],
        ['paper_size', ['A4', 'A4 and A5']],
      ],
      price: [3_400_00, 11_800_00],
      stock: [3, 48],
      moq: 1,
      grams: 6_400,
      mrp: 0.12,
    },
  ]),

  shelf('printer-supplies', [
    {
      key: 'off-supp-toner',
      type: 'Compatible toner cartridge',
      title: 'Compatible Toner Cartridge with Yield Stated on Box',
      brand: BRANDS.machines,
      short:
        'Compatible toner cartridge with the page yield and the test method stated on the box.',
      long: 'A compatible toner cartridge with the page yield printed on the box together with the coverage it was measured at, because a yield quoted without a coverage figure is not a number anybody can compare. Supplied sealed in a light-proof bag.',
      img: 'toner cartridge printer supplies office',
      specs: {
        Type: 'Compatible cartridge',
        Yield: 'Page yield and measurement coverage stated on box',
        Packaging: 'Sealed light-proof bag',
      },
      facets: ['Type'],
      axes: [
        ['colour', ['Black', 'Cyan', 'Magenta', 'Yellow']],
        ['page_yield', ['Standard yield', 'High yield']],
      ],
      price: [980_000, 4_800_000],
      stock: [12, 200],
      moq: 1,
      grams: 900,
      featured: true,
    },
    {
      key: 'off-supp-inkbottle',
      type: 'Ink tank refill bottle',
      title: 'Ink Tank Refill Bottle with Keyed Nozzle',
      brand: BRANDS.machines,
      short:
        'Refill bottle for tank printers, with a keyed nozzle that only fits the matching tank.',
      long: 'An ink refill bottle for tank printers, with a keyed nozzle shaped so it only enters the tank of the matching colour. The bottle stops flowing when the tank is full rather than overfilling it.',
      img: 'printer ink bottles refill supplies',
      specs: {
        Fitting: 'Keyed nozzle, colour specific',
        Flow: 'Stops when the tank is full',
        Volume: 'Printed on the bottle',
      },
      facets: ['Fitting'],
      axes: [
        ['colour', ['Black', 'Cyan', 'Magenta', 'Yellow']],
        ['pack_count', ['Single', 'Set of 4']],
      ],
      price: [280_000, 1_680_000],
      stock: [15, 240],
      moq: 1,
      grams: 140,
    },
    {
      key: 'off-supp-labelroll',
      type: 'Thermal label roll',
      title: 'Direct Thermal Label Roll for Desktop Printers',
      brand: BRANDS.packaging,
      short:
        'Direct thermal label roll with a permanent adhesive and a perforation between labels.',
      long: 'A direct thermal label roll for a desktop printer, wound face out on a standard core with a perforation between labels so they tear cleanly by hand. The liner is silicone coated and the adhesive is permanent.',
      img: 'thermal label rolls printer supplies',
      specs: {
        Method: 'Direct thermal, no ribbon',
        Adhesive: 'Permanent acrylic',
        Winding: 'Face out, perforated between labels',
      },
      facets: ['Method', 'Adhesive'],
      axes: [
        ['page_yield', ['100 x 150 mm', '58 x 40 mm', '38 x 25 mm']],
        ['pack_count', ['Single roll', 'Box of 10 rolls']],
      ],
      price: [120_000, 980_000],
      stock: [20, 320],
      moq: 1,
      grams: 480,
      mrp: 0.14,
    },
  ]),

  // =======================================================================
  // PACKAGING & SHIPPING
  // =======================================================================
  shelf('boxes-cartons', [
    {
      key: 'pack-box-singlewall',
      type: 'Single wall carton',
      title: 'Single Wall Cardboard Carton, Plain Kraft',
      brand: BRANDS.packaging,
      short:
        'Plain kraft single wall carton supplied flat, with a standard regular slotted construction.',
      long: 'A plain kraft single wall carton in the regular slotted construction, supplied flat and taped along the centre seam when it is made up. The internal dimensions are the stated ones, which matters when a product is being fitted to a box rather than the other way round.',
      img: 'cardboard boxes warehouse packaging stack',
      specs: {
        Construction: 'Regular slotted carton',
        Board: 'Single wall kraft',
        Dimensions: 'Quoted internally',
        Supply: 'Flat packed',
      },
      facets: ['Construction', 'Board'],
      axes: [
        ['internal_length', ['305 mm', '406 mm', '457 mm']],
        ['internal_width', ['229 mm', '305 mm']],
        ['pack_count', ['Pack of 25', 'Bundle of 50']],
      ],
      price: [96_000, 620_000],
      stock: [15, 260],
      moq: 1,
      grams: 6_400,
      sold: { content: [25, 'piece'], label: 'Pack of 25' },
      multipack: 25,
      featured: true,
    },
    {
      key: 'pack-box-doublewall',
      type: 'Double wall carton',
      title: 'Double Wall Export Carton for Heavy Goods',
      brand: BRANDS.packaging,
      short:
        'Double wall export carton with a higher board grade, for heavier or stacked loads.',
      long: 'A double wall carton for heavier goods and for loads that will be stacked on a pallet. The two fluted layers give the box its stacking strength; the board grade is printed inside the flap where it can still be read after the box is made up.',
      img: 'double wall export cartons warehouse boxes',
      specs: {
        Construction: 'Regular slotted carton',
        Board: 'Double wall',
        Marking: 'Board grade printed inside flap',
        Supply: 'Flat packed',
      },
      facets: ['Construction', 'Board'],
      axes: [
        ['internal_length', ['457 mm', '508 mm', '610 mm']],
        ['internal_height', ['305 mm', '406 mm']],
        ['pack_count', ['Pack of 10', 'Bundle of 25']],
      ],
      price: [180_000, 980_000],
      stock: [10, 180],
      moq: 1,
      grams: 9_800,
      sold: { content: [10, 'piece'], label: 'Pack of 10' },
      multipack: 10,
    },
    {
      key: 'pack-box-postal',
      type: 'Postal box',
      title: 'Die-Cut Postal Box with Peel-and-Seal Strip',
      brand: BRANDS.packaging,
      short:
        'Die-cut postal box with a peel-and-seal strip and a tear strip for opening.',
      long: 'A die-cut postal box that folds without tape: a peel-and-seal strip closes it and a tear strip opens it. The wall is a single corrugated layer with a white outer, so it takes a printed label cleanly.',
      img: 'postal boxes shipping packaging mailer',
      specs: {
        Closure: 'Peel-and-seal strip',
        Opening: 'Tear strip',
        Outer: 'White, label friendly',
      },
      facets: ['Closure', 'Outer'],
      axes: [
        ['internal_length', ['180 mm', '250 mm', '330 mm']],
        ['pack_count', ['Pack of 20', 'Pack of 50']],
      ],
      price: [140_000, 680_000],
      stock: [15, 240],
      moq: 1,
      grams: 3_400,
      sold: { content: [20, 'piece'], label: 'Pack of 20' },
      multipack: 20,
      mrp: 0.13,
    },
  ]),

  shelf('tapes-strapping', [
    {
      key: 'pack-tape-packing',
      type: 'Packing tape',
      title: 'Low-Noise Polypropylene Packing Tape',
      brand: BRANDS.packaging,
      short:
        'Low-noise polypropylene packing tape with a solvent-free acrylic adhesive.',
      long: 'A polypropylene packing tape with an acrylic adhesive and a low-noise release, so a packing bench is bearable. The adhesive is solvent free, the core is a standard 76 mm, and the roll is wound without the telescoping that makes a roll jam in a dispenser.',
      img: 'packing tape rolls packaging warehouse',
      specs: {
        Backing: 'Polypropylene',
        Adhesive: 'Solvent-free acrylic',
        Release: 'Low noise',
        Core: '76 mm',
      },
      facets: ['Backing', 'Adhesive', 'Release'],
      axes: [
        ['width', ['48 mm', '72 mm']],
        ['colour', ['Clear', 'Buff', 'Black']],
        ['pack_count', ['Pack of 6', 'Box of 36']],
      ],
      price: [46_000, 420_000],
      stock: [20, 360],
      moq: 1,
      grams: 1_600,
      sold: { content: [66, 'm'], per: [1, 'm'], label: 'Roll of 66 m' },
      featured: true,
    },
    {
      key: 'pack-tape-gummed',
      type: 'Gummed paper tape',
      title: 'Reinforced Gummed Paper Tape for Water Activation',
      brand: BRANDS.packaging,
      short:
        'Water-activated gummed paper tape with a glass fibre reinforcement, for tamper-evident sealing.',
      long: 'A water-activated gummed paper tape reinforced with glass fibre strands. Because it bonds into the board rather than onto it, a seal cannot be lifted and replaced without leaving a mark. It needs a water dispenser rather than a hand roller.',
      img: 'gummed paper tape kraft packaging',
      specs: {
        Activation: 'Water activated',
        Reinforcement: 'Glass fibre strands',
        Bond: 'Bonds into the board fibre',
        Dispenser: 'Requires a water dispenser',
      },
      facets: ['Activation', 'Reinforcement'],
      axes: [
        ['width', ['48 mm', '70 mm']],
        ['length', ['100 m', '200 m']],
      ],
      price: [180_000, 680_000],
      stock: [10, 180],
      moq: 1,
      grams: 1_400,
      sold: { content: [100, 'm'], per: [1, 'm'] },
    },
    {
      key: 'pack-strap-pet',
      type: 'Polyester strapping',
      title: 'Embossed Polyester Strapping on a Plastic Core',
      brand: BRANDS.packaging,
      short:
        'Embossed polyester strapping on a plastic core, for palletised loads with a hand tensioner.',
      long: 'A polyester strapping with an embossed surface, which is what stops a tensioned strap slipping through a buckle. Wound on a plastic core and supplied with the break load printed on the label.',
      img: 'polyester strapping coil packaging pallet',
      specs: {
        Material: 'Polyester',
        Surface: 'Embossed',
        Core: 'Plastic core, 406 mm',
        Marking: 'Break load printed on label',
      },
      facets: ['Material', 'Surface'],
      axes: [
        ['width', ['12 mm', '16 mm', '19 mm']],
        ['thickness', ['0.6 mm', '0.9 mm']],
      ],
      price: [280_000, 1_280_000],
      stock: [8, 140],
      moq: 1,
      grams: 14_000,
      sold: { content: [1500, 'm'], per: [1, 'm'] },
      mrp: 0.11,
    },
  ]),

  shelf('protective-packaging', [
    {
      key: 'pack-prot-bubble',
      type: 'Bubble wrap',
      title: 'Small Bubble Wrap Roll, Perforated Every Metre',
      brand: BRANDS.packaging,
      short:
        'Small bubble wrap on a roll, perforated every metre so a length tears off without a blade.',
      long: 'A small-bubble protective wrap on a roll, perforated every metre so a length comes off without a knife at the bench. The bubbles are on one face and the film is smooth on the other, which is the face that goes against the product.',
      img: 'bubble wrap protective packaging roll',
      specs: {
        Bubble: 'Small, 10 mm',
        Perforation: 'Every metre',
        Faces: 'Bubbles one side, smooth against the product',
      },
      facets: ['Bubble', 'Perforation'],
      axes: [
        ['width', ['500 mm', '750 mm', '1,000 mm']],
        ['length', ['50 m', '100 m']],
      ],
      price: [180_000, 980_000],
      stock: [10, 180],
      moq: 1,
      grams: 4_200,
      sold: { content: [100, 'm'], per: [1, 'm'] },
      featured: true,
    },
    {
      key: 'pack-prot-foam',
      type: 'Foam wrap',
      title: 'Polyethylene Foam Wrap for Surface Protection',
      brand: BRANDS.packaging,
      short:
        'Closed-cell polyethylene foam wrap for protecting finished and polished surfaces.',
      long: 'A closed-cell polyethylene foam wrap for finished surfaces, where a bubble wrap would print its pattern into a polish. It is soft enough to wrap a corner without creasing and does not shed.',
      img: 'foam wrap protective packaging roll',
      specs: {
        Material: 'Closed-cell polyethylene',
        Use: 'Finished and polished surfaces',
        Shedding: 'Non-shedding',
      },
      facets: ['Material', 'Use'],
      axes: [
        ['thickness', ['1 mm', '2 mm', '4 mm']],
        ['width', ['500 mm', '750 mm']],
      ],
      price: [240_000, 1_180_000],
      stock: [8, 140],
      moq: 1,
      grams: 3_800,
      sold: { content: [100, 'm'], per: [1, 'm'] },
    },
    {
      key: 'pack-prot-voidfill',
      type: 'Paper void fill',
      title: 'Kraft Paper Void Fill in a Fanfold Stack',
      brand: BRANDS.packaging,
      short:
        'Fanfold kraft paper void fill, supplied as a stack rather than a roll.',
      long: 'A kraft paper void fill supplied as a fanfold stack, which feeds without a spindle and does not need a dispenser bolted to the bench. The paper is crumpled by hand into the space around a product.',
      img: 'kraft paper void fill packaging',
      specs: {
        Material: 'Kraft paper',
        Presentation: 'Fanfold stack, no spindle needed',
        Recyclable: 'Single-material paper',
      },
      facets: ['Material', 'Recyclable'],
      axes: [
        ['width', ['380 mm', '500 mm']],
        ['pack_count', ['Stack of 250 m', 'Stack of 400 m']],
      ],
      price: [320_000, 980_000],
      stock: [6, 120],
      moq: 1,
      grams: 12_000,
      mrp: 0.12,
    },
  ]),

  shelf('bags-films', [
    {
      key: 'pack-bag-mailer',
      type: 'Polythene mailing bag',
      title: 'Opaque Polythene Mailing Bag with Peel Seal',
      brand: BRANDS.packaging,
      short:
        'Opaque co-extruded polythene mailing bag with a peel-and-seal lip and a returns strip.',
      long: 'A co-extruded polythene mailing bag, opaque so the contents cannot be read through it, with a peel-and-seal lip and a second adhesive strip for a return. The seams are welded rather than glued.',
      img: 'polythene mailing bags shipping packaging',
      specs: {
        Film: 'Co-extruded, opaque',
        Closure: 'Peel and seal with returns strip',
        Seams: 'Welded',
      },
      facets: ['Film', 'Closure'],
      axes: [
        ['width', ['250 mm', '350 mm', '450 mm']],
        ['colour', ['Grey', 'White']],
        ['pack_count', ['Pack of 100', 'Box of 500']],
      ],
      price: [96_000, 620_000],
      stock: [15, 280],
      moq: 1,
      grams: 1_800,
      sold: { content: [100, 'piece'], label: 'Pack of 100' },
      multipack: 100,
      featured: true,
    },
    {
      key: 'pack-bag-pallet',
      type: 'Pallet stretch film',
      title: 'Hand Pallet Stretch Film with Extended Core',
      brand: BRANDS.packaging,
      short:
        'Hand pallet stretch film on an extended core, so a pallet can be wrapped without a dispenser.',
      long: 'A hand stretch film on a core that extends past the film at both ends, giving something to hold while the pallet is walked round. The film is blown rather than cast, so it clings and tears less on a corner.',
      img: 'stretch film pallet wrap warehouse',
      specs: {
        Film: 'Blown polyethylene',
        Core: 'Extended handles both ends',
        Cling: 'One-sided cling',
      },
      facets: ['Film', 'Core'],
      axes: [
        ['thickness', ['17 micron', '20 micron', '23 micron']],
        ['pack_count', ['Single roll', 'Pack of 6 rolls']],
      ],
      price: [140_000, 780_000],
      stock: [12, 200],
      moq: 1,
      grams: 2_600,
      sold: { content: [300, 'm'], per: [1, 'm'] },
    },
    {
      key: 'pack-bag-ziplock',
      type: 'Grip seal bag',
      title: 'Grip Seal Bag with Write-On Panel',
      brand: BRANDS.packaging,
      short:
        'Clear grip seal bag with a write-on panel, for parts picking and small-item despatch.',
      long: 'A clear grip seal bag with three white write-on panels along the top, so a part number can be written on in pencil or marker. The seal is a press-together track that can be opened and closed repeatedly.',
      img: 'grip seal bags plastic packaging small',
      specs: {
        Film: 'Clear polythene',
        Closure: 'Press-together grip seal',
        Panel: 'Three write-on panels',
      },
      facets: ['Film', 'Closure'],
      axes: [
        ['width', ['75 x 75 mm', '100 x 140 mm', '150 x 230 mm']],
        ['pack_count', ['Pack of 100', 'Box of 1,000']],
      ],
      price: [38_000, 380_000],
      stock: [20, 360],
      moq: 1,
      grams: 900,
      sold: { content: [100, 'piece'], label: 'Pack of 100' },
      multipack: 100,
      mrp: 0.15,
    },
  ]),

  shelf('labels-marking', [
    {
      key: 'pack-label-laser',
      type: 'Laser address label',
      title: 'Laser Address Label Sheet with Rounded Corners',
      brand: BRANDS.packaging,
      short:
        'A4 laser label sheet with rounded corners and a permanent adhesive, laid out to a standard grid.',
      long: 'An A4 sheet of laser labels laid out to a standard grid, with rounded corners so a label does not lift at a point. The liner is split down the back so a single label can be taken off without bending the sheet.',
      img: 'address labels sheet printer office',
      specs: {
        Layout: 'Standard A4 grid',
        Corners: 'Rounded',
        Liner: 'Split back for single removal',
        Adhesive: 'Permanent',
      },
      facets: ['Adhesive', 'Corners'],
      axes: [
        ['label_size', ['99 x 38 mm', '63 x 38 mm', '105 x 74 mm']],
        ['labels_per_unit', ['100 sheets', '500 sheets']],
      ],
      price: [96_000, 480_000],
      stock: [15, 280],
      moq: 1,
      grams: 1_400,
      featured: true,
    },
    {
      key: 'pack-label-thermal-transfer',
      type: 'Thermal transfer label roll',
      title: 'Thermal Transfer Label Roll with Synthetic Face',
      brand: BRANDS.packaging,
      short:
        'Synthetic-faced thermal transfer label roll, for labels that must survive handling and damp.',
      long: 'A thermal transfer label roll on a synthetic face rather than paper, for labels that will be handled, washed down or stored outside. It needs a resin ribbon; the roll is wound face out on a 76 mm core.',
      img: 'thermal transfer labels roll industrial',
      specs: {
        Face: 'Synthetic',
        Method: 'Thermal transfer, resin ribbon required',
        Core: '76 mm, wound face out',
      },
      facets: ['Face', 'Method'],
      axes: [
        ['label_size', ['100 x 150 mm', '76 x 51 mm']],
        ['labels_per_unit', ['Single roll', 'Box of 4 rolls']],
      ],
      price: [280_000, 1_280_000],
      stock: [10, 180],
      moq: 1,
      grams: 900,
    },
    {
      key: 'pack-label-handling',
      type: 'Handling label',
      title: 'Printed Handling Label Roll, Plain Symbols',
      brand: BRANDS.packaging,
      short:
        'Pre-printed handling label roll carrying plain symbols such as fragile and this way up.',
      long: 'A roll of pre-printed handling labels carrying the plain symbols a carton needs - fragile, this way up, do not stack - in a strong colour with a permanent adhesive. Perforated between labels.',
      img: 'fragile handling labels roll packaging',
      specs: {
        Printing: 'Pre-printed symbols',
        Adhesive: 'Permanent',
        Perforation: 'Between labels',
      },
      facets: ['Printing', 'Adhesive'],
      axes: [
        ['label_type', ['Fragile', 'This way up', 'Do not stack', 'Mixed roll']],
        ['labels_per_unit', ['Roll of 500', 'Roll of 1,000']],
      ],
      price: [48_000, 280_000],
      stock: [20, 320],
      moq: 1,
      grams: 380,
      mrp: 0.14,
    },
  ]),

  // =======================================================================
  // SAFETY & PROTECTIVE EQUIPMENT
  //
  // Read the note at the top of this file before adding to any of these.
  // =======================================================================
  shelf('hand-protection', [
    {
      key: 'safe-glove-nitrilecoated',
      type: 'Coated work glove',
      title: 'Nitrile-Coated Work Glove on a Seamless Liner',
      brand: BRANDS.safety,
      short:
        'Seamless knitted liner with a nitrile palm coating, for general handling in dry and oily conditions.',
      long: 'A general handling glove built on a seamless knitted liner with a nitrile coating over the palm and fingertips. The back is left uncoated so the hand breathes, and the cuff is a knitted band rather than a cut edge.',
      img: 'work gloves nitrile coated safety',
      specs: {
        Liner: 'Seamless knitted',
        Coating: 'Nitrile, palm and fingertips',
        Back: 'Uncoated, breathable',
        Cuff: 'Knitted band',
      },
      facets: ['Liner', 'Coating'],
      axes: [
        ['size', ['7', '8', '9', '10', '11']],
        ['colour', ['Grey', 'Black']],
        ['pack_count', ['Pack of 12 pairs', 'Case of 120 pairs']],
      ],
      price: [96_000, 1_280_000],
      stock: [20, 360],
      moq: 1,
      grams: 1_200,
      sold: { content: [12, 'pair'], label: 'Pack of 12 pairs' },
      multipack: 12,
      featured: true,
    },
    {
      key: 'safe-glove-leather',
      type: 'Leather rigger glove',
      title: 'Leather Rigger Glove with Reinforced Palm',
      brand: BRANDS.safety,
      short:
        'Split-leather rigger glove with a reinforced palm patch and a rubberised safety cuff.',
      long: 'A split-leather rigger glove with a second layer of leather across the palm where wear happens, a cotton drill back and a rubberised safety cuff. The seams are stitched with a heat-resistant thread.',
      img: 'leather rigger work gloves safety',
      specs: {
        Leather: 'Split cowhide',
        Palm: 'Reinforced patch',
        Back: 'Cotton drill',
        Cuff: 'Rubberised safety cuff',
      },
      facets: ['Leather', 'Palm'],
      axes: [
        ['size', ['9', '10', '11']],
        ['pack_count', ['Pack of 10 pairs', 'Case of 100 pairs']],
      ],
      price: [180_000, 1_480_000],
      stock: [15, 280],
      moq: 1,
      grams: 1_800,
      sold: { content: [10, 'pair'], label: 'Pack of 10 pairs' },
      multipack: 10,
    },
    {
      key: 'safe-glove-disposable',
      type: 'Disposable nitrile glove',
      title: 'Powder-Free Disposable Nitrile Glove, Textured Fingertips',
      brand: BRANDS.safety,
      short:
        'Powder-free disposable nitrile glove with textured fingertips and a beaded cuff.',
      long: 'A powder-free disposable nitrile glove with textured fingertips and a beaded cuff, supplied in a dispenser box of one hundred. Ambidextrous, latex free, and available in a heavier gauge where more resistance to tearing is wanted.',
      img: 'disposable nitrile gloves box blue',
      specs: {
        Material: 'Nitrile, latex free',
        Powder: 'Powder free',
        Finish: 'Textured fingertips',
        Cuff: 'Beaded',
      },
      facets: ['Material', 'Powder'],
      axes: [
        ['size', ['Small', 'Medium', 'Large', 'Extra large']],
        ['thickness', ['Standard gauge', 'Heavy gauge']],
        ['colour', ['Blue', 'Black']],
      ],
      price: [46_000, 140_000],
      stock: [30, 600],
      moq: 1,
      grams: 1_100,
      sold: { content: [100, 'piece'], label: 'Box of 100' },
      multipack: 100,
      mrp: 0.16,
    },
  ]),

  shelf('eye-face-protection', [
    {
      key: 'safe-eye-spectacle',
      type: 'Safety spectacle',
      title: 'Wraparound Safety Spectacle with Anti-Fog Coating',
      brand: BRANDS.safety,
      short:
        'Wraparound polycarbonate safety spectacle with an anti-fog and anti-scratch coating.',
      long: 'A wraparound polycarbonate safety spectacle with a coating on both faces - anti-fog inside, anti-scratch outside. The temples adjust for length and ratchet for angle, and the brow carries a soft insert.',
      img: 'safety glasses eye protection industrial',
      specs: {
        Lens: 'Polycarbonate, wraparound',
        Coating: 'Anti-fog inside, anti-scratch outside',
        Temples: 'Length and angle adjustable',
        Brow: 'Soft insert',
      },
      facets: ['Lens', 'Coating'],
      axes: [
        ['lens_shade', ['Clear', 'Smoke', 'Amber']],
        ['pack_count', ['Single', 'Box of 12']],
      ],
      price: [38_000, 480_000],
      stock: [25, 420],
      moq: 1,
      grams: 60,
      featured: true,
    },
    {
      key: 'safe-eye-goggle',
      type: 'Safety goggle',
      title: 'Indirect-Vent Safety Goggle for Over-Spectacle Wear',
      brand: BRANDS.safety,
      short:
        'Indirect-vent safety goggle sized to fit over prescription spectacles, with an elasticated strap.',
      long: 'An indirect-vent safety goggle with a frame deep enough to go over prescription spectacles. The vents are baffled so the eye chamber breathes without a straight path in, and the strap is elasticated with a sliding buckle.',
      img: 'safety goggles eye protection lab',
      specs: {
        Ventilation: 'Indirect, baffled vents',
        Fit: 'Over prescription spectacles',
        Strap: 'Elasticated with sliding buckle',
        Lens: 'Polycarbonate',
      },
      facets: ['Ventilation', 'Fit'],
      axes: [
        ['lens_shade', ['Clear', 'Smoke']],
        ['pack_count', ['Single', 'Box of 10']],
      ],
      price: [68_000, 560_000],
      stock: [20, 360],
      moq: 1,
      grams: 110,
    },
    {
      key: 'safe-eye-faceshield',
      type: 'Face shield',
      title: 'Ratchet Headgear Face Shield with Replaceable Visor',
      brand: BRANDS.safety,
      short:
        'Face shield on ratchet headgear, with a visor that changes without tools.',
      long: 'A face shield on ratchet headgear with a sweatband, and a visor that unclips and changes without tools. The visor is polycarbonate and the headgear adjusts for both circumference and crown height.',
      img: 'face shield visor safety protection',
      specs: {
        Headgear: 'Ratchet with sweatband',
        Visor: 'Polycarbonate, tool-free change',
        Adjustment: 'Circumference and crown height',
      },
      facets: ['Headgear', 'Visor'],
      axes: [
        ['lens_shade', ['Clear', 'Smoke']],
        ['equipment_type', ['Complete assembly', 'Replacement visor only']],
      ],
      price: [96_000, 620_000],
      stock: [15, 240],
      moq: 1,
      grams: 320,
      mrp: 0.12,
    },
  ]),

  shelf('respiratory-protection', [
    {
      key: 'safe-resp-disposable',
      type: 'Disposable respirator',
      title: 'Moulded Cup Disposable Respirator with Exhalation Valve',
      brand: BRANDS.safety,
      short:
        'Moulded cup disposable respirator with an exhalation valve, an adjustable nose clip and twin straps.',
      long: 'A moulded cup disposable respirator with an exhalation valve to reduce heat build-up, an aluminium nose clip that holds its shape and twin straps stapled clear of the seal. The filter class is chosen at the point of purchase to suit the work.',
      img: 'disposable respirator mask valve safety',
      specs: {
        Form: 'Moulded cup',
        Valve: 'Exhalation valve',
        'Nose clip': 'Adjustable aluminium',
        Straps: 'Twin, stapled clear of seal',
      },
      facets: ['Form', 'Valve'],
      axes: [
        ['mask_type', ['Valved', 'Unvalved']],
        ['pack_count', ['Box of 10', 'Box of 20']],
      ],
      price: [96_000, 420_000],
      stock: [20, 360],
      moq: 1,
      grams: 320,
      featured: true,
    },
    {
      key: 'safe-resp-halfmask',
      type: 'Reusable half mask',
      title: 'Reusable Half Mask with Bayonet Filter Mounts',
      brand: BRANDS.safety,
      short:
        'Reusable silicone half mask with bayonet filter mounts and a four-point head harness.',
      long: 'A reusable half mask in a soft silicone face piece with bayonet mounts either side, so filters change with a quarter turn. The head harness has four points and drops away from the face without being taken off completely.',
      img: 'reusable half mask respirator safety',
      specs: {
        'Face piece': 'Silicone',
        Mounts: 'Bayonet, quarter turn',
        Harness: 'Four point, drop down',
        Cleaning: 'Washable, filters removed',
      },
      facets: ['Face piece', 'Mounts'],
      axes: [
        ['size', ['Small', 'Medium', 'Large']],
        ['pack_count', ['Mask only', 'Mask with filter pair']],
      ],
      price: [280_000, 1_180_000],
      stock: [12, 200],
      moq: 1,
      grams: 220,
    },
    {
      key: 'safe-resp-filter',
      type: 'Respirator filter',
      title: 'Bayonet Respirator Filter Pair with Sealed Bag',
      brand: BRANDS.safety,
      short:
        'Pair of bayonet-mount respirator filters, individually sealed until fitted.',
      long: 'A matched pair of bayonet-mount filters for a reusable half or full mask, sealed in a bag until they are fitted because a filter starts its life the moment it is opened. The date of opening is written on the supplied label.',
      img: 'respirator filters cartridge pair safety',
      specs: {
        Mount: 'Bayonet',
        Supply: 'Matched pair, sealed bag',
        Labelling: 'Date-of-opening label supplied',
      },
      facets: ['Mount'],
      axes: [
        ['mask_type', ['Particulate', 'Combined gas and particulate']],
        ['pack_count', ['One pair', 'Box of 5 pairs']],
      ],
      price: [180_000, 980_000],
      stock: [15, 240],
      moq: 1,
      grams: 180,
      mrp: 0.11,
    },
  ]),

  shelf('head-fall-protection', [
    {
      key: 'safe-head-helmet',
      type: 'Safety helmet',
      title: 'Vented Safety Helmet with Six-Point Harness',
      brand: BRANDS.safety,
      short:
        'Vented safety helmet with a six-point textile harness and a wheel ratchet adjuster.',
      long: 'A safety helmet with a six-point textile harness and a wheel ratchet at the back, adjustable one-handed while it is being worn. The shell is vented, accessory slots take ear defenders and a visor, and the harness is replaceable.',
      img: 'safety helmet hard hat construction',
      specs: {
        Harness: 'Six point textile, replaceable',
        Adjuster: 'Wheel ratchet',
        Shell: 'Vented',
        Accessories: 'Side slots for defenders and visor',
      },
      facets: ['Harness', 'Shell'],
      axes: [
        ['colour', ['White', 'Yellow', 'Blue', 'Red']],
        ['kit_configuration', ['Helmet only', 'Helmet with chin strap']],
      ],
      price: [96_000, 480_000],
      stock: [20, 320],
      moq: 1,
      grams: 380,
      featured: true,
    },
    {
      key: 'safe-fall-harness',
      type: 'Full body harness',
      title: 'Two-Point Full Body Harness with Quick-Connect Buckles',
      brand: BRANDS.safety,
      short:
        'Two-point full body harness with quick-connect leg buckles and an inspection record card.',
      long: 'A two-point full body harness with quick-connect leg buckles and a dorsal and sternal attachment. Each harness carries a unique serial number and an inspection record card in a pocket on the webbing.',
      img: 'safety harness fall protection equipment',
      specs: {
        Attachments: 'Dorsal and sternal',
        Buckles: 'Quick connect on legs',
        Traceability: 'Serial number and inspection record card',
        Webbing: 'Polyester',
      },
      facets: ['Attachments', 'Buckles'],
      axes: [
        ['size_range', ['Small to medium', 'Medium to large', 'Large to extra large']],
        ['kit_configuration', ['Harness only', 'Harness with lanyard']],
      ],
      price: [980_000, 4_800_000],
      stock: [8, 140],
      moq: 1,
      grams: 1_600,
    },
    {
      key: 'safe-head-defender',
      type: 'Ear defender',
      title: 'Helmet-Mounted Ear Defender with Replaceable Cushions',
      brand: BRANDS.safety,
      short:
        'Helmet-mounted ear defender on sprung arms, with cushions that change without tools.',
      long: 'An ear defender that clips into the accessory slots of a safety helmet, on sprung arms that hold three positions - worn, standby and parked. The cushions and the foam inserts change without tools and are sold as a kit.',
      img: 'ear defenders hearing protection safety',
      specs: {
        Mounting: 'Helmet accessory slots',
        Positions: 'Worn, standby, parked',
        Cushions: 'Tool-free replacement',
      },
      facets: ['Mounting', 'Cushions'],
      axes: [
        ['equipment_type', ['Helmet mounted', 'Headband']],
        ['colour', ['Black', 'Yellow']],
      ],
      price: [280_000, 1_280_000],
      stock: [12, 200],
      moq: 1,
      grams: 280,
      mrp: 0.12,
    },
  ]),

  shelf('protective-clothing', [
    {
      key: 'safe-cloth-coverall',
      type: 'Disposable coverall',
      title: 'Disposable Coverall with Elasticated Cuffs and Hood',
      brand: BRANDS.workwear,
      short:
        'Disposable coverall in a breathable non-woven, with elasticated cuffs, ankles and hood.',
      long: 'A disposable coverall in a breathable non-woven fabric, with elasticated cuffs, ankles and hood and a two-way zip under a storm flap. The seams are stitched and the fabric is low-linting.',
      img: 'disposable coverall protective clothing white',
      specs: {
        Fabric: 'Breathable non-woven, low linting',
        Closure: 'Two-way zip under storm flap',
        Elastication: 'Cuffs, ankles and hood',
        Seams: 'Stitched',
      },
      facets: ['Fabric', 'Closure'],
      axes: [
        ['size', ['M', 'L', 'XL', 'XXL']],
        ['colour', ['White', 'Blue']],
        ['pack_count', ['Single', 'Case of 25']],
      ],
      price: [38_000, 780_000],
      stock: [20, 360],
      moq: 1,
      grams: 420,
      featured: true,
    },
    {
      key: 'safe-cloth-hivis',
      type: 'High-visibility waistcoat',
      title: 'High-Visibility Waistcoat with Reflective Bands',
      brand: BRANDS.workwear,
      short:
        'High-visibility waistcoat in a knitted polyester with two horizontal reflective bands.',
      long: 'A high-visibility waistcoat in a lightweight knitted polyester, with two horizontal reflective bands and braces over the shoulders. It closes with a touch fastener so it comes off quickly, and it goes over a coat.',
      img: 'high visibility vest safety workwear',
      specs: {
        Fabric: 'Knitted polyester',
        Bands: 'Two horizontal, plus shoulder braces',
        Closure: 'Touch fastener',
        Fit: 'Over outerwear',
      },
      facets: ['Fabric', 'Closure'],
      axes: [
        ['size', ['M', 'L', 'XL', 'XXL']],
        ['colour', ['Yellow', 'Orange']],
        ['pack_count', ['Single', 'Pack of 10']],
      ],
      price: [22_000, 320_000],
      stock: [25, 420],
      moq: 1,
      grams: 180,
    },
    {
      key: 'safe-cloth-apron',
      type: 'Chemical apron',
      title: 'PVC-Coated Apron with Neck and Waist Ties',
      brand: BRANDS.workwear,
      short:
        'PVC-coated apron with welded edges, an adjustable neck strap and long waist ties.',
      long: 'A PVC-coated apron with welded rather than stitched edges, so there is no seam for liquid to wick through. The neck strap adjusts and the waist ties are long enough to cross behind and knot at the front.',
      img: 'pvc apron protective clothing industrial',
      specs: {
        Coating: 'PVC on a woven support',
        Edges: 'Welded',
        Neck: 'Adjustable strap',
        Ties: 'Long waist ties',
      },
      facets: ['Coating', 'Edges'],
      axes: [
        ['size', ['Standard', 'Long']],
        ['colour', ['White', 'Green', 'Navy']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [46_000, 420_000],
      stock: [20, 320],
      moq: 1,
      grams: 620,
      mrp: 0.13,
    },
  ]),

  shelf('safety-footwear', [
    {
      key: 'safe-boot-steeltoe',
      type: 'Safety boot',
      title: 'Leather Safety Boot with Steel Toe Cap',
      brand: BRANDS.workwear,
      short:
        'Full-grain leather safety boot with a steel toe cap, a padded collar and a dual-density sole.',
      long: 'A full-grain leather safety boot with a steel toe cap, a padded collar and a moulded dual-density sole - a softer midsole for standing on and a harder outsole for wear. The lacing runs through four eyelets and two speed hooks.',
      img: 'black safety work boots steel toe',
      specs: {
        Upper: 'Full grain leather',
        'Toe cap': 'Steel',
        Sole: 'Dual density, moulded',
        Lacing: 'Four eyelets and two speed hooks',
        Collar: 'Padded',
      },
      facets: ['Upper', 'Toe cap', 'Sole'],
      axes: [
        ['size_system', ['UK']],
        ['size', ['6', '7', '8', '9', '10', '11']],
        ['colour', ['Black', 'Brown']],
      ],
      price: [1_680_00, 4_800_00],
      stock: [6, 90],
      moq: 1,
      grams: 1_600,
      featured: true,
    },
    {
      key: 'safe-shoe-composite',
      type: 'Safety shoe',
      title: 'Composite Toe Safety Trainer with Breathable Upper',
      brand: BRANDS.workwear,
      short:
        'Lightweight safety trainer with a composite toe cap and a breathable textile upper.',
      long: 'A lightweight safety trainer with a composite toe cap rather than a steel one, so it carries no metal and weighs less. The upper is a breathable textile with synthetic overlays at the wear points, and the insole is removable.',
      img: 'safety trainer shoes work footwear',
      specs: {
        'Toe cap': 'Composite, non-metallic',
        Upper: 'Breathable textile with synthetic overlays',
        Insole: 'Removable',
        Sole: 'EVA midsole with rubber outsole',
      },
      facets: ['Toe cap', 'Upper'],
      axes: [
        ['size_system', ['UK', 'EU']],
        ['size', ['6', '7', '8', '9', '10']],
        ['colour', ['Black', 'Grey']],
      ],
      price: [1_980_00, 5_600_00],
      stock: [5, 80],
      moq: 1,
      grams: 1_100,
    },
    {
      key: 'safe-boot-wellington',
      type: 'Safety wellington',
      title: 'PVC Safety Wellington with Steel Toe and Midsole',
      brand: BRANDS.workwear,
      short:
        'PVC safety wellington with a steel toe cap, a steel midsole and a kick-off spur.',
      long: 'A one-piece moulded PVC safety wellington with a steel toe cap and a steel midsole, and a kick-off spur at the heel so it comes off without being touched. Being one piece, there is no seam to leak.',
      img: 'safety wellington boots pvc work',
      specs: {
        Construction: 'One-piece moulded PVC',
        'Toe cap': 'Steel',
        Midsole: 'Steel',
        Heel: 'Kick-off spur',
      },
      facets: ['Construction', 'Toe cap'],
      axes: [
        ['size_system', ['UK']],
        ['size', ['6', '7', '8', '9', '10', '11', '12']],
        ['colour', ['Green', 'Black', 'White']],
      ],
      price: [980_00, 2_800_00],
      stock: [8, 120],
      moq: 1,
      grams: 1_900,
      mrp: 0.12,
    },
  ]),

  shelf('fire-safety-first-aid', [
    {
      key: 'safe-fire-extinguisher',
      type: 'Dry powder fire extinguisher',
      title: 'Dry Powder Fire Extinguisher with Wall Bracket',
      brand: BRANDS.safety,
      short:
        'Dry powder fire extinguisher supplied with a wall bracket, a pressure gauge and a safety pin seal.',
      long: 'A dry powder fire extinguisher with a pressure gauge on the head, a tamper seal through the safety pin and a squeeze-grip discharge. A wall bracket is supplied, and a service label panel is left blank for the operator’s own record.',
      img: 'fire extinguisher safety equipment red',
      specs: {
        Medium: 'Dry powder',
        Gauge: 'Pressure gauge on head',
        Seal: 'Tamper seal through safety pin',
        Bracket: 'Wall bracket supplied',
      },
      facets: ['Medium', 'Gauge'],
      axes: [
        ['capacity', ['1 kg', '2 kg', '6 kg', '9 kg']],
        ['mounting', ['Wall bracket', 'Vehicle bracket']],
      ],
      price: [280_000, 1_680_000],
      stock: [10, 160],
      moq: 1,
      grams: 8_400,
      featured: true,
    },
    {
      key: 'safe-firstaid-kit',
      type: 'Workplace first aid kit',
      title: 'Workplace First Aid Kit in a Wall-Mountable Case',
      brand: BRANDS.safety,
      short:
        'Workplace first aid kit in a wall-mountable case with a contents list inside the lid.',
      long: 'A workplace first aid kit in a moulded case with a gasket, a carry handle and keyholes for a wall. The contents are listed inside the lid so a restock is a matter of reading rather than guessing, and refill packs are sold separately.',
      img: 'first aid kit workplace safety case',
      specs: {
        Case: 'Moulded with gasket and carry handle',
        Mounting: 'Keyholes for wall mounting',
        Contents: 'Listed inside the lid',
        Refills: 'Refill packs available separately',
      },
      facets: ['Case', 'Mounting'],
      axes: [
        ['content_level', ['Small workplace', 'Medium workplace', 'Large workplace']],
        ['mounting', ['Case only', 'Case with wall bracket']],
      ],
      price: [420_000, 1_980_000],
      stock: [10, 160],
      moq: 1,
      grams: 2_400,
    },
    {
      key: 'safe-fire-blanket',
      type: 'Fire blanket',
      title: 'Glass Fibre Fire Blanket in a Quick-Release Pouch',
      brand: BRANDS.safety,
      short:
        'Glass fibre fire blanket in a soft pouch with two pull tapes for quick release.',
      long: 'A woven glass fibre fire blanket folded into a soft wall pouch with two pull tapes, so it comes out with one movement. The pouch carries keyholes and an instruction panel printed on the front.',
      img: 'fire blanket safety equipment kitchen',
      specs: {
        Material: 'Woven glass fibre',
        Pouch: 'Soft pouch with two pull tapes',
        Mounting: 'Keyholes on pouch',
        Instructions: 'Printed on pouch front',
      },
      facets: ['Material', 'Pouch'],
      axes: [
        ['capacity', ['1.0 x 1.0 m', '1.2 x 1.2 m', '1.8 x 1.8 m']],
        ['pack_count', ['Single', 'Pack of 5']],
      ],
      price: [140_000, 980_000],
      stock: [15, 240],
      moq: 1,
      grams: 900,
      mrp: 0.13,
    },
  ]),

  // =======================================================================
  // CLEANING & HYGIENE
  // =======================================================================
  shelf('cleaning-chemicals', [
    {
      key: 'clean-chem-degreaser',
      type: 'Industrial degreaser',
      title: 'Concentrated Alkaline Degreaser for Dilution',
      brand: BRANDS.cleaning,
      short:
        'Concentrated alkaline degreaser with the dilution ratio printed on the label for each task.',
      long: 'A concentrated alkaline degreaser supplied for dilution, with a table on the label giving the ratio for light, medium and heavy soiling rather than a single figure. Free of solvent and low foaming, so it rinses without a second pass.',
      img: 'industrial degreaser cleaning chemical bottle',
      specs: {
        Formulation: 'Alkaline concentrate, solvent free',
        Foaming: 'Low foaming',
        Dilution: 'Ratio table on label',
        'pH type': 'Alkaline',
      },
      facets: ['Formulation', 'pH type'],
      axes: [
        ['net_volume', ['5 L', '20 L']],
        ['dilution_ratio', ['1:10', '1:50', '1:100']],
      ],
      price: [280_000, 1_480_000],
      stock: [10, 180],
      moq: 1,
      grams: 5_400,
      sold: { content: [5, 'L'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'clean-chem-floor',
      type: 'Neutral floor cleaner',
      title: 'Neutral pH Floor Cleaner for Sealed Surfaces',
      brand: BRANDS.cleaning,
      short:
        'Neutral pH floor cleaner for sealed and polished surfaces, safe on a floor finish.',
      long: 'A neutral pH floor cleaner for sealed and polished surfaces, which is the point - an alkaline cleaner will strip a floor finish over time and a neutral one will not. Low foaming, so it works in a scrubber dryer as well as a bucket.',
      img: 'floor cleaner chemical bottle cleaning',
      specs: {
        'pH type': 'Neutral',
        Use: 'Sealed and polished floors',
        Foaming: 'Low foaming, machine compatible',
      },
      facets: ['pH type', 'Use'],
      axes: [
        ['net_volume', ['5 L', '20 L']],
        ['fragrance', ['Unfragranced', 'Citrus', 'Floral']],
      ],
      price: [180_000, 980_000],
      stock: [12, 200],
      moq: 1,
      grams: 5_300,
      sold: { content: [5, 'L'], per: [1, 'L'] },
    },
    {
      key: 'clean-chem-washroom',
      type: 'Washroom cleaner',
      title: 'Acidic Washroom Cleaner and Descaler',
      brand: BRANDS.cleaning,
      short:
        'Acidic washroom cleaner and descaler in a trigger bottle, with a thickened formulation.',
      long: 'An acidic washroom cleaner thickened so it clings to a vertical surface long enough to work, rather than running to the floor. Supplied in a trigger bottle with a locking nozzle, and in refill containers for the same bottle.',
      img: 'washroom cleaner spray bottle cleaning',
      specs: {
        'pH type': 'Acidic',
        Consistency: 'Thickened, clings to vertical surfaces',
        Bottle: 'Trigger with locking nozzle',
      },
      facets: ['pH type', 'Consistency'],
      axes: [
        ['net_volume', ['750 ml', '5 L']],
        ['pack_count', ['Single', 'Case of 6']],
      ],
      price: [46_000, 680_000],
      stock: [15, 280],
      moq: 1,
      grams: 820,
      sold: { content: [750, 'ml'], per: [1, 'L'] },
      mrp: 0.14,
    },
  ]),

  shelf('disinfection-sterilisation', [
    {
      key: 'clean-disinf-surface',
      type: 'Surface disinfectant',
      title: 'Ready-to-Use Surface Disinfectant Spray',
      brand: BRANDS.cleaning,
      short:
        'Ready-to-use surface disinfectant with the contact time printed on the label.',
      long: 'A ready-to-use surface disinfectant supplied in a trigger bottle, with the contact time printed on the label because a disinfectant wiped off early has not done what it was bought to do. Alcohol free, so it does not craze acrylic.',
      img: 'surface disinfectant spray bottle cleaning',
      specs: {
        Form: 'Ready to use',
        Alcohol: 'Alcohol free',
        'Contact time': 'Printed on label',
        Surfaces: 'Safe on acrylic and painted surfaces',
      },
      facets: ['Form', 'Alcohol'],
      axes: [
        ['net_volume', ['750 ml', '5 L']],
        ['pack_count', ['Single', 'Case of 6']],
      ],
      price: [52_000, 720_000],
      stock: [15, 260],
      moq: 1,
      grams: 820,
      sold: { content: [750, 'ml'], per: [1, 'L'] },
      featured: true,
    },
    {
      key: 'clean-disinf-wipes',
      type: 'Disinfectant wipe',
      title: 'Disinfectant Wipes in a Flip-Top Tub',
      brand: BRANDS.cleaning,
      short:
        'Pre-saturated disinfectant wipes in a flip-top tub with a centre-pull feed.',
      long: 'Pre-saturated disinfectant wipes in a flip-top tub with a centre-pull feed, so the next wipe presents itself. The lid seals against the tub rim rather than a foil, which is what keeps the last wipe as wet as the first.',
      img: 'disinfectant wipes tub cleaning hygiene',
      specs: {
        Feed: 'Centre pull',
        Lid: 'Sealing flip top',
        Saturation: 'Pre-saturated',
      },
      facets: ['Feed', 'Saturation'],
      axes: [
        ['capacity', ['100 wipes', '200 wipes']],
        ['pack_count', ['Single tub', 'Case of 6 tubs']],
      ],
      price: [96_000, 980_000],
      stock: [15, 260],
      moq: 1,
      grams: 1_400,
    },
    {
      key: 'clean-disinf-handgel',
      type: 'Hand sanitising gel',
      title: 'Alcohol Hand Sanitising Gel with Pump Dispenser',
      brand: BRANDS.cleaning,
      short:
        'Alcohol hand sanitising gel with an added emollient, in a pump bottle or a refill.',
      long: 'An alcohol hand sanitising gel with an added emollient so repeated use does not dry the skin as quickly. Supplied in a pump bottle and in a refill container that fits the same wall dispenser.',
      img: 'hand sanitiser gel pump bottle hygiene',
      specs: {
        Base: 'Alcohol gel with emollient',
        Dispensing: 'Pump bottle or wall dispenser refill',
        Fragrance: 'Unfragranced',
      },
      facets: ['Base', 'Dispensing'],
      axes: [
        ['net_volume', ['500 ml', '1 L', '5 L']],
        ['application', ['Pump bottle', 'Dispenser refill']],
      ],
      price: [46_000, 680_000],
      stock: [20, 320],
      moq: 1,
      grams: 560,
      sold: { content: [500, 'ml'], per: [1, 'L'] },
      mrp: 0.15,
    },
  ]),

  shelf('cleaning-equipment', [
    {
      key: 'clean-equip-vacuum',
      type: 'Wet and dry vacuum',
      title: 'Wet and Dry Vacuum Cleaner with Stainless Drum',
      brand: BRANDS.cleaning,
      short:
        'Wet and dry vacuum cleaner in a stainless drum, with a blower port and castors.',
      long: 'A wet and dry vacuum cleaner in a stainless steel drum, with a float cut-out for wet pick-up and a blower port at the back. It runs on four castors, two of which brake, and the hose and tools clip to the drum.',
      img: 'wet dry vacuum cleaner industrial',
      specs: {
        Drum: 'Stainless steel',
        'Wet pick-up': 'Float cut-out',
        Blower: 'Rear blower port',
        Castors: 'Four, two braked',
      },
      facets: ['Drum', 'Wet pick-up'],
      axes: [
        ['capacity', ['20 L', '30 L', '50 L']],
        ['power', ['1,200 W', '1,400 W']],
      ],
      price: [6_800_00, 24_000_00],
      stock: [3, 48],
      moq: 1,
      grams: 9_800,
      featured: true,
    },
    {
      key: 'clean-equip-trolley',
      type: 'Janitorial trolley',
      title: 'Janitorial Trolley with Twin Buckets and Waste Bag',
      brand: BRANDS.cleaning,
      short:
        'Janitorial trolley with twin colour-coded buckets, a wringer and a waste bag holder.',
      long: 'A janitorial trolley with twin colour-coded buckets and a wringer that fits either, a waste bag holder on a hoop and a shelf for bottles. It moves on four castors, two braked, and the buckets lift out to be emptied.',
      img: 'janitorial cleaning trolley buckets mop',
      specs: {
        Buckets: 'Twin, colour coded, removable',
        Wringer: 'Fits either bucket',
        Waste: 'Bag holder on hoop',
        Castors: 'Four, two braked',
      },
      facets: ['Buckets', 'Waste'],
      axes: [
        ['capacity', ['2 x 25 L', '2 x 33 L']],
        ['attachments', ['Trolley only', 'Trolley with mop set']],
      ],
      price: [8_400_00, 22_000_00],
      stock: [3, 42],
      moq: 1,
      grams: 14_000,
    },
    {
      key: 'clean-equip-mopset',
      type: 'Flat mop set',
      title: 'Flat Mop Set with Microfibre Pads and Telescopic Handle',
      brand: BRANDS.cleaning,
      short:
        'Flat mop set with a telescopic handle, a hinged frame and washable microfibre pads.',
      long: 'A flat mop set with a telescopic aluminium handle and a hinged frame that folds flat to reach under furniture. The microfibre pads fasten with touch tape and are washable at sixty degrees.',
      img: 'flat mop microfibre cleaning equipment',
      specs: {
        Handle: 'Telescopic aluminium',
        Frame: 'Hinged, folds flat',
        Pads: 'Microfibre, washable at 60 C',
      },
      facets: ['Handle', 'Pads'],
      axes: [
        ['working_width', ['40 cm', '60 cm']],
        ['attachments', ['Set with 2 pads', 'Set with 5 pads']],
      ],
      price: [980_000, 3_800_000],
      stock: [10, 160],
      moq: 1,
      grams: 1_600,
      mrp: 0.13,
    },
  ]),

  shelf('washroom-supplies', [
    {
      key: 'clean-wash-handtowel',
      type: 'Paper hand towel',
      title: 'Interfold Paper Hand Towel for Dispensers',
      brand: BRANDS.cleaning,
      short:
        'Interfolded paper hand towel that presents one sheet at a time in a dispenser.',
      long: 'An interfolded paper hand towel: each sheet pulls the next partly out of the dispenser, so one is taken rather than a handful. Supplied in sleeved bundles that drop straight into a standard dispenser.',
      img: 'paper hand towels washroom supplies',
      specs: {
        Fold: 'Interfold, one sheet at a time',
        Presentation: 'Sleeved bundles',
        Fibre: 'Recycled',
      },
      facets: ['Fold', 'Fibre'],
      axes: [
        ['ply', ['1 ply', '2 ply']],
        ['colour', ['White', 'Natural']],
        ['pack_count', ['Case of 3,000', 'Case of 5,000']],
      ],
      price: [420_000, 1_480_000],
      stock: [8, 140],
      moq: 1,
      grams: 9_600,
      sold: { content: [3000, 'sheet'], label: 'Case of 3,000' },
      featured: true,
    },
    {
      key: 'clean-wash-toiletroll',
      type: 'Toilet tissue',
      title: 'Embossed Toilet Tissue in a Trade Case',
      brand: BRANDS.cleaning,
      short:
        'Embossed two-ply toilet tissue in a trade case, with the sheet count printed on each wrapper.',
      long: 'An embossed two-ply toilet tissue supplied in a trade case rather than a retail pack, with the sheet count and the roll length printed on each wrapper so usage can actually be costed.',
      img: 'toilet tissue rolls washroom supplies',
      specs: {
        Ply: 'Two ply, embossed',
        Marking: 'Sheet count and length on wrapper',
        Fibre: 'Recycled',
      },
      facets: ['Ply', 'Fibre'],
      axes: [
        ['sheet_size', ['Standard roll', 'Jumbo roll']],
        ['pack_count', ['Case of 36', 'Case of 48']],
      ],
      price: [480_000, 1_280_000],
      stock: [10, 180],
      moq: 1,
      grams: 8_400,
    },
    {
      key: 'clean-wash-soap',
      type: 'Foam hand soap',
      title: 'Foam Hand Soap Cartridge for Wall Dispensers',
      brand: BRANDS.cleaning,
      short:
        'Sealed foam hand soap cartridge with its own pump, for a wall dispenser.',
      long: 'A foam hand soap supplied in a sealed cartridge with its own pump, so the pump is replaced with the soap and nothing is topped up into a dirty reservoir. Unfragranced and dye free.',
      img: 'foam hand soap dispenser cartridge washroom',
      specs: {
        Form: 'Foam',
        Cartridge: 'Sealed, with integral pump',
        Fragrance: 'Unfragranced, dye free',
      },
      facets: ['Form', 'Cartridge'],
      axes: [
        ['product_type', ['800 ml cartridge', '1 L cartridge']],
        ['pack_count', ['Single', 'Case of 6']],
      ],
      price: [180_000, 980_000],
      stock: [12, 200],
      moq: 1,
      grams: 900,
      sold: { content: [800, 'ml'], per: [1, 'L'] },
      mrp: 0.12,
    },
  ]),

  shelf('waste-management', [
    {
      key: 'clean-waste-wheeliebin',
      type: 'Wheeled waste container',
      title: 'Two-Wheeled Waste Container with Hinged Lid',
      brand: BRANDS.cleaning,
      short:
        'Two-wheeled waste container in moulded polyethylene, with a hinged lid and a comb lifting bar.',
      long: 'A two-wheeled waste container moulded in one piece from polyethylene, with a hinged lid, solid rubber wheels on a steel axle and a comb lifting bar for a standard lifter. The body carries a moulded area for a printed number.',
      img: 'wheeled waste bin container refuse',
      specs: {
        Body: 'One-piece moulded polyethylene',
        Lid: 'Hinged',
        Wheels: 'Solid rubber on steel axle',
        Lifting: 'Comb bar',
      },
      facets: ['Body', 'Lifting'],
      axes: [
        ['capacity', ['120 L', '240 L', '360 L']],
        ['colour', ['Green', 'Black', 'Blue', 'Brown']],
      ],
      price: [2_800_00, 8_900_00],
      stock: [5, 80],
      moq: 1,
      grams: 11_000,
      featured: true,
    },
    {
      key: 'clean-waste-sackholder',
      type: 'Sack holder',
      title: 'Freestanding Sack Holder with Removable Hoop',
      brand: BRANDS.cleaning,
      short:
        'Freestanding powder-coated sack holder with a removable hoop and a weighted base.',
      long: 'A freestanding sack holder with a removable hoop that grips a refuse sack round the rim, on a weighted base so it does not tip when the sack is pulled out. It breaks down flat for storage.',
      img: 'sack holder waste stand cleaning',
      specs: {
        Frame: 'Powder-coated steel',
        Hoop: 'Removable',
        Base: 'Weighted',
        Storage: 'Breaks down flat',
      },
      facets: ['Frame', 'Hoop'],
      axes: [
        ['capacity', ['90 L', '120 L']],
        ['colour', ['Black', 'Grey']],
      ],
      price: [1_280_00, 3_400_00],
      stock: [6, 90],
      moq: 1,
      grams: 4_200,
    },
    {
      key: 'clean-waste-sacks',
      type: 'Refuse sack',
      title: 'Heavy Duty Refuse Sack on a Perforated Roll',
      brand: BRANDS.packaging,
      short:
        'Heavy duty refuse sack on a perforated roll, with a gusseted base for square bins.',
      long: 'A heavy duty refuse sack supplied on a perforated roll, with a gusseted base so it opens square into a bin rather than bunching at the corners. The gauge is printed on the roll label.',
      img: 'refuse sacks bin bags roll waste',
      specs: {
        Base: 'Gusseted',
        Supply: 'Perforated roll',
        Marking: 'Gauge printed on roll label',
      },
      facets: ['Base', 'Supply'],
      axes: [
        ['capacity', ['90 L', '120 L', '200 L']],
        ['colour', ['Black', 'Clear', 'Blue']],
        ['pack_count', ['Roll of 20', 'Case of 200']],
      ],
      price: [46_000, 480_000],
      stock: [20, 360],
      moq: 1,
      grams: 2_400,
      sold: { content: [20, 'piece'], label: 'Roll of 20' },
      multipack: 20,
      mrp: 0.14,
    },
  ]),
];
