CREATE TABLE `rfq_purchase_orders` (
  `id` CHAR(26) NOT NULL,
  `reference` VARCHAR(32) NOT NULL,
  `rfqId` CHAR(26) NOT NULL,
  `quoteId` CHAR(26) NOT NULL,
  `customerProfileId` CHAR(26) NOT NULL,
  `buyerCompanyId` CHAR(26) NULL,
  `sellerAccountId` CHAR(26) NOT NULL,
  `status` ENUM('PENDING_APPROVAL', 'APPROVED', 'REJECTED') NOT NULL,
  `version` INTEGER NOT NULL DEFAULT 0,
  `acceptedTermsHash` CHAR(64) NOT NULL,
  `contractHash` CHAR(64) NOT NULL,
  `contractJson` JSON NOT NULL,
  `buyerSku` VARCHAR(80) NULL,
  `currency` CHAR(3) NOT NULL,
  `goodsTotalMinor` BIGINT NOT NULL,
  `toolingMinor` BIGINT NOT NULL,
  `shippingMinor` BIGINT NOT NULL,
  `grandTotalMinor` BIGINT NOT NULL,
  `requestedByUserId` CHAR(26) NOT NULL,
  `eAcceptedAt` DATETIME(3) NOT NULL,
  `signatureName` VARCHAR(160) NOT NULL,
  `signatureTitle` VARCHAR(160) NULL,
  `approvalPolicyJson` JSON NULL,
  `approvedAt` DATETIME(3) NULL,
  `rejectedAt` DATETIME(3) NULL,
  `rejectionReason` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_rfq_po_reference` (`reference`),
  UNIQUE INDEX `uq_rfq_po_rfq` (`rfqId`),
  UNIQUE INDEX `uq_rfq_po_quote` (`quoteId`),
  INDEX `ix_rfq_po_buyer_status` (`buyerCompanyId`, `status`, `createdAt`),
  INDEX `ix_rfq_po_seller_status` (`sellerAccountId`, `status`, `createdAt`),
  CONSTRAINT `fk_rfq_po_rfq` FOREIGN KEY (`rfqId`) REFERENCES `rfq_requests` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_rfq_po_totals_nonnegative` CHECK (`goodsTotalMinor` >= 0 AND `toolingMinor` >= 0 AND `shippingMinor` >= 0 AND `grandTotalMinor` >= 0),
  CONSTRAINT `chk_rfq_po_decision_time` CHECK ((`status` = 'APPROVED' AND `approvedAt` IS NOT NULL AND `rejectedAt` IS NULL) OR (`status` = 'REJECTED' AND `approvedAt` IS NULL AND `rejectedAt` IS NOT NULL) OR (`status` = 'PENDING_APPROVAL' AND `approvedAt` IS NULL AND `rejectedAt` IS NULL))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `rfq_purchase_order_approvals` (
  `id` CHAR(26) NOT NULL,
  `purchaseOrderId` CHAR(26) NOT NULL,
  `stage` ENUM('APPROVER', 'FINANCE') NOT NULL,
  `decision` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `requestedByUserId` CHAR(26) NOT NULL,
  `decidedByUserId` CHAR(26) NULL,
  `decidedAt` DATETIME(3) NULL,
  `reason` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_rfq_po_approval_stage` (`purchaseOrderId`, `stage`),
  INDEX `ix_rfq_po_approval_queue` (`decision`, `stage`, `createdAt`),
  CONSTRAINT `fk_rfq_po_approval_po` FOREIGN KEY (`purchaseOrderId`) REFERENCES `rfq_purchase_orders` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `chk_rfq_po_approval_decision` CHECK ((`decision` = 'PENDING' AND `decidedByUserId` IS NULL AND `decidedAt` IS NULL) OR (`decision` <> 'PENDING' AND `decidedByUserId` IS NOT NULL AND `decidedAt` IS NOT NULL))
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
