/**
 * Dashboard insights: what the AI is allowed to say about a set of figures.
 *
 * Three role dashboards ask this the same question — "explain what I am
 * looking at" — and the answer has to be useful without ever being able to be
 * wrong about a number. That constraint is the whole design:
 *
 *   **The model never counts anything.** Every figure reaches it as a named
 *   metric that a role-scoped database aggregate produced. The model is asked
 *   to explain, rank and prioritise; it is never asked what the total is, and
 *   anything it says that is not anchored to a metric it was handed is
 *   discarded before the reply leaves this file.
 *
 *   **The tenant boundary is upstream and absolute.** This service is handed a
 *   metric bundle that a caller already scoped — a buyer's own orders, a
 *   carrier's own consignments, the platform queues an administrator holds the
 *   grant for. There is no id in this file, no query, and no way for a prompt
 *   to widen what it was given. A route that builds the bundle wrongly leaks;
 *   a prompt cannot.
 *
 *   **Nothing here can act.** The reply carries suggested actions as text and
 *   a link the caller already knows how to build. It approves no seller,
 *   charges no card, assigns no driver and resolves no exception. Every one of
 *   those remains a deliberate press on a screen, behind its own authorization
 *   check and its own audit entry.
 *
 * ---
 *
 * WHEN THERE IS NO PROVIDER
 *
 * A deployment with no key configured — which is the default — gets a
 * deterministic summary built from the same metric bundle, marked
 * `source: 'deterministic'`, and the panel says so. It is deliberately NOT
 * dressed up as a model reply: a dashboard that invents an AI voice when there
 * is no AI behind it is lying about the one thing a reader might act on. It is
 * also genuinely useful — ranking the queues that want somebody today is
 * arithmetic, not intelligence.
 */
import { z } from 'zod';
import { logger } from '../../infra/logger.js';
import { AssistantBusyError } from './provider.js';
import { activeProvider } from './assistant.service.js';

// ---------------------------------------------------------------------------
// What a dashboard hands in
// ---------------------------------------------------------------------------

/** Which dashboard is asking. Decides the vocabulary and the guardrails. */
export type InsightAudience = 'BUYER' | 'ADMIN' | 'LOGISTICS';

/**
 * How much somebody should care.
 *
 * Supplied by the caller from the metric's own meaning rather than inferred
 * from its size: five failed payments and five delivered parcels are the same
 * number and not the same day, and nothing in a bare figure says which is
 * which.
 */
export type MetricSeverity = 'info' | 'attention' | 'urgent';

export interface InsightMetric {
  /**
   * A stable key, e.g. `orders.pendingPayment`.
   *
   * The unit of evidence. A reply may only cite keys from this bundle, so this
   * is also the allow-list — see `sanitise` below.
   */
  key: string;
  /** Plain English, for the model. Never shown to the reader, who has their own translation. */
  label: string;
  value: number;
  /** "orders", "consignments", "EUR" — so the model does not guess. */
  unit: string;
  severity: MetricSeverity;
  /**
   * Where the reader goes to act on it, relative to their own app.
   *
   * Passed through to the reply so a suggested action can carry a destination.
   * NEVER generated by the model: a fabricated link in an operations console is
   * a link somebody follows.
   */
  href?: string | undefined;
}

export interface InsightRequest {
  audience: InsightAudience;
  /**
   * The reporting window the figures were measured over.
   *
   * Sent to the model so it cannot describe a 7-day figure as a monthly one,
   * and echoed in the reply so a screenshot of the panel says what it covers.
   */
  window: { from: string; to: string };
  /**
   * The filters in force, already reduced to labels.
   *
   * Labels rather than ids, and no personal data: "Country: Belgium" is
   * context the model needs, and a customer id is not.
   */
  filters: Record<string, string>;
  metrics: InsightMetric[];
  /** A question typed by the reader. Absent for the opening summary. */
  question?: string | undefined;
  /** The reader's language tag, so the answer comes back in it. */
  language?: string | undefined;
}

// ---------------------------------------------------------------------------
// What comes back
// ---------------------------------------------------------------------------

export interface InsightFinding {
  title: string;
  detail: string;
  severity: MetricSeverity;
  /** Metric keys this finding rests on. Validated against the bundle. */
  evidence: string[];
}

export interface InsightAction {
  label: string;
  detail: string;
  /** The metric it addresses, and therefore where the link comes from. */
  metricKey: string | null;
  /** Copied from that metric. Never model-generated. */
  href: string | null;
}

export interface InsightEvidence {
  metricKey: string;
  label: string;
  value: number;
  unit: string;
  href: string | null;
}

export interface Insight {
  summary: string;
  findings: InsightFinding[];
  suggestedActions: InsightAction[];
  evidence: InsightEvidence[];
  generatedAt: string;
  window: { from: string; to: string };
  /** Which metrics were in scope. A reader can check the answer against them. */
  metricKeys: string[];
  /** `model` or `deterministic`. Shown to the reader, never hidden. */
  source: 'model' | 'deterministic';
  /** The model's name where one answered, so the panel can disclose it. */
  model: string | null;
  /**
   * Why the deterministic path was taken, where it was.
   *
   * `null` on a model reply. `not-configured`, `unavailable` or `unusable` —
   * and the last one is the interesting case: the provider answered and the
   * answer did not survive validation, which is a fact worth surfacing rather
   * than papering over.
   */
  fallbackReason: 'not-configured' | 'unavailable' | 'unusable' | null;
}

// ---------------------------------------------------------------------------
// The prompt
// ---------------------------------------------------------------------------

/**
 * What the model is told it is, and the four things it must not do.
 *
 * Stable across every request on a deployment, so a provider that caches
 * prompt prefixes can. The per-request part — the metrics, the window, the
 * question — goes last, for the same reason `assistant.service.ts` puts the
 * customer block last.
 */
const BEHAVIOUR = `You are the insights panel on an operations dashboard for a European
business-to-business marketplace that sells medical and laboratory equipment between companies.

You are given a set of METRICS that the server has already computed from its database, a
reporting window, and the filters in force. Your job is to explain what they mean and what
somebody should do first.

Rules you must follow exactly:

1. NEVER state a number that is not in the METRICS. Do not add metrics together, do not compute
   percentages, do not estimate, and do not infer a figure the list does not contain. If you want
   to mention a quantity, quote a metric's value exactly as given.
2. NEVER invent a status, an order, a company, a shipment, a product or a person. The metrics are
   the only facts you have.
3. Every finding must cite the metric keys it rests on, using the exact keys given.
4. Do not give medical, clinical or regulatory advice, and do not comment on whether a product is
   suitable for a patient or a procedure. This is a logistics and commerce dashboard.
5. Do not tell the reader that you have done something. You cannot approve, pay, assign, cancel,
   resolve or change anything. Suggest; never claim to have acted.
6. If the metrics show nothing worth attention, say so plainly in one sentence rather than
   manufacturing a concern.

Write in plain, direct business English, in short sentences. No preamble, no sign-off, no emoji.

Reply in TWO parts, in this order, with nothing before the first and nothing after the second.

PART ONE is the summary: two or three sentences of plain prose. No JSON, no markdown, no heading.
This part is shown to the reader as you write it, so it must read correctly from the first word.

PART TWO is a single line containing exactly ---DETAIL--- and then JSON, matching this shape:

{
  "findings": [{"title": "...", "detail": "...", "severity": "info|attention|urgent", "evidence": ["metric.key"]}],
  "suggestedActions": [{"label": "short imperative", "detail": "one sentence", "metricKey": "metric.key"}]
}

At most four findings and at most three suggested actions.`;

/**
 * The marker between the part a reader watches arrive and the part a machine
 * parses.
 *
 * The whole reason the reply is split. A model asked for JSON alone streams as
 * `{"summary":"Thr` — technically a stream, and unreadable — so the prose comes
 * first as prose and the structure follows it. Nothing before the marker is
 * ever parsed and nothing after it is ever shown.
 */
const DETAIL_MARKER = '---DETAIL---';

/** What each dashboard is, in one line, so the answer uses the right nouns. */
const AUDIENCE_CONTEXT: Readonly<Record<InsightAudience, string>> = Object.freeze({
  BUYER:
    'The reader is a buyer at a customer company - typically hospital or clinic procurement staff. ' +
    'The metrics cover THEIR OWN organisation\'s orders, scheduled orders, spend and deliveries, and nothing else. ' +
    'Address them as the person who placed these orders.',
  ADMIN:
    'The reader is a member of the marketplace operator\'s staff, looking at platform-wide operational queues. ' +
    'The metrics cover work waiting to be decided - approvals, exceptions, alerts. ' +
    'Their question is always "what should the team do first".',
  LOGISTICS:
    'The reader is a dispatcher at a carrier company. ' +
    'The metrics cover consignments assigned to THEIR OWN company only, never another carrier\'s. ' +
    'Their question is always "what is at risk today".',
});

/** The bundle, rendered for the model. */
function renderContext(request: InsightRequest): string {
  const filters = Object.entries(request.filters);

  const lines = [
    AUDIENCE_CONTEXT[request.audience],
    '',
    `REPORTING WINDOW: ${request.window.from} to ${request.window.to}`,
    filters.length === 0
      ? 'FILTERS: none'
      : `FILTERS: ${filters.map(([key, value]) => `${key}=${value}`).join(', ')}`,
    '',
    'METRICS:',
    ...request.metrics.map(
      (metric) =>
        `- ${metric.key} | ${metric.label} | value=${String(metric.value)} ${metric.unit} | severity=${metric.severity}`,
    ),
  ];

  if (request.language !== undefined && request.language !== 'en') {
    lines.push('', `Write the reply in this language: ${request.language}`);
  }

  if (request.question !== undefined && request.question.trim().length > 0) {
    lines.push(
      '',
      'The reader asked this question. Answer it from the metrics above, and say plainly if the',
      'metrics do not contain the answer rather than guessing:',
      request.question.trim(),
    );
  } else {
    lines.push('', 'No question was asked. Summarise the metrics and say what to look at first.');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Validating what comes back
// ---------------------------------------------------------------------------

const modelReply = z.object({
  findings: z
    .array(
      z.object({
        title: z.string().min(1).max(160),
        detail: z.string().min(1).max(600),
        severity: z.enum(['info', 'attention', 'urgent']).catch('info'),
        evidence: z.array(z.string().max(120)).max(8).default([]),
      }),
    )
    .max(8)
    .default([]),
  suggestedActions: z
    .array(
      z.object({
        label: z.string().min(1).max(120),
        detail: z.string().min(1).max(400),
        metricKey: z.string().max(120).nullish(),
      }),
    )
    .max(6)
    .default([]),
});

/**
 * Cut a reply at the marker.
 *
 * A model that forgets the marker entirely is not an error: everything it
 * wrote is prose, there is no structured part, and the panel shows a summary
 * with no findings under it. That is a worse answer and a correct one, which
 * is the right way round.
 */
function splitReply(text: string): { prose: string; detail: string } {
  const at = text.indexOf(DETAIL_MARKER);
  if (at === -1) return { prose: text.trim(), detail: '' };

  return {
    prose: text.slice(0, at).trim(),
    detail: text.slice(at + DETAIL_MARKER.length),
  };
}

/**
 * The first JSON object in a reply.
 *
 * Models wrap JSON in a fenced block or preface it with a sentence often
 * enough that treating the whole string as JSON fails for a reason that has
 * nothing to do with the answer being wrong. This finds the outermost braces
 * and parses those.
 */
function extractJson(text: string): unknown {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start === -1 || end <= start) return null;

  try {
    return JSON.parse(text.slice(start, end + 1));
  } catch {
    return null;
  }
}

/**
 * Strip everything the model was not entitled to say.
 *
 * This is the control that makes the whole feature safe to point at real
 * operational data, so it is deliberately blunt:
 *
 *   - **A citation of a metric key that was not in the bundle is dropped.**
 *     Not corrected, not passed through with a warning: dropped. A fabricated
 *     key is the model having invented a fact, and there is no repair for that
 *     which is better than silence.
 *   - **A finding left with no evidence at all is dropped.** The panel's
 *     promise is that every claim can be checked against a figure on the same
 *     screen, and a finding with nothing behind it breaks that promise more
 *     quietly than a wrong number would.
 *   - **A link is never taken from the reply.** `href` is copied from the
 *     metric the action cites. A model-generated URL in an operations console
 *     is a URL somebody clicks.
 */
function sanitise(
  parsed: z.infer<typeof modelReply>,
  metrics: readonly InsightMetric[],
): { findings: InsightFinding[]; actions: InsightAction[] } {
  const byKey = new Map(metrics.map((metric) => [metric.key, metric]));

  const findings: InsightFinding[] = [];
  for (const finding of parsed.findings) {
    const evidence = finding.evidence.filter((key) => byKey.has(key));
    if (evidence.length === 0) continue;

    findings.push({
      title: finding.title,
      detail: finding.detail,
      severity: finding.severity,
      evidence,
    });
  }

  const actions: InsightAction[] = [];
  for (const action of parsed.suggestedActions) {
    const key = action.metricKey ?? null;
    const metric = key === null ? undefined : byKey.get(key);

    actions.push({
      label: action.label,
      detail: action.detail,
      metricKey: metric === undefined ? null : metric.key,
      href: metric?.href ?? null,
    });
  }

  return { findings: findings.slice(0, 4), actions: actions.slice(0, 3) };
}

// ---------------------------------------------------------------------------
// The deterministic answer
// ---------------------------------------------------------------------------

const SEVERITY_RANK: Readonly<Record<MetricSeverity, number>> = Object.freeze({
  urgent: 0,
  attention: 1,
  info: 2,
});

/**
 * The same panel, with no provider behind it.
 *
 * Ranks the metrics that are actually holding a number by how much they want
 * somebody, and says so. Every sentence is built from a figure the server
 * measured, so this path cannot be wrong about anything either — it is simply
 * less fluent, and it says which it is.
 */
export function deterministicInsight(
  request: InsightRequest,
  reason: NonNullable<Insight['fallbackReason']>,
): Insight {
  const generatedAt = new Date().toISOString();

  const pressing = request.metrics
    .filter((metric) => metric.severity !== 'info' && metric.value > 0)
    .sort(
      (a, b) =>
        SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity] || b.value - a.value,
    );

  const findings: InsightFinding[] = pressing.slice(0, 4).map((metric) => ({
    title: `${metric.label}: ${String(metric.value)}`,
    detail: `${String(metric.value)} ${metric.unit} in this queue over the selected period.`,
    severity: metric.severity,
    evidence: [metric.key],
  }));

  const summary =
    pressing.length === 0
      ? 'Nothing in this period needs attention. Every queue with a threshold is clear.'
      : `${String(pressing.length)} ${pressing.length === 1 ? 'queue needs' : 'queues need'} attention in this period. ` +
        `The largest is ${pressing[0]?.label ?? ''} at ${String(pressing[0]?.value ?? 0)} ${pressing[0]?.unit ?? ''}.`;

  return {
    summary,
    findings,
    suggestedActions: pressing.slice(0, 3).map((metric) => ({
      label: `Review ${metric.label.toLowerCase()}`,
      detail: `${String(metric.value)} ${metric.unit} waiting.`,
      metricKey: metric.key,
      href: metric.href ?? null,
    })),
    evidence: evidenceFor(request.metrics),
    generatedAt,
    window: request.window,
    metricKeys: request.metrics.map((metric) => metric.key),
    source: 'deterministic',
    model: null,
    fallbackReason: reason,
  };
}

/** Every metric in the bundle, as citable evidence. */
function evidenceFor(metrics: readonly InsightMetric[]): InsightEvidence[] {
  return metrics.map((metric) => ({
    metricKey: metric.key,
    label: metric.label,
    value: metric.value,
    unit: metric.unit,
    href: metric.href ?? null,
  }));
}

// ---------------------------------------------------------------------------
// The entry point
// ---------------------------------------------------------------------------

/** How long a dashboard waits before falling back. A panel is read, not chatted with. */
const TIMEOUT_MS = 20_000;

/**
 * An insight for a bundle of metrics.
 *
 * Never throws for a provider problem. Every failure — no key, a timeout, a
 * quota, an unparseable reply — comes back as the deterministic answer with
 * `fallbackReason` set, because a dashboard whose insight panel can take the
 * page down is a dashboard with a worse uptime than the database behind it.
 */
/**
 * The same insight, with the readable part delivered as it is written.
 *
 * `onDelta` receives only the prose before the marker — never a fragment of
 * JSON, and never a citation that has not been checked yet. The structured
 * half is buffered, parsed and sanitised exactly as `buildInsight` does it,
 * and the finished `Insight` is returned for the caller to send last.
 *
 * That ordering is the point. A reader watches a summary appear, and the
 * findings underneath it arrive only once every key they cite has been
 * verified against the bundle — so streaming buys responsiveness without
 * buying a window in which an unvalidated claim is on screen.
 *
 * Never throws for a provider problem, for the same reason `buildInsight`
 * does not: the deterministic answer is streamed instead, in one delta, with
 * `fallbackReason` set.
 */
export async function streamInsight(
  request: InsightRequest,
  onDelta: (text: string) => void,
  signal?: AbortSignal,
): Promise<Insight> {
  const provider = activeProvider();

  if (provider === null) {
    const insight = deterministicInsight(request, 'not-configured');
    onDelta(insight.summary);
    return insight;
  }

  const controller = new AbortController();
  const timer = setTimeout(() => {
    controller.abort();
  }, TIMEOUT_MS);

  // The caller's own abort — a reader closing the panel — must also stop the
  // generation this deployment is paying for.
  signal?.addEventListener('abort', () => {
    controller.abort();
  });

  try {
    let text = '';
    /*
     * How much of the prose has already been sent.
     *
     * The marker can arrive split across two deltas ("---DET" then "AIL---"),
     * so nothing is forwarded until it is certain it is not the beginning of
     * one. Holding back the last few characters is what makes that safe, and
     * it costs the reader nothing they can perceive.
     */
    let sent = 0;
    let markerSeen = false;

    const result = await provider.stream({
      systemPrompt: BEHAVIOUR,
      catalogue: AUDIENCE_CONTEXT[request.audience],
      turns: [{ role: 'user', content: renderContext(request) }],
      maxTokens: 900,
      signal: controller.signal,
      onText: (delta) => {
        text += delta;
        if (markerSeen) return;

        const at = text.indexOf(DETAIL_MARKER);

        if (at !== -1) {
          markerSeen = true;
          const remaining = text.slice(sent, at);
          if (remaining.length > 0) onDelta(remaining);
          sent = at;
          return;
        }

        // Keep back enough characters that a partial marker cannot escape.
        const safeUpTo = Math.max(sent, text.length - DETAIL_MARKER.length);
        if (safeUpTo > sent) {
          onDelta(text.slice(sent, safeUpTo));
          sent = safeUpTo;
        }
      },
    });

    if (result.refused) {
      logger.warn({ audience: request.audience }, 'insight provider refused');
      const insight = deterministicInsight(request, 'unusable');
      onDelta(insight.summary);
      return insight;
    }

    const { prose, detail } = splitReply(text);

    // Whatever was held back at the end, now that the reply is complete.
    if (!markerSeen && prose.length > sent) onDelta(prose.slice(sent));

    const parsed = modelReply.safeParse(extractJson(detail));

    /*
     * A summary with no parseable detail is still a usable answer, so this is
     * NOT the deterministic fallback: the prose already reached the reader and
     * replacing it now would rewrite what they just watched arrive. The
     * findings are simply empty, and `fallbackReason` records why.
     */
    if (!parsed.success) {
      logger.warn({ audience: request.audience }, 'insight detail did not parse');

      return {
        summary: prose,
        findings: [],
        suggestedActions: [],
        evidence: evidenceFor(request.metrics),
        generatedAt: new Date().toISOString(),
        window: request.window,
        metricKeys: request.metrics.map((metric) => metric.key),
        source: 'model',
        model: result.model,
        fallbackReason: 'unusable',
      };
    }

    const { findings, actions } = sanitise(parsed.data, request.metrics);

    return {
      summary: prose,
      findings,
      suggestedActions: actions,
      evidence: evidenceFor(request.metrics),
      generatedAt: new Date().toISOString(),
      window: request.window,
      metricKeys: request.metrics.map((metric) => metric.key),
      source: 'model',
      model: result.model,
      fallbackReason: null,
    };
  } catch (error) {
    const busy = error instanceof AssistantBusyError;
    logger.warn({ err: error, audience: request.audience, busy }, 'insight stream unavailable');

    const insight = deterministicInsight(request, 'unavailable');
    // Only if nothing reached them yet; half a model answer followed by a
    // different deterministic one is two answers to one question.
    if (!signal?.aborted) onDelta(insight.summary);
    return insight;
  } finally {
    clearTimeout(timer);
  }
}

export async function buildInsight(request: InsightRequest): Promise<Insight> {
  const provider = activeProvider();

  if (provider === null) return deterministicInsight(request, 'not-configured');

  const controller = new AbortController();
  const timer = setTimeout(() => {
    controller.abort();
  }, TIMEOUT_MS);

  try {
    let text = '';

    const result = await provider.stream({
      systemPrompt: BEHAVIOUR,
      // The catalogue seam this interface was built for carries the cacheable
      // middle of the prompt. Here that is the audience's own framing, which
      // is one of three fixed strings and therefore cacheable in the same way.
      catalogue: AUDIENCE_CONTEXT[request.audience],
      turns: [{ role: 'user', content: renderContext(request) }],
      maxTokens: 900,
      signal: controller.signal,
      onText: (delta) => {
        text += delta;
      },
    });

    if (result.refused) {
      logger.warn({ audience: request.audience }, 'insight provider refused');
      return deterministicInsight(request, 'unusable');
    }

    const { prose, detail } = splitReply(text);
    const parsed = modelReply.safeParse(extractJson(detail));

    if (!parsed.success) {
      logger.warn(
        { audience: request.audience, issues: parsed.error.issues.length },
        'insight reply did not parse',
      );
      return deterministicInsight(request, 'unusable');
    }

    const { findings, actions } = sanitise(parsed.data, request.metrics);

    return {
      summary: prose,
      findings,
      suggestedActions: actions,
      evidence: evidenceFor(request.metrics),
      generatedAt: new Date().toISOString(),
      window: request.window,
      metricKeys: request.metrics.map((metric) => metric.key),
      source: 'model',
      model: result.model,
      fallbackReason: null,
    };
  } catch (error) {
    // A busy provider, a quota, an abort, a socket. All of them mean the same
    // thing to the reader: there is no model answer right now.
    const busy = error instanceof AssistantBusyError;
    logger.warn(
      { err: error, audience: request.audience, busy },
      'insight provider unavailable, falling back',
    );

    return deterministicInsight(request, 'unavailable');
  } finally {
    clearTimeout(timer);
  }
}
