const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.UBOSS_PHONE_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(process.argv[2]),dir=path.join(root,'output/pass10-hero'),url='http://127.0.0.1:5198/output/search-preview/index.html';fs.mkdirSync(dir,{recursive:true});
async function claim(page,line,basis){const paragraph=page.locator('p').filter({has:page.getByText(basis,{exact:true})});await paragraph.waitFor();assert.equal(await paragraph.evaluate(el=>Array.from(el.childNodes).filter(n=>n.nodeType===Node.TEXT_NODE).map(n=>n.textContent).join('')),line);assert.equal(await paragraph.locator('span').innerText(),basis);}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const results=[];try{for(const width of [320,375,1280]){
 const context=await browser.newContext({viewport:{width,height:812},isMobile:width<500,hasTouch:width<500});await context.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:5198/')?route.continue():route.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const checkBounds=async label=>{const bounds=await page.evaluate(()=>({width:innerWidth,clientWidth:document.documentElement.clientWidth,documentWidth:document.documentElement.scrollWidth}));assert.ok(bounds.documentWidth <= bounds.clientWidth && bounds.clientWidth <= width,label+' horizontal overflow');};
 await page.goto(url,{waitUntil:'networkidle'});await claim(page,'Source from verified Indian manufacturers','Recorded verification by this marketplace; India is their registered country.');const input=page.getByRole('textbox',{name:'Search the catalogue',exact:true});await input.fill('Nitrile gloves & masks');const product=page.getByRole('link',{name:'Product',exact:true}),supplier=page.getByRole('link',{name:'Supplier',exact:true});assert.equal(await product.getAttribute('href'),'/products?q=Nitrile%20gloves%20%26%20masks');await checkBounds('hero');await page.screenshot({path:path.join(dir,'hero-'+width+'.png')});await product.focus();await page.keyboard.press('Tab');assert.ok(await supplier.evaluate(e=>e===document.activeElement));await page.keyboard.press('Enter');await page.getByRole('heading',{name:'Find a supplier',exact:true}).waitFor();const name=page.getByRole('textbox',{name:'Supplier public name',exact:true});assert.equal(await name.inputValue(),'Nitrile gloves & masks');await page.getByRole('link',{name:/Gloves manufacturer/}).waitFor();await checkBounds('suppliers');await page.screenshot({path:path.join(dir,'suppliers-'+width+'.png')});
 await name.fill('nomatch');await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByText('No approved suppliers matched. Try fewer words or clear the search.',{exact:true}).waitFor();await checkBounds('empty');await name.fill('retry');await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('alert').waitFor();await checkBounds('error');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('link',{name:/Gloves manufacturer/}).waitFor();await checkBounds('recovery');
 await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('textbox',{name:'Search the catalogue',exact:true}).fill('Nitrile gloves & masks');await page.getByRole('link',{name:'RFQ',exact:true}).click();await page.getByRole('heading',{name:'New request for quotation',exact:true}).waitFor();const title=page.getByRole('textbox',{name:'Title (required)',exact:true});assert.equal(await title.inputValue(),'Nitrile gloves & masks');await title.fill('Editable gloves requirement');assert.equal(await title.inputValue(),'Editable gloves requirement');const writes=await page.evaluate(()=>window.__searchCalls.filter(c=>c.url.includes('/rfqs')&&c.method!=='GET'));assert.deepEqual(writes,[]);await checkBounds('rfq');await page.screenshot({path:path.join(dir,'rfq-'+width+'.png')});
 await page.goto(url,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Image search',exact:true}).click();await page.getByRole('dialog').waitFor();await checkBounds('image');await page.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('button',{name:'Polski',exact:true}).click();const pl=JSON.parse(fs.readFileSync(path.join(root,'apps/customer-web/src/i18n/locales/pl.json')));await claim(page,pl['sourcingShortcuts.manufacturers'],pl['sourcingShortcuts.reviewBasis']);await page.getByRole('link',{name:pl['sourcingShortcuts.supplier'],exact:true}).click();await page.getByRole('heading',{name:pl['sourcingShortcuts.directoryTitle'],exact:true}).waitFor();await checkBounds('polish');await page.screenshot({path:path.join(dir,'polish-'+width+'.png')});const state=await page.evaluate(()=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,ids:Array.from(document.querySelectorAll('[id]')).map(e=>e.id)}));assert.equal(state.documentWidth,width);assert.equal(new Set(state.ids).size,state.ids.length);assert.deepEqual(errors,[]);results.push({width,manufacturerFact:true,productWords:true,supplierKeyboardNavigation:true,supplierWords:true,emptyAndRetry:true,editableRfqTitle:true,noRfqWrite:true,imageDialog:true,polishDestination:true,horizontalOverflow:false,duplicateIds:[],pageErrors:errors});await context.close();
 }fs.writeFileSync(path.join(dir,'browser-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));}finally{await browser.close();}})().catch(error=>{console.error(error.stack);process.exitCode=1});
