const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.UBOSS_PHONE_PLAYWRIGHT_MODULE || 'playwright');
const root=process.argv[2],dir=path.join(root,'output/pass10-summary');fs.mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:process.env.UBOSS_PHONE_BROWSER,headless:true}),results=[];
try{for(const width of [320,375]){const context=await browser.newContext({viewport:{width,height:812},isMobile:true,hasTouch:true,locale:'en-US',reducedMotion:'reduce'});await context.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:5197/')?route.continue():route.abort());const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:5197/output/phone-preview/index.html?case=summary',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Accept these terms',exact:true}).tap();const dialog=page.getByRole('dialog'),sheet=dialog.getByRole('region',{name:'Final term sheet'});await sheet.waitFor();await page.waitForFunction(()=>{const el=document.querySelector('dialog[open]');return el!==null&&Number(getComputedStyle(el).opacity)>=0.999;});assert.equal(await sheet.locator('[data-term]').count(),18);assert.equal(await page.evaluate(()=>window.__phoneCalls.filter(c=>c.method==='POST').length),0);
const bounds=await dialog.evaluate(el=>({width:innerWidth,documentWidth:document.documentElement.scrollWidth,rect:el.getBoundingClientRect().toJSON()}));assert.equal(bounds.documentWidth,width);assert.ok(bounds.rect.left>=0&&bounds.rect.right<=width&&bounds.rect.top>=0&&bounds.rect.bottom<=812);
await page.screenshot({path:path.join(dir,'summary-'+width+'.png'),fullPage:false});await sheet.locator('[data-term="exportDocuments"]').scrollIntoViewIfNeeded();assert.ok((await sheet.locator('[data-term="exportDocuments"]').innerText()).includes('Certificate of origin'));await page.screenshot({path:path.join(dir,'summary-scrolled-'+width+'.png'),fullPage:false});
await dialog.getByRole('button',{name:'Accept these terms',exact:true}).tap();await page.waitForFunction(()=>window.__phoneCalls.some(c=>c.method==='POST'&&c.url.endsWith('/accept')));const call=await page.evaluate(()=>window.__phoneCalls.find(c=>c.method==='POST'&&c.url.endsWith('/accept')));assert.deepEqual(call.body,{versionId:'v2',termsHash:'b'.repeat(64)});assert.deepEqual(errors,[]);results.push({width,bounds,clauses:18,body:call.body,errors});await context.close();}fs.writeFileSync(path.join(dir,'browser-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results));}finally{await browser.close();}})().catch(error=>{console.error(error.stack);process.exitCode=1;});
