// Adds "how to verify" steps to every Master row that has none, so Checklist.md
// explains each row: what to open and see for a done row, and for a row that is
// not done, why not and how it will be verified once built.
const fs=require('fs');const file='verification-evidence/pass4/state.json';const s=JSON.parse(fs.readFileSync(file,'utf8'));
const S='http://localhost:5174', A='http://localhost:5173';
const URL={13:`${S}/seller/factories`,14:`${S}/account/rfqs/new`,15:`${S}/account/dashboard`,16:`${S}/account/rfqs`,17:`${S}/account/rfqs/<id>/compare`,18:`${S}/account/rfqs/<id>/quotes/<quoteId>`,19:`${S}/account/rfqs/<id>`,24:`${S}/account/orders/<id>/claim, then /account/disputes`,25:`${S}/cart`,26:`${S}/checkout`,27:`${S}/checkout/payment/<orderId>`,28:`${S}/account/orders`,29:`${S}/account/orders/<id>`,30:`${S}/account/orders/<id>/return, then /account/returns`,31:`${S}/account/reviews`,32:`${S}/account/wishlist`,34:`${S}/seller/factories and /seller/profile`,35:`${S}/seller/listings`,36:`${S}/seller/listings/<id>/edit`,38:`${S}/seller/rfqs`,39:`${S}/seller/rfqs/<id> (Quote tab)`,57:`${S}/account/orders/<id> (tracking)`,62:`${S}/account/messages`,63:`${S}/support`,64:`${A}/disputes`,65:`${A}/customers and ${A}/sellers`,66:`${A}/sellers/<id>`,67:`${A}/listing-review`,68:`${A}/orders`,73:`${A}/audit`,77:`${A}/integrations (Payment reconciliation)`,78:`${S}/account/dashboard (Buy again)`,79:`${S}/ (language/country/currency menu)`,80:`${S}/ (theme toggle)`,81:`${S}/ai (AI Mode)`,82:`${S}/ (camera icon in the search box)`,83:`${S}/ (microphone in the search box)`,84:`${S}/account/schedules`,85:`${S}/account/autopay`,86:`${S}/account/integrations`,88:`${S}/account/dashboard (Continue sourcing)`,89:`${S}/tools/landed-cost`,90:`${S}/products?q=gloves`,91:`${S}/account`,93:`${S}/suppliers/<slug> (badge)`,96:`${S}/account/erp`,97:`${S}/account/notifications`};
const INSP='Not done: needs the inspection feature. The rules, jobs, evidence, release and gate services exist in backend/src/modules/inspection, but there are no HTTP routes and no agency, inspector or buyer screens yet.';
const WHY={20:'Blocked: needs the paid-sample checkout (sample fee, tax and shipping through the existing checkout).',22:'Not done: no B2B order milestones (production, inspection, shipment, documents, payment) exist yet.',33:'Not done: the seller dashboard shows sales, orders and payouts but no RFQ, inspection or compliance items. Inspection must be built first.',92:'Not done: same gap as row 33 - Seller Hub home lacks RFQ, inspection and compliance queues.',37:'Not done: bulk catalogue import exists for the operator (admin Product import) but not for sellers.',40:'Not done: no seller production milestones (confirm, manufacture, ready, exceptions).',41:INSP,42:'Not done: no shipment document pack (invoice, packing list, COO, BL/AWB).',43:'Not done: settlements and fees are shown, but reserves and reconciliation need the payout build (decision D13: facilitator + Stripe Connect).',44:'Not done: no seller performance analytics (conversion, OTIF, quality, cancellations, claims).',56:'Not done: no shipment booking (mode, carrier, route, Incoterm, pickup, port).',58:'Not done: escrow / milestone payments wait on the Stripe Connect payout build (D13).',59:'Not done: no transaction ledger screen; waits on the payout build (D13).',60:'Not done: seller settlement release and bank payout wait on the payout build (D13).',61:'Not done: chargeback accounting screen waits on the payout build (D13). Buyer refunds and disputes are built (rows 24, 30, 64).',69:'Not done: no country compliance rules (restricted goods, documents, thresholds).',71:'Not done: no logistics rate cards or serviceability rules in the admin.',72:'Not done: no CMS / banners / promotions module.',74:'Not done: reports cover sales, orders, payments, inventory and customers; GMV by supplier quality, inspection, disputes and settlement reports are missing, and inspection must exist first.',75:'Not done: categories and currencies exist; units of measure, Incoterms and defect codes as master data do not.',76:'Not done: email and SMS templates can be edited through the API (settings/notifications) but there is no admin screen, and WhatsApp / in-app templates do not exist.',87:'Not done: no saved searches or alerts (needs a table and an alert job).',94:INSP,95:INSP};
for(const id of [23,45,46,47,48,49,50,51,52,53,54,55,70])WHY[id]=INSP;
let added=0;
for(const r of s.rows){
  if(Array.isArray(r.manual)&&r.manual.length>0)continue;
  const done=r.status==='VERIFIED'||r.status==='FIXED_AND_VERIFIED';
  if(done){
    r.manual=[`Start the stack (.\scripts\dev-stack.ps1) and sign in as the right role. Open ${URL[r.id]??'the screen named in this row'}.`,
      r.fix&&r.fix!=='No change needed.'&&r.fix!=='No product change needed.'?`Check what was built: ${r.fix}`:'Check that every item in the row\'s requirement is present on the screen.',
      `Automated proof recorded: ${r.tests??r.testResult??r.evidence??r.verification??'see the Evidence column'}.`];
  }else{
    r.manual=[WHY[r.id]??'Not done yet: see the triage table at the top of this file.',
      'Once built, verify it the same way as the rows above: open the screen, do the main action and one failure case, check it in two languages and at phone width, and run the new automated tests.'];
  }
  added++;
}
fs.writeFileSync(file,JSON.stringify(s,null,2)+'\n');console.log('added',added);
