/**
 * Checkout.
 *
 * The whole page exists to get one thing right: **exactly one order is
 * created, whatever the customer or their network does.**
 *
 *   - The idempotency key is generated once, when the page mounts, and reused
 *     for every attempt. A new key per click is precisely the duplicate-order
 *     bug the header exists to prevent, so it is created outside the submit
 *     handler where nobody can accidentally regenerate it.
 *   - The submit button disables while in flight, but that is the weak guard.
 *     The strong one is the key: a customer who double-clicks, retries after a
 *     timeout, or refreshes and submits again still gets one order, and the
 *     server tells us with `replayed` which of those happened.
 *   - Nothing is inferred about payment. Checkout creates the order; payment
 *     happens on the next page and is only ever confirmed by the backend.
 *
 * The totals shown here are the server's, re-read with the chosen delivery
 * method. This page never adds tax or shipping itself — a second pricing
 * engine that eventually disagrees with the first is worse than no preview.
 */
import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useStorefront } from '@/app/storefront-context';
import { AddressForm } from '@/components/AddressForm';
import { Button, ErrorState, Field, LoadingState, Textarea } from '@/components/ui';
import { ApiError, NetworkError, api, newIdempotencyKey } from '@/lib/api';
import { formatMoney, formatNumber } from '@/lib/format';
import { useDocumentMeta } from '@/lib/useDocumentMeta';
import type { Address, Cart, CheckoutResult } from '@/lib/types';

type PaymentMode = 'ONLINE' | 'PAYMENT_LINK';

function AddressCard({
  address,
  isSelected,
  onSelect,
}: {
  address: Address;
  isSelected: boolean;
  onSelect: () => void;
}): React.JSX.Element {
  return (
    <label
      className={`flex cursor-pointer gap-3 rounded-lg border p-4 transition-colors ${
        isSelected ? 'border-brand bg-brand-soft' : 'border-border bg-surface hover:border-brand/40'
      }`}
    >
      <input
        type="radio"
        name="shippingAddress"
        className="mt-1 h-4 w-4 border-border-strong text-brand"
        checked={isSelected}
        onChange={onSelect}
      />
      <span className="min-w-0 text-sm">
        {address.label !== null && (
          <span className="block font-medium text-ink">{address.label}</span>
        )}
        <span className="block font-medium text-ink">{address.contactName}</span>
        <span className="mt-0.5 block text-ink-muted">
          {address.line1}
          {address.line2 !== null && `, ${address.line2}`}, {address.city}, {address.state}{' '}
          {address.postalCode}, {address.country}
        </span>
        <span className="mt-0.5 block text-xs text-ink-subtle">{address.contactPhone}</span>
      </span>
    </label>
  );
}

export function CheckoutPage(): React.JSX.Element {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { business } = useStorefront();

  const [shippingAddressId, setShippingAddressId] = useState<string | null>(null);
  const [billingSameAsShipping, setBillingSameAsShipping] = useState(true);
  const [billingAddressId, setBillingAddressId] = useState<string | null>(null);
  const [paymentMode, setPaymentMode] = useState<PaymentMode>('ONLINE');
  const [customerNote, setCustomerNote] = useState('');
  const [isAddingAddress, setIsAddingAddress] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  useDocumentMeta({ title: 'Checkout', noIndex: true }, business.displayName);

  /**
   * One key for this checkout attempt, for the life of the page.
   *
   * Created here rather than inside the submit handler so it cannot be
   * regenerated by a re-render or a retry. Every attempt from this page — a
   * double click, a retry after a timeout — carries the same key, and the
   * server answers with the same order.
   */
  const idempotencyKey = useMemo(() => newIdempotencyKey(), []);

  const addresses = useQuery({
    queryKey: ['addresses'],
    queryFn: () => api.get<{ addresses: Address[] }>('/account/addresses'),
  });

  const cart = useQuery({
    queryKey: ['cart'],
    queryFn: () => api.get<{ cart: Cart }>('/cart'),
  });

  const usableAddresses = useMemo(
    () => (addresses.data?.addresses ?? []).filter((address) => address.archivedAt === null),
    [addresses.data],
  );

  // Preselect the customer's default so the common case is zero clicks.
  useEffect(() => {
    if (shippingAddressId !== null || usableAddresses.length === 0) return;

    const preferred =
      usableAddresses.find((address) => address.isDefaultShipping) ?? usableAddresses[0];

    setShippingAddressId(preferred?.id ?? null);
  }, [usableAddresses, shippingAddressId]);

  const submit = useMutation({
    mutationFn: () =>
      api.post<CheckoutResult>(
        '/cart/checkout',
        {
          shippingAddressId,
          ...(billingSameAsShipping || billingAddressId === null
            ? {}
            : { billingAddressId }),
          paymentMode,
          customerNote: customerNote.trim() === '' ? null : customerNote.trim(),
        },
        { idempotencyKey },
      ),
    onSuccess: async (result) => {
      setSubmitError(null);

      // The cart is now an order; anything cached about it is stale.
      await queryClient.invalidateQueries({ queryKey: ['cart'] });
      await queryClient.invalidateQueries({ queryKey: ['orders'] });

      // Payment happens on its own page, which owns the provider handshake and
      // the wait for a verified result. Nothing about payment is decided here.
      if (result.paymentMode === 'ONLINE' && !result.requiresApproval) {
        void navigate(`/checkout/payment/${result.orderId}`, {
          replace: true,
          state: { replayed: result.replayed === true },
        });
        return;
      }

      void navigate(`/order-confirmation/${result.orderId}`, {
        replace: true,
        state: { replayed: result.replayed === true },
      });
    },
    onError: (error) => {
      if (error instanceof NetworkError) {
        // The order may or may not have been created. The same key is still
        // held, so retrying is safe and will not produce a second one —
        // which is exactly what the message promises.
        setSubmitError(
          `${error.message} If your order did go through, trying again will not create a second one.`,
        );
        return;
      }

      setSubmitError(
        error instanceof ApiError ? error.message : 'Your order could not be placed. Please try again.',
      );

      // A rejection usually means the cart changed underneath — re-read it so
      // the customer sees what the server is objecting to.
      void queryClient.invalidateQueries({ queryKey: ['cart'] });
    },
  });

  if (cart.isPending || addresses.isPending) return <LoadingState label="Preparing your checkout" />;

  if (cart.isError) {
    return (
      <ErrorState
        error={cart.error}
        onRetry={() => {
          void cart.refetch();
        }}
      />
    );
  }

  const currentCart = cart.data.cart;

  if (currentCart.lines.length === 0) {
    return (
      <div className="mx-auto max-w-lg py-16 text-center">
        <h1 className="text-2xl font-semibold tracking-tight text-ink">Your cart is empty</h1>
        <p className="mt-3 text-sm text-ink-muted">There is nothing to check out.</p>
        <Link
          to="/products"
          className="mt-6 inline-flex h-12 items-center rounded-md bg-action px-6 text-base font-medium text-white hover:bg-action-hover"
        >
          Browse products
        </Link>
      </div>
    );
  }

  const canSubmit =
    currentCart.checkoutReady && shippingAddressId !== null && !submit.isPending;

  return (
    <>
      <h1 className="mb-6 text-2xl font-semibold tracking-tight text-ink">Checkout</h1>

      <div className="grid gap-6 lg:grid-cols-[1fr_22rem]">
        <div className="space-y-6">
          {/* --- Delivery address ------------------------------------------ */}
          <section aria-labelledby="address-heading" className="rounded-lg border border-border bg-surface p-5">
            <h2 id="address-heading" className="text-base font-semibold text-ink">
              Delivery address
            </h2>

            {usableAddresses.length === 0 && !isAddingAddress && (
              <div className="mt-3">
                <p className="text-sm text-ink-muted">
                  You have no saved addresses yet. Add one to continue.
                </p>
                <Button
                  variant="primary"
                  className="mt-3"
                  onClick={() => {
                    setIsAddingAddress(true);
                  }}
                >
                  Add an address
                </Button>
              </div>
            )}

            {usableAddresses.length > 0 && (
              <fieldset className="mt-3">
                <legend className="sr-only">Choose a delivery address</legend>
                <div className="space-y-2">
                  {usableAddresses.map((address) => (
                    <AddressCard
                      key={address.id}
                      address={address}
                      isSelected={address.id === shippingAddressId}
                      onSelect={() => {
                        setShippingAddressId(address.id);
                      }}
                    />
                  ))}
                </div>
              </fieldset>
            )}

            {isAddingAddress ? (
              <div className="mt-4 border-t border-border pt-4">
                <h3 className="mb-3 text-sm font-medium text-ink">New address</h3>
                <AddressForm
                  onSaved={(addressId) => {
                    setShippingAddressId(addressId);
                    setIsAddingAddress(false);
                  }}
                  onCancel={() => {
                    setIsAddingAddress(false);
                  }}
                />
              </div>
            ) : (
              usableAddresses.length > 0 && (
                <Button
                  size="sm"
                  className="mt-3"
                  onClick={() => {
                    setIsAddingAddress(true);
                  }}
                >
                  Add a different address
                </Button>
              )
            )}

            {usableAddresses.length > 0 && (
              <div className="mt-4 border-t border-border pt-4">
                <label className="flex items-center gap-2 text-sm text-ink">
                  <input
                    type="checkbox"
                    className="h-4 w-4 rounded border-border-strong text-brand"
                    checked={billingSameAsShipping}
                    onChange={(event) => {
                      setBillingSameAsShipping(event.target.checked);
                      if (event.target.checked) setBillingAddressId(null);
                    }}
                  />
                  Bill to the same address
                </label>

                {!billingSameAsShipping && (
                  <fieldset className="mt-3">
                    <legend className="mb-2 text-sm font-medium text-ink">Billing address</legend>
                    <div className="space-y-2">
                      {usableAddresses.map((address) => (
                        <label
                          key={address.id}
                          className={`flex cursor-pointer gap-3 rounded-lg border p-3 text-sm ${
                            address.id === billingAddressId
                              ? 'border-brand bg-brand-soft'
                              : 'border-border bg-surface'
                          }`}
                        >
                          <input
                            type="radio"
                            name="billingAddress"
                            className="mt-0.5 h-4 w-4 border-border-strong text-brand"
                            checked={address.id === billingAddressId}
                            onChange={() => {
                              setBillingAddressId(address.id);
                            }}
                          />
                          <span>
                            {address.contactName} — {address.line1}, {address.city}
                          </span>
                        </label>
                      ))}
                    </div>
                  </fieldset>
                )}
              </div>
            )}
          </section>

          {/* --- How to pay ------------------------------------------------- */}
          <section aria-labelledby="payment-heading" className="rounded-lg border border-border bg-surface p-5">
            <h2 id="payment-heading" className="text-base font-semibold text-ink">
              How would you like to pay?
            </h2>

            <fieldset className="mt-3">
              <legend className="sr-only">Payment method</legend>

              <div className="space-y-2">
                <label
                  className={`flex cursor-pointer gap-3 rounded-lg border p-4 ${
                    paymentMode === 'ONLINE'
                      ? 'border-brand bg-brand-soft'
                      : 'border-border bg-surface hover:border-brand/40'
                  }`}
                >
                  <input
                    type="radio"
                    name="paymentMode"
                    className="mt-1 h-4 w-4 border-border-strong text-brand"
                    checked={paymentMode === 'ONLINE'}
                    onChange={() => {
                      setPaymentMode('ONLINE');
                    }}
                  />
                  <span className="text-sm">
                    <span className="block font-medium text-ink">Pay now</span>
                    <span className="mt-0.5 block text-ink-muted">
                      You will be taken to our payment provider to complete the payment securely.
                      Card details never touch this site.
                    </span>
                  </span>
                </label>

                <label
                  className={`flex cursor-pointer gap-3 rounded-lg border p-4 ${
                    paymentMode === 'PAYMENT_LINK'
                      ? 'border-brand bg-brand-soft'
                      : 'border-border bg-surface hover:border-brand/40'
                  }`}
                >
                  <input
                    type="radio"
                    name="paymentMode"
                    className="mt-1 h-4 w-4 border-border-strong text-brand"
                    checked={paymentMode === 'PAYMENT_LINK'}
                    onChange={() => {
                      setPaymentMode('PAYMENT_LINK');
                    }}
                  />
                  <span className="text-sm">
                    <span className="block font-medium text-ink">Send a payment link</span>
                    <span className="mt-0.5 block text-ink-muted">
                      Place the order now and have a secure payment link emailed for approval. The
                      order waits at Pending payment until it is paid.
                    </span>
                  </span>
                </label>
              </div>
            </fieldset>
          </section>

          {/* --- Note ------------------------------------------------------- */}
          <section aria-labelledby="note-heading" className="rounded-lg border border-border bg-surface p-5">
            <h2 id="note-heading" className="text-base font-semibold text-ink">
              Anything we should know?
            </h2>
            <div className="mt-3">
              <Field label="Note for this order" hint="Optional. Delivery instructions, a PO number, a site contact.">
                {({ inputId, describedBy }) => (
                  <Textarea
                    id={inputId}
                    rows={3}
                    value={customerNote}
                    maxLength={2000}
                    aria-describedby={describedBy}
                    onChange={(event) => {
                      setCustomerNote(event.target.value);
                    }}
                  />
                )}
              </Field>
            </div>
          </section>
        </div>

        {/* --- Review and place ---------------------------------------------- */}
        <aside aria-labelledby="review-heading" className="lg:sticky lg:top-40 lg:self-start">
          <div className="rounded-lg border border-border bg-surface p-5">
            <h2 id="review-heading" className="text-base font-semibold text-ink">
              Your order
            </h2>

            <ul className="mt-3 max-h-56 space-y-2 overflow-y-auto text-sm">
              {currentCart.lines.map((line) => (
                <li key={line.itemId} className="flex justify-between gap-3">
                  <span className="min-w-0 text-ink-muted">
                    <span className="block truncate text-ink">{line.name}</span>
                    <span className="text-xs">× {formatNumber(line.quantity)}</span>
                  </span>
                  <span className="shrink-0 tabular text-ink">{formatMoney(line.lineTotal)}</span>
                </li>
              ))}
            </ul>

            <dl className="mt-4 space-y-2 border-t border-border pt-4 text-sm">
              <div className="flex justify-between">
                <dt className="text-ink-muted">Subtotal</dt>
                <dd className="tabular text-ink">{formatMoney(currentCart.totals.subtotal)}</dd>
              </div>
              {currentCart.totals.discount.minor !== '0' && (
                <div className="flex justify-between">
                  <dt className="text-ink-muted">Discount</dt>
                  <dd className="tabular text-success">
                    −{formatMoney(currentCart.totals.discount)}
                  </dd>
                </div>
              )}
              <div className="flex justify-between">
                <dt className="text-ink-muted">Tax</dt>
                <dd className="tabular text-ink">{formatMoney(currentCart.totals.tax)}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-ink-muted">Delivery</dt>
                <dd className="tabular text-ink">{formatMoney(currentCart.totals.shipping)}</dd>
              </div>
              <div className="flex justify-between border-t border-border pt-2 text-base font-semibold">
                <dt>Total</dt>
                <dd className="tabular">{formatMoney(currentCart.totals.grandTotal)}</dd>
              </div>
            </dl>

            {currentCart.requiresApproval && (
              <div
                role="status"
                className="mt-4 rounded-md border border-warning/30 bg-warning-soft px-3 py-2.5 text-xs text-ink"
              >
                <p className="font-medium text-warning">This order needs approval</p>
                <p className="mt-0.5">
                  {currentCart.approvalReason ??
                    'It goes to your approver before it is confirmed. You will be told when it is.'}
                </p>
              </div>
            )}

            {currentCart.blockingIssues.length > 0 && (
              <div
                role="alert"
                className="mt-4 rounded-md border border-danger/30 bg-danger-soft px-3 py-2.5 text-xs"
              >
                <p className="font-medium text-danger">Fix these before placing the order</p>
                <ul className="mt-1 space-y-1 text-ink">
                  {currentCart.blockingIssues.map((issue) => (
                    <li key={`${issue.code}:${issue.message}`}>{issue.message}</li>
                  ))}
                </ul>
                <Link
                  to="/cart"
                  className="mt-2 inline-block font-semibold text-ink underline underline-offset-2"
                >
                  Back to the cart
                </Link>
              </div>
            )}

            {submitError !== null && (
              <div
                role="alert"
                className="mt-4 rounded-md border border-danger/30 bg-danger-soft px-3 py-2.5 text-sm text-danger"
              >
                {submitError}
              </div>
            )}

            <Button
              variant="action"
              size="lg"
              fullWidth
              className="mt-5"
              disabled={!canSubmit}
              isLoading={submit.isPending}
              onClick={() => {
                submit.mutate();
              }}
            >
              {paymentMode === 'ONLINE' ? 'Place order and pay' : 'Place order'}
            </Button>

            {shippingAddressId === null && (
              <p className="mt-2 text-center text-xs text-ink-muted">
                Choose a delivery address to continue.
              </p>
            )}

            <p className="mt-3 text-center text-xxs text-ink-subtle">
              Placing this order does not charge you yet. Payment is taken on the next step and is
              only confirmed once our payment provider verifies it.
            </p>
          </div>
        </aside>
      </div>
    </>
  );
}
