// Pass 4: regenerates the Master Checklist section at the top of Checklist.md
// from state.json and the live Word counts. Run: node verification-evidence/pass4/build-report.cjs
// The older pass 1-3 report below the marker is kept untouched.
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const AdmZip = require(path.join(__dirname, '../../scripts/node_modules/adm-zip'));

const ROOT = path.join(__dirname, '../..');
const DOCX = path.join(ROOT, 'UBoss_Gloviaa_Mart_Detailed_Screen_Checklist_V2.docx');
const REPORT = path.join(ROOT, 'Checklist.md');
const STATE = path.join(__dirname, 'state.json');
const START = '<!-- PASS4:START -->';
const END = '<!-- PASS4:END -->';

const decode = (s) => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
const text = (s) => decode([...s.matchAll(/<w:t(?:\s[^>]*)?>([^<]*)<\/w:t>/g)].map((m) => m[1]).join(''));

function readDocx() {
  const xml = new AdmZip(DOCX).readAsText('word/document.xml');
  const all = text(xml);
  const total = { checked: (all.match(/☑/g) || []).length, unchecked: (all.match(/☐/g) || []).length };
  const idx = xml.indexOf('Master Screen Inventory');
  const t0 = xml.indexOf('<w:tbl>', idx);
  const t1 = xml.indexOf('</w:tbl>', t0);
  const rows = [];
  for (const r of xml.slice(t0, t1).matchAll(/<w:tr[ >][\s\S]*?<\/w:tr>/g)) {
    const cells = [...r[0].matchAll(/<w:tc>[\s\S]*?<\/w:tc>/g)].map((c) => text(c[0]).trim());
    if (!/^\d+$/.test(cells[0])) continue;
    rows.push({ id: Number(cells[0]), module: cells[1], role: cells[2], screen: cells[3], requirement: cells[4], priority: cells[5], checked: cells[6].includes('☑') });
  }
  return { total, rows };
}

const esc = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
const git = (c) => execSync(`git ${c}`, { cwd: ROOT, encoding: 'utf8' }).trim();

const { total, rows } = readDocx();
const state = JSON.parse(fs.readFileSync(STATE, 'utf8'));
const byId = new Map(state.rows.map((r) => [r.id, r]));

// Reconciliation: a ticked row must be VERIFIED/FIXED_AND_VERIFIED and vice versa.
const PASS = new Set(['VERIFIED', 'FIXED_AND_VERIFIED']);
const problems = [];
for (const row of rows) {
  const s = byId.get(row.id);
  const status = s?.status ?? 'NOT_STARTED';
  const reverifiedPass = PASS.has(status);
  if (row.checked && !reverifiedPass) problems.push(`#${row.id} ticked in Word but ${status}; reconcile earlier-pass evidence`);
  if (!row.checked && reverifiedPass) problems.push(`#${row.id} ${status} but not ticked in Word`);
}
if (rows.length !== 97) problems.push(`Master table has ${rows.length} rows, expected 97`);

const counts = {};
for (const row of rows) {
  const st = byId.get(row.id)?.status ?? 'NOT_STARTED';
  counts[st] = (counts[st] ?? 0) + 1;
}
const masterChecked = rows.filter((r) => r.checked).length;
const done = rows.filter((r) => byId.get(r.id)?.pass4Done).length;

const now = new Date();
const ist = new Date(now.getTime() + 5.5 * 3600e3).toISOString().replace('T', ' ').slice(0, 16) + ' IST';
const branch = git('rev-parse --abbrev-ref HEAD');
const head = git('rev-parse --short HEAD');

const lines = [];
lines.push(START);
lines.push('# Gloviaa Mart — Master Checklist Verification (Pass 4)');
lines.push('');
lines.push('Generated by `verification-evidence/pass4/build-report.cjs` from `verification-evidence/pass4/state.json` and a live read of the Word file. Edit the state file, not this section.');
lines.push('');
lines.push('## Executive summary');
lines.push('');
lines.push('| | |');
lines.push('|---|---|');
lines.push('| **Project** | Gloviaa Mart — Powered by UBOSS (repository `UBoss-Software`) |');
lines.push('| **Source Word file** | `UBoss_Gloviaa_Mart_Detailed_Screen_Checklist_V2.docx` (the only copy edited) |');
lines.push(`| **Latest update** | ${ist} |`);
lines.push(`| **Git branch / commit** | \`${branch}\` @ \`${head}\` |`);
lines.push(`| **Total Master rows** | ${rows.length} |`);
for (const st of ['VERIFIED', 'FIXED_AND_VERIFIED', 'FAILED', 'BLOCKED', 'NEEDS_HUMAN_VERIFICATION', 'DEFERRED', 'NOT_APPLICABLE', 'IN_PROGRESS', 'NOT_STARTED']) {
  lines.push(`| ${st} | ${counts[st] ?? 0} |`);
}
lines.push(`| **Rows processed in pass 4** | ${done} of ${rows.length} (remaining ${rows.length - done}) |`);
lines.push(`| **Word — whole document** | ${total.checked} ☑ / ${total.unchecked} ☐ (of ${total.checked + total.unchecked}) |`);
lines.push(`| **Word — Master table** | ${masterChecked} ☑ / ${rows.length - masterChecked} ☐ |`);
lines.push(`| **Reconciliation** | ${problems.length === 0 ? 'Word and this report agree' : 'MISMATCH: ' + esc(problems.join('; '))} |`);
lines.push(`| **Release recommendation** | **${state.recommendation}** — ${esc(state.recommendationWhy)} |`);
lines.push('');
lines.push('## Checkpoint');
lines.push('');
const cp = state.checkpoint;
lines.push('| | |');
lines.push('|---|---|');
lines.push(`| Last fully completed Master ID | ${cp.lastCompleted ?? '—'} |`);
lines.push(`| Next Master ID | ${cp.next} |`);
lines.push(`| Word checked / unchecked | ${total.checked} / ${total.unchecked} |`);
lines.push(`| Master checked / unchecked | ${masterChecked} / ${rows.length - masterChecked} |`);
lines.push(`| Branch / commit | \`${branch}\` @ \`${head}\` |`);
lines.push(`| Timestamp | ${ist} |`);
lines.push(`| Latest test result | ${esc(cp.latestTest)} |`);
lines.push(`| Current blocker | ${esc(cp.blocker ?? 'None')} |`);
lines.push('');
// The current batch (rows 11-20): its own summary, and one row per Master row
// in the columns the batch brief asks for.
if (state.batch) {
  const b = state.batch;
  const inBatch = rows.filter((r) => r.id >= b.from && r.id <= b.to);
  const count = (st) => inBatch.filter((r) => (byId.get(r.id)?.status ?? 'NOT_STARTED') === st).length;
  lines.push(`## Master Rows ${b.from}–${b.to} Verification`);
  lines.push('');
  lines.push(`- Batch scope: Rows ${b.from}–${b.to}`);
  lines.push(`- Last completed row: ${b.lastCompleted ?? '—'}`);
  lines.push(`- Next row: ${b.next}`);
  lines.push(`- Verified: ${count('VERIFIED')}`);
  lines.push(`- Fixed and verified: ${count('FIXED_AND_VERIFIED')}`);
  lines.push(`- Failed: ${count('FAILED')}`);
  lines.push(`- Blocked: ${count('BLOCKED')}`);
  lines.push(`- Needs human verification: ${count('NEEDS_HUMAN_VERIFICATION')}`);
  lines.push(`- In progress: ${count('IN_PROGRESS')}`);
  lines.push(`- Word Master checked count: ${masterChecked}`);
  lines.push(`- Word Master unchecked count: ${rows.length - masterChecked}`);
  lines.push(`- Overall checked count: ${total.checked}`);
  lines.push(`- Overall unchecked count: ${total.unchecked}`);
  lines.push(`- Git branch: ${branch}`);
  lines.push(`- Git commit: ${head}`);
  lines.push(`- Last updated: ${ist}`);
  lines.push('');
  lines.push('| Master Row | Screen | Previous State | Current Status | Finding | Implementation | Files Changed | Tests Added/Updated | Commands and Results | Manual Verification | Security Verification | Evidence | Verified At | Blocker |');
  lines.push('| ---------- | ------ | -------------- | -------------- | ------- | -------------- | ------------- | ------------------- | -------------------- | ------------------- | --------------------- | -------- | ----------- | ------- |');
  for (const row of inBatch) {
    const s = byId.get(row.id) ?? {};
    lines.push('| ' + [
      row.id, row.screen, s.previous ?? '', `**${s.status ?? 'NOT_STARTED'}**`, s.finding ?? '', s.fix ?? '', s.files ?? '',
      s.tests ?? '', s.testResult ?? '', s.verification ?? '', s.security ?? '', s.evidence ?? '', s.verifiedAt ?? '', s.blocker ?? '',
    ].map(esc).join(' | ') + ' |');
  }
  lines.push('');
}
// Boxes outside the Master table ticked in this pass, each with its evidence.
if (state.otherBoxes?.length) {
  const all = [...new AdmZip(DOCX).readAsText('word/document.xml').matchAll(/<w:t(?:\s[^>]*)?>([^<]*)<\/w:t>/g)].map((m) => m[1]).join('');
  const marks = [...all.matchAll(/[☐☑]/g)].map((m) => m[0]);
  const mapping = Object.values(require('../checklist-mapping.json'));
  const ord = new Map(mapping.map((m) => [m.id, m.ord]));
  lines.push('## Other checklist boxes verified in this pass');
  lines.push('');
  lines.push('Boxes outside the Master table (Definition of Done, Security, Go-live, Journeys and others). Ticked only with the evidence shown; the Word column says whether the box reads ☑ now.');
  lines.push('');
  lines.push('| Box | Requirement | Status | Evidence | Word | Verified At |');
  lines.push('| --- | ----------- | ------ | -------- | ---- | ----------- |');
  for (const b of state.otherBoxes) {
    const mark = marks[(ord.get(b.id) ?? 0) - 1] ?? '?';
    if (PASS.has(b.status) && mark !== '☑') problems.push(`${b.id} ${b.status} but not ticked in Word`);
    if (!PASS.has(b.status) && mark === '☑') problems.push(`${b.id} ticked in Word but ${b.status}`);
    lines.push('| ' + [b.id, mapping.find((m) => m.id === b.id)?.requirement ?? '', `**${b.status}**`, b.evidence, mark, b.verifiedAt ?? ''].map(esc).join(' | ') + ' |');
  }
  const other = problems.filter((x) => !x.startsWith('#') && !x.startsWith('Master'));
  lines.push('');
  lines.push(`Reconciliation for these boxes: ${other.length === 0 ? 'Word and this report agree' : 'MISMATCH: ' + esc(other.join('; '))}`);
  lines.push('');
}
if (state.notes?.length) {
  lines.push('## Notes for this pass');
  lines.push('');
  for (const n of state.notes) lines.push(`- ${n}`);
  lines.push('');
}
lines.push('## Master table');
lines.push('');
lines.push('Previous state = the Word box at the start of pass 4, then the pass 1–3 status from the report below. Only VERIFIED and FIXED_AND_VERIFIED rows are ticked in Word.');
lines.push('');
lines.push('| Master ID | Screen # | Priority | Module | Role | Screen | Requirement | Previous State | Current Status | Implementation/Fix | Verification | Evidence | Files Changed | Test Result | Verified At | Blocker/Owner |');
lines.push('| --------- | -------- | -------- | ------ | ---- | ------ | ----------- | -------------- | -------------- | ------------------ | ------------ | -------- | ------------- | ----------- | ----------- | ------------- |');
for (const row of rows) {
  const s = byId.get(row.id) ?? {};
  lines.push('| ' + [
    row.id, row.id, row.priority, row.module, row.role, row.screen, row.requirement,
    s.previous ?? '', `**${s.status ?? 'NOT_STARTED'}**`, s.fix ?? '', s.verification ?? '', s.evidence ?? '',
    s.files ?? '', s.testResult ?? '', s.verifiedAt ?? '', s.blocker ?? '',
  ].map(esc).join(' | ') + ' |');
}
lines.push('');
lines.push('## How to verify each row yourself');
lines.push('');
lines.push('Start the stack with `.\\scripts\\dev-stack.ps1` (storefront http://localhost:5174, admin http://localhost:5173, API http://localhost:4000). Each row lists what to open and what you should see, then the automated tests that prove the same thing. Run backend tests from `backend` and storefront tests from `apps/customer-web`, one run at a time: they share the test database.');
lines.push('');
for (const row of rows) {
  const st = byId.get(row.id);
  if (!st || !Array.isArray(st.manual) || st.manual.length === 0) continue;
  lines.push(`### Row ${row.id} — ${row.screen} (${st.status})`);
  lines.push('');
  st.manual.forEach((step, i) => lines.push(`${i + 1}. ${step}`));
  if (Array.isArray(st.commands) && st.commands.length > 0) {
    lines.push('');
    lines.push('Automated checks:');
    lines.push('');
    lines.push('```powershell');
    for (const c of st.commands) lines.push(c);
    lines.push('```');
  }
  lines.push('');
}
lines.push('---');
lines.push('');
lines.push('# Earlier passes (1–3) — kept for history');
lines.push('');
lines.push(END);

const existing = fs.readFileSync(REPORT, 'utf8');
const checkpoint = existing.includes(START) ? existing.slice(0, existing.indexOf(START)) : '';
let rest = existing;
if (existing.includes(START)) rest = existing.slice(existing.indexOf(END) + END.length).replace(/^\r?\n/, '');
const tmp = REPORT + '.tmp';
fs.writeFileSync(tmp, checkpoint + lines.join('\n') + '\n\n' + rest);
fs.renameSync(tmp, REPORT);
console.log(JSON.stringify({ total, masterChecked, masterUnchecked: rows.length - masterChecked, counts, problems }));
