/** A complete, plausible profile for the screen and form tests to start from. */
import type { LogisticsProfile } from './profile';

export function profileFixture(overrides: Partial<LogisticsProfile> = {}): LogisticsProfile {
  return {
    identity: {
      id: '01J0000000000000000000000A',
      partnerCode: 'LP-000123',
      legalName: 'Alpha Freight Ltd',
      displayName: 'Alpha Freight',
      partnerKind: 'MARKETPLACE_CARRIER',
      status: 'ACTIVE',
      suspensionReason: null,
      verificationState: 'UNVERIFIED',
      verifiedAt: null,
      logoUrl: null,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-01T00:00:00.000Z',
    },
    company: {
      registeredAddress: { line1: '1 Dock Road', city: 'Cork', countryCode: 'IE' },
      operationalAddress: null,
      registrationCountry: 'IE',
      registrationNumber: null,
      taxNumber: null,
      websiteUrl: null,
      businessDescription: null,
    },
    contacts: {
      contactEmail: 'ops@alpha.test',
      contactPhone: null,
      primaryContactName: null,
      primaryContactTitle: null,
      emergencyContactName: null,
      emergencyPhone: null,
      supportEmail: null,
      supportPhone: null,
      billingContactName: null,
      billingEmail: null,
      billingPhone: null,
    },
    coverage: { regions: [], countries: [], hubLocations: [] },
    capabilities: {
      selfManaged: false,
      levels: [],
      pricedTransportModes: [],
      declaredTransportModes: [],
      approved: [],
      fleetSize: 0,
      activeDrivers: 0,
      vehicleKinds: [],
      maxVehicleLoadKg: null,
      refrigeratedVehicles: 0,
      operatingHours: null,
      timeZone: null,
    },
    compliance: {
      licenceNumber: null,
      licenceExpiresAt: null,
      contractStatus: 'ACTIVE',
      contractEndsAt: null,
      items: [
        { kind: 'BUSINESS_LICENCE', status: 'MISSING', expiresOn: null },
        { kind: 'INSURANCE_CERTIFICATE', status: 'MISSING', expiresOn: null },
        { kind: 'TRANSPORT_PERMIT', status: 'MISSING', expiresOn: null },
      ],
      documents: [],
    },
    integrations: [
      { key: 'DHL', status: 'CREDENTIALS_REQUIRED', lastSuccessAt: null },
      { key: 'INDIA_POST', status: 'MANUAL_TRACKING', lastSuccessAt: null },
    ],
    review: { pendingChange: null, lastDecision: null },
    history: [],
    completion: { percent: 20, missing: ['logo', 'timeZone'] },
    editing: { canEdit: true, immediate: [], reverified: [] },
    ...overrides,
  };
}
